Repository growilabs/growi, pull requests merged in 2021-10, with the labels that each got.

#4442 imprv: Slackbot reaction to user
  packages/app/src/server/models/vo/slack-command-handler-error.ts
  packages/app/src/server/models/vo/slackbot-error.js
  packages/app/src/server/routes/apiv3/slack-integration.js
  packages/app/src/server/service/slack-command-handler/create-page-service.js
  packages/app/src/server/service/slack-command-handler/error-handler.ts
  packages/app/src/server/service/slack-command-handler/respond-if-slackbot-error.js
  packages/app/src/server/service/slack-command-handler/search.js
  packages/app/src/server/service/slack-command-handler/togetter.js
  packages/app/src/server/service/slack-integration.ts
  packages/slack/src/index.ts
  packages/slack/src/utils/interaction-payload-accessor.ts
Labels: improvement

#4373 imprv: Show modal when enabling Textlint
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/components/PageEditor/DownloadDictModal.tsx
  packages/app/src/components/PageEditor/OptionsSelector.jsx
Labels: improvement

#4443 fix: Redirected to apiv3 endpoint when guest mode is enabled
  packages/app/src/client/services/EditorContainer.js
Labels: bug

#4498 support: Replaced PageList with SWR
  packages/app/src/components/PageList.jsx
  packages/app/src/interfaces/paging-result.ts
  packages/app/src/stores/page.tsx
Labels: support
