Repository growilabs/growi, pull requests merged in 2021-09, with the labels that each got.

#4236 support: New release workflow
  .github/git-pr-release-template.erb
  .github/release-drafter.yml
  .github/workflows/auto-labeling.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/ci.yml
  .github/workflows/draft-release.yml
  .github/workflows/release-rc.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  bump-versions.config.js
  package.json
  packages/slackbot-proxy/package.json
  yarn.lock
Labels: support

#4241 support: Add bump-versions script
  .github/release-drafter.yml
  .github/workflows/auto-labeling.yml
  .github/workflows/pr-to-master.yml
  bin/bump-versions/README.md
  bin/bump-versions/cli.js
  bin/bump-versions/flow/bump-versions.js
  bin/bump-versions/index.js
  bin/bump-versions/step/printHelp.js
  bump-versions.config.js
Labels: support

#4243 fix: test for rename page recursively
  packages/app/src/test/service/page.test.js
Labels: exclude from changelog

#4246 fix: plugin endpoint
  packages/plugin-attachment-refs/index.js
  packages/plugin-attachment-refs/src/index.js
  packages/plugin-lsx/src/index.js
  packages/plugin-lsx/src/meta.js
  packages/plugin-pukiwiki-like-linker/src/index.js
  packages/plugin-pukiwiki-like-linker/src/meta.js
Labels: exclude from changelog

#4247 support: Supress warnings for mongo
  packages/app/config/migrate.js
  packages/app/src/server/console.js
  packages/app/src/server/crowi/index.js
  packages/app/src/server/util/mongoose-utils.ts
  packages/app/src/test/config/migrate.test.js
  packages/app/src/test/global-setup.js
  packages/app/src/test/setup.js
Labels: support

#4252 fix: Proxy uri checking
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
  packages/app/src/server/service/slack-integration.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/join-to-conversation.ts
Labels: bug, exclude from changelog

#4245 fix: adminRequired middleware for socket.io
  packages/app/package.json
  packages/app/src/server/middlewares/admin-required.js
  packages/app/src/server/service/socket-io.js
  yarn.lock
Labels: bug, improvement

#4259 imprv: 7348 slackappintegration set default as true
  packages/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
  packages/app/src/server/models/slack-app-integration.js
Labels: improvement, exclude from changelog

#4261 Prepare v4.4.1-RC.0
  CHANGELOG.md
  bin/bump-versions/cli.js
  bin/bump-versions/flow/bump-versions.js
  bin/bump-versions/index.js
  bin/bump-versions/step/printHelp.js
  bump-versions.config.js
  package.json
  packages/app/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: support, exclude from changelog

#4263 support: Make lerna mode fixed
  bump-versions.config.js
  lerna.json
Labels: support

#4264 chore: Skip jobs by PR label
  .github/release-drafter.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/ci.yml
  .github/workflows/pr-to-master.yml
Labels: support, exclude from changelog

#4271 fix: Plugin backend's permission
  packages/plugin-attachment-refs/src/server/routes/refs.js
  packages/plugin-lsx/src/server/routes/index.js
Labels: bug

#4272 fix: Update lsx (had broken by lerna import miscue)
  packages/plugin-lsx/src/client-entry.js
  packages/plugin-lsx/src/client/css/index.css
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxListView.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/PagePathWrapper.jsx
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxLogoutInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPreRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/LsxCacheHelper.js
  packages/plugin-lsx/src/client/js/util/LsxContext.js
  packages/plugin-lsx/src/client/js/util/TagCacheManagerFactory.js
  packages/plugin-lsx/src/server/routes/lsx.js
Labels: exclude from changelog

#4274 support: Make lerna mode fixed
  .github/workflows/release.yml
  bin/github-actions/bump-versions/README.md
  bin/github-actions/bump-versions/cli.js
  bin/github-actions/bump-versions/flow/bump-versions.js
  bin/github-actions/bump-versions/index.js
  bin/github-actions/bump-versions/step/printHelp.js
  bump-versions.config.js
Labels: support

#4280 support: Update APIv3 docs for pages
  packages/app/src/server/routes/apiv3/pages.js
Labels: support

#4286 fix(slackbot-proxy): Call next in connect-styled middleware
  packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
Labels: bug

#4293 imprv: Recent changes of sidebar
  packages/app/src/components/PagePathHierarchicalLink.jsx
  packages/app/src/components/Sidebar/CustomSidebar.jsx
  packages/app/src/components/Sidebar/RecentChanges.jsx
  packages/app/src/server/models/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/styles/_recent-changes.scss
  packages/app/src/styles/_sidebar.scss
  packages/app/src/styles/_tag.scss
  packages/app/src/styles/style-app.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: improvement

#4302 feat: Slack command permission for each channel
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
  packages/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
  packages/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/src/server/models/slack-app-integration.js
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
  packages/app/src/server/routes/apiv3/slack-integration.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/slack-command-handler/create.js
  packages/app/src/server/service/slack-command-handler/search.js
  packages/app/src/server/util/slack-integration.ts
  packages/slack/src/middlewares/verify-growi-to-slack-request.ts
  packages/slackbot-proxy/src/controllers/growi-to-slack.ts
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/entities/relation.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
  packages/slackbot-proxy/src/services/SelectGrowiService.ts
Labels: feature

#4307 imprv: Use socket.io room
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/services/SocketIoContainer.js
  packages/app/src/components/EmptyTrashModal.jsx
  packages/app/src/server/models/page.js
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/hackmd.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.js
  packages/app/src/server/service/socket-io.js
  packages/app/src/server/service/system-events/sync-page-status.ts
  packages/app/src/server/util/socket-io-helpers.ts
  packages/app/src/test/service/page.test.js
Labels: improvement

#4303 imprv: Copy buttons interaction
  packages/app/src/components/Admin/AdminHome/AdminHome.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Labels: improvement

#4295 feat: restrict command each channel
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
  packages/app/src/server/routes/apiv3/slack-integration.js
Labels: feature

#4314 imprv: get supported growi actions reg exps
  packages/app/src/server/util/slack-integration.ts
  packages/slack/src/utils/get-supported-growi-actions-regexps.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
Labels: improvement

#4315 fix: delete checkmark
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
Labels: bug, exclude from changelog

#4316 imprv: reduced image size
  packages/app/public/images/slack-integration/activate-public-dist.png
  packages/app/public/images/slack-integration/basicinfo-all-checked.png
  packages/app/public/images/slack-integration/click-add-to-slack.png
  packages/app/public/images/slack-integration/growi-bot-kun-icon.png
  packages/app/public/images/slack-integration/growi-register-modal.png
  packages/app/public/images/slack-integration/growi-register-sentence.png
  packages/app/public/images/slack-integration/growi-set-proxy-url.png
  packages/app/public/images/slack-integration/impossible.png
  packages/app/public/images/slack-integration/possible.png
  packages/app/public/images/slack-integration/slack-bot-install-to-workspace-joined-bot.png
  packages/app/public/images/slack-integration/slack-bot-install-to-workspace.png
  packages/app/public/images/slack-integration/slack-bot-install-your-app-complete.png
  packages/app/public/images/slack-integration/slack-bot-install-your-app-introduction-to-channel.png
  packages/app/public/images/slack-integration/slack-bot-install-your-app-introduction.png
  packages/app/public/images/slack-integration/slack-bot-install-your-app-transition-destination.png
  packages/app/public/images/slack-integration/triangle-basic-gray.png
Labels: improvement, exclude from changelog

#4318 fix: migration
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
Labels: bug, exclude from changelog

#4312 fix: Keyword highlight styling in search result
  packages/app/src/styles/_variables.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/antarctic.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/default.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/halloween.scss
  packages/app/src/styles/theme/hufflepuff.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mono-blue.scss
  packages/app/src/styles/theme/nature.scss
  packages/app/src/styles/theme/spring.scss
  packages/app/src/styles/theme/wood.scss
Labels: bug

#4313 imprv: Send error name instead of error type
  packages/slackbot-proxy/src/controllers/growi-to-slack.ts
Labels: improvement

#4321 fix: Response when no pages are found /growi search
  packages/app/src/server/service/slack-command-handler/search.js
Labels: bug

#4228 feat: Add Textlint Support
  packages/app/.gitignore
  packages/app/bin/cdn/cdn-resources-downloader.ts
  packages/app/config/cdn.js
  packages/app/docker/Dockerfile
  packages/app/package.json
  packages/app/resource/cdn-manifests.js
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/components/Me/EditorSettings.tsx
  packages/app/src/components/Me/PersonalSettings.jsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/Editor.jsx
  packages/app/src/components/PageEditor/OptionsSelector.jsx
  packages/app/src/server/models/editor-settings.ts
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/services/cdn-resources-service.js
  packages/codemirror-textlint/.gitignore
  packages/codemirror-textlint/package.json
  packages/codemirror-textlint/src/index.ts
  packages/codemirror-textlint/src/utils/logger/index.ts
  packages/codemirror-textlint/tsconfig.base.json
  packages/codemirror-textlint/tsconfig.build.json
  packages/codemirror-textlint/tsconfig.json
  yarn.lock
Labels: feature

#4326 fix: Highlighting section header
  packages/app/src/client/legacy/crowi.js
  packages/app/src/styles/_mixins.scss
  packages/app/src/styles/_variables.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/antarctic.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/default.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/halloween.scss
  packages/app/src/styles/theme/hufflepuff.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mono-blue.scss
  packages/app/src/styles/theme/nature.scss
  packages/app/src/styles/theme/spring.scss
  packages/app/src/styles/theme/wood.scss
Labels: bug

#4327 imprv: Highlighting searching keyword
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/styles/_variables.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/antarctic.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/default.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/halloween.scss
  packages/app/src/styles/theme/hufflepuff.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mono-blue.scss
  packages/app/src/styles/theme/nature.scss
  packages/app/src/styles/theme/spring.scss
  packages/app/src/styles/theme/wood.scss
Labels: improvement

#4335 fix: IME suggestion list obscures inputted text
  packages/app/src/styles/_override-codemirror.scss
Labels: bug

#4338 feat: add word
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Labels: feature

#4345 fix: Recent Created of home is empty
  packages/app/src/server/routes/apiv3/users.js
Labels: bug

#4347 fix: Backspace key on last line doesn't work in vim mode
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Labels: bug

#4360 chore: Update passport-saml 2.2.0
  packages/app/package.json
  yarn.lock
Labels: support

#4364 support: Upgrade codemirror to 5.63.0
  packages/app/package.json
  packages/app/resource/cdn-manifests.js
  yarn.lock
Labels: dependencies, support

#4368 fix: ERROR: Cannot find module 'tslib' on v4.4.4
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/ci.yml
  package.json
  packages/app/docker/Dockerfile
  yarn.lock
Labels: bug

#4370 support: bump @promster/express and @promster/server
  packages/app/package.json
  yarn.lock
Labels: support

#4342 imprv(slackbot-proxy): Show version on the top page
  packages/slackbot-proxy/src/controllers/top.ts
  packages/slackbot-proxy/src/views/commons/footer.ejs
  packages/slackbot-proxy/src/views/top.ejs
Labels: improvement

#4296 imprv: Slackbot response flow
  packages/app/src/server/routes/apiv3/slack-integration.js
  packages/app/src/server/service/slack-command-handler/create-page-service.js
  packages/app/src/server/service/slack-command-handler/create.js
  packages/app/src/server/service/slack-command-handler/help.js
  packages/app/src/server/service/slack-command-handler/search.js
  packages/app/src/server/service/slack-command-handler/slack-command-handler.js
  packages/app/src/server/service/slack-command-handler/togetter.js
  packages/app/src/server/service/slack-integration.ts
  packages/slack/package.json
  packages/slack/src/index.ts
  packages/slack/src/interfaces/growi-command-processor.ts
  packages/slack/src/interfaces/growi-command.ts
  packages/slack/src/interfaces/growi-interaction-processor.ts
  packages/slack/src/interfaces/request-from-slack.ts
  packages/slack/src/interfaces/response-url.ts
  packages/slack/src/middlewares/parse-slack-interaction-request.ts
  packages/slack/src/utils/interaction-payload-accessor.ts
  packages/slack/src/utils/payload-interaction-id-helpers.ts
  packages/slack/src/utils/post-ephemeral-errors.ts
  packages/slack/src/utils/response-url.ts
  packages/slack/src/utils/slash-command-parser.ts
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/interfaces/slack-to-growi/growi-command-processor.ts
  packages/slackbot-proxy/src/interfaces/slack-to-growi/slack-oauth-req.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/extract-growi-uri-from-req.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/parse-interaction-req.ts
  packages/slackbot-proxy/src/services/RegisterService.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
  packages/slackbot-proxy/src/services/SelectGrowiService.ts
  packages/slackbot-proxy/src/services/UnregisterService.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
Labels: improvement

#4384 fix(slackbot-proxy): Use pkg up
  packages/slackbot-proxy/package.json
  packages/slackbot-proxy/src/controllers/top.ts
Labels: bug, exclude from changelog

#4385 support(slackbot-proxy): Bump slackbot proxy version independentry
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  bin/github-actions/bump-versions/flow/bump-versions.js
  bin/github-actions/bump-versions/step/printHelp.js
  packages/slackbot-proxy/bump-versions.config.js
Labels: support

#4395 fix: Migrations do not run
  packages/app/.env.production
  packages/app/config/migrate.js
  packages/app/docker/Dockerfile
  packages/app/docker/docker-entrypoint.sh
  packages/app/src/migrations/20180926134048-make-email-unique.js
  packages/app/src/migrations/20181019114028-abolish-page-group-relation.js
  packages/app/src/migrations/20190618104011-add-config-app-installed.js
  packages/app/src/migrations/20200402160380-remove-deleteduser-from-relationgroup.js
  packages/app/src/migrations/20200620203632-normalize-locale-id.js
  packages/app/src/migrations/20210420160380-convert-double-to-date.js
  packages/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/src/server/console.js
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/models/editor-settings.ts
  packages/app/src/server/models/password-reset-order.ts
  packages/app/src/server/models/update-post.ts
  packages/app/src/test/config/migrate.test.js
  packages/app/src/test/global-setup.js
  packages/app/src/test/setup.js
  packages/app/tsconfig.build.server.json
  packages/core/src/index.js
  packages/core/src/utils/mongoose-utils.ts
Labels: bug

#4396 chore: Add .dockerignore
  packages/app/docker/Dockerfile.dockerignore
  packages/slackbot-proxy/docker/Dockerfile.dockerignore
Labels: support

#4397 fix: Copy correct dotenv file for NO_CDN docker image
  .github/workflows/release.yml
  packages/app/docker/Dockerfile
  packages/app/docker/nocdn/.env.production.local
  packages/app/docker/nocdn/env.prod.js
Labels: bug

#4398 imprv: Apply terminus for graceful shutdown
  packages/app/package.json
  packages/app/src/server/crowi/index.js
  packages/app/src/server/service/socket-io.js
  packages/slackbot-proxy/package.json
  yarn.lock
Labels: improvement

#4381 fix: Dictionary path of kuromoji invalid when uploaded to server
  .gitattributes
  THIRD-PARTY-NOTICES.md
  packages/app/.gitignore
  packages/app/bin/cdn/cdn-resources-downloader.ts
  packages/app/config/cdn.js
  packages/app/public/static/dict/base.dat.gz
  packages/app/public/static/dict/cc.dat.gz
  packages/app/public/static/dict/check.dat.gz
  packages/app/public/static/dict/tid.dat.gz
  packages/app/public/static/dict/tid_map.dat.gz
  packages/app/public/static/dict/tid_pos.dat.gz
  packages/app/public/static/dict/unk.dat.gz
  packages/app/public/static/dict/unk_char.dat.gz
  packages/app/public/static/dict/unk_compat.dat.gz
  packages/app/public/static/dict/unk_invoke.dat.gz
  packages/app/public/static/dict/unk_map.dat.gz
  packages/app/public/static/dict/unk_pos.dat.gz
  packages/app/resource/cdn-manifests.js
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Labels: bug

#4403 imprv: Omit textlint-rule-en-capitalization
  .github/workflows/ci.yml
  packages/app/.gitignore
  packages/app/config/webpack.prod.js
  packages/app/src/components/Me/EditorSettings.tsx
  packages/codemirror-textlint/package.json
  packages/codemirror-textlint/src/index.ts
  yarn.lock
Labels: improvement

#4406 fix: Migrations for updating data for slackbot
  packages/app/src/migrations/20210830074539-update-configs-for-slackbot.js
  packages/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
Labels: bug

#4411 fix: Stop using ts-node in production
  package.json
  packages/app/.env.development
  packages/app/.eslintrc.js
  packages/app/docker/Dockerfile
  packages/app/migrate-mongo-config.js
  packages/app/package.json
  packages/app/src/migrations/20180926134048-make-email-unique.js
  packages/app/src/migrations/20180927102719-init-serverurl.js
  packages/app/src/migrations/20181019114028-abolish-page-group-relation.js
  packages/app/src/migrations/20190618055300-abolish-crowi-classic-auth.js
  packages/app/src/migrations/20190618104011-add-config-app-installed.js
  packages/app/src/migrations/20190619055421-adjust-page-grant.js
  packages/app/src/migrations/20190624110950-fill-last-update-user.js
  packages/app/src/migrations/20190629193445-make-root-page-public.js
  packages/app/src/migrations/20191102223900-drop-configs-indices.js
  packages/app/src/migrations/20191102223901-drop-pages-indices.js
  packages/app/src/migrations/20191126173016-adjust-pages-path.js
  packages/app/src/migrations/20191127023815-drop-wrong-index-of-page-tag-relation.js
  packages/app/src/migrations/20200402160380-remove-deleteduser-from-relationgroup.js
  packages/app/src/migrations/20200420160390-remove-crowi-layout.js
  packages/app/src/migrations/20200512005851-remove-behavior-type.js
  packages/app/src/migrations/20200514001356-update-theme-color-for-dark.js
  packages/app/src/migrations/20200620203632-normalize-locale-id.js
  packages/app/src/migrations/20200827045151-remove-layout-setting.js
  packages/app/src/migrations/20200828024025-copy-aws-setting.js
  packages/app/src/migrations/20200901034313-update-mail-transmission.js
  packages/app/src/migrations/20200901034314-update-mail-transmission-fix.js
  packages/app/src/migrations/20200903080025-remove-timeline-type.js.js
  packages/app/src/migrations/20200915035234-rename-s3-config.js
  packages/app/src/migrations/20210420160380-convert-double-to-date.js
  packages/app/src/migrations/20210830074539-update-configs-for-slackbot.js
  packages/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/src/test/config/migrate.test.js
Labels: bug

#4412 support: Reorganize tests
  packages/app/jest.config.js
  packages/app/src/test/integration/crowi/crowi.test.js
  packages/app/src/test/integration/global-setup.js
  packages/app/src/test/integration/global-teardown.js
  packages/app/src/test/integration/middlewares/access-token-parser.test.js
  packages/app/src/test/integration/middlewares/login-required.test.js
  packages/app/src/test/integration/models/config.test.js
  packages/app/src/test/integration/models/page.test.js
  packages/app/src/test/integration/models/share-link.test.js
  packages/app/src/test/integration/models/update-post.test.js
  packages/app/src/test/integration/models/user.test.js
  packages/app/src/test/integration/service/acl.test.js
  packages/app/src/test/integration/service/config-manager.test.js
  packages/app/src/test/integration/service/page.test.js
  packages/app/src/test/integration/service/passport.test.js
  packages/app/src/test/integration/service/search-delegator/searchbox.test.js
  packages/app/src/test/integration/setup-crowi.js
  packages/app/src/test/integration/setup.js
  packages/app/src/test/integration/utils/slack-legacy.test.js
  packages/app/src/test/unit/middlewares/safe-redirect.test.js
  packages/app/src/test/unit/migrate-mongo-config.test.js
  packages/app/src/test/unit/utils/to-array-from-csv.test.js
Labels: exclude from changelog

#4405 support: Install Git LFS when provisioning of devcontainer
  .devcontainer/Dockerfile
Labels: support

#4414 support: Add test for migrate-slack-app-integration-schema
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/src/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  packages/app/src/test/integration/setup-crowi.js
Labels: exclude from changelog

#4413 fix: Modified a migration file for mongodb compatibility
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/src/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  packages/app/src/test/integration/setup-crowi.js
Labels: bug

#4416 fix: A problem that GROWI server doesn't retrieve connection status from Official bot proxy
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
Labels: bug

#4410 feat: 7325 append menu item bulk export
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/src/components/Page/PageManagement.jsx
  packages/app/src/server/routes/apiv3/export-jobs.js
  packages/app/src/server/routes/apiv3/index.js
Labels: feature

#4417 fix(slackbot): Sync permission when data stored is not enough
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/entities/relation.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
Labels: bug

#4420 imprv: Slackbot search
  packages/app/src/server/service/slack-command-handler/search.js
  packages/app/src/server/service/slack-integration.ts
  packages/slack/src/utils/response-url.ts
Labels: improvement

#4424 fix(slackbot): Stop auto-join to channels with middlewarer
  packages/slackbot-proxy/src/controllers/slack.ts
Labels: bug
