Repository growilabs/growi, pull requests merged in 2021-12, with the labels that each got.

#4770 imprv: apiv3 client
  packages/app/src/client/util/apiv3-client.ts
  packages/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
  packages/app/src/server/routes/apiv3/response.js
Labels: improvement, breaking

#4800 fix(slackbot-proxy): Support new API v3 data scheme
  packages/slackbot-proxy/package.json
  packages/slackbot-proxy/src/services/RelationsService.ts
Labels: bug

#4806 fix: /admin/slack-integration page dump undefined error
  packages/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
Labels: bug

#4811 fix: Added scope for unfurl
  packages/app/src/server/service/slack-command-handler/search.js
  packages/app/src/server/service/slack-event-handler/link-shared.ts
  packages/slack/src/index.ts
  packages/slack/src/utils/generate-last-update-markdown.ts
  packages/slack/src/utils/required-scopes.ts
Labels: bug

#4820 imprv: CodeMirrorEditor setScrollTopByLine
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Labels: improvement

#4830 Imprv/inject user UI settings
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Sidebar.tsx
  packages/app/src/components/StickyStretchableScroller.jsx
  packages/app/src/server/middlewares/inject-user-ui-settings-to-localvars.ts
  packages/app/src/server/models/user-ui-settings.ts
  packages/app/src/server/routes/apiv3/user-ui-settings.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/views/layout/layout.html
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_sidebar.scss
Labels: exclude from changelog

#4834 imprv: Disable rubber band scroll for Mac & iOS users
  packages/app/src/styles/_layout.scss
Labels: improvement

#4827 imprv: Use SWR for isSlackEnabled
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/SlackNotification.jsx
  packages/app/src/components/SlackNotification.tsx
  packages/app/src/stores/editor.tsx
Labels: improvement

#4862 feat: user activation by email
  packages/app/resource/locales/en_US/notifications/userActivation.txt
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/notifications/userActivation.txt
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/notifications/userActivation.txt
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/nologin.jsx
  packages/app/src/client/services/AdminLocalSecurityContainer.js
  packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
  packages/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  packages/app/src/components/CompleteUserRegistrationForm.tsx
  packages/app/src/components/LoginForm.jsx
  packages/app/src/server/middlewares/inject-user-registration-order-by-token-middleware.ts
  packages/app/src/server/models/user-registration-order.ts
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/user-activation.ts
  packages/app/src/server/routes/user.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/views/login.html
  packages/app/src/server/views/user-activation.html
  packages/app/src/styles/atoms/_buttons.scss
Labels: feature

#4864 fix: dependabot alert set-value
  yarn.lock
Labels: bug, improvement

#4869 support: Transplant search service from dev/5.0.x
  packages/app/package.json
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/interfaces/common.ts
  packages/app/src/interfaces/named-query.ts
  packages/app/src/interfaces/page.ts
  packages/app/src/interfaces/search.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/interfaces/search.ts
  packages/app/src/server/models/named-query.ts
  packages/app/src/server/routes/search.js
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/service/search-delegator/searchbox.js
  packages/app/src/server/service/search.js
  packages/app/src/server/service/search.ts
  packages/app/src/test/integration/service/search-delegator/searchbox.test.js
  packages/app/src/test/integration/service/search/search-service.test.js
  yarn.lock
Labels: support

#4884 fix: Set min-height to sidebar scroll target
  packages/app/src/components/Sidebar.tsx
Labels: bug

#4846 imprv: Support SWR for Slack channels
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/components/Page.jsx
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/stores/context.tsx
Labels: improvement

#4878 fix: dependabot alert xmlhttprequest-ssl
  packages/app/package.json
  yarn.lock
Labels: bug, improvement

#4867 imprv: fix and debug mixin-deep dependabot alert
  yarn.lock
Labels: improvement

#4892 imprv: dependabot alert ini
  yarn.lock
Labels: improvement

#4891 imprv: dependabot alert kind-of
  yarn.lock
Labels: improvement

#4888 fix: slack notification not working, SWRize slackChannels
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/client/util/editor.ts
  packages/app/src/components/Page.jsx
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/PageEditorByHackmd.jsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/stores/context.tsx
Labels: bug, exclude from changelog

#4916 fix: GROWI Bot search command after transplanting search service from dev/5.0.x
  packages/app/src/server/service/slack-command-handler/search.js
Labels: bug

#4938 support: omit growi-commons
  packages/app/bin/download-cdn-resources.ts
  packages/app/config/webpack.common.js
  packages/app/config/webpack.dev.dll.js
  packages/app/package.json
  packages/app/src/client/util/interceptor/detach-code-blocks.js
  packages/app/src/client/util/interceptor/drawio-interceptor.js
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditor/MarkdownTableInterceptor.js
  packages/app/src/components/PageEditor/PreventMarkdownListInterceptor.js
  packages/app/src/server/models/GlobalNotificationSetting/index.js
  packages/app/src/server/models/page.js
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/slack-command-handler/create-page-service.js
  packages/app/src/server/util/middlewares.js
  packages/app/src/server/util/swigFunctions.js
  packages/app/src/services/cdn-resources-service.js
  packages/core/README.md
  packages/core/src/index.js
  packages/core/src/plugin/service/tag-cache-manager.js
  packages/core/src/service/localstorage-manager.js
  packages/core/src/utils/basic-interceptor.js
  packages/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPostRenderInterceptor.js
  packages/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPreRenderInterceptor.js
  packages/plugin-attachment-refs/src/client/js/util/RefsContext.js
  packages/plugin-attachment-refs/src/client/js/util/TagCacheManagerFactory.js
  packages/plugin-attachment-refs/src/server/routes/refs.js
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxLogoutInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPreRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/LsxContext.js
  packages/plugin-lsx/src/client/js/util/TagCacheManagerFactory.js
  packages/plugin-lsx/src/server/routes/lsx.js
  packages/ui/README.md
  yarn.lock
Labels: support

#4941 support: Upgrade node to 16.x
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/ci.yml
  .github/workflows/list-unhealthy-branches.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  package.json
  packages/app/docker/Dockerfile
  packages/slackbot-proxy/docker/Dockerfile
Labels: breaking

#4906 fix: dependabot alert js-yaml
  packages/app/package.json
  yarn.lock
Labels: bug, improvement

#4910 fix: dependabot alert serialize-javascript
  yarn.lock
Labels: bug, improvement

#4934 fix: dependabot alert socket.io-parser
  yarn.lock
Labels: bug, improvement

#4951 fix: dependabot alert acorn
  packages/app/package.json
  yarn.lock
Labels: support

#4959 fix: dependabot alert elliptic
  yarn.lock
Labels: support

#4960 fix: dependabot alert axios
  yarn.lock
Labels: bug, improvement

#4964 fix: dependabot alert object-path
  packages/app/package.json
  yarn.lock
Labels: bug, improvement

#4819 imprv: 82973 replace createdAt to swr
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Navbar/AuthorInfo.jsx
  packages/app/src/components/Navbar/GrowiSubNavigation.jsx
  packages/app/src/components/PageContentFooter.jsx
  packages/app/src/server/views/widget/page_content.html
  packages/app/src/stores/context.tsx
Labels: improvement

#4988 fix: Sidebar height is a little large
  packages/app/src/styles/_sidebar.scss
Labels: bug

#4982 support: Typescriptize search components
  packages/app/src/client/interfaces/focusable.ts
  packages/app/src/client/interfaces/react-bootstrap-typeahead.ts
  packages/app/src/components/Navbar/GlobalSearch.jsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/SearchForm.jsx
  packages/app/src/components/SearchForm.tsx
  packages/app/src/components/SearchPage/SearchPageForm.jsx
  packages/app/src/components/SearchTypeahead.jsx
  packages/app/src/components/SearchTypeahead.tsx
Labels: support

#4954 imprv: Make updatedAt SWR
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Navbar/AuthorInfo.jsx
  packages/app/src/components/Navbar/GrowiSubNavigation.jsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageContentFooter.jsx
  packages/app/src/server/views/widget/page_content.html
  packages/app/src/stores/context.tsx
Labels: improvement

#5003 imprv: Focus to input when resetting SearchTypeahead
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/PagePathAutoComplete.jsx
  packages/app/src/components/SearchTypeahead.tsx
Labels: support, improvement

#5004 imprv: Change reaction icons
  packages/app/src/client/app.jsx
  packages/app/src/components/Admin/Notification/GlobalNotificationList.jsx
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
  packages/app/src/components/BookmarkButton.jsx
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/ContentLinkButtons.jsx
  packages/app/src/components/Icons/BookmarkIcon.jsx
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.jsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/Page/PageManagement.jsx
  packages/app/src/components/PageReactionButtons.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/User/LikerList.jsx
  packages/app/src/server/views/layout-growi/user_page.html
  packages/app/src/server/views/widget/page_list.html
  packages/app/src/styles/_subnav.scss
  packages/app/src/styles/atoms/_buttons.scss
  packages/ui/src/components/PagePath/PageListMeta.jsx
Labels: improvement

#5005 imprv: Omit magnifier icon from global SearchTypeahead
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/styles/_search.scss
Labels: improvement

#5006 feat: Hotkey to focus to search
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Hotkeys/HotkeysManager.jsx
  packages/app/src/components/Hotkeys/Subscribers/FocusToGlobalSearch.jsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/SearchForm.tsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/server/views/modal/shortcuts.html
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_search.scss
Labels: feature

#4957 imprv: Migrate editor container grant to SWR
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/client/util/editor.ts
  packages/app/src/components/Page.jsx
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditorByHackmd.jsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/stores/ui.tsx
Labels: improvement

#4792 feat: InAppNotification
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/admin.jsx
  packages/app/src/client/app.jsx
  packages/app/src/components/FormattedDistanceDate.jsx
  packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
  packages/app/src/components/InAppNotification/InAppNotificationList.tsx
  packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
  packages/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  packages/app/src/components/Me/InAppNotificationSettings.tsx
  packages/app/src/components/Me/PersonalSettings.jsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/SubNavButtons.jsx
  packages/app/src/components/PaginationWrapper.tsx
  packages/app/src/components/SubscribeButton.tsx
  packages/app/src/interfaces/in-app-notification.ts
  packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/events/activity.ts
  packages/app/src/server/events/comment.ts
  packages/app/src/server/models/activity.ts
  packages/app/src/server/models/comment.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/models/in-app-notification-settings.ts
  packages/app/src/server/models/in-app-notification.ts
  packages/app/src/server/models/page.js
  packages/app/src/server/models/revision.js
  packages/app/src/server/models/subscription.ts
  packages/app/src/server/routes/all-in-app-notifications.ts
  packages/app/src/server/routes/apiv3/bookmarks.js
  packages/app/src/server/routes/apiv3/in-app-notification.ts
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/server/routes/comment.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/service/activity.ts
  packages/app/src/server/service/comment.ts
  packages/app/src/server/service/in-app-notification.ts
  packages/app/src/server/service/page.js
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/service/search.ts
  packages/app/src/server/util/activityDefine.ts
  packages/app/src/server/views/me/all-in-app-notifications.html
  packages/app/src/stores/in-app-notification.ts
  packages/app/src/stores/page.tsx
  packages/app/src/styles/_navbar.scss
  packages/app/src/styles/_subnav.scss
  packages/app/src/styles/atoms/_buttons.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/test/integration/service/page.test.js
Labels: feature

#5009 feat: Automatically subscribe when page is duplicated
  packages/app/src/server/routes/apiv3/pages.js
Labels: exclude from changelog

#5016 feat: OIDC reconnection
  packages/app/package.json
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/passport.ts
Labels: feature

#4973 support: dependabot alert ssri
  yarn.lock
Labels: support

#4921 fix: dependabot alert dot-prop
  package.json
  yarn.lock
Labels: support

#4931 fix: dependabot alert trim-newlines
  yarn.lock
Labels: bug, improvement
