Repository growilabs/growi, pull requests merged in 2021-11, with the labels that each got.

#4577 fix: CSRF with api client
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/util/apiv1-client.ts
  packages/app/src/client/util/apiv3-client.ts
Labels: exclude from changelog

#4578 support: Update passport-ldpauth from ^2.0.0 to ^3.0.1
  packages/app/package.json
  yarn.lock
Labels: dependencies, support, improvement

#4602 fix: /pages/info API is broken
  packages/app/src/client/services/PageContainer.js
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#4585 support: refs 79379 79549 Implemented error message handling in pageList
  packages/app/src/components/PageList.jsx
Labels: support

#4615 feat(search-result): 80324 80529 adjust checkbox position
  packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
  packages/app/src/components/SearchPage/SearchResultListItem.tsx
  packages/app/src/styles/_search.scss
Labels: feature

#4639 fix: Timeline was broken
  packages/app/src/components/PageTimeline.jsx
Labels: bug

#4638 support: Bump mpath with mongoose
  packages/app/package.json
  yarn.lock
Labels: support

#4629 fix: Slack Integration 'note' command causes expired_trigger_id error
  packages/app/src/server/service/slack-command-handler/note.js
Labels: bug

#4651 fix: Unescape Attribute-based Login Control field value
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  packages/app/src/server/service/passport.ts
Labels: bug

#4656 imprv: SAML settings by DB
  packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  packages/app/src/server/service/config-manager.ts
Labels: improvement

#4592 feat: 77525 80783 control selected pages
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage/SearchResultListItem.tsx
Labels: feature

#4669 fix: cannot edit HackMD
  packages/app/package.json
  yarn.lock
Labels: bug

#4703 feat: including comments in full text search
  packages/app/resource/search/mappings.json
  packages/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.jsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/events/comment.ts
  packages/app/src/server/models/comment.js
  packages/app/src/server/routes/comment.js
  packages/app/src/server/service/search-delegator/elasticsearch.js
  packages/app/src/server/service/search.js
Labels: feature

#4594 feat/#80481 SubNavButton refactor like button
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/LikeButtons.jsx
  packages/app/src/components/Navbar/GrowiSubNavigation.jsx
  packages/app/src/components/Navbar/SubNavButtons.jsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/PageReactionButtons.tsx
  packages/app/src/components/SearchPage.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
  packages/app/src/interfaces/page-info.ts
  packages/app/src/server/models/page.js
  packages/app/src/stores/page.tsx
Labels: feature

#4688 fix: Interactions from private channels not working
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/server/routes/apiv3/slack-integration.js
  packages/app/src/server/util/slack-integration.ts
  packages/slack/src/index.ts
  packages/slack/src/interfaces/channel.ts
  packages/slack/src/utils/interaction-payload-accessor.ts
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
  packages/slackbot-proxy/src/services/SelectGrowiService.ts
Labels: bug

#4659 imprv: Upgrade mongoose from 5.x to 6.x
  packages/app/package.json
  packages/app/src/server/models/editor-settings.ts
  packages/app/src/server/models/external-account.js
  packages/app/src/server/models/page.js
  packages/app/src/server/models/password-reset-order.ts
  packages/app/src/server/models/update-post.ts
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/attachment.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/page.js
  packages/app/src/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  packages/core/src/utils/mongoose-utils.ts
  yarn.lock
Labels: improvement

#4739 fix: fix bug in tags page
  packages/app/src/server/views/tags.html
Labels: bug

#4740 imprv: SWRize context
  packages/app/src/client/app.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/server/views/layout/layout.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/use-static-swr.tsx
  packages/app/src/utils/swr-utils.ts
Labels: improvement

#4720 feat: Slackbot unfurl
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
  packages/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/interfaces/slack-integration/events.ts
  packages/app/src/server/interfaces/slack-integration/link-shared-unfurl.ts
  packages/app/src/server/models/page.js
  packages/app/src/server/models/slack-app-integration.js
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
  packages/app/src/server/routes/apiv3/slack-integration.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/slack-event-handler/base-event-handler.ts
  packages/app/src/server/service/slack-event-handler/link-shared.ts
  packages/app/src/server/service/slack-integration.ts
  packages/slack/src/index.ts
  packages/slack/src/interfaces/growi-bot-event.ts
  packages/slack/src/interfaces/growi-event-processor.ts
  packages/slack/src/middlewares/verify-slack-request.ts
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/url-verification.ts
  packages/slackbot-proxy/src/repositories/relation.ts
  packages/slackbot-proxy/src/services/LinkSharedService.ts
  packages/slackbot-proxy/src/services/RegisterService.ts
Labels: feature

#4754 fix(Slackbot): Slash commands response when sent from disabled channels
  packages/app/src/server/util/slack-integration.ts
  packages/slack/src/index.ts
  packages/slack/src/utils/permission-parser.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
Labels: bug

#4755 imprv: Show site url in unfurl footer
  packages/app/src/server/service/slack-event-handler/link-shared.ts
Labels: improvement

#4727 imprv: upgrade passport from v0.4.x to v0.5.x
  packages/app/package.json
  packages/app/src/server/routes/avoid-session-routes.js
  yarn.lock
Labels: improvement
