Repository growilabs/growi, pull requests merged in 2022-07, with the labels that each got.

#6141 feat: Add testcode for updateDescendantCountOfPagesWithPaths
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.page.test.ts
Labels: feature

#5706 imprv: Add testcode for page model user-group
  packages/app/test/integration/models/v5.page.test.js
Labels: improvement

#6191 support: Ease rate limit temporary
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/index.js
Labels: support

#6077 imprv: Add shouldEmit argument and excute socket.emit only in addAllPages
  packages/app/src/server/interfaces/search.ts
  packages/app/src/server/models/interfaces/page-operation.ts
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/service/interfaces/search.ts
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: improvement

#6182 imprv: Omit Personal Container
  packages/app/src/client/app.jsx
  packages/app/src/client/services/PersonalContainer.js
  packages/app/src/components/Admin/Security/LdapAuthTest.jsx
  packages/app/src/components/Me/ApiSettings.jsx
  packages/app/src/components/Me/ApiSettings.tsx
  packages/app/src/components/Me/AssociateModal.jsx
  packages/app/src/components/Me/AssociateModal.tsx
  packages/app/src/components/Me/BasicInfoSettings.jsx
  packages/app/src/components/Me/BasicInfoSettings.tsx
  packages/app/src/components/Me/DisassociateModal.jsx
  packages/app/src/components/Me/DisassociateModal.tsx
  packages/app/src/components/Me/ExternalAccountLinkedMe.jsx
  packages/app/src/components/Me/PasswordSettings.jsx
  packages/app/src/interfaces/external-account.ts
  packages/app/src/interfaces/user.ts
  packages/app/src/stores/personal-settings.tsx
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: support

#6201 fix: Slack integration connection test
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Labels: bug

#6213 imprv: update subscribe button icon on Navbar
  packages/app/src/components/BookmarkButtons.tsx
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/SubscribeButton.tsx
  packages/app/src/components/User/SeenUserInfo.tsx
  packages/app/src/styles/atoms/_buttons.scss
Labels: improvement

#6226 fix: Use APIv3 for api get check_username
  packages/app/src/components/CompleteUserRegistrationForm.tsx
  packages/app/src/components/InstallerForm.jsx
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/views/invited.html
  packages/app/src/server/views/login.html
Labels: bug

#6132 support: gw7741 VRT pagelist
  packages/app/src/components/DescendantsPageListModal.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
Labels: support, exclude from changelog

#6124 imprv: Reflect tmp tag data
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/server/routes/page.js
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/ui.tsx
  packages/core/src/utils/page-path-utils.ts
Labels: improvement

#6053 feat: Rate Limit by rate-limit-flexible
  packages/app/config/rate-limiter.ts
  packages/app/package.json
  packages/app/src/server/middlewares/rate-limiter.ts
  packages/app/src/server/routes/apiv3/activity.ts
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/util/rate-limiter.ts
  packages/app/tsconfig.build.server.json
  packages/core/src/utils/page-utils.ts
  yarn.lock
Labels: feature

#6033 support: gw7740 vrt tag
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support

#6223 support: Refactor growi renderer using hooks
  packages/app/src/client/plugin.js
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/util/GrowiRenderer.js
  packages/app/src/client/util/PreProcessor/XssFilter.js
  packages/app/src/client/util/reveal/plugins/growi-renderer.js
  packages/app/src/components/MyDraftList/Draft.jsx
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/components/PageTimeline.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/interfaces/global.ts
  packages/app/src/interfaces/services/renderer.ts
  packages/app/src/server/routes/page.js
  packages/app/src/services/renderer/PostProcessor/.keep
  packages/app/src/services/renderer/PreProcessor/CsvToTable.js
  packages/app/src/services/renderer/PreProcessor/EasyGrid.js
  packages/app/src/services/renderer/PreProcessor/Linker.js
  packages/app/src/services/renderer/PreProcessor/XssFilter.ts
  packages/app/src/services/renderer/growi-renderer.ts
  packages/app/src/services/renderer/interceptor/detach-code-blocks.js
  packages/app/src/services/renderer/interceptor/drawio-interceptor.js
  packages/app/src/services/renderer/markdown-it/blockdiag.js
  packages/app/src/services/renderer/markdown-it/drawio-viewer.js
  packages/app/src/services/renderer/markdown-it/emoji-mart-data.ts
  packages/app/src/services/renderer/markdown-it/emoji.js
  packages/app/src/services/renderer/markdown-it/footernote.js
  packages/app/src/services/renderer/markdown-it/header-line-number.js
  packages/app/src/services/renderer/markdown-it/header-with-edit-link.js
  packages/app/src/services/renderer/markdown-it/header.js
  packages/app/src/services/renderer/markdown-it/link-by-relative-path.ts
  packages/app/src/services/renderer/markdown-it/mathjax.js
  packages/app/src/services/renderer/markdown-it/plantuml.js
  packages/app/src/services/renderer/markdown-it/table-with-handsontable-button.js
  packages/app/src/services/renderer/markdown-it/table.js
  packages/app/src/services/renderer/markdown-it/task-lists.js
  packages/app/src/services/renderer/markdown-it/toc-and-anchor.js
  packages/app/src/services/xss/xssOption.js
  packages/app/src/services/xss/xssOption.ts
  packages/app/src/stores/context.tsx
  packages/app/src/stores/renderer.tsx
  packages/plugin-pukiwiki-like-linker/src/client-entry.js
Labels: support

#6237 support: Refactor growi renderer using hooks 2
  packages/app/src/services/renderer/growi-renderer.ts
  packages/app/src/stores/renderer.tsx
Labels: support

#6249 fix: Blink section header on init
  packages/app/src/client/legacy/crowi.js
  packages/app/src/client/util/blink-section-header.ts
  packages/app/src/components/Page.jsx
  packages/app/src/stores/context.tsx
Labels: bug

#6224 feat: Add delete and download activity
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/routes/admin.js
  packages/app/src/server/routes/apiv3/export.js
Labels: feature, exclude from changelog

#6275 fix: Drawio rendering
  packages/app/src/components/Drawio.tsx
  packages/app/src/interfaces/graph-viewer.ts
Labels: bug

#6278 imprv: Corrected to WESEEK style
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/service/config-loader.ts
Labels: exclude from changelog

#6283 support: Refactor PageInfo types
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/PageList/PageList.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchForm.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/interfaces/search.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/search.ts
Labels: support

#6276 feat: Add activity
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/apiv3/search.js
  packages/app/src/server/routes/apiv3/users.js
Labels: exclude from changelog

#6308 fix: Variable Value
  packages/app/src/interfaces/activity.ts
Labels: bug

#6311 support: Prepare v5.1.0-RC.3
  lerna.json
  package.json
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: support

#5709 feat: Custom brand logo image
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
  packages/app/src/components/Common/ImageCropModal.tsx
  packages/app/src/components/Me/ImageCropModal.jsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/server/interfaces/attachment.ts
  packages/app/src/server/models/attachment.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/server/routes/attachment.js
  packages/app/src/server/service/attachment.js
Labels: feature

#6317 fix: Username is not saved in activity
  packages/app/src/server/routes/login-passport.js
Labels: bug, exclude from changelog

#6045 feat: create migration for attachmentType of existing attachments
  packages/app/src/migrations/20220613064207-add-attachment-type-to-existing-attachments.js
Labels: feature

#6319 support: Prepare v5.1.0-RC.4
  lerna.json
  package.json
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: support, exclude from changelog

#6322 feat: Separate trust proxies by type
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/service/config-loader.ts
Labels: feature, exclude from changelog

#6333 feat: Render /_search.page.tsx by accessing /_search
  packages/app/src/pages/_search.page.tsx
  packages/app/src/server/routes/index.js
Labels: feature

#6327 feat: Reset search criteria button
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/client/interfaces/clearable.ts
  packages/app/src/components/Admin/AuditLog/SearchUsernameTypeahead.tsx
  packages/app/src/components/Admin/AuditLogManagement.tsx
Labels: feature

#6336 support: FC/TSize PageAttachment
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/PageAttachment.jsx
  packages/app/src/components/PageAttachment.tsx
  packages/app/src/interfaces/attachment.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/server/routes/apiv3/attachment.js
  packages/app/src/stores/attachment.tsx
  packages/app/src/stores/context.tsx
  packages/core/src/index.ts
Labels: support

#6342 feat: Show user picture in Audit Log
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
  packages/app/src/server/models/activity.ts
  packages/app/src/server/routes/apiv3/activity.ts
  packages/app/src/stores/activity.ts
Labels: feature

#6348 fix: "Error: cannnot get grant label" occured with lsx
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Page/FixPageGrantAlert.tsx
Labels: bug

#6351 imprv(auditlog): Include delete-related actions in small group
  packages/app/src/interfaces/activity.ts
Labels: improvement

#6364 fix: Migration script for inserting NamedQuery
  packages/app/src/migrations/20211129125654-initialize-private-legacy-pages-named-query.js
Labels: bug

#6353 feat(auditlog): Display number of actions that can be saved
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
Labels: feature

#6368 fix: Fix page path
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/interfaces/page-operation.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/app/src/utils/page-operation.ts
  packages/app/test/integration/service/v5.page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: bug

#6378 fix: Default markdown linker with relative path does not respect the current page path (v5.1.0)
  packages/app/src/services/renderer/markdown-it/link-by-relative-path.ts
Labels: bug
