Repository growilabs/growi, pull requests merged in 2022-03, with the labels that each got.

#5452 imprv: show toaster after page has been deleted and duplicateed
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
Labels: improvement, exclude from changelog

#5453 imprv: show toaster and revalidate after page has been renamed on Growi Search Result Content
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement

#5456 fix: revert error in case that recursively property is null
  packages/app/src/server/routes/page.js
Labels: bug, exclude from changelog

#5458 fix: Normalize parent
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.migration.test.js
Labels: bug, exclude from changelog

#5459 imprv: v5 test for rename
  packages/app/test/integration/service/v5.page.test.ts
Labels: improvement

#5460 imprv: Hide rename menu item in /trash
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/PageList/PageList.tsx
Labels: exclude from changelog

#5461 imprv: Put back single renaming for v4
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/page.test.js
Labels: improvement, exclude from changelog

#5463 imprv: hide alert on first focus
  packages/app/src/components/Common/ClosableTextInput.tsx
Labels: improvement, exclude from changelog

#5467 imprv: revalidate pagelist and show toaster when page has been reverted
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/PageList/PageList.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PutbackPageModal.jsx
Labels: improvement, exclude from changelog

#5465 imprv: Tune ItemsTree socket conn performance
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: improvement, exclude from changelog

#5441 fix: 89052 VRT for Presentation modal
  packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
Labels: bug, exclude from changelog

#5470 fix: Domain whitelist is not respected (fix #5408)
  packages/app/src/server/routes/apiv3/personal-setting.js
Labels: bug

#5455 fix: 89241 Custom Sidebar
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
Labels: bug, exclude from changelog

#5469 feat: 89743 Rename from PageTree input
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: feature, exclude from changelog

#5471 imprv: change icon-plus size and the position
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_page-tree.scss
Labels: improvement, exclude from changelog

#5472 imprv: 89795 add cursor pointer to sort elm on search page
  packages/app/src/components/SearchPage/SearchControl.tsx
Labels: improvement

#5473 imprv: chnage fontsize of page item count
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_page-tree.scss
Labels: improvement, exclude from changelog

#5477 imprv: time to open page item directory
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: improvement, exclude from changelog

#5478 imprv: 89790 page item control style on pagelist
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/styles/_page_list.scss
  packages/app/src/styles/_subnav.scss
Labels: improvement, exclude from changelog

#5480 feat: Link back to ancestor group
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/interfaces/user-group-response.ts
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/stores/user-group.tsx
Labels: feature

#5449 imprv: vrt color mode switching
  .github/workflows/reusable-app-prod.yml
  packages/app/test/cypress/integration/4-switch-dark-mode/switch-dark-mode.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-home.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-user-settings.spec.ts
Labels: exclude from changelog

#5450 imprv: vrt sidebar mode switching
  .github/workflows/reusable-app-prod.yml
  packages/app/test/cypress/integration/5-switch-sidebar-mode/switching-sidebar-mode.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-home.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-user-settings.spec.ts
Labels: improvement, exclude from changelog

#5451 imprv: vrt home settings
  .github/workflows/reusable-app-prod.yml
  packages/app/test/cypress/integration/6-home-settings/access-home.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-user-settings.spec.ts
Labels: improvement

#5475 imprv: vrt other menu
  packages/app/test/cypress/integration/7-other-menu/changelog.spec.ts
  packages/app/test/cypress/integration/7-other-menu/create-edit-template.spec.ts
  packages/app/test/cypress/integration/7-other-menu/duplicate-page.spec.ts
  packages/app/test/cypress/integration/7-other-menu/export-page-in-markdown-format.spec.ts
  packages/app/test/cypress/integration/7-other-menu/presentation.spec.ts
Labels: exclude from changelog

#5481 fix: Path link anyone with link
  packages/app/src/server/routes/page.js
Labels: bug, exclude from changelog

#5474 imprv: 89859 Omit renderable props
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageTimeline.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
Labels: improvement, exclude from changelog

#5491 fix: Swiping to previous/next page for Mac users (5.0.x)
  packages/app/src/styles/_layout.scss
Labels: bug

#5483 fix: page list meta layout
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PageList/PageListItemS.jsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/ui/src/components/PagePath/PageListMeta.jsx
Labels: bug, exclude from changelog

#5493 fix: checkbox position on search page
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: exclude from changelog

#5489 imprv: add snippet highlight comment
  packages/app/src/server/service/search.ts
Labels: exclude from changelog

#5498 imprv: Modal for renaming and duplicating 2
  packages/app/src/components/ComparePathsTable.jsx
  packages/app/src/components/PageDuplicateModal.tsx
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/styles/molecules/compare-paths-table.scss
  packages/app/src/styles/style-app.scss
Labels: exclude from changelog

#5497 imprv: private legacy pages UI when it's hovered
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
Labels: improvement, exclude from changelog

#5499 fix: test empty page not included on normalize
  packages/app/src/server/service/page.ts
Labels: bug

#5505 fix: Normalize parent when empty pages already exist
  packages/app/src/server/models/page.ts
  packages/app/src/server/service/page.ts
Labels: bug, exclude from changelog

#5500 feat: 89977 Use the breadcrumb to display user groups
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/server/models/user-group.ts
  packages/app/src/server/routes/apiv3/user-group.js
Labels: feature, exclude from changelog

#5482 fix: Operate anyone-with-link pages
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/core/src/index.js
  packages/core/src/utils/page-utils.ts
Labels: bug, exclude from changelog

#5501 imprv: dark theme form color
  packages/app/src/styles/theme/_apply-colors-dark.scss
Labels: bug, exclude from changelog

#5318 imprv: Added VRT for opening sidebar pagetree
  packages/app/test/cypress/integration/2-basic-features/switch-sidebar-contents.spec.ts
Labels: improvement, exclude from changelog

#5504 imprv: btn-page-item-control ui
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/theme/_apply-colors.scss
Labels: improvement, exclude from changelog

#5486 feat: Maintenance mode
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/routes/apiv3/import.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/service/app.ts
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/views/forgot-password.html
  packages/app/src/server/views/maintenance-mode.html
Labels: feature

#5509 fix: Rename & shouldUseV4Process
  packages/app/src/server/service/page.ts
Labels: bug, exclude from changelog

#5508 imprv: show personal dropdown over search control
  packages/app/src/components/SearchPage/SearchControl.tsx
  packages/app/src/styles/_navbar.scss
  packages/app/src/styles/_variables.scss
Labels: improvement, exclude from changelog

#5485 feat(test-for-v5-migration): add test for normalize pages
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.migration.test.js
Labels: feature

#5510 feat(test-code): create test code base for non public page
  packages/app/test/integration/service/v5.non-public-page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: feature

#5512 imprv: sidebar bg-color for default light
  packages/app/src/styles/theme/default.scss
Labels: improvement, exclude from changelog

#5513 imprv: pagetree count colors
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
Labels: improvement, exclude from changelog

#5516 imprv: Prepare UserGroup for integration test
  packages/app/test/integration/service/v5.non-public-page.test.ts
Labels: improvement

#5515 fix: Normalize parent with empty pages
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.migration.test.js
Labels: bug, exclude from changelog

#5517 fix: 89954 rename input and count position
  packages/app/src/components/Common/ClosableTextInput.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5514 imprv: test code revert non public page
  packages/app/test/integration/service/v5.non-public-page.test.ts
Labels: improvement

#5502 imprv: add space btw page list meta and page view control
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
Labels: improvement

#5519 support: improve tsconfig for prod build
  packages/app/tsconfig.build.server.json
  packages/codemirror-textlint/tsconfig.build.json
  packages/core/tsconfig.build.cjs.json
  packages/core/tsconfig.build.esm.json
  packages/plugin-attachment-refs/tsconfig.build.cjs.json
  packages/plugin-attachment-refs/tsconfig.build.esm.json
  packages/plugin-lsx/tsconfig.build.cjs.json
  packages/plugin-lsx/tsconfig.build.esm.json
  packages/plugin-pukiwiki-like-linker/tsconfig.build.cjs.json
  packages/plugin-pukiwiki-like-linker/tsconfig.build.esm.json
  packages/slack/tsconfig.build.json
  packages/slackbot-proxy/tsconfig.build.json
  packages/ui/tsconfig.build.json
Labels: exclude from changelog

#5476 feat: Auto scroll pagetree on init
  packages/app/config/logger/config.dev.js
  packages/app/package.json
  packages/app/src/components/Sidebar.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/StickyStretchableScroller.jsx
  packages/app/src/components/StickyStretchableScroller.tsx
  packages/app/src/components/TableOfContents.jsx
  packages/app/src/interfaces/page-listing-results.ts
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_override-simplebar.scss
  packages/app/src/styles/_sidebar.scss
  packages/app/src/styles/_vendor.scss
  packages/app/src/styles/style-app.scss
  packages/app/test/cypress/integration/1-install/install.spec.ts
  packages/app/test/cypress/support/index.ts
  yarn.lock
Labels: bug, feature

#5520 improve sedebar bgColor on default dark
  packages/app/src/styles/theme/default.scss
Labels: improvement, exclude from changelog

#5522 imprv: 90334 apply btn-page-item-control to button-outline-variant
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
Labels: improvement

#5479 feat: 89895 Show spinner until rename request is complete
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: feature, exclude from changelog

#5524 imprv: 90335 triangle btn color with button-outline-svg-icon-variant
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_mixins.scss
  packages/app/src/styles/_page-tree.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
Labels: improvement, exclude from changelog

#5525 fix: Too many retrieving pageinfo
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
Labels: exclude from changelog

#5530 fix: scroll target item class name
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: bug, exclude from changelog

#5534 fix: modify sentence on rename modal
  packages/app/resource/locales/en_US/translation.json
Labels: bug

#5531 imprv: i18n maintenance mode
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
  packages/app/src/components/Admin/App/ConfirmModal.tsx
  packages/app/src/components/Admin/App/MaintenanceMode.tsx
Labels: improvement

#5535 fix: hide plus btn on page tree item if the item is user page
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5532 feat: 90457 Show spinner until page tree has finished loading
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
Labels: feature, exclude from changelog

#5533 fix: Update parent after page update & remove unnecessary empty pages
  packages/app/src/server/models/page.ts
Labels: bug, exclude from changelog

#5537 fix: isCreatablePage pattern
  packages/core/src/utils/page-path-utils.ts
Labels: bug, exclude from changelog

#5536 imprv: #90521: rename page tree rename control label
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: improvement, exclude from changelog

#5527 feat: Delete permission config
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
  packages/app/src/interfaces/page-delete-config.ts
  packages/app/src/migrations/20220311011114-convert-page-delete-config.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
Labels: feature

#5541 feat: 90556 add logout
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/server/views/maintenance-mode.html
Labels: feature

#5539 imprv: isDraggable variable
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug

#5538 fix(i18n): use same words
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/V5PageMigration.tsx
Labels: bug, exclude from changelog

#5526 feat: Maintenance mode
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminAppContainer.js
  packages/app/src/client/services/AdminHomeContainer.js
  packages/app/src/components/Admin/AdminHome/AdminHome.jsx
  packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
  packages/app/src/components/Admin/App/ConfirmModal.tsx
  packages/app/src/components/Admin/App/MaintenanceMode.tsx
  packages/app/src/components/Admin/App/V5PageMigration.tsx
  packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
  packages/app/src/server/routes/apiv3/admin-home.js
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/routes/apiv3/import.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/service/app.ts
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/views/forgot-password.html
  packages/app/src/server/views/maintenance-mode.html
Labels: feature

#5546 imprv: empty page operation collection
  packages/app/src/server/crowi/index.js
  packages/app/src/server/service/page-operation.ts
Labels: improvement

#5529 feat: 90117 Show spinner until create request is complete
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: feature, exclude from changelog

#5555 fix: Hide spinner after page creation failure
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5559 imprv: 90547 show err on page create modal
  packages/app/src/components/PageCreateModal.jsx
Labels: improvement, exclude from changelog

#5560 imprv: show specific err reason on put back modal
  packages/app/src/server/routes/page.js
Labels: improvement, exclude from changelog

#5554 feat: Update UserGroups from modal
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
Labels: feature

#5547 imprv: vrt delete bootstrap4
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/test/cypress/integration/2-basic-features/open-page-delete-modal.spec.ts
Labels: improvement

#5563 imprv: Disable upcoming VRT, wait until all VRT ready
  .github/workflows/reusable-app-prod.yml
Labels: improvement

#5562 imprv: update validator version
  packages/app/package.json
  yarn.lock
Labels: improvement

#5550 imprv: cannnot drop page item under user home page directory
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: improvement, exclude from changelog

#5553 imprv: show error message in case page path is set directory under user page
  packages/app/src/components/PageRenameModal.tsx
Labels: bug, exclude from changelog

#5552 imprv: add test for updatePage
  packages/app/test/integration/models/v5.page.test.js
Labels: improvement

#5548 fix: show page tree properly
  packages/app/src/server/models/page.ts
  packages/app/test/integration/models/v5.page.test.js
Labels: bug

#5216 imprv: update nanoid yarn.lock v3.1.30 to v3.2.0
  yarn.lock
Labels: improvement

#5204 imprv: dependabot dot-drop
  yarn.lock
Labels: improvement

#5333 imprv: dependabot ajv
  yarn.lock
Labels: improvement

#5335 imprv: dependabot extend
  yarn.lock
Labels: improvement

#5569 imprv: Switch sidebar tabs' position
  packages/app/src/components/Sidebar/SidebarContents.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement, exclude from changelog

#5565 feat: Change parent from form
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/interfaces/user-group-response.ts
  packages/app/src/server/routes/admin.js
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/stores/user-group.tsx
Labels: feature, exclude from changelog

#5352 imprv: dependabot highlight.js
  yarn.lock
Labels: improvement

#5337 imprv: dependabot @npmcli/git
  yarn.lock
Labels: improvement

#5336 imprv: dependabot trim-off-newlines
  yarn.lock
Labels: improvement

#5572 fix: 90801 Close modal if Update / Create is successful
  packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
Labels: bug, exclude from changelog

#5578 fix: Normalize parent add test and fix
  packages/app/src/components/LegacyPrivatePagesMigrationModal.tsx
  packages/app/src/server/interfaces/page-operation.ts
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/page-grant.test.js
  packages/app/test/integration/service/v5.migration.test.js
Labels: bug, exclude from changelog

#5521 imprv: test code rename non public
  packages/app/test/integration/service/v5.non-public-page.test.ts
Labels: improvement

#5215 imprv: update yarn git-hosted-info v2.8.8 to v2.8.9
  yarn.lock
Labels: improvement

#5581 imprv: Validate deletion settings
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
  packages/app/src/interfaces/page-delete-config.ts
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/service/page.ts
  packages/app/src/utils/page-delete-config.ts
  packages/app/test/unit/utils/page-delete-config.test.ts
Labels: improvement

#5588 feat: Release parent group
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
Labels: feature, exclude from changelog

#5595 fix: Remove "Anyone with the link page" completely
  packages/app/src/components/Page/TrashPageAlert.jsx
Labels: bug, exclude from changelog

#5592 feat: SecuritySetting UI
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
Labels: feature, exclude from changelog

#5583 imprv: SearchTypeahead
  packages/app/package.json
  packages/app/src/client/interfaces/react-bootstrap-typeahead.ts
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/PageCreateModal.jsx
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/PageEditor/PreviewWithSuspense.jsx
  packages/app/src/components/PagePathAutoComplete.jsx
  packages/app/src/components/SearchForm.tsx
  packages/app/src/components/SearchPage/SearchControl.tsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/stores/search.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/_reboot-bootstrap-dropdown.scss
  packages/app/src/styles/theme/antarctic.scss
  packages/app/src/styles/theme/blackboard.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/default.scss
  packages/app/src/styles/theme/fire-red.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/halloween.scss
  packages/app/src/styles/theme/hufflepuff.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/jade-green.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mono-blue.scss
  packages/app/src/styles/theme/nature.scss
  packages/app/src/styles/theme/spring.scss
  packages/app/src/styles/theme/wood.scss
  yarn.lock
Labels: improvement, exclude from changelog

#5596 fix: fix i18n for maintenance mode
  packages/app/src/components/Admin/AdminHome/AdminHome.jsx
Labels: bug

#5597 feat: Add caution in modal to delete child group
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
Labels: feature, exclude from changelog

#5598 imprv: envvar to select elasticsearch version
  .github/workflows/reusable-app-prod.yml
  packages/app/.env.development
  packages/app/package.json
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  yarn.lock
Labels: exclude from changelog

#5590 imprv: remove expectalltobetruthy
  packages/app/test/integration/service/v5.migration.test.js
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: improvement

#5585 imprv: add test for delete completely
  packages/app/test/integration/service/v5.non-public-page.test.ts
Labels: bug

#5607 fix: Add healthcheck to admin router
  packages/app/src/server/routes/apiv3/index.js
Labels: bug, exclude from changelog

#5564 imprv: test code for delete non public page
  packages/app/test/integration/service/v5.non-public-page.test.ts
Labels: improvement

#5566 Fix: enable to reflect like and bookmark count
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/ui/src/components/PagePath/PageListMeta.jsx
Labels: bug, exclude from changelog

#5610 feat: Force update ancestor groups
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/interfaces/user.ts
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/server/service/user-group.ts
  packages/app/src/stores/modal.tsx
Labels: feature

#5614 imprv: Add description for user addition
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.jsx
Labels: improvement

#5612 imprv: Usergroup confirm modal i18n design
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
Labels: improvement

#5616 imprv: Item Count Badge
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_page-tree.scss
Labels: improvement, exclude from changelog

#5618 feat: Usergroup force update option
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.jsx
  packages/app/src/interfaces/user.ts
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/server/service/user-group.ts
  packages/app/src/stores/modal.tsx
Labels: feature

#5617 imprv: Show v5 migration status with a progress bar
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Admin/App/V5PageMigration.tsx
  packages/app/src/interfaces/websocket.ts
  packages/app/src/server/service/page.ts
  packages/app/src/stores/websocket.tsx
Labels: improvement, exclude from changelog

#5620 fix: Tags input
  packages/app/src/components/Page/TagsInput.jsx
  packages/app/src/components/Page/TagsInput.tsx
  packages/app/src/interfaces/tag.ts
Labels: bug, exclude from changelog

#5622 fix: Rendering with contexts
  packages/app/resource/locales/en_US/sandbox.md
  packages/app/resource/locales/ja_JP/sandbox.md
  packages/app/resource/locales/zh_CN/sandbox.md
  packages/app/src/client/util/GrowiRenderer.js
  packages/app/src/client/util/interceptor/detach-code-blocks.js
  packages/app/src/client/util/reveal/plugins/growi-renderer.js
  packages/app/src/components/MyDraftList/Draft.jsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageComment/Comment.jsx
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/PageEditor/Preview.jsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/components/PageEditor/PreviewWithSuspense.jsx
  packages/app/src/components/PageTimeline.jsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_on-edit.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPostRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js
  packages/plugin-pukiwiki-like-linker/src/resource/js/util/PreProcessor/PukiwikiLikeLinker.js
Labels: bug, exclude from changelog

#5621 fix: Hide snippet when private
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/interfaces/search.ts
  packages/app/src/server/routes/search.js
  packages/app/src/server/service/search.ts
Labels: bug, exclude from changelog

#5185 feat: gw7660 upgrade openid client
  packages/app/package.json
  packages/app/src/server/service/passport.ts
  yarn.lock
Labels: feature

#5629 fix: Redering preview
  packages/app/src/components/PageEditor.jsx
Labels: bug, exclude from changelog

#5619 fix: remove em tag from page path to be displayed
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PagePathHierarchicalLink.jsx
  packages/app/src/server/service/search.ts
Labels: bug, exclude from changelog

#5625 fix: Search highlight snippet
  packages/app/src/server/routes/search.js
  packages/app/src/server/service/search.ts
  packages/app/src/utils/page-delete-config.ts
Labels: bug, exclude from changelog

#5630 fix: Displaying minimum length of password
  packages/app/src/server/middlewares/register-form-validator.ts
  packages/app/src/server/routes/apiv3/user-activation.ts
Labels: bug

#5634 fix: display kibana v7 on growi v5 in dev
  .devcontainer/docker-compose.yml
Labels: bug, exclude from changelog

#5635 fix: Create modal auto fill page path
  packages/app/src/components/Fab.jsx
  packages/app/src/components/Hotkeys/Subscribers/CreatePage.jsx
Labels: bug, exclude from changelog

#5636 fix: Show full text on presentation mode
  packages/app/src/styles/style-presentation.scss
Labels: bug

#5637 fix: explanation
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
Labels: bug

#5611 imprv: Security Setting UI
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
Labels: improvement, exclude from changelog

#5640 support: Improve VRT efficiency
  .github/workflows/reusable-app-prod.yml
  packages/app/test/cypress/integration/2-basic-features/access-to-me-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-special-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/open-page-create-modal.spec.ts
  packages/app/test/cypress/integration/2-basic-features/open-page-delete-modal.spec.ts
  packages/app/test/cypress/integration/2-basic-features/open-page-duplicate-modal.spec.ts
  packages/app/test/cypress/integration/2-basic-features/open-page-move-rename-modal.spec.ts
  packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
  packages/app/test/cypress/integration/2-basic-features/switch-sidebar-contents.spec.ts
  packages/app/test/cypress/integration/2-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/3-search/access-to-private-legacy-pages-directly.spec.ts
  packages/app/test/cypress/integration/3-search/search.spec.ts
  packages/app/test/cypress/integration/4-admin/access-to-admin-page.spec.ts
  packages/app/test/cypress/support/commands.ts
Labels: support, exclude from changelog
