Repository growilabs/growi, pull requests merged in 2022-02, with the labels that each got.

#5211 fix: /_api/v3/page with pageId param occurs an 500 error (merge into master)
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page.js
Labels: bug

#5218 imprv: Sidebar opening delay (merge into master)
  packages/app/src/components/Sidebar.tsx
Labels: improvement, exclude from changelog

#5195 imprv: add kibana docker image
  .devcontainer/docker-compose.yml
Labels: improvement

#5214 support: Replace esa-nodejs with esa-node
  packages/app/package.json
  packages/app/src/server/util/importer.js
  yarn.lock
Labels: support, feature, breaking

#5267 imprv: show deleteModal from sub navigation bar
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement

#5287 feat: API delete multiple pages & improve deleteModalStatus
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/SearchPage.jsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/common.ts
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/stores/ui.tsx
  packages/app/test/integration/service/v5-migration.test.js
  packages/core/src/utils/page-path-utils.ts
Labels: feature

#5268 imprv: show renameModal from sub navigation bar
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement

#5269 imprv: show duplicateModal from sub navigation bar
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement

#5292 feat: Rename(Move) by Drag & Drop
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: feature

#5290 fix: Fixed duplicate route
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug, exclude from changelog

#5281 imprv: rename modal with swr
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: improvement

#5278 feat: 87755 Use SWR to display duplicate modal (search dropdown)
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: feature

#5296 imprv: Limit pages to validate grant at once
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
Labels: improvement, exclude from changelog

#5297 fix: Change pagetitle links to parmanent url
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: bug, exclude from changelog

#5270 imprv: 87816 show presentation modal from sub navigation bar
  packages/app/src/client/base.jsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PagePresentationModal.jsx
  packages/app/src/server/views/layout/layout.html
  packages/app/src/stores/ui.tsx
Labels: improvement, exclude from changelog

#5289 fix: Regression fo codemirror commonization
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/PageEditor/AbstractEditor.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/UncontrolledCodeMirror.tsx
Labels: bug

#5208 feat: Scroll into highlighted word in search result page
  packages/app/src/components/Page/RevisionBody.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: feature

#5306 imprv: 88215 refactoring modals
  packages/app/src/components/DescendantsPageListModal.tsx
  packages/app/src/components/Fab.jsx
  packages/app/src/components/Hotkeys/Subscribers/CreatePage.jsx
  packages/app/src/components/IdenticalPathPage.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/PageManagement.jsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/components/PageCreateModal.jsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/PageDuplicateModal.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PagePresentationModal.jsx
  packages/app/src/components/PageRenameModal.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement

#5298 feat: Create page from PageTree
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Common/ClosableTextInput.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/server/models/revision.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/util/swigFunctions.js
  packages/app/src/server/views/widget/not_found_content.html
  packages/core/src/utils/path-utils.js
Labels: feature

#5302 feat: Update descendant count by normalize parent
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/core/src/utils/page-path-utils.ts
Labels: feature, exclude from changelog

#5310 fix: UserGroup model updateGroup method
  packages/app/src/server/service/user-group.ts
Labels: bug, exclude from changelog

#5309 feat: 88142 Remove the display from PageTree when a page is deleted
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: feature, exclude from changelog

#5308 feat: 88096 Show delete and duplicate in empty pages
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
Labels: feature, exclude from changelog

#5315 imprv: refactor search page
  packages/app/src/client/app.jsx
  packages/app/src/client/interfaces/selectable-all.ts
  packages/app/src/components/IdenticalPathPage.tsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PaginationWrapper.tsx
  packages/app/src/components/SearchPage.jsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
  packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
  packages/app/src/components/SearchPage/OperateAllControl.tsx
  packages/app/src/components/SearchPage/SearchControl.tsx
  packages/app/src/components/SearchPage/SearchOptionModal.tsx
  packages/app/src/components/SearchPage/SearchPageLayout.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage/SortControl.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/interfaces/search.ts
  packages/app/src/server/interfaces/search.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/service/search-delegator/private-legacy-pages.ts
  packages/app/src/server/service/search.ts
  packages/app/src/stores/search.tsx
  packages/app/src/styles/_search.scss
  packages/app/src/styles/atoms/_custom_control.scss
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/3-search/access-to-result-page-directly.spec.ts
Labels: improvement, exclude from changelog

#5314 imprv: 87936 switch delete modal ui of pagetree pageItemControl
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
Labels: improvement, exclude from changelog

#5317 imprv: Add edit page test
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
Labels: improvement

#5319 feat: add draft page vrt
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
Labels: feature

#5320 feat: add tags page vrt
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
Labels: feature

#5321 imprv: Add visual regression test
  packages/app/test/cypress/integration/2-basic-features/access-to-admin-page.spec.ts
Labels: improvement

#5323 imprv: Added VRT for me page
  packages/app/test/cypress/integration/2-basic-features/access-to-me-page.spec.ts
Labels: improvement

#5324 imprv: page access test trash
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
Labels: improvement

#5299 imprv: show delete modal in PageListItemLwith swr
  packages/app/src/components/IdenticalPathPage.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
Labels: looking for implementers, improvement

#5342 fix: trash page
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/DescendantsPageListModal.tsx
  packages/app/src/components/ForbiddenPage.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/TrashPageList.jsx
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/views/layout-growi/page_list.html
Labels: exclude from changelog

#5295 feat: 87970 List child groups
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/admin.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/interfaces/user-group-response.ts
  packages/app/src/server/routes/admin.js
  packages/app/src/server/service/user-group.ts
  packages/app/src/stores/context.tsx
  packages/app/src/stores/user-group.tsx
Labels: feature, exclude from changelog

#5340 fix: 88258 Prevent items hidden when dropped outside the PageTree
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5346 imprv: VRT tests
  .github/workflows/reusable-app-prod.yml
  packages/app/config/ci/.env.local.for-auto-install
  packages/app/config/ci/.env.local.for-ci
Labels: exclude from changelog

#5350 imprv: Create page
  packages/app/src/server/models/page.ts
Labels: bug, exclude from changelog

#5326 feat: vrt test for create page modal
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/PageCreateModal.jsx
  packages/app/test/cypress/integration/2-basic-features/create-page.spec.ts
Labels: feature, exclude from changelog

#5351 imprv: vrt tests
  packages/app/config/ci/.env.local.for-auto-install
  packages/app/resource/search/mappings-es6-for-ci.json
  packages/app/src/client/app.jsx
  packages/app/src/components/Admin/AdminHome/AdminHome.jsx
  packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/ExportArchiveDataPage.jsx
  packages/app/src/components/Admin/FullTextSearchManagement.jsx
  packages/app/src/components/Admin/ImportData/ImportDataPageContents.jsx
  packages/app/src/components/Admin/LegacySlackIntegration/LegacySlackIntegration.jsx
  packages/app/src/components/Admin/MarkdownSetting/MarkDownSettingContents.jsx
  packages/app/src/components/Admin/Notification/NotificationSetting.jsx
  packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
  packages/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserManagement.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/components/TrashPageList.jsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/installer.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/views/layout-growi/page_list.html
  packages/app/src/server/views/tags.html
  packages/app/test/cypress/integration/2-basic-features/access-to-admin-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-me-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-special-page.spec.ts
  packages/app/test/cypress/integration/3-search/access-to-result-page-directly.spec.ts
Labels: exclude from changelog

#5325 feat: 88078 i18n & delete toastSuccess
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: feature, exclude from changelog

#5339 imprv: switch delete modal ui of GrowiContextualSubNavigation
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
Labels: improvement

#5347 support: Separate DB for v4 and v5 test
  .github/workflows/ci-app.yml
  packages/app/jest.config.js
  packages/app/package.json
  packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  packages/app/test/integration/global-setup.js
  packages/app/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  packages/app/test/integration/service/page-grant.test.js
  packages/app/test/integration/service/v5.migration.test.js
Labels: support

#5280 support: Add args to choose ES version on docker-compose.yml for devcontainer
  .devcontainer/docker-compose.yml
  packages/app/.env.development
Labels: support

#5329 imprv: 88321 restoration deleted sentence on page delete modal
  packages/app/src/components/PageDeleteModal.tsx
Labels: improvement, exclude from changelog

#5362 fix: navigate user to pages correctly
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5356 imprv: switch delete modal ui of search result content
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: improvement, exclude from changelog

#5365 imprv: add i18n
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: improvement, exclude from changelog

#5359 imprv: show delete compreatly modal on trash page
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageDeleteModal.tsx
Labels: improvement, exclude from changelog

#5358 feat: Migrate page format from v4 to v5 on private legacy pages
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/app.jsx
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/LegacyPrivatePagesMigrationModal.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/views/private-legacy-pages.html
  packages/app/src/server/views/search.html
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/search.tsx
  packages/app/src/styles/_override-bootstrap.scss
  packages/app/test/cypress/integration/3-search/access-to-private-legacy-pages-directly.spec.ts
  packages/core/src/test/util/page-path-utils.test.js
  packages/core/src/utils/page-path-utils.ts
Labels: feature

#5368 fix: 88632 Prevent duplication with not creatable paths
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug, exclude from changelog

#5369 feat: 88261 Add header to the body of the page
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/stores/context.tsx
Labels: feature, exclude from changelog

#5374 fix: Header for PrivateLegacyPage overlaps search help dropdown
  packages/app/src/components/PrivateLegacyPages.tsx
Labels: bug, exclude from changelog

#5372 imprv: 88686 Pass boolean with props
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: improvement, exclude from changelog

#5363 fix: not allow user page to be moved
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page.ts
Labels: bug, exclude from changelog

#5373 fix: Page view count stops at 15
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/User/SeenUserInfo.tsx
Labels: bug, exclude from changelog

#5375 fix: Call mutate to update siblings after deletion
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: bug

#5253 imprv: Page v5 test code rename
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.page.test.ts
Labels: improvement

#5377 fix: Show only migratable pages
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/search-delegator/private-legacy-pages.ts
Labels: bug, exclude from changelog

#5330 imprv: Page v5 test code delete completely
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.page.test.ts
Labels: improvement

#5348 imprv: page model v5 test create
  packages/app/test/integration/models/v5.page.test.js
Labels: improvement

#5379 imprv: can open global putback page modal
  packages/app/src/client/base.jsx
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout/layout.html
  packages/app/src/stores/modal.tsx
Labels: improvement

#5301 imprv: page v5 test code duplication
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.page.test.ts
Labels: improvement

#5382 fix: No throw when PageRedirect insertion dup key error
  packages/app/src/server/service/page.ts
Labels: bug, exclude from changelog

#5384 support: refactor page-path-utils and PageService.findPageAndMetaDataByViewer
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/subscription.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
  packages/app/test/integration/models/page.test.js
  packages/core/src/test/util/page-path-utils.test.js
  packages/core/src/utils/page-path-utils.ts
Labels: exclude from changelog

#5355 imprv: switch delete modal ui of pageListItemL
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
Labels: improvement

#5385 imprv: Refactor PageDeleteModal
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/server/service/page.ts
  packages/app/src/stores/modal.tsx
Labels: exclude from changelog

#5383 imprv: get PageInfo from PageItemControl
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/stores/modal.tsx
Labels: improvement, exclude from changelog

#5386 fix: show highlight on paths
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PagePathHierarchicalLink.jsx
Labels: bug, exclude from changelog

#5387 fix: PageDeleteModal force completely deletion mode
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/stores/modal.tsx
Labels: bug, exclude from changelog

#5354 imprv: page v5 test code revert
  .github/workflows/ci-app.yml
  packages/app/jest.config.js
  packages/app/src/server/service/page.ts
  packages/app/test/integration/global-setup.js
  packages/app/test/integration/models/v5.page.test.js
  packages/app/test/integration/service/v5.page.test.ts
Labels: improvement

#5388 imprv: Revalidate after deletion
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageList/PageList.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/ui.ts
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/page-listing.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/search.tsx
  packages/app/src/stores/use-static-swr.tsx
Labels: exclude from changelog

#5392 imprv: Revalidate after deletion
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/server/models/page.ts
Labels: exclude from changelog

#5390 imprv: 88785 refactoring page rename modal
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PageRenameModal.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
Labels: improvement, exclude from changelog

#5393 feat: Page operation block (The first stage)
  packages/app/src/server/crowi/index.js
  packages/app/src/server/interfaces/page-operation.ts
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/models/page-redirect.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/page.test.js
  packages/app/test/integration/service/v5.migration.test.js
  packages/app/test/integration/service/v5.page.test.ts
Labels: feature, exclude from changelog

#5391 imprv: refactoring page duplicate modal
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/PageDuplicateModal.jsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PagePathAutoComplete.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
Labels: improvement

#5394 support: merge rc/5.0.x into master
  lerna.json
  package.json
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#5395 fix: Reset offset when search
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/server/service/search-delegator/private-legacy-pages.ts
Labels: exclude from changelog

#5396 imprv: PageTree dropdown (hide only buttons, show dropdown menu always)
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_page-tree.scss
Labels: exclude from changelog

#5399 fix: Delete trash page recursively
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/server/models/page.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/page.test.js
Labels: bug

#5400 fix: 88961 Insert page title header
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5397 feat: Modal to create UserGroup
  packages/app/src/components/Admin/UserGroup/UserGroupCreateModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
Labels: feature

#5370 fix: 88924 Show presentation modal in top page
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
Labels: bug, exclude from changelog

#5403 fix: Renaming to under target
  packages/app/src/server/models/page.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/global-setup.js
Labels: bug, exclude from changelog

#5402 fix: 88620 background color of plus button on pagetree and padding adjustment
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug

#5406 fix: Layer stack of grw-navigation-resize-button
  packages/app/src/styles/_sidebar.scss
  packages/app/test/cypress/support/commands.ts
Labels: exclude from changelog

#5410 fix: Subordinated list api for empty pages
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PageDuplicateModal.jsx
  packages/app/src/components/PageRenameModal.jsx
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug, exclude from changelog

#5411 fix: Bookmark operation
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/server/routes/apiv3/bookmarks.js
  packages/app/src/server/service/page.ts
  packages/app/src/stores/page.tsx
Labels: exclude from changelog

#5413 fix: remove dead links from README
  README.md
  README_JP.md
Labels: bug, exclude from changelog

#5405 feat: 88978 Display user group create modal in detail screen
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
Labels: feature, exclude from changelog

#5416 fix: 89241 open rename modal
  packages/app/src/components/PageRenameModal.jsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug, exclude from changelog

#5417 imprv: Utilize canMoveByPath
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/core/src/utils/page-path-utils.ts
Labels: improvement, exclude from changelog

#5415 fix: 88984 Prevent rendering of revision on empty pages
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
Labels: bug, exclude from changelog

#5420 fix: Item component canDrop handler and improve pageItemDropHandler
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: exclude from changelog

#5418 imprv: revalidate when page has been renamed
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PageRenameModal.jsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/ui.ts
  packages/app/src/stores/modal.tsx
Labels: improvement, exclude from changelog

#5422 imprv: 88871 revalidate after duplication on pagetree
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PageDuplicateModal.jsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/ui.ts
  packages/app/src/stores/modal.tsx
Labels: improvement, exclude from changelog

#5424 imprv: show toastr on delete
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement, exclude from changelog

#5345 fix: 87983 88132 access empty page with page URL
  packages/app/src/server/routes/page.js
Labels: bug, exclude from changelog

#5431 imprv: revalidate when page has been duplicated on search result content
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement, exclude from changelog

#5432 imprv: revalidate when page has been deleted
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: improvement, exclude from changelog

#5433 imprv: reload page when page has been renamed on growi contextual subnavigation
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: improvement, exclude from changelog

#5434 imprv: revalidate after page has been duplicated
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
Labels: improvement, exclude from changelog

#5435 imprv: 89046 reload after page has been duplicated on growi contextual subnavgation
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageDuplicateModal.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/ui.ts
Labels: improvement

#5438 Imprv: PageDeleteModal fetching pageinfo
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/IdenticalPathPage.tsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/PageList/PageList.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/interfaces/search.ts
  packages/app/src/server/middlewares/apiv3-form-validator.ts
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/routes/apiv3/attachment.js
  packages/app/src/server/routes/apiv3/bookmarks.js
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/server/routes/apiv3/export.js
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/apiv3/markdown-setting.js
  packages/app/src/server/routes/apiv3/notification-setting.js
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/server/routes/apiv3/revisions.js
  packages/app/src/server/routes/apiv3/search.js
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/routes/apiv3/share-links.js
  packages/app/src/server/routes/apiv3/slack-integration-legacy-settings.js
  packages/app/src/server/routes/apiv3/slack-integration-settings.js
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/server/routes/apiv3/user-ui-settings.ts
  packages/app/src/server/routes/apiv3/users.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/search.ts
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/page.tsx
Labels: exclude from changelog

#5427 fix: show revision body
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageTimeline.jsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: bug, exclude from changelog

#5430 fix: Permalink not found
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Page/NotFoundAlert.tsx
  packages/app/src/interfaces/page-listing-results.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/page.js
  packages/app/src/server/views/layout-growi/not_found.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: bug, exclude from changelog

#5442 fix: Elasticsearch sort query
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: bug, exclude from changelog

#5443 fix: highlight when search
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage2/SearchPageBase.tsx
  packages/app/src/styles/theme/_apply-colors.scss
Labels: exclude from changelog

#5445 fix: TrashPageAlert.openPageDeleteModalHandler
  packages/app/src/components/Page/TrashPageAlert.jsx
Labels: exclude from changelog

#5439 fix: 88633 movable user pages on pagetree
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/core/src/utils/page-path-utils.ts
Labels: bug, exclude from changelog

#5444 fix: Rename to under descendant
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
Labels: bug, exclude from changelog

#5414 fix: 89163 Do not highlight empty body pages in search results.
  packages/app/src/components/Page/RevisionRenderer.jsx
Labels: bug, exclude from changelog

#5447 fix: pagetree item state
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/page-listing.tsx
Labels: exclude from changelog

#5448 fix: 89534
  packages/app/src/components/Page/RevisionRenderer.jsx
Labels: bug, exclude from changelog
