Repository growilabs/growi, pull requests merged in 2022-12, with the labels that each got.

#7022 imprv: Run lerna build production before run cypress ci
  .github/workflows/reusable-app-prod.yml
Labels: improvement

#6975 feat: Create error handler for external account
  packages/app/src/components/LoginForm.tsx
  packages/app/src/interfaces/errors/external-account-login-error.ts
  packages/app/src/models/vo/external-account-login-error.ts
  packages/app/src/pages/login.page.tsx
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
Labels: feature

#7023 imprv: Support multibyte characters with growi-directive
  packages/remark-growi-plugin/src/micromark-extension-growi-plugin/lib/factory-attributes.js
  packages/remark-growi-plugin/test/micromark-extension-growi-plugin.test.js
Labels: exclude from changelog

#7016 fix: Language Dropdown UI
  packages/app/src/components/InstallerForm.tsx
  packages/app/src/components/Layout/NoLoginLayout.module.scss
Labels: bug

#7025 fix: CI Cypress
  .github/workflows/reusable-app-prod.yml
Labels: bug

#7020 fix: Add serverside translation function
  packages/app/src/pages/tags.page.tsx
Labels: bug

#6641 support: fix dependabot alert jpeg-js
  yarn.lock
Labels: support

#7014 fix: Normalize VRT (20-basic-features)
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#7028 feat: Optimize table component rerendering on Preview
  packages/app/src/components/ReactMarkdownComponents/Table.tsx
  packages/app/src/services/renderer/remark-plugins/table.ts
  packages/app/src/services/renderer/renderer.tsx
Labels: feature

#7021 feat: Update cypress 10 install
  packages/app/test/cypress/integration/10-install/install.spec.ts
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: feature

#7019 fix: sandbox math toc vrt
  packages/app/src/components/TableOfContents.tsx
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: bug

#7024 fix: Err messages on Duplicated Modal
  packages/app/src/components/PageDuplicateModal.tsx
Labels: bug

#7033 fix: text-truncate does not work on Recent Changes
  packages/app/src/components/Sidebar/RecentChanges.tsx
Labels: bug

#7032 fix: Infinity Spinner of Page Item Control on Trash Page List
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: bug

#7031 fix: Omit /register api
  packages/app/src/server/routes/index.js
Labels: bug

#7026 fix: Unable to update pages that have already been created
  packages/app/src/components/PageEditor.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#7029 fix: Attach create modal style
  packages/app/src/components/CreateTemplateModal.jsx
  packages/app/src/components/EmptyTrashModal.tsx
  packages/app/src/components/PageAlert/FixPageGrantAlert.tsx
  packages/app/src/components/PageCreateModal.jsx
  packages/app/src/components/PageCreateModal.module.scss
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/PrivateLegacyPagesMigrationModal.tsx
  packages/app/src/components/PutbackPageModal.jsx
Labels: bug

#7042 fix: Custom sidebar does not appear on certain pages
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
Labels: bug

#7034 feat: New plugin
  packages/app/bin/templates/plugin-definitions.js.swig
  packages/app/package.json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/client/services/AdminHomeContainer.js
  packages/app/src/client/services/activate-plugin.ts
  packages/app/src/components/Admin/AdminHome/AdminHome.jsx
  packages/app/src/components/Admin/AdminHome/InstalledPluginTable.jsx
  packages/app/src/components/Admin/Common/AdminInstallButtonRow.tsx
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/PluginsExtension/Loading.js
  packages/app/src/components/Admin/PluginsExtension/PluginCard.module.scss
  packages/app/src/components/Admin/PluginsExtension/PluginCard.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginInstallerForm.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginsExtensionPageContents.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/EditorIcon.jsx
  packages/app/src/components/TemplateModal.tsx
  packages/app/src/components/TemplateTab.tsx
  packages/app/src/components/Theme/ThemeDefault.global.scss
  packages/app/src/components/Theme/ThemeDefault.tsx
  packages/app/src/components/Theme/utils/ThemeInjector.tsx
  packages/app/src/interfaces/github-api.ts
  packages/app/src/interfaces/plugin.ts
  packages/app/src/pages/_app.page.tsx
  packages/app/src/pages/_document.page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/pages/admin/plugins.page.tsx
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/growi-plugin.ts
  packages/app/src/server/plugins/plugin-utils.js
  packages/app/src/server/routes/apiv3/admin-home.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/plugins-extention.ts
  packages/app/src/server/service/plugin.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/stores/template.tsx
  packages/app/src/stores/useInstalledPlugins.ts
  packages/app/src/utils/growi-facade.ts
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
  packages/core/src/index.ts
  packages/core/src/interfaces/growi-facade.ts
  packages/core/src/interfaces/template.ts
Labels: feature

#7030 fix: Can transition to installer page with installed GROWI
  packages/app/src/server/middlewares/application-not-installed.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/index.js
Labels: bug

#7043 fix: Global Search component is shown after moving to admin page
  packages/app/src/components/Layout/AdminLayout.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
Labels: bug

#6931 support: next page status alert
  packages/app/_obsolete/src/client/services/PageContainer.js
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.jsx
  packages/app/src/components/PageStatusAlert.module.scss
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/interfaces/websocket.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/hackmd.ts
  packages/app/src/stores/page.tsx
  packages/app/src/stores/remote-latest-page.ts
  packages/app/src/stores/websocket.tsx
  packages/app/src/styles/_page.scss
Labels: support

#7036 fix: Login users able to access invited page
  packages/app/src/pages/invited.page.tsx
Labels: bug

#7046 fix: CommentEditor
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageEditor/LinkEditModal.jsx
Labels: bug

#7038 fix: Not reload after dnd
  packages/app/src/stores/page-listing.tsx
Labels: bug

#7002 fix: VRT 30 search all pages 1, 2, 3
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: bug

#7050 imprv: Use react-toastify
  packages/app/package.json
  packages/app/src/client/util/apiNotification.js
  packages/app/src/client/util/toastr.ts
  packages/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.tsx
  packages/app/src/components/Layout/RawLayout.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/styles/_editor.scss
  packages/app/src/styles/molecules/toastr.scss
  packages/app/src/utils/array-utils.ts
  yarn.lock
Labels: exclude from changelog

#7054 fix: trash page is not redirected on production environment
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
Labels: bug, improvement

#7044 support: Cypress v12.0.1
  package.json
  packages/app/cypress.config.ts
  packages/app/cypress.json
  packages/app/test/cypress/integration/10-install/10-install--install.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-pagelist.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--click-page-icons.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.spec.ts
  packages/app/test/cypress/integration/30-search/30-search--search.spec.ts
  packages/app/test/cypress/integration/40-admin/40-admin--access-to-admin-page.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--access-to-side-bar.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--switching-sidebar-mode.spec.ts
  packages/app/test/cypress/integration/60-home/60-home--home.spec.ts
  packages/app/test/cypress/plugins/index.ts
  yarn.lock
Labels: support

#7058 fix: Avoid flickering on dropdownmenu without enable right
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Page/CopyDropdown.jsx
Labels: bug

#7063 fix: Do not show author info in UsersHomePage
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: bug

#7061 fix: Redirect does not work after delething page on production environment
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
Labels: bug

#7060 imprv: In-app notification snapshot parsing process in SWR
  packages/app/src/components/InAppNotification/InAppNotificationList.tsx
  packages/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  packages/app/src/interfaces/in-app-notification.ts
  packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
  packages/app/src/stores/in-app-notification.ts
Labels: improvement

#7064 imprv: Revive preLogin
  packages/app/src/server/routes/login.js
Labels: improvement

#7062 fix: HackMD load styles
  packages/app/src/components/PageEditorByHackmd/HackmdEditor.jsx
  packages/hackmd/src/hackmd-styles.js
  packages/hackmd/src/index.js
Labels: bug

#7065 feat: Update admin json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
Labels: bug

#7075 fix: Remove unwanted dropdowndivider in appearance mode dropdown
  packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
Labels: bug

#7080 fix: next conflict diff modal
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/remote-latest-page.ts
Labels: support

#7073 imprv: VRT for Page Deletion
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
Labels: improvement

#7070 fix: _reboot-toastr-colors.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/_reboot-bootstrap-border-colors.scss
  packages/app/src/styles/theme/_reboot-toastr-colors.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/theme/_apply-colors.scss
  packages/preset-themes/src/styles/theme/_reboot-bootstrap-border-colors.scss
  packages/preset-themes/src/styles/theme/_reboot-toastr-colors.scss
Labels: bug

#7076 fix: Anchor link decoration
  packages/app/src/styles/bootstrap/_variables.scss
  packages/preset-themes/src/styles/bootstrap/_variables.scss
Labels: bug

#7071 fix: VRT V5 Page Migration should be visible
  packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
  packages/app/test/cypress/integration/40-admin/40-admin--access-to-admin-page.spec.ts
Labels: bug

#7082 feat: Refactor install plugins feature without using execSync
  packages/app/src/server/routes/apiv3/plugins-extension.ts
  packages/app/src/server/service/plugin.ts
Labels: feature

#7079 fix: show restart hackmd
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/interfaces/websocket.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/remote-latest-page.ts
Labels: bug

#7083 fix: 110743 tooltip for guest
  packages/app/src/components/BookmarkButtons.tsx
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/Navbar/PageEditorModeManager.jsx
  packages/app/src/components/NotAvailableForGuest.jsx
  packages/app/src/components/Page/RenderTagLabels.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/SubscribeButton.tsx
Labels: bug, support

#7085 imprv: Omit className expandContainer from BasicLayout
  packages/app/src/client/services/use-current-layout-class-name.ts
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Layout/SearchResultLayout.tsx
  packages/app/src/components/Layout/ShareLinkLayout.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
Labels: improvement

#7081 fix: blackout toc for sandbox math vrt fot guest
  packages/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.spec.ts
Labels: bug

#7089 fix: disable sidebar button for guest
  packages/app/package.json
  packages/app/src/components/NotAvailableForGuest.jsx
  packages/app/src/components/NotAvailableForGuest.tsx
  packages/app/src/components/Page/RenderTagLabels.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  yarn.lock
Labels: bug

#7074 fix:reboot bootstrap colors.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/_reboot-bootstrap-buttons.scss
  packages/app/src/styles/theme/_reboot-bootstrap-colors.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/theme/_apply-colors-dark.scss
  packages/preset-themes/src/styles/theme/_apply-colors-light.scss
  packages/preset-themes/src/styles/theme/_apply-colors.scss
  packages/preset-themes/src/styles/theme/_reboot-bootstrap-buttons.scss
  packages/preset-themes/src/styles/theme/_reboot-bootstrap-colors.scss
  packages/preset-themes/src/styles/theme/_reboot-bootstrap-theme-colors.scss
  packages/preset-themes/src/styles/theme/mixins/_list-group.scss
Labels: bug

#7088 fix: 110781 refactor load latest
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.tsx
Labels: bug

#7096 fix: disable tooltip for logged in user
  packages/app/src/components/NotAvailableForGuest.tsx
Labels: bug

#6985 feat: Use rehype sanitize plugin only when xss prevention is enabled
  packages/app/src/services/renderer/renderer.tsx
Labels: feature

#7087 fix: Redirect to under /trash path
  packages/app/src/components/PageAlert/PageRedirectedAlert.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/server/views/widget/page_alerts.html
Labels: bug

#7098 imprv: Do no get tags on share link page
  packages/app/src/components/Page.tsx
Labels: improvement

#7090 imprv: Handling themes
  packages/app/src/client/services/activate-plugin.ts
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/Customize/CustomizeThemeOptions.jsx
  packages/app/src/components/Admin/Customize/CustomizeThemeOptions.tsx
  packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
  packages/app/src/components/Admin/Customize/ThemeColorBox.jsx
  packages/app/src/components/Admin/Customize/ThemeColorBox.tsx
  packages/app/src/components/Layout/Admin.module.scss
  packages/app/src/interfaces/customize.ts
  packages/app/src/interfaces/plugin.ts
  packages/app/src/interfaces/theme.ts
  packages/app/src/pages/_document.page.tsx
  packages/app/src/pages/admin/customize.page.tsx
  packages/app/src/pages/admin/plugins.page.tsx
  packages/app/src/server/models/config.ts
  packages/app/src/server/models/growi-plugin.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/server/service/plugin.ts
  packages/app/src/stores/admin/customize.tsx
  packages/app/src/stores/context.tsx
  packages/core/src/index.ts
  packages/core/src/interfaces/growi-theme-metadata.ts
  packages/core/src/interfaces/vite.ts
  packages/preset-themes/.eslintrc.js
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/index.ts
  packages/preset-themes/src/interfaces/growi-theme-metadata.ts
  packages/preset-themes/src/interfaces/manifest.ts
  packages/preset-themes/src/utils/index.ts
Labels: improvement, exclude from changelog

#7101 fix: Redirect to root page when moving to a shared page with no id
  packages/app/src/server/routes/index.js
Labels: bug

#7055 imprv: implement skeltons of sidebar
  packages/app/src/components/Sidebar.tsx
  packages/app/src/components/Sidebar/CustomSidebar.module.scss
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.module.scss
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/components/Sidebar/RecentChanges.module.scss
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/Sidebar/SidebarHeaderReloadButton.tsx
  packages/app/src/components/Sidebar/Skeleton/CustomSidebarContentSkeleton.tsx
  packages/app/src/components/Sidebar/Skeleton/PageTreeContentSkeleton.tsx
  packages/app/src/components/Sidebar/Skeleton/RecentChangesContentSkeleton.tsx
  packages/app/src/components/Sidebar/Skeleton/SidebarSkeleton.module.scss
  packages/app/src/components/Sidebar/Skeleton/SidebarSkeleton.tsx
  packages/app/src/components/Sidebar/Skeleton/TagContentSkeleton.tsx
  packages/app/src/components/Sidebar/Tag.module.scss
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/Skeleton.tsx
  packages/app/src/styles/_mixins.scss
Labels: improvement

#7094 fix: apply oiptionsToSave
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/SavePageControls.tsx
Labels: bug

#7105 fix: Do not show global search bar on share link page
  packages/app/src/components/Layout/ShareLinkLayout.tsx
Labels: bug

#7100 fix: refactor useHasDraftOnHackmd initialize
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#7069 imprv: Markdown Help Modal styles
  packages/app/src/components/PageEditor/Cheatsheet.jsx
  packages/app/src/components/PageEditor/Cheatsheet.tsx
  packages/app/src/components/PageEditor/Editor.module.scss
  packages/app/src/components/PageEditor/Editor.tsx
Labels: bug

#7103 fix: save tag
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: bug

#7106 fix: Author info and page path are not displayed on share link page
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: bug

#6994 feat: Recommendations and customization can be set from admin setting
  packages/app/src/client/services/AdminMarkDownContainer.js
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  packages/app/src/interfaces/rehype.ts
  packages/app/src/interfaces/services/renderer.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/markdown-setting.js
Labels: feature

#7108 imprv: Discontinue Basic Authentication
  packages/app/_obsolete/src/client/nologin.jsx
  packages/app/package.json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/services/AdminBasicSecurityContainer.js
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/components/Admin/Security/BasicSecuritySetting.jsx
  packages/app/src/components/Admin/Security/BasicSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
  packages/app/src/components/Layout/NoLoginLayout.module.scss
  packages/app/src/components/LoginForm.tsx
  packages/app/src/interfaces/activity.ts
  packages/app/src/migrations/20221219011829-remove-basic-auth-related-config.js
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/login.page.tsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/service/passport.ts
  yarn.lock
Labels: improvement

#7104 imprv: VRT
  package.json
  packages/app/cypress.config.ts
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/LoginForm.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/components/User/UserInfo.tsx
  packages/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.spec.ts
  packages/app/test/cypress/integration/60-home/60-home--home.spec.ts
  packages/app/test/cypress/support/commands.ts
  yarn.lock
Labels: exclude from changelog

#7113 imprv(re): Do no get tags on share link page
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: improvement

#7114 fix: Remove obsoleted link from cheat sheet
  packages/app/src/components/PageEditor/Cheatsheet.tsx
Labels: bug, improvement

#7107 fix: Unlink for trash pagelist
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/PageAlert/PageRedirectedAlert.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/stores/page-redirect.tsx
Labels: bug

#7116 feat: Replace tags and attr in recommended settings with config in rehype
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
Labels: feature

#7119 feat: Custom headers
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/client/services/AdminCustomizeContainer.js
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  packages/app/src/interfaces/activity.ts
  packages/app/src/pages/_document.page.tsx
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/server/service/customize.ts
Labels: exclude from changelog

#7118 fix: update editing markdown after hackmd saved
  packages/app/src/client/services/page-operation.ts
Labels: bug

#7066 fix: Cypress (20-basic-features)
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-pagelist.spec.ts
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
Labels: bug

#7125 fix: show empty page
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#7117 fix: unsaved alert in hackmd editor
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: bug

#7124 feat: Save prevent xss custom settings in new format
  packages/app/src/client/services/AdminMarkDownContainer.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/markdown-setting.js
Labels: feature

#7121 imprv: Organize app package deps
  packages/app/package.json
  packages/app/src/components/StickyStretchableScroller.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/stores/ui.tsx
  yarn.lock
Labels: improvement

#7131 fix: refactor websocket
  packages/app/src/stores/websocket.tsx
Labels: bug

#7059 imprv: Apply getLayout pattern
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/services/layout.ts
  packages/app/src/components/Layout/AdminLayout.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Layout/NoLoginLayout.tsx
  packages/app/src/components/Layout/RawLayout.tsx
  packages/app/src/components/Layout/SearchResultLayout.tsx
  packages/app/src/components/Layout/ShareLinkLayout.tsx
  packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
  packages/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_app.page.tsx
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/admin/[...path].page.tsx
  packages/app/src/pages/admin/app.page.tsx
  packages/app/src/pages/admin/audit-log.page.tsx
  packages/app/src/pages/admin/customize.page.tsx
  packages/app/src/pages/admin/export.page.tsx
  packages/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
  packages/app/src/pages/admin/global-notification/new.page.tsx
  packages/app/src/pages/admin/importer.page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/pages/admin/markdown.page.tsx
  packages/app/src/pages/admin/notification.page.tsx
  packages/app/src/pages/admin/plugins.page.tsx
  packages/app/src/pages/admin/search.page.tsx
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/admin/slack-integration-legacy.page.tsx
  packages/app/src/pages/admin/slack-integration.page.tsx
  packages/app/src/pages/admin/user-group-detail/[userGroupId].page.tsx
  packages/app/src/pages/admin/user-groups.page.tsx
  packages/app/src/pages/admin/users/external-accounts.page.tsx
  packages/app/src/pages/admin/users/index.page.tsx
  packages/app/src/pages/installer.page.tsx
  packages/app/src/pages/invited.page.tsx
  packages/app/src/pages/login.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/pages/user-activation.page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_layout.scss
Labels: exclude from changelog

#7134 fix: Deserialization in sync-to-storage
  packages/app/src/stores/middlewares/sync-to-storage.ts
Labels: bug

#7115 fix: Cypress error 10 30 50
  packages/app/test/cypress/integration/10-install/10-install--install.spec.ts
  packages/app/test/cypress/integration/30-search/30-search--search.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--access-to-side-bar.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--switching-sidebar-mode.spec.ts
Labels: bug

#7136 support: bump version to rc12
  lerna.json
  package.json
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/preset-themes/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: support

#7126 imprv:apply colors apply to bootstrap
  packages/app/src/styles/theme/_apply-colors.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/theme/_apply-colors.scss
  packages/preset-themes/src/styles/theme/_hsl-functions.scss
  packages/preset-themes/src/styles/theme/_override-functions.scss
  packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss
Labels: improvement

#7137 feat: depricate growi own link
  packages/app/src/components/PageEditor/LinkEditModal.jsx
Labels: feature

#7139 imprv: Dropdown in PageTree
  packages/app/package.json
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  yarn.lock
Labels: improvement

#7141 fix: remove useCallback
  packages/app/src/components/PageEditor/Editor.tsx
Labels: bug

#7135 imprv: improve sidebar components and skeleton
  packages/app/src/components/Sidebar.tsx
  packages/app/src/components/Sidebar/RecentChanges.module.scss
  packages/app/src/components/Sidebar/SidebarContents.tsx
  packages/app/src/components/Sidebar/Skeleton/SidebarSkeleton.tsx
  packages/app/src/components/Sidebar/Skeleton/TagContentSkeleton.tsx
  packages/app/src/components/Sidebar/Tag.module.scss
Labels: improvement

#7140 imprv:apply-colors grw global navigation
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/mixins/_hsl-button.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/theme/_apply-colors.scss
Labels: improvement

#7148 fix: 111740 guest tooltip
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/SearchPage.tsx
Labels: bug

#7143 fix: update state after save
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: bug

#7122 feat: Plugin reinstall features
  packages/app/src/components/Admin/PluginsExtension/PluginInstallerForm.tsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/routes/apiv3/plugins.ts
  packages/app/src/server/service/plugin.ts
Labels: feature

#7147 fix: 111902 hackmd editing alert
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: bug

#7145 fix: Internal Server Err when approval pending and suspended user login
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/CompleteUserRegistration.tsx
  packages/app/src/components/LoginForm.tsx
  packages/app/src/pages/login/error/[message].page.tsx
  packages/app/src/pages/login/index.page.tsx
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/routes/login.js
  packages/app/src/server/views/login/error.html
Labels: bug

#7150 fix: Deprecate Rendering Draw.io function
  packages/app/src/components/PageEditor/OptionsSelector.tsx
  packages/app/src/interfaces/editor-settings.ts
  packages/app/src/server/models/editor-settings.ts
  packages/app/src/server/routes/apiv3/personal-setting.js
Labels: bug, improvement

#7151 support: Remove Twitter authentication :wave:
  packages/app/_obsolete/src/client/nologin.jsx
  packages/app/package.json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/client/services/AdminGeneralSecurityContainer.js
  packages/app/src/client/services/AdminTwitterSecurityContainer.js
  packages/app/src/components/Admin/Security/FacebookSecuritySetting.jsx
  packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
  packages/app/src/components/Admin/Security/TwitterSecuritySetting.jsx
  packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
  packages/app/src/components/Layout/NoLoginLayout.module.scss
  packages/app/src/components/LoginForm.tsx
  packages/app/src/components/Me/AssociateModal.tsx
  packages/app/src/interfaces/activity.ts
  packages/app/src/migrations/20180927102719-init-serverurl.js
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/login/index.page.tsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/passport.ts
  packages/app/src/server/views/login.html
  yarn.lock
Labels: support

#7156 feat: fix i18n error message
  packages/app/src/server/routes/login.js
Labels: feature

#7157 fix: Update admin i18n
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/MailSetting.tsx
  packages/app/src/server/routes/login.js
Labels: bug

#7068 feat: Display plugin cards dynamically
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/components/Admin/PluginsExtension/Loading.js
  packages/app/src/components/Admin/PluginsExtension/PluginCard.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginInstallerForm.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginsExtensionPageContents.tsx
  packages/app/src/interfaces/plugin.ts
  packages/app/src/server/models/growi-plugin.ts
  packages/app/src/server/routes/apiv3/plugins.ts
  packages/app/src/server/service/plugin.ts
  packages/app/src/stores/plugin.tsx
  packages/app/src/stores/useInstalledPlugins.ts
Labels: feature

#7160 fix: PageEditor and CodeMirrorEditor rendering optimization
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/remote-latest-page.ts
Labels: bug

#7158 fix: unexpected alert
  packages/app/src/client/services/page-operation.ts
Labels: bug

#7163 imprv: search page layout fix
  packages/app/src/components/Layout/SearchResultLayout.tsx
  packages/app/src/pages/_search.page.tsx
Labels: improvement

#7159 fix: Toaster success after deleting user group
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
Labels: bug

#7167 fix: isEnabledLinebreaksInComments is not applied
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/renderer.tsx
Labels: bug

#7166 support: Remove unnecessary code
  packages/app/src/server/routes/all-in-app-notifications.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/me.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/routes/private-legacy-pages.ts
  packages/app/src/server/routes/search.ts
  packages/app/src/server/routes/tag.js
  packages/app/test/integration/models/share-link.test.js
Labels: exclude from changelog

#7164 fix: Renderers
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/PageTimeline.module.scss
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/services/renderer/PostProcessor/.keep
  packages/app/src/services/renderer/PreProcessor/CsvToTable.js
  packages/app/src/services/renderer/PreProcessor/Linker.js
  packages/app/src/services/renderer/PreProcessor/XssFilter.ts
  packages/app/src/services/renderer/interceptor/detach-code-blocks.js
  packages/app/src/services/renderer/markdown-it/PreProcessor/EasyGrid.js
  packages/app/src/services/renderer/markdown-it/drawio-viewer.js
  packages/app/src/services/renderer/markdown-it/emoji-mart-data.ts
  packages/app/src/services/renderer/markdown-it/emoji.js
  packages/app/src/services/renderer/markdown-it/footernote.js
  packages/app/src/services/renderer/markdown-it/header-line-number.js
  packages/app/src/services/renderer/markdown-it/header-with-edit-link.js
  packages/app/src/services/renderer/markdown-it/header.js
  packages/app/src/services/renderer/markdown-it/link-by-relative-path.ts
  packages/app/src/services/renderer/markdown-it/mathjax.js
  packages/app/src/services/renderer/markdown-it/plantuml.ts
  packages/app/src/services/renderer/markdown-it/table-with-handsontable-button.js
  packages/app/src/services/renderer/markdown-it/table.js
  packages/app/src/services/renderer/markdown-it/task-lists.js
  packages/app/src/services/renderer/markdown-it/toc-and-anchor.js
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/renderer.tsx
Labels: bug, exclude from changelog

#7173 support: Remove plugin settings
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/client/services/AdminAppContainer.js
  packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
  packages/app/src/components/Admin/App/PluginSetting.tsx
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/views/layout/layout.html
Labels: support

#7175 imprv:apply colors light last
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/theme/_apply-colors-light.scss
Labels: improvement

#7161 feat: Update error handling to clean up data
  packages/app/src/server/service/plugin.ts
Labels: feature

#7170 fix: show editor navbar
  packages/app/src/components/PageEditor/Editor.tsx
Labels: bug

#7171 fix: Putback modal & Replace router.reload to router.push
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/stores/modal.tsx
Labels: bug

#7176 feat: Enable plugin i18n
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/PluginsExtension/PluginCard.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginInstallerForm.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginsExtensionPageContents.tsx
  packages/app/src/pages/admin/plugins.page.tsx
Labels: feature

#7177 imprv: nologin layout
  packages/app/src/components/CompleteUserRegistration.tsx
  packages/app/src/components/CompleteUserRegistrationForm.tsx
  packages/app/src/components/InstallerForm.tsx
  packages/app/src/components/InvitedForm.tsx
  packages/app/src/components/Layout/Login.module.scss
  packages/app/src/components/Layout/NoLoginLayout.module.scss
  packages/app/src/components/Layout/NoLoginLayout.tsx
  packages/app/src/components/LoginForm.module.scss
  packages/app/src/components/LoginForm.tsx
  packages/app/src/pages/login/error/[message].page.tsx
  packages/app/src/pages/login/index.module.scss
  packages/app/src/pages/login/index.page.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/src/styles/island.scss
  packages/preset-themes/src/styles/nature.scss
  packages/preset-themes/src/styles/spring.scss
  packages/preset-themes/src/styles/theme/_apply-colors-dark.scss
  packages/preset-themes/src/styles/theme/_apply-colors-light.scss
  packages/preset-themes/src/styles/wood.scss
Labels: exclude from changelog

#7174 imprv: SSR
  packages/app/src/components/IdenticalPathPage.tsx
  packages/app/src/components/Layout/MainPane.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/ShareLinkAlert.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageSideContents.module.scss
  packages/app/src/components/PageSideContents.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement, exclude from changelog

#7172 feat: Use configured xss custom whitelist
  packages/app/src/components/Admin/MarkdownSetting/WhiteListInput.jsx
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  packages/app/src/interfaces/rehype.ts
  packages/app/src/interfaces/services/renderer.ts
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
Labels: feature, exclude from changelog
