Repository growilabs/growi, pull requests merged in 2022-04, with the labels that each got.

#5651 fix: Page items disappear when dnd
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug

#5656 imprv: remove min-width from search-sort-option-btn
  packages/app/src/components/SearchPage/SortControl.tsx
  packages/app/src/styles/_search.scss
Labels: improvement

#5660 imprv: Add an expiration date for the link in the email
  packages/app/resource/locales/en_US/notifications/passwordReset.txt
  packages/app/resource/locales/en_US/notifications/userActivation.txt
  packages/app/resource/locales/ja_JP/notifications/passwordReset.txt
  packages/app/resource/locales/ja_JP/notifications/userActivation.txt
  packages/app/resource/locales/zh_CN/notifications/passwordReset.txt
  packages/app/resource/locales/zh_CN/notifications/userActivation.txt
  packages/app/src/server/models/password-reset-order.ts
  packages/app/src/server/models/user-registration-order.ts
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/user-activation.ts
Labels: feature

#5663 feat: Implement namedquery filter by prefix
  packages/app/src/server/interfaces/search.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/models/vo/error-search.ts
  packages/app/src/server/routes/search.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/service/search-delegator/private-legacy-pages.ts
  packages/app/src/server/service/search.ts
Labels: feature

#5665 imprv: Clickable area of PageListItemL
  packages/app/src/components/PageList/PageListItemL.tsx
Labels: improvement

#5655 imprv: adjust spaces in page item control and subnav btn
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/styles/style-app.scss
Labels: improvement

#5600 feat: Remove child group from parent group
  packages/app/resource/locales/en_US/admin/admin.json
  packages/app/resource/locales/ja_JP/admin/admin.json
  packages/app/resource/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/server/routes/apiv3/user-group.js
Labels: feature

#5666 imprv: Adjust layout for PageTree Descendant Count
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_page-tree.scss
Labels: improvement

#5673 support: Update eslint-config-weseek
  package.json
  yarn.lock
Labels: support

#5672 fix: Page path is not pre populated
  packages/app/src/components/PageCreateModal.jsx
Labels: bug, exclude from changelog

#5674 fix: Description of deletion authority
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
Labels: bug, exclude from changelog

#5667 fix: Sync change of count for both like and bookmark in search page
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/ui/src/components/PagePath/PageListMeta.jsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: bug

#5683 fix: Cannot register new users
  packages/app/src/server/models/user.js
Labels: bug

#5682 imprv: Adjust pagelist and comment position
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/styles/_page-accessories-control.scss
Labels: improvement

#5685 fix: Password reset gives error update password failed when submitting a new password
  packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt
  packages/app/resource/locales/zh_CN/notifications/passwordResetSuccessful.txt
Labels: bug

#5688 fix: VRT for /Sandbox with anchor hash
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
Labels: exclude from changelog

#5689 support: Reorganize import order
  .eslintrc.js
  packages/codemirror-textlint/src/index.ts
  packages/core/src/index.js
  packages/core/src/test/plugin/service/tag-cache-manager.test.js
  packages/core/src/utils/page-path-utils.ts
  packages/plugin-attachment-refs/src/client-entry.js
  packages/plugin-attachment-refs/src/client/js/components/AttachmentList.jsx
  packages/plugin-attachment-refs/src/client/js/components/ExtractedAttachments.jsx
  packages/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPostRenderInterceptor.js
  packages/plugin-lsx/src/client-entry.js
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxListView.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/PagePathWrapper.jsx
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPreRenderInterceptor.js
  packages/slack/src/interfaces/growi-interaction-processor.ts
  packages/slack/src/middlewares/parse-slack-interaction-request.ts
  packages/slack/src/middlewares/verify-growi-to-slack-request.ts
  packages/slack/src/middlewares/verify-slack-request.ts
  packages/slack/src/utils/check-communicable.ts
  packages/slack/src/utils/interaction-payload-accessor.ts
  packages/slack/src/utils/post-ephemeral-errors.ts
  packages/slack/src/utils/respond-util-factory.ts
  packages/slackbot-proxy/src/Server.ts
  packages/slackbot-proxy/src/controllers/growi-to-slack.ts
  packages/slackbot-proxy/src/controllers/slack.ts
  packages/slackbot-proxy/src/controllers/top.ts
  packages/slackbot-proxy/src/entities/installation.ts
  packages/slackbot-proxy/src/entities/order.ts
  packages/slackbot-proxy/src/entities/relation.ts
  packages/slackbot-proxy/src/interfaces/growi-to-slack/growi-req.ts
  packages/slackbot-proxy/src/middlewares/GlobalHttpErrorHandlingMiddleware.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/extract-growi-uri-from-req.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/join-to-conversation.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/parse-interaction-req.ts
  packages/slackbot-proxy/src/middlewares/slack-to-growi/url-verification.ts
  packages/slackbot-proxy/src/models/errors.ts
  packages/slackbot-proxy/src/services/LinkSharedService.ts
  packages/slackbot-proxy/src/services/RegisterService.ts
  packages/slackbot-proxy/src/services/RelationsService.ts
  packages/slackbot-proxy/src/services/SelectGrowiService.ts
  packages/slackbot-proxy/src/services/SystemInformationService.ts
  packages/slackbot-proxy/src/services/UnregisterService.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/ActionsBlockPayloadDelegator.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/SectionBlockPayloadDelegator.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/ViewInteractionPayloadDelegator.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
  packages/slackbot-proxy/src/services/growi-uri-injector/block-elements/CheckboxesActionPayloadDelegator.ts
  packages/slackbot-proxy/src/utils/welcome-message.ts
  packages/ui/src/components/Attachment/Attachment.jsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
  packages/ui/src/components/User/UserPicture.jsx
Labels: exclude from changelog

#5691 fix: Do not include in search results if the page grant is restricted
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: bug

#5693 fix: Do not include granted users if change page permission restricted
  packages/app/src/server/models/obsolete-page.js
Labels: bug

#5694 support: Migration for setting sparce option to slack member id
  packages/app/src/migrations/20220411114257-set-sparse-option-to-slack-member-id.js
Labels: support

#5697 support: improve home.spec.ts
  .github/workflows/reusable-app-prod.yml
  packages/app/src/components/Me/ApiSettings.jsx
  packages/app/src/components/Me/AssociateModal.jsx
  packages/app/src/components/Me/BasicInfoSettings.jsx
  packages/app/src/components/Me/EditorSettings.tsx
  packages/app/src/components/Me/ExternalAccountLinkedMe.jsx
  packages/app/src/components/Me/InAppNotificationSettings.tsx
  packages/app/src/components/Me/PasswordSettings.jsx
  packages/app/src/components/Me/PersonalSettings.jsx
  packages/app/src/components/Me/UserSettings.jsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/server/views/layout-growi/user_page.html
  packages/app/src/server/views/layout/layout.html
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-home.spec.ts
  packages/app/test/cypress/integration/6-home-settings/access-user-settings.spec.ts
  packages/app/test/cypress/integration/6-home/home.spec.ts
Labels: support, improvement, exclude from changelog

#5700 imprv: Add spinner to tag sidebar
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagsList.jsx
  packages/app/src/components/TagsList.tsx
  packages/app/src/interfaces/tag.ts
  packages/app/src/stores/tag.tsx
Labels: improvement

#5702 fix: Prevent auto completing email with username stored by browser in /me page
  packages/app/src/components/Me/PasswordSettings.jsx
Labels: bug

#5701 support: Commonize browser detection
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/utils/project-dir-utils.ts
  packages/app/test/cypress/integration/3-search/search.spec.ts
  packages/core/src/index.js
  packages/core/src/utils/browser-utils.ts
Labels: exclude from changelog

#5678 fix: Normalize parent so it does not include siblings
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.migration.test.js
Labels: bug

#5715 fix: Correction of expiredAt attached to email
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/user-activation.ts
Labels: bug

#5716 support: prepare 5.0.2
  CHANGELOG.md
  lerna.json
  package.json
  packages/app/docker/README.md
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#5717 support: prepare 4.5.19
  CHANGELOG.md
  lerna.json
  package.json
  packages/app/docker/README.md
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#5718 fix: Share link list occures error when related page is not found
  packages/app/src/components/ShareLink/ShareLinkList.jsx
  packages/app/src/components/ShareLink/ShareLinkList.tsx
  packages/app/src/server/routes/apiv3/share-links.js
Labels: bug

#5719 fix: Edit button to open built-in editor does not work when HackMD is disabled
  packages/app/src/components/Navbar/PageEditorModeManager.jsx
Labels: bug

#5721 support: prepare v5.0.3
  CHANGELOG.md
  lerna.json
  package.json
  packages/app/docker/README.md
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#5695 imprv: Adding tests for getParentAndFillAncestors
  packages/app/src/server/models/page.ts
  packages/app/test/integration/models/v5.page.test.js
Labels: feature

#5696 imprv: Adding tests for updating page's grant to GRANT_OWNER
  packages/app/src/server/models/page.ts
  packages/app/test/integration/models/v5.page.test.js
Labels: improvement

#5722 imprv: Change the order of menu items
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
Labels: improvement

#5704 support: creating test file for v5 updateGroup
  packages/app/src/server/crowi/index.js
  packages/app/src/server/service/user-group.ts
  packages/app/test/integration/service/user-groups.test.ts
  packages/app/test/integration/setup-crowi.js
Labels: support

#5727 fix: Too many footstamps icons are shown by lsx output
  packages/app/src/styles/_page_list.scss
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/plugin-lsx/src/server/routes/lsx.js
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: bug

#5735 fix: New user notification email is also sent TO: deleted_at_<epoch_time>@deleted
  packages/app/src/server/models/user.js
  packages/app/test/integration/models/user.test.js
Labels: bug

#5726 fix: Get attachment list api without "page" parameter returns 500 response
  packages/app/src/components/PageAttachment.jsx
  packages/app/src/server/routes/apiv3/attachment.js
Labels: bug

#5737 imprv: Dark theme color optimization
  packages/app/src/styles/theme/_apply-colors-dark.scss
Labels: improvement

#5723 feat: Search on private legacy pages
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage/SearchControl.tsx
  packages/app/src/components/SearchTypeahead.tsx
  packages/app/src/server/interfaces/search.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/models/vo/error-search.ts
  packages/app/src/server/routes/search.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  packages/app/src/server/service/search-delegator/private-legacy-pages.ts
  packages/app/src/server/service/search.ts
  packages/app/src/stores/page-listing.tsx
  packages/app/src/stores/search.tsx
  packages/app/test/integration/service/search/search-service.test.js
Labels: WIP, feature

#5742 support: Prepare v5.0.4-RC
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  lerna.json
  package.json
  packages/app/docker/README.md
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#5647 feat: Infinite scroll for Recent Changes in Sidebar
  packages/app/src/components/Sidebar/InfiniteScroll.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/stores/page.tsx
Labels: feature

#5740 feat: Add count badge to Page List button and Comment button
  packages/app/src/components/Common/CountBadge.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/styles/_page-tree.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
Labels: feature

#5745 support: Set paths to workflows
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/codeql-analysis.yml
Labels: exclude from changelog

#5747 imprv: i18n for already_exists error in PutBackPageModal
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/server/models/errors.ts
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
Labels: improvement

#5749 feat: Create notification when page is duplicated
  packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
  packages/app/src/server/service/page.ts
  packages/app/src/server/util/activityDefine.ts
Labels: feature

#5730 imprv: Redesign tags
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/app.jsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagList.tsx
  packages/app/src/components/TagPage.tsx
  packages/app/src/components/TagsList.tsx
  packages/app/src/interfaces/tag.ts
  packages/app/src/stores/tag.tsx
Labels: improvement

#5756 feat: Create notification when page is reverted
  packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
  packages/app/src/server/service/page.ts
  packages/app/src/server/util/activityDefine.ts
Labels: feature

#5759 fix: footstamp-icon size
  packages/app/src/styles/_page_list.scss
Labels: bug

#5760 feat: Private legacy pages convert by path API
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
Labels: feature

#5763 fix: Too many footstamps icons are shown by lsx output 2
  packages/app/src/styles/_page_list.scss
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
  packages/plugin-lsx/src/server/routes/lsx.js
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: bug

#5762 imprv: Omit activityDefine
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/models/activity.ts
  packages/app/src/server/models/in-app-notification.ts
  packages/app/src/server/models/subscription.ts
  packages/app/src/server/service/comment.ts
  packages/app/src/server/service/page.ts
Labels: exclude from changelog

#5774 fix: Not create unnecessary empty pages when ancestors are public
  packages/app/src/server/models/page.ts
Labels: bug

#5751 imprv: Change GET method to POST for logout operation
  packages/app/src/client/app.jsx
  packages/app/src/client/nologin.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/MaintenanceModeContent.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/logout.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/views/maintenance-mode.html
Labels: improvement

#5786 fix: Include any public pages as applicable ancestors
  packages/app/src/server/models/page.ts
  packages/app/test/integration/models/v5.page.test.js
Labels: bug

#5787 feat: Private legacy pages convert by path
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/app.jsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/PrivateLegacyPagesMigrationModal.tsx
  packages/app/src/interfaces/errors/v5-conversion-error.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/models/vo/search-error.ts
  packages/app/src/server/models/vo/v5-conversion-error.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/search.ts
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/search.ts
  packages/app/src/stores/modal.tsx
Labels: feature

#5788 fix: Default markdown linker with relative path does not respect the current page path
  packages/app/src/client/util/GrowiRenderer.js
  packages/app/src/client/util/markdown-it/link-by-relative-path.ts
Labels: bug
