Repository growilabs/growi, pull requests merged in 2022-05, with the labels that each got.

#5807 fix: Trim space when copying password to a clipboard
  packages/app/src/components/Admin/Users/UserInviteModal.jsx
Labels: exclude from changelog

#5792 fix: Activity is not generated when a page is created
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug, exclude from changelog

#5809 imprv: Rename function on pagetree
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: improvement

#5810 feat: 82580 private legacy page migration toast
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/interfaces/websocket.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
Labels: feature

#5805 feat: 94310 page path auto complete function for page rename modal
  packages/app/src/components/PageCreateModal.jsx
  packages/app/src/components/PageDuplicateModal.tsx
  packages/app/src/components/PageRenameModal.tsx
Labels: improvement

#5812 feat: designed light theme and refactored the part about the theme of pagetree.
  packages/app/src/styles/_page-tree.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/default.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/island.scss
  packages/app/src/styles/theme/kibela.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
Labels: feature

#5793 fix: Error when renaming
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#5816 feat: Empty trash button in trash page
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/base.jsx
  packages/app/src/components/CustomNavigation/CustomNav.jsx
  packages/app/src/components/CustomNavigation/CustomNavAndContents.jsx
  packages/app/src/components/EmptyTrashButton.tsx
  packages/app/src/components/EmptyTrashModal.jsx
  packages/app/src/components/EmptyTrashModal.tsx
  packages/app/src/components/PageDeleteModal.tsx
  packages/app/src/components/TrashPageList.jsx
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/views/layout/layout.html
  packages/app/src/stores/modal.tsx
Labels: feature

#5817 feat: 94469 wood theme sidebar bg-color assignment
  packages/app/src/styles/theme/wood.scss
Labels: feature

#5799 fix: Display admin link only with logged in
  packages/app/src/components/MaintenanceModeContent.tsx
Labels: bug

#5707 support: 92828 test for force update of user group
  packages/app/test/integration/service/user-groups.test.ts
Labels: support

#5835 feat: 94577-grw-count-badge
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/styles/_mixins.scss
  packages/app/src/styles/_page-tree.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/mixins/_list-group.scss
  packages/app/src/styles/theme/nature.scss
Labels: feature

#5778 support: Typescriptize tag model
  packages/app/src/components/Page/TagsInput.tsx
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagList.tsx
  packages/app/src/components/TagPage.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/interfaces/tag.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/page-tag-relation.js
  packages/app/src/server/models/tag.js
  packages/app/src/server/models/tag.ts
  packages/app/src/server/routes/tag.js
  packages/app/src/stores/tag.tsx
  packages/app/test/integration/models/v5.page.test.js
  packages/app/test/integration/service/page.test.js
  packages/app/test/integration/service/v5.non-public-page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: support

#5846 fix: Change the execution user of the official docker image to root
  packages/app/docker/Dockerfile
Labels: bug

#5794 imprv: Put snapshot in activity document
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/events/comment.ts
  packages/app/src/server/models/activity.ts
  packages/app/src/server/models/comment.js
  packages/app/src/server/models/in-app-notification-settings.ts
  packages/app/src/server/models/in-app-notification.ts
  packages/app/src/server/models/subscription.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/comment.js
  packages/app/src/server/service/comment.ts
  packages/app/src/server/service/page.ts
Labels: improvement

#5668 imprv: Emoji - replace emojione to emojimart
  packages/app/bin/shrink-emojione-strategy.js
  packages/app/package.json
  packages/app/resource/cdn-manifests.js
  packages/app/resource/locales/en_US/sandbox.md
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/sandbox.md
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/sandbox.md
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/util/emojione/emoji_strategy_shrinked.json
  packages/app/src/client/util/markdown-it/emoji-mart-data.ts
  packages/app/src/client/util/markdown-it/emoji.js
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/Editor.jsx
  packages/app/src/components/PageEditor/EditorIcon.jsx
  packages/app/src/components/PageEditor/EmojiAutoCompleteHelper.js
  packages/app/src/components/PageEditor/EmojiPicker.tsx
  packages/app/src/components/PageEditor/EmojiPickerHelper.ts
  packages/app/src/styles/_override-bootstrap.scss
  packages/app/src/styles/_vendor.scss
  packages/app/src/styles/theme/_apply-colors.scss
  yarn.lock
Labels: feature

#5838 support: User Group Relation test
  packages/app/src/server/routes/apiv3/user-group.js
  packages/app/src/server/service/user-group.ts
  packages/app/test/integration/service/user-groups.test.ts
Labels: support

#5854 fix: Can not toggle textlint function on v5.0.x
  packages/app/src/components/PageEditor/OptionsSelector.jsx
Labels: bug

#5858 feat: Customize menu in navbar for guest user
  packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/theme/_apply-colors.scss
Labels: feature

#5739 feat: Add method to restart rename page operation
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/service/page.ts
  packages/core/src/utils/page-path-utils.ts
Labels: feature

#5856 feat: Show username suggestion for mention in comment
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/CommentMentionHelper.ts
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/apiv3/users.js
Labels: feature

#5883 feat: Auto focus on open emojiPicker from icon
  packages/app/src/components/PageEditor/EmojiPicker.tsx
Labels: feature, exclude from changelog

#5841 imprv: Add contributors to staff credit
  packages/app/resource/Contributor.js
Labels: improvement

#5880 imprv: Initial rendering when opening Custom Sidebar
  packages/app/src/components/Sidebar/CustomSidebar.tsx
Labels: improvement

#5886 fix(google-oauth2): Automatically bind external accounts does not work for 5.0.x
  packages/app/src/client/services/AdminGoogleSecurityContainer.js
  packages/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  packages/app/src/server/routes/apiv3/security-setting.js
  packages/app/src/server/service/passport.ts
Labels: bug

#5860 imprv: Automatic login after registration
  packages/app/config/logger/config.dev.js
  packages/app/src/server/routes/login.js
Labels: improvement

#5892 imprv: Move code to the appropriate place for fix browser auto-complete email wiith username
  packages/app/src/components/Me/PasswordSettings.jsx
Labels: improvement

#5903 feat: Fix grant alert
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/app.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Page/FixPageGrantAlert.tsx
  packages/app/src/interfaces/page-grant.ts
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/models/user-group-relation.js
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/views/widget/page_alerts.html
  packages/app/src/server/views/widget/page_content.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: feature

#5902 feat: Admin only page convert by path
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/interfaces/errors/v5-conversion-error.ts
  packages/app/src/server/events/user.js
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/attachment.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/installer.ts
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page.ts
  packages/app/src/server/service/slack-command-handler/create-page-service.js
  packages/app/src/server/util/createGrowiPagesFromImports.js
  packages/app/test/integration/models/v5.page.test.js
Labels: feature

#5894 fix: Memory leak by EditorSettings and InterceptorManager
  packages/app/src/client/util/interceptor/drawio-interceptor.js
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/MarkdownTableInterceptor.js
  packages/app/src/components/PageEditor/Preview.tsx
Labels: exclude from changelog

#5906 feat: Send in-app notification when containing username mention in comment
  packages/app/src/server/service/comment.ts
Labels: feature

#5904 imprv: Mixin of argument-of-override-list-group-item-for-pagetree for dark theme
  packages/app/src/styles/theme/_apply-colors-dark.scss
Labels: feature

#5909 fix: doubling of name in staff credits
  packages/app/resource/Contributor.js
Labels: bug, exclude from changelog

#5912 feat: Update emoji regex pattern
  packages/app/src/components/PageEditor/EmojiPickerHelper.ts
Labels: bug, feature, exclude from changelog

#5907 feat: API to find username
  packages/app/src/components/PageEditor/CommentMentionHelper.ts
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/apiv3/users.js
Labels: feature

#5917 fix: Search result screen is broken under content 100% setting
  packages/app/src/server/util/middlewares.js
  packages/app/src/server/views/layout/layout.html
  packages/app/src/server/views/private-legacy-pages.html
  packages/app/src/server/views/search.html
Labels: bug

#5918 support: Add test for normalize parent by path
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.migration.test.js
Labels: exclude from changelog

#5899 feat: Set the min length of passwords by environment variable
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/src/components/Me/PasswordSettings.jsx
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/server/service/config-loader.ts
Labels: feature

#5916 imprv: Unify reload buttons
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/components/Sidebar/Tag.tsx
Labels: improvement, exclude from changelog

#5929 support: Add VRT for guest mode
  .github/workflows/reusable-app-prod.yml
  packages/app/config/ci/.env.local.for-auto-install-with-allowing-guest
  packages/app/src/server/crowi/index.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/installer.ts
  packages/app/test/cypress/integration/10-install/install.spec.ts
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
  packages/app/test/cypress/integration/50-switch-sidebar-mode/switching-sidebar-mode.spec.ts
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: support, exclude from changelog

#5927 fix: Server error due to the canDeleteLogic method
  packages/app/src/server/service/page.ts
Labels: bug

#5930 fix: Page is not rendered for guest
  packages/app/src/components/Page/RevisionRenderer.jsx
Labels: bug

#5928 feat: Icremental search for username
  packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
  packages/app/src/components/Admin/AuditLog/SearchUsernameTypeahead.tsx
  packages/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
  packages/app/src/components/Admin/AuditLogManagement.tsx
  packages/app/src/server/routes/apiv3/activity.ts
  packages/app/src/stores/activity.ts
  packages/app/src/stores/user.tsx
Labels: feature

#5919 imprv: Deleted NotFoundAlert page entirely as well as the import in app.jsx
  packages/app/src/client/app.jsx
  packages/app/src/components/Page/NotFoundAlert.tsx
  packages/app/src/server/views/layout-growi/not_found.html
Labels: improvement

#5893 feat: 92028-darkthemes-snippet-color
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: feature

#5937 imprv: add name to staff credits
  packages/app/resource/Contributor.js
Labels: improvement, exclude from changelog

#5644 imprv: vrt create edit template bootstrap4
  packages/app/src/components/CreateTemplateModal.jsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PagePresentationModal.jsx
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: improvement
