Repository growilabs/growi, pull requests merged in 2022-06, with the labels that each got.

#5949 fix: Editor scroll sync by Preview scrolling does not work
  packages/app/src/components/PageEditor/Preview.tsx
Labels: bug

#5939 imprv: 95974 eliminate reload in adding name to group
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserFormByInput.jsx
Labels: improvement, exclude from changelog

#5947 imprv: Add explanation comment on forceCreateBySystem
  packages/app/src/server/service/page.ts
Labels: improvement, exclude from changelog

#5959 fix: Login required when viewing sharelink page
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: bug

#5960 support: omit unstated
  packages/app/src/client/legacy/crowi.js
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/util/editor.ts
  packages/app/src/client/util/markdown-it/header-with-edit-link.js
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/RevisionBody.jsx
  packages/app/src/components/PageEditor.jsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_page_list.scss
Labels: exclude from changelog

#5961 imprv: PageStatusAlert labels when data is outdated
  packages/app/src/components/PageStatusAlert.jsx
Labels: improvement

#5911 fix: Slack channels are not automatically filled after setting up user trigger notification on v5.0.x
  packages/app/src/client/services/CommentContainer.js
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/PageEditorByHackmd.jsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/components/SlackNotification.tsx
  packages/app/src/interfaces/user-trigger-notification.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/service/user-notification/index.ts
  packages/app/src/server/views/layout-growi/identical-path-page.html
  packages/app/src/server/views/widget/page_content.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/editor.tsx
  packages/app/test/integration/models/update-post.test.js
Labels: bug

#5920 feat: 96375-darktheme-pagelist-bg
  packages/app/src/components/PageList/PageList.tsx
  packages/app/src/styles/theme/_apply-colors.scss
Labels: feature

#5970 imprv: Snippet Colors on light theme
  packages/app/src/styles/theme/_apply-colors-light.scss
Labels: feature

#5978 imprv: ProfileImageSettings
  packages/app/src/client/services/PersonalContainer.js
  packages/app/src/components/Me/ImageCropModal.jsx
  packages/app/src/components/Me/ProfileImageSettings.jsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
  packages/app/src/interfaces/attachment.ts
  packages/app/src/interfaces/user.ts
  packages/app/src/server/models/user.js
  packages/app/src/utils/gravatar.ts
Labels: exclude from changelog

#5986 support: Enable garbage collection at runtime with expose-gc package
  packages/app/package.json
  packages/app/src/server/service/import.js
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  yarn.lock
Labels: support

#5973 fix: Chinese notation is broken on create new page modal
  packages/app/resource/locales/zh_CN/translation.json
Labels: bug

#5984 imprv: Fix sidebar tag layout
  packages/app/package.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagList.tsx
  packages/app/src/styles/_tag.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  yarn.lock
Labels: improvement

#5972 imprv: Set Content-Length header in response of attachment
  packages/app/src/server/routes/attachment.js
Labels: improvement

#5995 imprv: Fix subnavigation spacing
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/styles/_on-edit.scss
Labels: improvement

#6000 fix: Too many footstamps icons are shown by lsx output 3
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxListView.jsx
  packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
Labels: bug

#5991 imprv: Limit display of notification paths
  packages/app/src/components/FormattedDistanceDate.jsx
  packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  packages/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  packages/app/src/styles/_navbar.scss
Labels: improvement

#6009 feat: generate activity when registration
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login.js
Labels: feature

#5957 feat: gw7728 vrt notification
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: feature

#5941 support: TestCode for calcApplicableGrantData
  packages/app/src/interfaces/page.ts
  packages/app/src/server/service/page-grant.ts
  packages/app/test/integration/service/page-grant.test.js
Labels: support

#6012 imprv: 94754-each-theme-sidebar-color-fix
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/blackboard.scss
  packages/app/src/styles/theme/christmas.scss
  packages/app/src/styles/theme/fire-red.scss
  packages/app/src/styles/theme/future.scss
  packages/app/src/styles/theme/halloween.scss
  packages/app/src/styles/theme/hufflepuff.scss
  packages/app/src/styles/theme/jade-green.scss
  packages/app/src/styles/theme/nature.scss
  packages/app/src/styles/theme/spring.scss
  packages/app/src/styles/theme/wood.scss
Labels: improvement

#6020 fix: MathJax does not working
  packages/app/src/components/Page/RevisionBody.jsx
Labels: bug

#6023 fix: Getting page API is broken
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#6025 imprv: Render MathJax in Preview tab of comment
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageComment/CommentPreview.jsx
Labels: improvement

#6004 support: Omit unstated
  packages/app/config/webpack.common.js
  packages/app/src/client/base.jsx
  packages/app/src/client/installer.jsx
  packages/app/src/client/legacy/crowi.js
  packages/app/src/client/nologin.jsx
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/services/CommentContainer.js
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/util/apiv1-client.ts
  packages/app/src/client/util/apiv3-client.ts
  packages/app/src/client/util/markdown-it/toc-and-anchor.js
  packages/app/src/client/util/reveal/plugins/growi-renderer.js
  packages/app/src/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
  packages/app/src/components/Drawio.tsx
  packages/app/src/components/InstallerForm.jsx
  packages/app/src/components/LoginForm.jsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
  packages/app/src/components/MyDraftList/Draft.jsx
  packages/app/src/components/Page/RevisionRenderer.jsx
  packages/app/src/components/PageComment/Comment.jsx
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/components/PasswordResetExecutionForm.jsx
  packages/app/src/components/PasswordResetRequestForm.jsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/views/installer.html
  packages/app/src/stores/context.tsx
  packages/plugin-attachment-refs/src/client-entry.js
  packages/plugin-lsx/src/client-entry.js
  packages/plugin-lsx/src/client/js/components/Lsx.jsx
  packages/plugin-lsx/src/client/js/util/Interceptor/LsxPostRenderInterceptor.js
Labels: support, exclude from changelog

#6031 fix: Remove unnecessary type definition
  packages/app/src/components/Admin/App/AwsSetting.jsx
Labels: bug, exclude from changelog

#6039 imprv: move getParentAndFillAncestors
  packages/app/test/integration/models/v5.page.test.js
  packages/app/test/integration/service/page.test.js
Labels: improvement, exclude from changelog

#6038 fix: Omit admin socket from inappropriate places
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/server/service/page.ts
  packages/app/src/stores/websocket.tsx
Labels: exclude from changelog

#6026 support: create isGrantNormalized test
  packages/app/test/integration/models/v5.page.test.js
  packages/app/test/integration/service/v5.non-public-page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: support

#6032 feat: Testcode for rename operation interruption
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: feature

#5862 feat: Implement resume rename page operations
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/interfaces/page-operation.ts
  packages/app/src/interfaces/page.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/global-setup.js
  packages/app/test/integration/service/v5.page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
  packages/core/src/utils/page-path-utils.ts
Labels: feature

#6048 support: Omit unstated
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Admin/Users/RemoveAdminButton.jsx
  packages/app/src/components/Admin/Users/RemoveAdminMenuItem.tsx
  packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
  packages/app/src/components/Admin/Users/StatusSuspendedButton.jsx
  packages/app/src/components/Admin/Users/UserMenu.jsx
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/components/TrashPageList.jsx
  packages/app/src/stores/ui.tsx
Labels: support, exclude from changelog

#5982 imprv: omit ustated-> RevisionComparerContainer
  packages/app/src/client/app.jsx
  packages/app/src/client/services/RevisionComparerContainer.js
  packages/app/src/components/PageHistory.jsx
  packages/app/src/components/PageHistory/PageRevisionTable.jsx
  packages/app/src/components/RevisionComparer/RevisionComparer.jsx
Labels: improvement

#6057 support: Relocate locale files and remove locale-utils
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/en_US/meta.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/index.js
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/ja_JP/meta.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/public/static/locales/zh_CN/meta.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/admin.jsx
  packages/app/src/client/services/AppContainer.js
  packages/app/src/client/util/i18n.js
  packages/app/src/next-i18next.config.ts
  packages/app/src/server/crowi/dev.js
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/apiv3/app-settings.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/utils/locale-utils.ts
Labels: exclude from changelog

#6062 imprv: SWRize apiGet /tag.search
  packages/app/src/components/Page/TagsInput.tsx
  packages/app/src/stores/tag.tsx
Labels: support

#6051 feat: Get GCS instance that uses Application Default Credentials for v5
  packages/app/src/server/service/file-uploader/gcs.js
Labels: feature

#5661 imprv: Remove toc and page authors in empty page
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout-growi/not_found.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement

#6061 fix: Support 3 types of syntax for OpenID Connect Issuer Host
  packages/app/src/server/service/passport.ts
Labels: bug

#6049 support: Omit Tag Container
  packages/app/src/client/app.jsx
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/client/services/TagContainer.js
  packages/app/src/client/util/apiv1-client.ts
  packages/app/src/client/util/editor.ts
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/components/Page.jsx
  packages/app/src/components/Page/TagLabels.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.jsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/interfaces/pageTagsInfo.ts
  packages/app/src/interfaces/tag.ts
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/page.tsx
Labels: support, improvement, exclude from changelog

#6073 fix: Revision err when updating tags
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/SavePageControls/GrantSelector.tsx
  packages/app/src/interfaces/common.ts
  packages/app/src/interfaces/tag.ts
Labels: bug

#6082 support: Upgrade typescript to ^4.6.0
  package.json
  packages/app/src/components/UncontrolledCodeMirror.tsx
  packages/app/src/server/service/s2s-messaging/nchan.ts
  tsconfig.base.json
  yarn.lock
Labels: support

#5638 imprv: Show page control on subnavigation at existing empty page
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout-growi/not_found.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement

#6070 feat: Show page control menu for empty page at the page tree and sub navigation bar
  packages/app/src/client/app.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/FixPageGrantAlert.tsx
  packages/app/src/server/routes/page.js
  packages/app/src/server/views/widget/not_found_content.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: feature

#6063 feat: Do not create an Activity if it is an action that does not belong to the Action Group
  packages/app/.env.development
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/models/activity.ts
  packages/app/src/server/service/activity.ts
  packages/app/src/server/service/config-loader.ts
Labels: feature

#6103 feat: Show page item control menu on empty page
  packages/app/src/client/app.jsx
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page-listing.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout-growi/not_found.html
  packages/app/src/server/views/widget/not_found_content.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: feature

#6111 feat: Sidebar default mode settings
  packages/app/public/images/customize-settings/dock-dark.svg
  packages/app/public/images/customize-settings/dock-light.svg
  packages/app/public/images/customize-settings/drawer-dark.svg
  packages/app/public/images/customize-settings/drawer-light.svg
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  packages/app/src/interfaces/sidebar-config.ts
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_admin.scss
Labels: feature

#6114 imprv/ SWRize apiv3 get personal external accounts
  packages/app/src/client/services/PersonalContainer.js
  packages/app/src/components/Me/AssociateModal.jsx
  packages/app/src/components/Me/DisassociateModal.jsx
  packages/app/src/components/Me/ExternalAccountLinkedMe.jsx
  packages/app/src/interfaces/external-account.ts
  packages/app/src/stores/personal-settings.tsx
Labels: exclude from changelog

#6113 imprv: Search only available action groups
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/routes/apiv3/activity.ts
  packages/app/src/server/service/activity.ts
  packages/app/src/stores/activity.ts
Labels: improvement

#6121 fix: Ensure backword compatibility for ES6 when using max_analyzed_offset
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: bug

#6072 fix: Show page history comparation modal on init
  packages/app/src/client/app.jsx
  packages/app/src/client/base.jsx
  packages/app/src/client/services/ShowPageAccessoriesModal.tsx
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/server/views/layout/layout.html
Labels: bug

#6128 support: gw7730 VRT click page icons
  packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
Labels: support

#6147 support: Omit comment container
  packages/app/src/client/app.jsx
  packages/app/src/client/services/CommentContainer.js
  packages/app/src/components/Drawio.tsx
  packages/app/src/components/PageComment/CommentEditor.jsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/interfaces/comment.ts
  packages/app/src/interfaces/global.ts
  packages/app/src/interfaces/graph-viewer.ts
  packages/app/src/interfaces/interceptor-manager.ts
  packages/app/src/server/routes/comment.js
  packages/app/src/stores/comment.tsx
Labels: improvement

#6130 Feat: Add file upload config activity
  packages/app/src/interfaces/activity.ts
  packages/app/src/server/routes/apiv3/app-settings.js
Labels: feature

#6148 fix: Scrolling preview
  packages/app/src/components/Page/RevisionBody.jsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/Preview.tsx
Labels: bug

#6155 feat: Remove getGrantLabels and use i18n
  packages/app/src/server/crowi/express-init.js
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/views/widget/page_alerts.html
Labels: feature, exclude from changelog

#6163 imprv: remove isDeleted
  packages/app/src/client/services/ContextExtractor.tsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Page/TrashPageAlert.jsx
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/views/layout-growi/identical-path-page.html
  packages/app/src/server/views/widget/page_content.html
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement, exclude from changelog

#6168 fix: Empty trash doesn't work
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug

#6022 support: gw7739 vrt search
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Page/TagsInput.tsx
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support

#6170 feat: Integrate recount descendant count after paths fix
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/v5.page.test.ts
Labels: feature
