Repository growilabs/growi, pull requests merged in 2022-08, with the labels that each got.

#6379 feat: Users can set users per ip from env var at API Rate Limit
  packages/app/src/server/util/rate-limiter.ts
Labels: feature

#6384 fix: In-app notification VRT
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6374 support: Make Editor component Functional Component and TypeScript
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/PageEditor/Editor.jsx
  packages/app/src/components/PageEditor/Editor.tsx
  packages/app/src/interfaces/editor-methods.ts
Labels: support

#6107 feat: Make content width of each page configurable
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout/layout.html
Labels: feature

#6397 imprv: Switch content width
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/service/page.ts
  packages/app/src/server/views/layout/layout.html
Labels: improvement, exclude from changelog

#6395 imprv(auditlog): Date Range Picker
  packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
  packages/app/src/styles/_admin.scss
Labels: improvement

#6398 imprv(auditlog): Clear and reload button
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/components/Admin/AuditLogManagement.tsx
Labels: improvement

#6381 support: Rendering CommentEditorLazyRenderer
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.jsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
  packages/app/src/components/PageComment/CommentPreview.tsx
  packages/app/src/components/PageComment/ReplayComments.jsx
  packages/app/src/components/PageComment/ReplyComments.tsx
  packages/app/src/interfaces/editor-settings.ts
  packages/app/src/pages/[[...path]].page.tsx
Labels: support

#6409 feat: Apply katex
  packages/app/next.config.js
  packages/app/package.json
  packages/app/src/components/CommonStyles/katex.module.scss
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/services/renderer/renderer.tsx
  yarn.lock
Labels: feature

#6430 support: Use vscode-stylelint
  .devcontainer/devcontainer.json
  .vscode/settings.json
  packages/app/src/linter-checker/test.scss
Labels: support

#6421 feat(auditlog): Copy URL of the table
  packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
Labels: feature

#6442 feat: Pukiwiki like linker
  .vscode/launch.json
  package.json
  packages/app/docker/Dockerfile
  packages/app/jest.config.js
  packages/app/package.json
  packages/app/resource/locales/en_US/sandbox.md
  packages/app/resource/locales/ja_JP/sandbox.md
  packages/app/resource/locales/zh_CN/sandbox.md
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.ts
  packages/app/src/services/renderer/rehype-plugins/relative-links.ts
  packages/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.ts
  packages/app/src/services/renderer/renderer.ts
  packages/app/test/unit/services/renderer/pukiwiki-like-linker.test.ts
  packages/plugin-pukiwiki-like-linker/.eslintignore
  packages/plugin-pukiwiki-like-linker/.gitignore
  packages/plugin-pukiwiki-like-linker/README.md
  packages/plugin-pukiwiki-like-linker/package.json
  packages/plugin-pukiwiki-like-linker/src/client-entry.js
  packages/plugin-pukiwiki-like-linker/src/index.js
  packages/plugin-pukiwiki-like-linker/src/resource/js/util/PreProcessor/PukiwikiLikeLinker.js
  packages/plugin-pukiwiki-like-linker/tsconfig.base.json
  packages/plugin-pukiwiki-like-linker/tsconfig.build.cjs.json
  packages/plugin-pukiwiki-like-linker/tsconfig.build.esm.json
  packages/plugin-pukiwiki-like-linker/tsconfig.json
  tsconfig.base.json
  yarn.lock
Labels: feature

#6415 support: isLoading PageComment
  packages/app/src/components/PageComment.module.scss
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.module.scss
  packages/app/src/components/PageComment/CommentEditor.module.scss
  packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
  packages/app/src/components/PageCommentSkelton.tsx
Labels: support

#6444 imprv(auditlog): Activity paging UI
  packages/app/src/components/Admin/AuditLogManagement.tsx
  packages/app/src/styles/_admin.scss
Labels: improvement

#6468 fix: Pager is not displayed
  packages/app/src/components/DescendantsPageList.tsx
Labels: bug

#6436 imprv: make PageEditorByHackmd.jsx fc
  packages/app/src/components/PageEditor/Editor.tsx
  packages/app/src/components/PageEditorByHackmd.jsx
Labels: improvement

#6445 support: DeleteCommentModal client side rendering
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/DeleteCommentModal.tsx
Labels: support

#6477 support: PageComment html files apply nextjs
  packages/app/src/components/Comments.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/server/views/layout-growi/widget/comments.html
Labels: support

#6474 fix: Uploading image using shortcut key(ctrl+v) shows toastError
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/PageEditor/Editor.tsx
Labels: bug

#6478 fix: Label of alert when updating tags
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: bug

#6462 feat: Not increment ordered list number in CodeMirror
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/services/renderer/growi-renderer.ts
Labels: feature

#6192 feat: In-app notifications when removing descendants of subscribed pages
  packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
  packages/app/src/interfaces/activity.ts
  packages/app/src/interfaces/subscription.ts
  packages/app/src/server/models/activity.ts
  packages/app/src/server/models/subscription.ts
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/activity.ts
  packages/app/src/server/service/in-app-notification.ts
  packages/app/src/server/service/page.ts
  packages/app/test/integration/service/page.test.js
  packages/app/test/integration/service/v5.non-public-page.test.ts
  packages/app/test/integration/service/v5.page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
Labels: feature

#6496 fix: Modified wording of alert when tags are updated
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageStatusAlert.jsx
Labels: bug, exclude from changelog
