Repository growilabs/growi, pull requests merged in 2022-01, with the labels that each got.

#5001 imprv: improve tags functions
  packages/app/package.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/Page/TagLabels.jsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/Sidebar/SidebarContents.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagsList.jsx
  packages/app/src/interfaces/ui.ts
  packages/app/src/migrations/20210921173042-add-is-trashed-field.js
  packages/app/src/server/models/page-tag-relation.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/routes/tag.js
  packages/app/src/server/service/page.js
  packages/app/src/server/views/tags.html
  yarn.lock
Labels: improvement

#5028 feat: add oidc client clock tolerance to config manager
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/passport.ts
Labels: feature

#5012 feat: Resolve conflict with 3-way merge like editor
  packages/app/package.json
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/EditorContainer.js
  packages/app/src/client/services/PageContainer.js
  packages/app/src/client/util/apiv1-client.ts
  packages/app/src/components/ExpandOrContractButton.jsx
  packages/app/src/components/ExpandOrContractButton.tsx
  packages/app/src/components/PageEditor/AbstractEditor.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageEditor/Editor.jsx
  packages/app/src/components/PageStatusAlert.jsx
  packages/app/src/components/SavePageControls.jsx
  packages/app/src/components/UncontrolledCodeMirror.tsx
  packages/app/src/interfaces/revision.ts
  packages/app/src/server/models/vo/s2c-message.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/util/apiResponse.js
  yarn.lock
Labels: feature

#5043 imprv: Switching editor mode behavior
  packages/app/src/components/EventListeneres/HashChanged.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement

#5047 imprv: Subnavigation behavior
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx
  packages/app/src/styles/_sidebar.scss
Labels: improvement

#5059 support: Bump re2 to 1.17.2
  packages/app/package.json
  yarn.lock
Labels: support

#5061 fix: Built-in editor was broken
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Labels: bug

#5062 fix: Subnavigation sticking initialization
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx
Labels: bug

#5044 feat: Display a list of bookmarked users
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/BookmarkButton.jsx
  packages/app/src/components/BookmarkButtons.tsx
  packages/app/src/components/Navbar/SubNavButtons.jsx
  packages/app/src/interfaces/bookmarks.ts
  packages/app/src/server/routes/apiv3/bookmarks.js
  packages/app/src/stores/bookmarks.tsx
Labels: feature

#5069 support: Bump tar to 6.1.11
  yarn.lock
Labels: support

#5070 support: Omit prettier-stylelint
  .stylelintrc.json
  package.json
  packages/app/.stylelintrc.json
  packages/app/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/plugin-pukiwiki-like-linker/package.json
  packages/ui/package.json
  yarn.lock
Labels: support

#5071 support: Bump y18n to v4.0.3
  yarn.lock
Labels: support

#5089 support: Omit node-re2
  packages/app/package.json
  packages/app/src/server/service/search.ts
  yarn.lock
Labels: support

#5090 support: Improve multistage build
  packages/app/docker/Dockerfile
  packages/app/docker/Dockerfile.dockerignore
  packages/slackbot-proxy/docker/Dockerfile
  packages/slackbot-proxy/docker/Dockerfile.dockerignore
Labels: support

#5099 fix: OIDC issuer host availability check
  packages/app/package.json
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/passport.ts
  yarn.lock
Labels: bug

#5103 fix: /_api/v3/page is broken and dump 500 error "get-page-failed TypeError: user.canDeleteCompletely is not a function"
  packages/app/src/server/models/user.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/service/page.js
  packages/app/src/server/util/swigFunctions.js
  packages/app/src/server/views/widget/page_content.html
Labels: bug

#5104 fix: OIDC reconnection bug fix
  packages/app/package.json
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/passport.ts
  yarn.lock
Labels: bug

#5116 imprv: 79291 make password min length 8 charactors
  packages/app/resource/locales/en_US/translation.json
  packages/app/src/server/routes/apiv3/forgot-password.js
  packages/app/src/server/routes/apiv3/personal-setting.js
  packages/app/src/server/routes/index.js
Labels: improvement

#5030 support: VRT with Cypress
  .devcontainer/Dockerfile
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
  bin/github-actions/generate-cypress-spec-arg.js
  package.json
  packages/app/.gitignore
  packages/app/cypress.json
  packages/app/jest.config.js
  packages/app/package.json
  packages/app/regconfig.json
  packages/app/src/client/nologin.jsx
  packages/app/src/components/InstallerForm.jsx
  packages/app/src/components/LoginForm.jsx
  packages/app/src/interfaces/user.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/routes/installer.js
  packages/app/src/server/service/app.ts
  packages/app/src/server/service/installer.ts
  packages/app/src/server/views/installer.html
  packages/app/src/test/integration/setup-crowi.js
  packages/app/test/cypress/.eslintrc.js
  packages/app/test/cypress/fixtures/user-admin.json
  packages/app/test/cypress/integration/1-install/install.spec.ts
  packages/app/test/cypress/integration/2-advanced-examples/misc.spec.ts
  packages/app/test/cypress/integration/2-advanced-examples/viewport.spec.ts
  packages/app/test/cypress/integration/2-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/plugins/index.ts
  packages/app/test/cypress/support/commands.ts
  packages/app/test/cypress/support/index.ts
  packages/app/test/cypress/tsconfig.json
  packages/app/test/integration/crowi/crowi.test.js
  packages/app/test/integration/global-setup.js
  packages/app/test/integration/global-teardown.js
  packages/app/test/integration/middlewares/access-token-parser.test.js
  packages/app/test/integration/middlewares/login-required.test.js
  packages/app/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  packages/app/test/integration/models/config.test.js
  packages/app/test/integration/models/page.test.js
  packages/app/test/integration/models/share-link.test.js
  packages/app/test/integration/models/update-post.test.js
  packages/app/test/integration/models/user.test.js
  packages/app/test/integration/service/acl.test.js
  packages/app/test/integration/service/config-manager.test.js
  packages/app/test/integration/service/page.test.js
  packages/app/test/integration/service/passport.test.js
  packages/app/test/integration/service/search/search-service.test.js
  packages/app/test/integration/setup-crowi.js
  packages/app/test/integration/setup.js
  packages/app/test/integration/utils/slack-legacy.test.js
  packages/app/test/tsconfig.json
  packages/app/test/unit/middlewares/safe-redirect.test.js
  packages/app/test/unit/migrate-mongo-config.test.js
  packages/app/test/unit/utils/to-array-from-csv.test.js
  packages/app/tsconfig.build.server.json
  packages/slack/package.json
  yarn.lock
Labels: support

#5141 feat: Automatic installation
  .github/workflows/reusable-app-prod.yml
  packages/app/config/ci/.env.local.for-auto-install
  packages/app/src/interfaces/lang.ts
  packages/app/src/server/crowi/index.js
  packages/app/src/server/routes/installer.js
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/installer.ts
Labels: feature

#5137 imprv: Migrate like states to swr
  packages/app/resource/locales/en_US/translation.json
  packages/app/resource/locales/ja_JP/translation.json
  packages/app/resource/locales/zh_CN/translation.json
  packages/app/src/client/app.jsx
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/LikeButtons.jsx
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/Navbar/SubNavButtons.jsx
  packages/app/src/components/PageAccessoriesModalControl.jsx
  packages/app/src/components/User/LikerList.jsx
  packages/app/src/components/User/SeenUserInfo.jsx
  packages/app/src/components/User/SeenUserInfo.tsx
  packages/app/src/interfaces/page.ts
  packages/app/src/interfaces/user.ts
  packages/app/src/server/routes/apiv3/users.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/user.js
  packages/app/src/stores/middlewares/user.ts
  packages/app/src/stores/page.tsx
  packages/app/src/stores/user.tsx
Labels: improvement

#5155 fix: 86631-cannot-reset-password-in-case-that-register-limitation-is-Closed
  packages/app/src/components/LoginForm.jsx
Labels: bug

#5080 feat: Support Elasticsearch 7
  packages/app/.env.development
  packages/app/package.json
  packages/app/resource/search/mappings-es6.json
  packages/app/resource/search/mappings-es7.json
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/search-delegator/elasticsearch-client-types.ts
  packages/app/src/server/service/search-delegator/elasticsearch-client.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
  yarn.lock
Labels: feature

#5129 imprv: replace express form to express validator
  packages/app/package.json
  packages/app/src/server/form/admin/userGroupCreate.js
  packages/app/src/server/form/index.js
  packages/app/src/server/form/invited.js
  packages/app/src/server/form/login.js
  packages/app/src/server/form/register.js
  packages/app/src/server/middlewares/login-form-validator.ts
  packages/app/src/server/middlewares/register-form-validator.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/views/invited.html
  packages/app/src/server/views/login.html
  yarn.lock
Labels: improvement

#5159 imprv: Update engine.io version to 5.2.1
  yarn.lock
Labels: improvement

#5163 imprv: update follow-redirects to v1.14.7
  yarn.lock
Labels: improvement

#5166 imprv: colors
  packages/app/package.json
  yarn.lock
Labels: improvement

#5175 fix: Internal server error occured when "Restrict complete deletion of pages" option's value is "Admin and author"
  packages/app/src/server/service/page.js
Labels: bug

#5190 support: Support Node.js 16.x and end support for 12.x
  .devcontainer/Dockerfile
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/draft-release.yml
  .github/workflows/list-unhealthy-branches.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
  README.md
  README_JP.md
  package.json
  packages/app/docker/Dockerfile
  packages/app/package.json
  packages/slackbot-proxy/docker/Dockerfile
Labels: support, breaking

#5149 imprv: elasticsearch reindex on boot
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: improvement

#5199 fix: Permissions issue for run-cypress job
  .github/workflows/reusable-app-prod.yml
Labels: exclude from changelog

#5094 imprv: add filter method about tag to recent changes
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/server/routes/apiv3/pages.js
Labels: improvement

#5201 fix: gw7681 fix OIDC reconnection
  packages/app/src/server/service/passport.ts
Labels: bug
