Repository growilabs/growi, pull requests merged in 2022-10, with the labels that each got.

#6683 support: fix vrt
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
  packages/app/test/cypress/integration/50-sidebar/switching-sidebar-mode.spec.ts
Labels: support, exclude from changelog

#6696 feat: Update CommentEditor for enable SlackChannels
  packages/app/src/components/PageComment/CommentEditor.tsx
Labels: feature

#6694 feat: Exception handling
  packages/app/src/components/InvitedForm.tsx
  packages/app/src/server/middlewares/invited-form-validator.ts
  packages/app/src/server/routes/apiv3/invited.ts
Labels: feature

#6695 feat: Attach styles
  packages/app/src/components/InvitedForm.tsx
Labels: feature

#6689 imprv: Emoji picker performance master
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/EmojiPicker.tsx
  packages/app/src/components/PageEditor/EmojiPickerHelper.ts
Labels: improvement

#6700 feat: Convert form to xhr for invited form integrate
  packages/app/config/rate-limiter.ts
  packages/app/src/components/InvitedForm.tsx
  packages/app/src/server/middlewares/invited-form-validator.ts
  packages/app/src/server/middlewares/login-form-validator.ts
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/invited.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/routes/login.js
Labels: feature

#6721 fix: RevisionLoader to ts/fc
  packages/app/src/components/Layout/SearchResultLayout.tsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
Labels: bug

#6706 fix: refactor Editor dynamic import
  packages/app/src/components/PageComment/CommentEditor.module.scss
  packages/app/src/components/PageComment/CommentEditor.tsx
Labels: bug

#6703 fix: Global search is not displayed
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
Labels: bug

#6704 imprv: Add style for code element
  packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
  packages/app/src/styles/atoms/_code.scss
  packages/app/src/styles/atoms/_mixins.scss
  packages/app/src/styles/style-next.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: improvement

#6726 fix: Normalization Custom Title
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/Customize/CustomizeTitle.jsx
  packages/app/src/components/Admin/Customize/CustomizeTitle.tsx
  packages/app/src/components/Layout/AdminLayout.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
Labels: bug

#6711 fix: Toggle wide view
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  packages/app/src/interfaces/customize.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/utils/layout.ts
  packages/app/src/stores/admin/customize.tsx
  packages/app/src/stores/context.tsx
  packages/core/src/interfaces/page.ts
Labels: bug

#6722 fix: 104900 fix convert to v5
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/server/service/page.ts
Labels: bug

#6730 fix: i18n in Customize Settings
  packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeTitle.tsx
Labels: bug

#6712 fix: image not showing and exceed crop modal area
  packages/app/src/components/Common/ImageCropModal.tsx
Labels: bug

#6736 fix: No transition to edit screen when creating a new page
  packages/app/src/components/PageCreateModal.jsx
Labels: bug

#6731 fix: SearchResultContent page scroll for chrome
  packages/app/src/components/Layout/SearchResultLayout.module.scss
Labels: bug

#6742 support: Request scoped SWR
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/components/PagePathNav.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_app.page.tsx
  packages/app/src/stores/use-static-swr.tsx
  packages/app/src/utils/swr-utils.ts
Labels: support

#6744 feat: Remove config customize:isSavedStatesOfTabChanges and add migration to remove the data from DB
  packages/app/src/client/services/AdminCustomizeContainer.js
  packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  packages/app/src/migrations/20221014130200-remove-customize-is-saved-states-of-tab-changes.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
Labels: feature

#6723 feat: Enable styles for PageAccessoriesModal diffs
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/components/PageHistory.tsx
  packages/app/src/components/PageHistory/PageRevisionTable.module.scss
  packages/app/src/components/PageHistory/PageRevisionTable.tsx
  packages/app/src/components/PageHistory/Revision.jsx
  packages/app/src/components/PageHistory/Revision.module.scss
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/PageHistory/RevisionDiff.jsx
  packages/app/src/components/PageHistory/RevisionDiff.module.scss
  packages/app/src/components/PageHistory/RevisionDiff.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.module.scss
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/styles/_page-history.scss
  packages/app/src/styles/_page.scss
  packages/core/src/interfaces/revision.ts
Labels: feature

#6743 feat: Enable function section in admin/customize
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page-listing.tsx
Labels: feature

#6753 feat: Admin TSzation ManageExternalAccount
  packages/app/src/components/Admin/ManageExternalAccount.jsx
  packages/app/src/components/Admin/ManageExternalAccount.tsx
Labels: feature

#6740 feat: admin typescriptzation ExternalAccountTable
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Users/ExternalAccountTable.jsx
  packages/app/src/components/Admin/Users/ExternalAccountTable.module.scss
  packages/app/src/components/Admin/Users/ExternalAccountTable.tsx
  packages/app/src/components/PageComment.tsx
  packages/core/src/interfaces/user.ts
Labels: feature

#6748 fix: Cannot login because of the error occured by passing undefined/null to router.push()
  packages/app/src/components/LoginForm.tsx
Labels: bug

#6758 fix: reload page tree after convrtting pages by path
  packages/app/src/components/PrivateLegacyPages.tsx
Labels: bug

#6756 support: Add missing div with id=grw-subnav-container
  packages/app/src/pages/[[...path]].page.tsx
Labels: support, exclude from changelog

#6741 imprv: Show OptionsSelector
  packages/app/_obsolete/src/client/services/ContextExtractor.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/ui.tsx
  packages/ui/src/utils/browser-utils.ts
Labels: improvement

#6767 support: bump version to 6.0.0 rc.3
  lerna.json
  package.json
  packages/app/package.json
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/remark-growi-plugin/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
Labels: exclude from changelog

#6755 feat: Admin TSzation Users 01
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/Users/GiveAdminButton.jsx
  packages/app/src/components/Admin/Users/GiveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminButton.jsx
  packages/app/src/components/Admin/Users/RemoveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminMenuItem.tsx
  packages/app/src/components/Admin/Users/SortIcons.tsx
  packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
  packages/app/src/components/Admin/Users/UserTable.jsx
  packages/app/src/components/ContentLinkButtons.tsx
  packages/app/src/components/User/UserInfo.tsx
Labels: feature

#6774 fix: Load KeyMap correctly
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/Editor.tsx
Labels: bug

#6627 support: fix dependabot alert jose
  yarn.lock
Labels: bug, support

#6634 support: fix dependabot alert passport
  packages/app/package.json
  yarn.lock
Labels: support

#6777 fix: code block styles
  packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
  packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
  packages/app/src/styles/atoms/_code.scss
  packages/app/src/styles/atoms/_mixins.scss
  packages/app/src/styles/atoms/mixins/_code.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: bug

#6784 fix: Show toastr
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor.tsx
Labels: bug

#6786 fix: Normalize VRT (task-21)
  packages/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.tsx
Labels: bug

#6787 fix: Normalize VRT (task-22)
  packages/app/src/components/Fab.tsx
Labels: bug

#6789 imprv: Implement updateStateAfterSave
  packages/app/src/client/services/PageContainer.js
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: improvement

#6780 support: Omit CustomizeHighlightSettings
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/client/services/AdminCustomizeContainer.js
  packages/app/src/components/Admin/Customize/Customize.jsx
  packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  packages/app/src/interfaces/customize.ts
  packages/app/src/server/routes/admin.js
  packages/app/src/styles/_hljs.scss
  packages/app/src/styles/_wiki.scss
Labels: support

#6781 fix: Set fallbackData as option of useEditorSettings
  packages/app/src/components/Me/EditorSettings.tsx
  packages/app/src/interfaces/editor-settings.ts
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/middlewares/sync-to-storage.ts
Labels: bug

#6792 fix: Change language at installer
  packages/app/src/components/InstallerForm.tsx
  packages/app/src/pages/installer.page.tsx
Labels: bug

#6795 fix: Comments button with react-scroll
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageComment.tsx
Labels: bug

#6782 feat: Common translation files
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
Labels: feature

#6788 feat: VRT normalization user page
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: feature, exclude from changelog

#6797 fix: Cannnot download archive data
  packages/app/src/server/routes/index.js
Labels: bug

#6798 feat: Apply common translations
  packages/app/src/components/Admin/App/AppSetting.jsx
  packages/app/src/components/Admin/App/FileUploadSetting.tsx
  packages/app/src/components/Admin/App/MailSetting.tsx
  packages/app/src/components/Admin/App/PluginSetting.tsx
  packages/app/src/components/Admin/App/SiteUrlSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeTitle.tsx
  packages/app/src/components/Admin/MarkdownSetting/IndentForm.tsx
  packages/app/src/components/Admin/MarkdownSetting/LineBreakForm.jsx
  packages/app/src/components/Admin/MarkdownSetting/PresentationForm.jsx
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  packages/app/src/components/Admin/Notification/GlobalNotification.jsx
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySecretTokenSection.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
  packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
  packages/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/components/Me/ApiSettings.tsx
  packages/app/src/components/Me/BasicInfoSettings.tsx
  packages/app/src/components/Me/EditorSettings.tsx
  packages/app/src/components/Me/InAppNotificationSettings.tsx
  packages/app/src/components/Me/PasswordSettings.jsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
  packages/app/src/components/PasswordResetExecutionForm.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
  packages/app/src/pages/forgot-password.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/reset-password.page.tsx
Labels: feature

#6802 fix: Pressing various buttons in the three-point reader on an empty page does not open the modal
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: bug

#6801 fix: Show alert when appsiteurl is not set
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/AppSetting.jsx
  packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
  packages/app/src/components/AlertSiteUrlUndefined.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
  packages/app/src/pages/utils/commons.ts
Labels: bug

#6804 fix: 106996 private legacy style
  packages/app/src/styles/theme/_reboot-bootstrap-theme-colors.scss
Labels: bug

#6805 fix: Staff credit
  packages/app/public/static/fonts/PressStart2P.ttf
  packages/app/src/components/Hotkeys/HotkeysDetector.jsx
  packages/app/src/components/Hotkeys/HotkeysManager.jsx
  packages/app/src/components/StaffCredit/StaffCredit.jsx
  packages/app/src/components/StaffCredit/StaffCredit.module.scss
  packages/app/src/components/StaffCredit/StaffCredit.tsx
  packages/app/src/pages/_document.page.tsx
  packages/app/src/stores/staff.tsx
  packages/app/src/styles/_fonts.scss
  packages/app/src/styles/_variables.scss
  packages/app/src/styles/style-next.scss
Labels: bug

#6793 fix: VRT PageDeleteModal is shown successfully failed
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#6794 fix: Modal styles and Enable Lato font
  packages/app/src/components/Page/CopyDropdown.jsx
  packages/app/src/components/Page/CopyDropdown.module.scss
  packages/app/src/components/RevisionComparer/RevisionComparer.module.scss
  packages/app/src/pages/_document.page.tsx
  packages/app/src/styles/_layout.scss
Labels: bug

#6791 fix: Update useCallback for redo calcViewHeight
  packages/app/src/components/TableOfContents.tsx
Labels: bug

#6809 imprv: Show Import Form
  packages/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  packages/app/src/components/Admin/ImportData/GrowiArchiveSection.jsx
Labels: improvement

#6812 fix: Image not showing and exceeding crop modal area
  packages/app/src/components/Common/ImageCropModal.tsx
Labels: bug

#6796 feat: isolate hackmd from app
  lerna.json
  package.json
  packages/app/docker/Dockerfile
  packages/app/package.json
  packages/app/src/server/routes/hackmd.js
  packages/app/src/server/routes/index.js
  packages/codemirror-textlint/package.json
  packages/core/package.json
  packages/hackmd/.gitignore
  packages/hackmd/package.json
  packages/hackmd/src/hackmd-agent.js
  packages/hackmd/src/hackmd-styles.js
  packages/hackmd/src/index.js
  packages/hackmd/src/styles.scss
  packages/hackmd/vite.config.js
  packages/plugin-attachment-refs/package.json
  packages/plugin-lsx/package.json
  packages/remark-growi-plugin/package.json
  packages/slack/package.json
  packages/slackbot-proxy/package.json
  packages/ui/package.json
  yarn.lock
Labels: feature

#6815 fix: config i18n in trash
  packages/app/src/pages/trash.page.tsx
Labels: bug

#6819 fix: Error when opening notification created on page update
  packages/app/src/server/routes/page.js
Labels: bug

#6811 fix: Add alert component for expired page
  packages/app/src/pages/share/[[...path]].page.tsx
Labels: bug

#6813 fix: Normalize VRT (30-search)
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: bug

#6806 fix: Remove pagelist from forbidden page component
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/ForbiddenPage.tsx
Labels: bug

#6810 imprv: Create a new global notification trigger
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
Labels: improvement

#6824 fix: FullTextSearchManagement header is not shown
  packages/app/src/components/Admin/FullTextSearchManagement.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
Labels: bug, improvement

#6825 imprv: Pass non-null socket to props for ImportForm component
  packages/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
Labels: improvement

#6826 imprv: Smooth scroll
  packages/app/package.json
  packages/app/src/client/util/smooth-scroll.ts
  packages/app/src/components/ContentLinkButtons.tsx
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/ReplyComments.tsx
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/services/renderer/rehype-plugins/keyword-highlighter.ts
  yarn.lock
Labels: improvement

#6829 feat: Attach scss module styles for DeleteAttachmentModal
  packages/app/src/components/PageAttachment/DeleteAttachmentModal.module.scss
  packages/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/styles/_attachments.scss
Labels: feature

#6814 feat: Enable change logo from admin/customize
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_app.page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/stores/context.tsx
Labels: feature

#6803 fix: tags page VRT
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6830 fix: Links in duplicate pages do not work
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/IdenticalPathPage.tsx
Labels: bug

#6832 fix: Finding "Anyone with the link" page
  packages/app/src/server/models/page.ts
  packages/app/src/server/service/page.ts
Labels: bug

#6837 fix: i18n PageTree
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Sidebar/PageTree.tsx
Labels: bug

#6840 imprv: Use next/route
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
  packages/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  packages/app/src/components/InstallerForm.tsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Sidebar/Tag.tsx
Labels: improvement

#6808 fix: Unable to update empty pages
  packages/app/src/client/services/page-operation.ts
Labels: bug

#6820 fix: reload trash page lists after empty the trash
  packages/app/src/components/EmptyTrashButton.tsx
  packages/app/src/components/EmptyTrashModal.tsx
  packages/app/src/components/TrashPageList.tsx
  packages/app/src/stores/modal.tsx
Labels: bug

#6841 fix: pageMove notification message
  packages/app/src/server/routes/apiv3/pages.js
Labels: bug

#6818 imprv: Refactoring admin pages
  packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  packages/app/src/components/Layout/AdminLayout.tsx
  packages/app/src/pages/admin/[[...path]].page.tsx
  packages/app/src/pages/admin/app.page.tsx
  packages/app/src/pages/admin/audit-log.page.tsx
  packages/app/src/pages/admin/customize.page.tsx
  packages/app/src/pages/admin/export.page.tsx
  packages/app/src/pages/admin/global-notification/new.page.tsx
  packages/app/src/pages/admin/importer.page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/pages/admin/markdown.page.tsx
  packages/app/src/pages/admin/notification.page.tsx
  packages/app/src/pages/admin/search.page.tsx
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/admin/slack-integration-legacy.page.tsx
  packages/app/src/pages/admin/slack-integration.page.tsx
  packages/app/src/pages/admin/user-groups.page.tsx
  packages/app/src/pages/admin/users/external-accounts.page.tsx
  packages/app/src/pages/admin/users/index.page.tsx
  packages/app/src/pages/maintenance.page.tsx
  packages/app/src/utils/admin-page-util.ts
Labels: improvement

#6836 feat: 106971 Update PageAccessories modal for next routing
  packages/app/src/components/PageAttachment.tsx
  packages/app/src/components/PageAttachment/PageAttachmentList.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/core/src/interfaces/attachment.ts
  packages/ui/src/components/Attachment/Attachment.jsx
  packages/ui/src/components/Attachment/Attachment.tsx
Labels: feature

#6833 fix: Disable single deletion of empty pages
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/PageManagement/ApiErrorMessage.jsx
  packages/app/src/server/routes/page.js
Labels: bug, feature

#6847 fix: Show deleteUser insteadof lastUpdateUser in the alert of trashed pages
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
Labels: bug

#6846 imprv: UserPicture with next/router
  packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  packages/app/src/components/Admin/Users/UserTable.jsx
  packages/app/src/styles/bootstrap/_override.scss
  packages/ui/src/components/User/UserPicture.jsx
  packages/ui/src/components/User/UserPicture.tsx
Labels: exclude from changelog

#6845 fix: Normalize VRT (50-sidebar)
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug

#6828 support: Fix error caused by the absence of a reference
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support, exclude from changelog

#6835 fix: refactor method to put back page from trash
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/server/service/page.ts
Labels: bug

#6851 fix: 107357 fix put back parent from trash for master
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/server/service/page.ts
Labels: bug

#6848 imprv: Use next/router after page processing
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: improvement, exclude from changelog

#6854 imprv: Use next/router when put back
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/ui.tsx
Labels: improvement, exclude from changelog

#6850 support: 107722 refactor hackmd state
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/hackmd.ts
Labels: support

#6842 feat: Admin typescriptzation integrate
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/ManageExternalAccount.jsx
  packages/app/src/components/Admin/ManageExternalAccount.tsx
  packages/app/src/components/Admin/Security/DeleteAllShareLinksModal.jsx
  packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
  packages/app/src/components/Admin/Security/ShareLinkSetting.jsx
  packages/app/src/components/Admin/Security/ShareLinkSetting.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/UserManagement.jsx
  packages/app/src/components/Admin/UserManagement.module.scss
  packages/app/src/components/Admin/UserManagement.tsx
  packages/app/src/components/Admin/Users/ExternalAccountTable.jsx
  packages/app/src/components/Admin/Users/ExternalAccountTable.module.scss
  packages/app/src/components/Admin/Users/ExternalAccountTable.tsx
  packages/app/src/components/Admin/Users/GiveAdminButton.jsx
  packages/app/src/components/Admin/Users/GiveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminMenuItem.tsx
  packages/app/src/components/Admin/Users/SortIcons.tsx
  packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
  packages/app/src/components/Admin/Users/UserTable.jsx
  packages/app/src/components/Admin/Users/UserTable.tsx
  packages/app/src/components/Navbar/AuthorInfo.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/DeleteCommentModal.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/PageStatusAlert.jsx
  packages/app/src/components/ShareLink/ShareLinkList.tsx
  packages/app/src/components/User/UserInfo.tsx
  packages/app/src/components/User/Username.jsx
  packages/app/src/components/User/Username.tsx
  packages/core/src/interfaces/user.ts
Labels: feature

#6807 imprv: Normalize VRT (20, 21)
  packages/app/src/components/Layout/RawLayout.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
  packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
  packages/app/test/cypress/support/commands.ts
Labels: improvement

#6858 feat: Display sign-up form for email verification
  packages/app/src/pages/login.page.tsx
Labels: feature
