Repository growilabs/growi, pull requests merged in 2022-09, with the labels that each got.

#6516 feat: Rendering Fab component
  packages/app/src/components/Fab.jsx
  packages/app/src/components/Fab.module.scss
  packages/app/src/components/Layout/BasicLayout.tsx
Labels: feature

#6483 imprv: Apply Nextjs to BookmarkList
  packages/app/src/components/Admin/UserGroupDetail/UserGroupPageList.tsx
  packages/app/src/components/ContentLinkButtons.tsx
  packages/app/src/components/PageList/BookmarkList.tsx
  packages/app/src/components/PageList/PageListItemS.jsx
  packages/app/src/components/PageList/PageListItemS.tsx
  packages/app/src/components/RecentCreated/RecentCreated.tsx
  packages/app/src/components/UsersHomePageFooter.module.scss
  packages/app/src/components/UsersHomePageFooter.tsx
  packages/app/src/interfaces/bookmark-info.ts
  packages/app/src/pages/[[...path]].page.module.scss
  packages/app/src/pages/[[...path]].page.tsx
Labels: improvement

#6263 feat: Truncate long path when recent changes is in S size
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/styles/_recent-changes.scss
Labels: feature

#6466 imprv: gw7859 hide changed item vrt install
  packages/app/test/cypress/integration/10-install/install.spec.ts
Labels: improvement

#6537 fix: Disallow retrieval of revision data that does not match the page
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#6538 fix: Disallow retrieval of revision data that does not match the page for v4
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#6525 fix: Make PageTree input not draggable when editting
  packages/app/src/components/Common/ClosableTextInput.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug

#6554 imprv: Added page URL to mail subject
  packages/app/src/server/service/global-notification/global-notification-mail.js
  packages/app/src/server/service/global-notification/index.js
Labels: improvement

#6539 feat: Create invitedForm
  packages/app/config/rate-limiter.ts
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Invited.module.scss
  packages/app/src/components/InvitedForm.tsx
  packages/app/src/components/Layout/NoLoginLayout.tsx
  packages/app/src/pages/installer.page.tsx
  packages/app/src/pages/invited.page.tsx
  packages/app/src/pages/login.page.tsx
  packages/app/src/server/middlewares/login-required.js
  packages/app/src/server/routes/index.js
  packages/app/test/integration/middlewares/login-required.test.js
Labels: feature

#6548 feat: Update PageComment and PageContentFooter for SearchesultContent page
  packages/app/src/components/Comments.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/CommentPreview.tsx
  packages/app/src/components/PageComment/ReplyComments.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/pages/[[...path]].page.tsx
Labels: feature

#6530 fix: Cannot update user group without parent
  packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
Labels: bug

#6566 imprv: Update PageContentFooter for present updated data
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/pages/[[...path]].page.tsx
Labels: improvement

#6518 imprv: Update Footer content integrate
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/UserGroupDetail/UserGroupPageList.tsx
  packages/app/src/components/Comments.tsx
  packages/app/src/components/ContentLinkButtons.tsx
  packages/app/src/components/Icons/RecentlyCreatedIcon.tsx
  packages/app/src/components/Navbar/DrawerToggler.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/RevisionLoader.jsx
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/Page/TagLabels.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageComment/CommentPreview.tsx
  packages/app/src/components/PageComment/DeleteCommentModal.tsx
  packages/app/src/components/PageComment/ReplyComments.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/components/PageList/BookmarkList.tsx
  packages/app/src/components/PageList/PageListItemS.jsx
  packages/app/src/components/PageList/PageListItemS.tsx
  packages/app/src/components/PagePathHierarchicalLink.tsx
  packages/app/src/components/RecentCreated/RecentCreated.jsx
  packages/app/src/components/RecentCreated/RecentCreated.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/components/UsersHomePageFooter.module.scss
  packages/app/src/components/UsersHomePageFooter.tsx
  packages/app/src/interfaces/bookmark-info.ts
  packages/app/src/pages/[[...path]].page.module.scss
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/styles/_user.scss
Labels: improvement

#6594 support: Add cy.collapseSidebar(false) to use-tools.spec.ts
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, support

#6592 imprv: Ensure initial pages order
  packages/app/src/server/service/installer.ts
Labels: improvement

#6593 imprv: Constant toastr transparency (VRT)
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: improvement, exclude from changelog

#6595 support: refactoring search screen VRT
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support, exclude from changelog

#6602 support: Activate collapse sidebar for guest user's access to page
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/support/commands.ts
  packages/app/test/cypress/support/index.ts
Labels: support, exclude from changelog

#6601 support: Update access-to-page.spec.ts for VRT normalization
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: exclude from changelog

#6589 imprv: ToC
  packages/app/package.json
  packages/app/src/client/util/blink-section-header.ts
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/components/TableOfContents.module.scss
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/services/renderer/rehype-plugins/relocate-toc.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  yarn.lock
Labels: improvement

#6610 support: wait for toastr to change its color occured by mouseover
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support, exclude from changelog

#6608 support: Close sidebar in unnecessary pages
  packages/app/src/server/routes/index.js
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: support, exclude from changelog

#6607 fix: Visiting the trash page with the sidebar closed when in guest mode (VRT)
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: exclude from changelog

#6615 support: Take screenshot after #grw-tag-labels is visible for VRT normalization
  packages/app/src/components/Page/TagLabels.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support, exclude from changelog

#6611 support: Update search.spec.ts use-tools.spec.ts for VRT normalization
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support, exclude from changelog

#6614 fix: Do not wait to save user-ui-settings (VRT)
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug, exclude from changelog

#6616 imprv: VRT search by tag
  packages/app/src/server/service/installer.ts
Labels: improvement

#6603 support: Fix Page List VRT with force to focus the element
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support, exclude from changelog

#6621 support: Update search.spec.ts for VRT normalization
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: exclude from changelog

#6619 imprv: VRT access to page by guest
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: improvement

#6633 support: VRT fix waitind for pagelist rendering
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
Labels: support, exclude from changelog

#6632 support: VRT fix scroll timing
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support, exclude from changelog

#6631 fix: firstName and lastName japanese translations in SAML
  packages/app/public/static/locales/ja_JP/translation.json
Labels: bug, improvement

#6648 support: Add wait for loading layout image in VRT
  packages/app/test/cypress/integration/30-search/search.spec.ts
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
Labels: support, exclude from changelog

#6650 support: Update spec ts for VRT normalization
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: exclude from changelog

#6658 imprv: Remove unnecessary test
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: improvement, exclude from changelog

#6635 feat: Avoid Fab sticky-events errors
  packages/app/src/client/util/smooth-scroll.ts
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Icons/CreatePageIcon.tsx
  packages/app/src/components/Icons/ReturnTopIcon.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
Labels: feature

#6663 support: Update Fab dynamic import to ShareLinkLayout.tsx
  packages/app/src/components/Layout/ShareLinkLayout.tsx
Labels: exclude from changelog

#6665 support: Enable Fab
  packages/app/src/components/Fab.tsx
Labels: exclude from changelog

#6585 feat: Modify middlewares used for POST /login with apiv3
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/LoginForm.tsx
  packages/app/src/server/middlewares/login-form-validator.ts
  packages/app/src/server/middlewares/register-form-validator.ts
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/routes/login.js
Labels: feature

#6659 fix: VRT page-control-item-menu on search page
  packages/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#6669 fix: Update PagePathHierarchicalLink for hydration error
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PagePathNav.tsx
Labels: bug

#6679 feat: Disable StickyEvents
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Layout/ShareLinkLayout.tsx
Labels: feature

#6677 feat: Add option to not use crop modal on brand logo upload
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
  packages/app/src/components/Common/ImageCropModal.tsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
Labels: feature

#6649 support: add wait for header style in VRT
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
Labels: support, exclude from changelog

#6688 fix(auditlog): Attachment download is displayed even if the filter is unchecked
  packages/app/public/static/locales/en_US/admin/admin.json
  packages/app/public/static/locales/ja_JP/admin/admin.json
  packages/app/public/static/locales/zh_CN/admin/admin.json
  packages/app/src/interfaces/activity.ts
Labels: bug, exclude from changelog
