Repository growilabs/growi, pull requests merged in 2022-11, with the labels that each got.

#6864 fix: Cannot create / update pages by specifying groups
  packages/app/src/components/SavePageControls/GrantSelector.tsx
Labels: bug

#6844 imprv: Show UserGroupDetail and GlobalNotificationDetail pages
  packages/app/_obsolete/src/client/admin.jsx
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
  packages/app/src/pages/admin/user-group-detail/[userGroupId].page.tsx
  packages/app/src/server/routes/admin.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/notification-setting.js
  packages/app/src/server/views/admin/global-notification-detail.html
  packages/app/src/server/views/admin/user-group-detail.html
  packages/app/src/stores/global-notification.ts
Labels: improvement

#6863 fix: 107952 Update Admin i18n
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/AppSetting.jsx
  packages/app/src/components/Admin/Security/ShareLinkSetting.tsx
  packages/app/src/components/Admin/Users/GiveAdminButton.tsx
  packages/app/src/components/Admin/Users/PasswordResetModal.jsx
  packages/app/src/components/Admin/Users/RemoveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminMenuItem.tsx
  packages/app/src/components/Admin/Users/StatusActivateButton.jsx
  packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
  packages/app/src/components/Admin/Users/UserRemoveButton.jsx
  packages/app/src/components/ShareLink/ShareLink.tsx
  packages/app/src/components/ShareLink/ShareLinkList.tsx
Labels: bug

#6857 support: 107721 refactor page status alert ts fc
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.jsx
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/stores/hackmd.ts
Labels: support, exclude from changelog

#6862 imprv: 104019 Display HandsontableModal
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/HandsontableModal.jsx
  packages/app/src/components/PageEditor/HandsontableModal.module.scss
  packages/app/src/styles/_handsontable.scss
  packages/app/src/styles/style-app.scss
  packages/app/src/styles/style-next.scss
Labels: improvement

#6861 fix: Behavior when the email settings is not set up
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/login.js
Labels: bug

#6860 support: refactor context
  packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
  packages/app/src/interfaces/admin.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/utils/layout.ts
  packages/app/src/stores/admin/customize.tsx
  packages/app/src/stores/context.tsx
Labels: support, exclude from changelog

#6859 feat: Enable email sending for email authentication
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  packages/app/src/components/LoginForm.tsx
  packages/app/src/pages/login.page.tsx
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/user-activation.ts
Labels: feature

#6872 imprv: TypeScriptize ManageGlobalNotification
  packages/app/public/static/locales/en_US/admin.json
  packages/app/src/client/interfaces/global-notification.ts
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.tsx
  packages/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
  packages/app/src/pages/admin/global-notification/new.page.tsx
  packages/app/src/stores/global-notification.ts
Labels: improvement

#6875 fix: Add addActivity middleware
  packages/app/src/server/routes/apiv3/users.js
Labels: bug

#6874 imprv: Show AdminNotFoundPage
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/NotFoundPage.tsx
  packages/app/src/components/Layout/AdminLayout.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/pages/admin/[...path].page.tsx
Labels: improvement

#6853 fix: clear underline of notification icon
  packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
Labels: bug

#6877 fix: 107157 Update Admin i18n
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Notification/GlobalNotificationList.jsx
  packages/app/src/components/Admin/Notification/ManageGlobalNotification.tsx
  packages/app/src/components/Admin/Notification/NotificationDeleteModal.jsx
  packages/app/src/components/Admin/SlackIntegration/ConfirmBotChangeModal.jsx
  packages/app/src/components/Common/ImageCropModal.tsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/components/Page/CopyDropdown.jsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/pages/admin/global-notification/new.page.tsx
Labels: bug

#6866 feat: UserActivationPage
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/CompleteUserRegistrationForm.tsx
  packages/app/src/interfaces/errors/user-activation.ts
  packages/app/src/pages/user-activation.page.tsx
  packages/app/src/server/middlewares/inject-user-registration-order-by-token-middleware.ts
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/user-activation.ts
Labels: feature

#6883 fix: Normalize VRT (60-home/home.spec.ts/home--visit-home.png)
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: bug

#6882 imprv: VRT normalization 107991
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
Labels: improvement

#6884 fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-recent-changes-1-page-list.png)
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug

#6879 fix: 108203 Enable Open GROWI Cloud Settings
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/AppSetting.jsx
  packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
  packages/app/src/components/AlertSiteUrlUndefined.tsx
  packages/app/src/pages/admin/app.page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/stores/context.tsx
Labels: bug

#6887 feat: HandsonTableModal TSFC hooks
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/HandsontableModal.jsx
  packages/app/src/components/PageEditor/HandsontableModal.module.scss
  packages/app/src/components/PageEditor/HandsontableModal.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/styles/style-next.scss
Labels: feature

#6888 fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-page-tree-1-access-to-page-tree.png)
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug

#6889 fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-access-to-trash-page.png)
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Labels: bug

#6869 support: 107942 refactor static swr for context
  packages/app/src/stores/context.tsx
  packages/app/src/stores/use-context-swr.tsx
Labels: support

#6896 fix: accessory modal vrt
  packages/app/src/components/User/UserDate.jsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, exclude from changelog

#6880 fix: page item controll VRT
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, exclude from changelog

#6891 fix: Fix User group bugs
  packages/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
Labels: bug

#6899 fix: Gear button does not appear on user group details
  packages/app/src/pages/admin/user-group-detail/[userGroupId].page.tsx
Labels: bug

#6903 fix: Cannot automatically transition to root when login with external account
  packages/app/src/server/routes/login-passport.js
Labels: bug

#6873 imprv: Mutate current page data after page operation by PageTree
  packages/app/src/components/Comments.tsx
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Hotkeys/Subscribers/CreatePage.jsx
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/GrowiNavbarBottom.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/components/SavePageControls.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/installer.page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page-listing.tsx
  packages/app/src/stores/page-redirect.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/stores/ui.tsx
Labels: exclude from changelog

#6904 support: refactor swr initialize
  packages/app/src/stores/page.tsx
Labels: support

#6868 support: normalize guest sandbox vrt
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: support, exclude from changelog

#6898 fix: tag-operations-page-rename VRT
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, exclude from changelog

#6886 fix: Do not allow users to login when user registration is restricted
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/CompleteUserRegistration.tsx
  packages/app/src/components/CompleteUserRegistrationForm.tsx
  packages/app/src/components/LoginForm.tsx
  packages/app/src/interfaces/registration-mode.ts
  packages/app/src/pages/login.page.tsx
  packages/app/src/pages/user-activation.page.tsx
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/login.js
Labels: bug

#6905 fix: 107915 GlobalNotification toolchip update
  packages/app/src/client/interfaces/global-notification.ts
  packages/app/src/client/interfaces/notification.ts
  packages/app/src/components/Admin/Notification/GlobalNotificationList.jsx
  packages/app/src/components/Admin/Notification/NotificationTypeIcon.jsx
  packages/app/src/components/Admin/Notification/NotificationTypeIcon.tsx
  packages/app/src/components/Admin/Notification/UserNotificationRow.jsx
Labels: bug

#6911 fix: page wide view not working
  packages/app/src/server/service/page.ts
Labels: bug

#6912 support: VRT search all page
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support

#6915 fix: Check if entered email address is included in whitelist
  packages/app/src/server/routes/apiv3/user-activation.ts
  packages/app/src/server/routes/login.js
Labels: bug

#6913 fix: Normalize VRT for 107990
  packages/app/src/components/Navbar/PageEditorModeManager.jsx
  packages/app/src/components/PageEditor/Editor.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: exclude from changelog

#6895 support: refactor page wide view
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/SubNavButtons.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/server/service/page.ts
  packages/app/src/stores/context.tsx
  packages/core/src/interfaces/page.ts
Labels: support

#6918 feat: Cannot display default logo on sidebar
  packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/server/routes/apiv3/customize-setting.js
Labels: feature

#6916 fix: User registration form is not displayed when registration mode is close
  packages/app/src/components/LoginForm.tsx
  packages/app/src/pages/login.page.tsx
  packages/app/src/server/routes/apiv3/user-activation.ts
Labels: bug

#6919 support: refactor customize layout in admin
  packages/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
Labels: bug, support

#6923 fix: Cannot Login to GROWI by local machine in VRT
  packages/app/test/cypress/support/commands.ts
Labels: bug

#6922 fix: Password reset link appears on login form when password reset is not enabled
  packages/app/src/pages/login.page.tsx
Labels: bug

#6926 feat: Enable PasteFiles and ScrollCursorIntoView on CodeMirrorEditor
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/UncontrolledCodeMirror.tsx
Labels: feature

#6900 fix: login ui is shown on navigation bar even if users are logged in
  packages/app/src/pages/admin/[...path].page.tsx
  packages/app/src/pages/admin/app.page.tsx
  packages/app/src/pages/admin/audit-log.page.tsx
  packages/app/src/pages/admin/customize.page.tsx
  packages/app/src/pages/admin/export.page.tsx
  packages/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
  packages/app/src/pages/admin/global-notification/new.page.tsx
  packages/app/src/pages/admin/importer.page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/pages/admin/markdown.page.tsx
  packages/app/src/pages/admin/notification.page.tsx
  packages/app/src/pages/admin/search.page.tsx
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/admin/slack-integration-legacy.page.tsx
  packages/app/src/pages/admin/slack-integration.page.tsx
  packages/app/src/pages/admin/user-group-detail/[userGroupId].page.tsx
  packages/app/src/pages/admin/user-groups.page.tsx
  packages/app/src/pages/admin/users/external-accounts.page.tsx
  packages/app/src/pages/admin/users/index.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/utils/admin-page-util.ts
Labels: bug

#6925 fix: share link modal vrt
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, exclude from changelog

#6933 support: Extend defaultCommandTimrout for VRT
  packages/app/cypress.json
Labels: exclude from changelog

#6921 feat: Enable HandsonTableModal
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/HandsontableModal.jsx
  packages/app/src/components/PageEditor/HandsontableModal.module.scss
  packages/app/src/components/PageEditor/HandsontableModal.tsx
  packages/app/src/components/PageEditor/MarkdownTableDataImportForm.jsx
  packages/app/src/components/PageEditor/MarkdownTableDataImportForm.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/styles/style-next.scss
Labels: feature

#6936 fix: Template page selection dropdown not working
  packages/app/src/components/PageCreateModal.jsx
Labels: bug

#6856 feat: 106973 Enable View this version on PageAccessoriesModal History tab
  packages/app/src/components/Comments.tsx
  packages/app/src/components/Navbar/PageEditorModeManager.jsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageEditor/Editor.tsx
  packages/app/src/components/PageHistory.tsx
  packages/app/src/components/PageHistory/PageRevisionTable.tsx
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/PageHistory/RevisionDiff.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: feature

#6941 feat: Update not latest version alert for ja
  packages/app/public/static/locales/ja_JP/translation.json
Labels: feature

#6935 fix: visit home vrt
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: bug, exclude from changelog

#6939 fix: Normalize VRT (20-basic-features/use-tools.spec.ts/Modal for page operation -- Trying to create template page under the root page fail (failed).png)
  packages/app/src/components/PageCreateModal.jsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#6942 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/Access to meall-in-app-notifications -- All In-App Notification list is successfully loaded (failed).png)
  packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6943 support: Normalize vrt add wait skeleton disappear
  packages/app/src/components/Admin/Notification/NotificationSetting.jsx
  packages/app/src/components/Navbar/AuthorInfo.module.scss
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.module.scss
  packages/app/src/components/Navbar/GrowiSubNavigation.tsx
  packages/app/src/components/Navbar/PageEditorModeManager.module.scss
  packages/app/src/components/Page/TagLabels.module.scss
  packages/app/src/components/Page/TagLabels.tsx
  packages/app/src/components/PageComment.module.scss
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.module.scss
  packages/app/src/components/PageCommentSkeleton.tsx
  packages/app/src/components/PageContentFooter.module.scss
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/Skeleton.tsx
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
  packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
  packages/app/test/cypress/integration/60-home/home.spec.ts
  packages/app/test/cypress/support/commands.ts
  packages/app/test/cypress/support/index.ts
Labels: support

#6927 imprv: Update Cypress test 108870 108871 108872
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
  packages/app/test/cypress/integration/30-search/search.spec.ts
  packages/app/test/cypress/support/commands.ts
  packages/app/test/cypress/support/index.ts
Labels: improvement

#6924 support: Normalize vrt 107989
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: exclude from changelog

#6928 fix: Unsend Email notification styles
  packages/app/src/components/Admin/Security/ShareLinkSetting.tsx
  packages/app/src/components/Admin/Users/GiveAdminButton.tsx
  packages/app/src/components/Admin/Users/RemoveAdminMenuItem.tsx
  packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
  packages/app/src/components/Admin/Users/UserMenu.jsx
  packages/app/src/components/Admin/Users/UserMenu.module.scss
  packages/app/src/components/Admin/Users/UserMenu.tsx
  packages/app/src/styles/_user.scss
  packages/core/src/interfaces/user.ts
Labels: bug

#6955 feat: Update Admin i18n
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/App/AppSetting.jsx
  packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
  packages/app/src/components/Admin/App/SiteUrlSetting.tsx
  packages/app/src/components/Admin/Notification/NotificationSetting.jsx
  packages/app/src/components/Admin/Notification/UserTriggerNotification.jsx
  packages/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  packages/app/src/components/Admin/UserManagement.tsx
  packages/app/src/components/Common/ImageCropModal.tsx
  packages/app/src/components/PageEditor/HandsontableModal.tsx
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
  packages/slackbot-proxy/src/services/SelectGrowiService.ts
Labels: feature

#6950 fix: Make body template work
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#6932 fix: Show footer and not show alert
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/SavePageControls.tsx
  packages/app/src/components/UnsavedAlertDialog.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/page.tsx
Labels: bug

#6929 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/Access to page -- Sandbox with edit is successfully loaded (failed).png)
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6953 fix: PageAttachment vrt
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug, exclude from changelog

#6937 support: Normalize vrt 108861
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: support, exclude from changelog

#6944 fix: 10740 Refactoring useIsSearchPage and GlobalSearch
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/pages/admin/[...path].page.tsx
  packages/app/src/pages/admin/security.page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/stores/context.tsx
Labels: bug, improvement

#6958 feat: Update History feature Next Link path
  packages/app/src/components/Navbar/GlobalSearch.tsx
  packages/app/src/components/PageAlert/OldRevisionAlert.tsx
  packages/app/src/components/PageHistory.tsx
  packages/app/src/components/PageHistory/PageRevisionTable.tsx
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/PageHistory/RevisionDiff.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/core/src/utils/path-utils.js
Labels: feature

#6960 fix: Normalize VRT (20-basic-features/use-tools.spec.ts/Modal for page operation -- Trying to create template page under the root page fail (failed).png)
  packages/app/src/components/PageCreateModal.jsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#6963 fix: Update Admin i18n
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
  packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
  packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
Labels: bug

#6972 fix: Show page after page create
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/SavePageControls.tsx
  packages/app/src/components/UnsavedAlertDialog.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/stores/use-context-swr.tsx
  packages/app/src/stores/use-static-swr.tsx
Labels: bug

#6969 fix: sandbox header vrt
  packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
Labels: exclude from changelog

#6970 support: Cherry pick #6910
  packages/app/src/interfaces/page-operation.ts
  packages/app/src/server/models/interfaces/page-operation.ts
  packages/app/src/server/models/obsolete-page.js
  packages/app/src/server/models/page-operation.ts
  packages/app/src/server/models/page.ts
  packages/app/src/server/models/user-group-relation.js
  packages/app/src/server/models/user-group.ts
  packages/app/src/server/routes/apiv3/page.js
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/routes/page.js
  packages/app/src/server/routes/tag.js
  packages/app/src/server/service/installer.ts
  packages/app/src/server/service/page-grant.ts
  packages/app/src/server/service/page-operation.ts
  packages/app/src/server/service/page.ts
  packages/app/src/stores/page.tsx
  packages/app/test/integration/models/v5.page.test.js
  packages/app/test/integration/service/page-grant.test.js
  packages/app/test/integration/service/v5.non-public-page.test.ts
  packages/app/test/integration/service/v5.public-page.test.ts
  packages/core/src/interfaces/page.ts
Labels: support

#6964 fix: Keep URL parameter when change editor mode
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/stores/ui.tsx
Labels: bug

#6966 feat: Create in-app notification when empty trash
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
Labels: feature

#6967 feat: Update Footer and Comment Skeleton
  packages/app/src/components/Comments.tsx
  packages/app/src/components/PageComment.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageComment/ReplyComments.tsx
  packages/app/src/components/PageCommentSkeleton.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/pages/[[...path]].page.tsx
Labels: feature

#6973 fix: VRT 20 basic-features-use-tools.spec.ts-Tag Oprations
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#6979 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-headers.png)
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6981 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-math.png)
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6987 fix: Login strategy name
  packages/app/src/pages/login.page.tsx
Labels: bug

#6988 imprv: VRT Check isEnabledLinebreaksInComments is enabled
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
Labels: bug

#6971 fix: Fixed use of revision in request parameters
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: bug

#6968 support: page operation socket
  packages/app/_obsolete/src/client/services/PageContainer.js
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/interfaces/websocket.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/websocket.tsx
Labels: support

#6980 support: Add dependency to ItemsTree > onClickDeleteMenuItem
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Labels: support

#6983 feat: Remove all tags and attrs section in admin/markdown
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
Labels: feature

#6984 feat: Update useSWRxCurrentPage for specific revisionId url param
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: feature

#6885 imprv: sidebar skelton pagetree
  packages/app/src/components/Sidebar.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.module.scss
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/Sidebar/SidebarHeaderReloadButton.tsx
  packages/app/src/components/Sidebar/Skelton/PageTreeContentSkelton.tsx
  packages/app/src/components/Sidebar/Skelton/SidebarHeaderSkelton.module.scss
  packages/app/src/components/Sidebar/Skelton/SidebarHeaderSkelton.tsx
  packages/app/src/components/Sidebar/Skelton/SidebarSkelton.tsx
  packages/app/src/components/Sidebar/Tag.tsx
Labels: improvement

#6986 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-special-pages--tags.png)
  packages/app/src/pages/tags.page.tsx
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#6993 fix: Normalize VRT (20-basic-features/access-to-pagelist.spec.ts/access-to-pagelist-6-page-list-modal-size-normal.png)
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
Labels: bug

#6938 support: Normalize VRT 108863
  packages/app/test/cypress/integration/30-search/search.spec.ts
Labels: support, exclude from changelog

#6978 support: Normalize VRT 109445
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/test/cypress/integration/60-home/home.spec.ts
Labels: exclude from changelog

#6996 fix: Update admin i18n GrowiNavbar
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Navbar/GrowiNavbar.tsx
Labels: bug, feature

#6961 fix: AttachTitleHeader
  packages/app/src/components/PageEditor.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
Labels: bug

#6995 fix: Enable link to home at editor
  packages/app/src/components/EventListeneres/HashChanged.tsx
  packages/app/src/stores/ui.tsx
Labels: bug

#6998 imprv: Add throttle and debounce for cursor moving events
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Labels: exclude from changelog

#6999 fix: Normalize VRT (20-basic-features/click-page-icons)
  packages/app/src/components/BookmarkButtons.tsx
  packages/app/src/components/LikeButtons.tsx
  packages/app/src/components/SubscribeButton.tsx
  packages/app/src/components/User/SeenUserInfo.tsx
  packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
Labels: bug

#7000 fix: Normalize VRT (20-basic-features/access-to-pagelist)
  packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
Labels: bug

#7001 fix: VRT 40 Admin Page Security
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
Labels: bug

#6991 fix: Normalize VRT 50-sidebar
  packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
  packages/app/test/cypress/integration/50-sidebar/switching-sidebar-mode.spec.ts
Labels: bug

#7008 fix: Normalize VRT (20-basic-features/access-to-page.spec.ts)
  packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
Labels: bug

#7006 imprv: i18n for Admin Security
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
Labels: bug

#6977 support: 108172 for updated alert
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.module.scss
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/hackmd.ts
  packages/app/src/stores/page.tsx
  packages/app/src/stores/remote-latest-page.ts
  packages/app/src/styles/_page.scss
Labels: support

#7007 fix: CustomCss does not work
  packages/app/src/pages/_document.page.tsx
Labels: bug, improvement, exclude from changelog

#6989 feat: Add default markdown config values
  packages/app/src/interfaces/rehype.ts
  packages/app/src/server/models/config.ts
Labels: feature

#7009 fix: Disabled rename button when rename modal is opened
  packages/app/src/components/PageRenameModal.tsx
Labels: bug

#6920 feat: Remark drawio plugin
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  packages/app/docker/Dockerfile
  packages/app/resource/locales/en_US/sandbox-diagrams.md
  packages/app/resource/locales/ja_JP/sandbox-diagrams.md
  packages/app/resource/locales/zh_CN/sandbox-diagrams.md
  packages/app/src/client/services/page-operation.ts
  packages/app/src/client/util/editor.ts
  packages/app/src/components/Drawio.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageEditor/DrawioCommunicationHelper.ts
  packages/app/src/components/PageEditor/DrawioModal.tsx
  packages/app/src/components/PageEditor/MarkdownDrawioUtil.js
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/ReactMarkdownComponents/DrawioViewerWithEditButton.module.scss
  packages/app/src/components/ReactMarkdownComponents/DrawioViewerWithEditButton.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/SavePageControls.tsx
  packages/app/src/components/Script/DrawioViewerScript.tsx
  packages/app/src/interfaces/editor-settings.ts
  packages/app/src/interfaces/global.ts
  packages/app/src/interfaces/graph-viewer.ts
  packages/app/src/interfaces/page-operation.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/server/service/config-loader.ts
  packages/app/src/server/views/widget/headers/drawio.html
  packages/app/src/services/renderer/interceptor/drawio-interceptor.js
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/styles/_page.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/remark-drawio-plugin/.eslintignore
  packages/remark-drawio-plugin/.eslintrc.js
  packages/remark-drawio-plugin/.gitignore
  packages/remark-drawio-plugin/README.md
  packages/remark-drawio-plugin/package.json
  packages/remark-drawio-plugin/src/components/DrawioViewer.module.scss
  packages/remark-drawio-plugin/src/components/DrawioViewer.tsx
  packages/remark-drawio-plugin/src/index.ts
  packages/remark-drawio-plugin/src/interfaces/graph-viewer.ts
  packages/remark-drawio-plugin/src/services/renderer/remark-drawio-plugin.ts
  packages/remark-drawio-plugin/src/utils/embed.ts
  packages/remark-drawio-plugin/src/utils/global.ts
  packages/remark-drawio-plugin/tsconfig.base.json
  packages/remark-drawio-plugin/tsconfig.build.json
  packages/remark-drawio-plugin/tsconfig.json
  yarn.lock
Labels: exclude from changelog

#7003 fix: Normalize VRT (20-basic-features/use-tools.spec.ts)
  packages/app/src/components/PageRenameModal.tsx
  packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
Labels: bug

#7010 fix: VRT Check GROWI User Group Table is shown
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
Labels: bug

#7012 feat: HandsonTableModal direct editing from Page
  packages/app/src/components/Page.module.scss
  packages/app/src/components/Page.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/HandsontableModal.tsx
  packages/app/src/components/PageEditor/MarkdownTableUtil.js
  packages/app/src/components/ReactMarkdownComponents/DrawioViewerWithEditButton.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/TableWithEditButton.module.scss
  packages/app/src/components/ReactMarkdownComponents/TableWithEditButton.tsx
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/styles/_page.scss
Labels: feature

#6974 fix: sandbox math vrt
  packages/app/src/stores/middlewares/sync-to-storage.ts
Labels: bug

#7018 imprv: Optimize lsx
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .vscode/launch.json
  packages/app/docker/Dockerfile
  packages/app/package.json
  packages/app/src/server/crowi/index.js
  packages/app/src/services/renderer/renderer.tsx
  packages/app/tsconfig.build.client.json
  packages/app/tsconfig.build.server.json
  packages/app/tsconfig.json
  packages/core/src/index.ts
  packages/core/src/plugin/service/tag-cache-manager.js
  packages/core/src/test/plugin/service/tag-cache-manager.test.js
  packages/plugin-lsx/src/components/Lsx.tsx
  packages/plugin-lsx/src/components/LsxPageList/LsxListView.jsx
  packages/plugin-lsx/src/components/PageNode.js
  packages/plugin-lsx/src/components/index.ts
  packages/plugin-lsx/src/components/tag-cache-manager.ts
  packages/remark-drawio-plugin/package.json
  packages/remark-lsx/.eslintignore
  packages/remark-lsx/.eslintrc.js
  packages/remark-lsx/.gitignore
  packages/remark-lsx/README.md
  packages/remark-lsx/package.json
  packages/remark-lsx/src/components/Lsx.module.scss
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/components/LsxPageList/LsxListView.module.scss
  packages/remark-lsx/src/components/LsxPageList/LsxListView.tsx
  packages/remark-lsx/src/components/LsxPageList/LsxPage.tsx
  packages/remark-lsx/src/components/index.ts
  packages/remark-lsx/src/components/lsx-context.ts
  packages/remark-lsx/src/index.ts
  packages/remark-lsx/src/interfaces/page-node.ts
  packages/remark-lsx/src/server/routes/index.js
  packages/remark-lsx/src/server/routes/lsx.js
  packages/remark-lsx/src/services/renderer/index.ts
  packages/remark-lsx/src/services/renderer/lsx.ts
  packages/remark-lsx/src/stores/lsx.tsx
  packages/remark-lsx/tsconfig.base.json
  packages/remark-lsx/tsconfig.build.cjs.json
  packages/remark-lsx/tsconfig.build.esm.json
  packages/remark-lsx/tsconfig.json
Labels: exclude from changelog
