Repository growilabs/growi, pull requests merged in 2023-04, with the labels that each got.

#7525 fix: The "search" command of the GROWI bot is not functioning
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: bug

#7537 fix(drawio): Rendering uncompressed data
  packages/remark-drawio/package.json
  packages/remark-drawio/src/utils/embed.ts
  yarn.lock
Labels: bug

#7536 fix(drawio): Set compressXml option
  packages/app/src/components/PageEditor/DrawioCommunicationHelper.ts
  packages/app/src/components/PageEditor/DrawioModal.tsx
Labels: bug

#7541 fix: H6 line-height
  packages/app/src/styles/bootstrap/_override.scss
Labels: bug

#7548 fix: Username incremental search is not working in comment
  packages/app/src/components/PageComment/CommentEditor.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.module.scss
  packages/app/src/components/PageEditor/CommentMentionHelper.ts
  packages/app/src/components/PageSideContents.tsx
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--username-mention.spec.ts
Labels: bug

#7542 fix: PageTree mutiple DnD unexpected disappear and unexpected tree move if renamed path
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/server/service/page.ts
Labels: bug

#7554 fix: Is not working i18n on `/admin/export`
  packages/app/src/components/Admin/ExportArchiveDataPage.tsx
Labels: bug

#7555 fix(drawio): Render uncompressed data when line-breaks option is set
  packages/remark-drawio/src/components/DrawioViewer.tsx
Labels: bug

#7553 fix: Templates are not applied when pages are created from PageTree
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
Labels: bug

#7559 support: Use react-markdown-customkeyprop to reduce re-rendering
  packages/app/next.config.js
  packages/app/package.json
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/PagePresentationModal.tsx
  packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/TableWithEditButton.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/services/renderer/remark-plugins/table.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/consts/index.ts
  packages/remark-drawio/src/services/renderer/remark-drawio.ts
  packages/remark-lsx/src/services/renderer/lsx.ts
  yarn.lock
Labels: support

#7563 feat: VRT expansion of template page operations
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
Labels: feature

#7566 fix: Uncaught type error by `sticky-event`
  packages/app/package.json
  packages/app/src/client/side-effects/use-sticky.ts
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.tsx
  packages/app/src/components/StickyStretchableScroller.tsx
  yarn.lock
Labels: bug

#7575 imprv: Loading draw.io (diagrams.net) resources
  apps/app/src/components/PageEditor/DrawioModal.tsx
  apps/app/src/components/Script/DrawioViewerScript.tsx
  apps/app/src/interfaces/services/renderer.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/server/service/config-loader.ts
  apps/app/src/stores/context.tsx
Labels: improvement

#7577 imprv: Inject PlantUML URI with config-loader
  apps/app/src/interfaces/services/renderer.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/service/config-loader.ts
  apps/app/src/services/renderer/remark-plugins/plantuml.ts
Labels: improvement

#7576 support: Remove Blockdiag codes
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/interfaces/services/renderer.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/services/renderer/markdown-it/blockdiag.ts
  apps/app/src/services/renderer/renderer.tsx
Labels: support

#7579 imprv: Show a spinner into the save button while the saving processing
  apps/app/src/components/PageEditor.tsx
  apps/app/src/components/PageEditorByHackmd.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/stores/editor.tsx
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
Labels: improvement

#7582 fix: Show lsx page list in trash page correctly
  packages/remark-lsx/src/server/routes/lsx.ts
Labels: bug

#7584 support: Typescriptize CustomNav
  apps/app/src/components/Admin/Notification/NotificationSetting.jsx
  apps/app/src/components/Admin/Security/SecurityManagementContents.jsx
  apps/app/src/components/CustomNavigation/CustomNav.tsx
  apps/app/src/components/CustomNavigation/CustomTabContent.tsx
  apps/app/src/components/DescendantsPageListModal.tsx
  apps/app/src/components/InAppNotification/InAppNotificationPage.tsx
  apps/app/src/components/Me/PersonalSettings.jsx
  apps/app/src/components/NotFoundPage.tsx
  apps/app/src/components/PageAccessoriesModal.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/TrashPageList.tsx
  apps/app/src/interfaces/ui.ts
  apps/app/src/pages/installer.page.tsx
  packages/remark-lsx/src/server/routes/lsx.ts
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: support

#7578 support: Omit textlint
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/codeql-analysis.yml
  apps/app/next.config.js
  apps/app/package.json
  apps/app/public/static/dict/base.dat.gz
  apps/app/public/static/dict/cc.dat.gz
  apps/app/public/static/dict/check.dat.gz
  apps/app/public/static/dict/tid.dat.gz
  apps/app/public/static/dict/tid_map.dat.gz
  apps/app/public/static/dict/tid_pos.dat.gz
  apps/app/public/static/dict/unk.dat.gz
  apps/app/public/static/dict/unk_char.dat.gz
  apps/app/public/static/dict/unk_compat.dat.gz
  apps/app/public/static/dict/unk_invoke.dat.gz
  apps/app/public/static/dict/unk_map.dat.gz
  apps/app/public/static/dict/unk_pos.dat.gz
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Me/EditorSettings.tsx
  apps/app/src/components/Me/PersonalSettings.jsx
  apps/app/src/components/PageEditor.tsx
  apps/app/src/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/src/components/PageEditor/DownloadDictModal.tsx
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/UncontrolledCodeMirror.tsx
  apps/app/src/interfaces/editor-settings.ts
  apps/app/src/server/models/editor-settings.ts
  apps/app/src/server/routes/apiv3/personal-setting.js
  apps/app/src/stores/editor.tsx
  apps/app/test/cypress/integration/60-home/60-home--home.spec.ts
  apps/app/tsconfig.build.client.json
  apps/app/tsconfig.json
  package.json
  packages/codemirror-textlint/.eslintignore
  packages/codemirror-textlint/.gitignore
  packages/codemirror-textlint/package.json
  packages/codemirror-textlint/src/index.ts
  packages/codemirror-textlint/src/utils/logger/index.ts
  packages/codemirror-textlint/tsconfig.base.json
  packages/codemirror-textlint/tsconfig.build.json
  packages/codemirror-textlint/tsconfig.json
  packages/remark-lsx/package.json
  packages/remark-lsx/vite.server.config.ts
  yarn.lock
Labels: support

#7571 feat: Cypress test for useSticky features
  apps/app/src/components/Fab.tsx
  apps/app/src/components/Navbar/GrowiSubNavigationSwitcher.tsx
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--sticky-features.spec.ts
  apps/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest.spec.ts
Labels: feature

#7589 imprv: Enable browsing video (for v6.1.0)
  apps/app/src/server/routes/attachment.js
  apps/app/src/services/renderer/renderer.tsx
Labels: improvement

#7587 fix: Reverted descendant pages do not appear in search results
  apps/app/src/server/service/page.ts
  apps/app/src/server/service/search.ts
  apps/app/test/integration/service/page.test.js
Labels: bug

#7591 imprv: Allow registering without GROWI email settings for ID/Password authentication's restricted registration
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/PageNotification/UserModelNotification.tsx
  apps/app/src/components/PasswordResetRequestForm.tsx
  apps/app/src/interfaces/activity.ts
  apps/app/src/interfaces/in-app-notification.ts
  apps/app/src/models/serializers/in-app-notification-snapshot/user.ts
  apps/app/src/pages/forgot-password.page.tsx
  apps/app/src/server/routes/login.js
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/stores/in-app-notification.ts
Labels: improvement

#7597 feat: Revive attachment-refs with remark
  apps/app/package.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/models/page.ts
  packages-obsolete/plugin-attachment-refs/package.json
  packages-obsolete/plugin-attachment-refs/src/client-entry.js
  packages-obsolete/plugin-attachment-refs/src/client/css/index.css
  packages-obsolete/plugin-attachment-refs/src/client/js/components/AttachmentList.jsx
  packages-obsolete/plugin-attachment-refs/src/client/js/components/ExtractedAttachments.jsx
  packages-obsolete/plugin-attachment-refs/src/client/js/util/GalleryContext.js
  packages-obsolete/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPostRenderInterceptor.js
  packages-obsolete/plugin-attachment-refs/src/client/js/util/Interceptor/RefsPreRenderInterceptor.js
  packages-obsolete/plugin-attachment-refs/src/client/js/util/RefsContext.js
  packages-obsolete/plugin-attachment-refs/src/client/js/util/TagCacheManagerFactory.js
  packages-obsolete/plugin-attachment-refs/src/index.js
  packages-obsolete/plugin-attachment-refs/src/server-entry.js
  packages-obsolete/plugin-attachment-refs/src/server/routes/index.js
  packages-obsolete/plugin-attachment-refs/tsconfig.base.json
  packages-obsolete/plugin-attachment-refs/tsconfig.build.cjs.json
  packages-obsolete/plugin-attachment-refs/tsconfig.build.esm.json
  packages-obsolete/plugin-attachment-refs/tsconfig.json
  packages/core/src/interfaces/attachment.ts
  packages/remark-attachment-refs/.eslintignore
  packages/remark-attachment-refs/.gitignore
  packages/remark-attachment-refs/README.md
  packages/remark-attachment-refs/package.json
  packages/remark-attachment-refs/src/client/components/AttachmentList.module.scss
  packages/remark-attachment-refs/src/client/components/AttachmentList.tsx
  packages/remark-attachment-refs/src/client/components/ExtractedAttachments.tsx
  packages/remark-attachment-refs/src/client/components/Gallery.tsx
  packages/remark-attachment-refs/src/client/components/Ref.tsx
  packages/remark-attachment-refs/src/client/components/RefImg.tsx
  packages/remark-attachment-refs/src/client/components/Refs.tsx
  packages/remark-attachment-refs/src/client/components/RefsImg.tsx
  packages/remark-attachment-refs/src/client/components/index.ts
  packages/remark-attachment-refs/src/client/components/util/refs-context.ts
  packages/remark-attachment-refs/src/client/index.ts
  packages/remark-attachment-refs/src/client/services/renderer/refs.ts
  packages/remark-attachment-refs/src/client/stores/refs.tsx
  packages/remark-attachment-refs/src/server/index.ts
  packages/remark-attachment-refs/src/server/routes/refs.ts
  packages/remark-attachment-refs/src/utils/logger/index.ts
  packages/remark-attachment-refs/tsconfig.json
  packages/remark-attachment-refs/vite.client.config.ts
  packages/remark-attachment-refs/vite.server.config.ts
  turbo.json
Labels: feature

#7606 fix: AlignRight DropdownMenu flickering
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/Page/CopyDropdown.jsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
  packages/ui/src/interfaces/popper-data.ts
  packages/ui/src/utils/index.ts
  packages/ui/src/utils/reactstrap-modifiers.ts
Labels: bug

#7608 imprv: Create getCustomModifiers
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  packages/ui/src/interfaces/popper-data.ts
  packages/ui/src/utils/reactstrap-modifiers.ts
Labels: improvement

#7603 imprv: show alert when comment not posted
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/stores/comment.tsx
Labels: improvement
