Repository growilabs/growi, pull requests merged in 2023-08, with the labels that each got.

#7935 fix: Auto-scroll search result content
  apps/app/src/components/Comments.tsx
  apps/app/src/components/Page/RevisionLoader.tsx
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
Labels: type/bug

#7936 imprv: Persist the installed date in the Config collection
  apps/app/config/logger/config.dev.js
  apps/app/src/migrations/20230731075753-add_installed_date_to_config.js
  apps/app/src/server/models/config.ts
Labels: type/improvement

#7884 Feat/120030 126901 set batch size for promise all
  apps/app/src/features/external-user-group/server/models/external-user-group-relation.integ.ts
  apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
  apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
  apps/app/src/utils/promise.spec.ts
  apps/app/src/utils/promise.ts
Labels: type/feature

#7940 fix: SWR settings for searching
  apps/app/src/stores/search.tsx
Labels: type/bug

#7912 fix: Unsaved comments remain in the editor when transitioning to a new page
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts
  apps/app/test/cypress/support/commands.ts
  apps/app/test/cypress/support/index.ts
Labels: type/bug

#7921 imprv: Able to customize users homepage deletion
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/services/AdminGeneralSecurityContainer.js
  apps/app/src/client/services/AdminHomeContainer.js
  apps/app/src/components/Admin/AuditLog/ActivityTable.tsx
  apps/app/src/components/Admin/Common/AdminNavigation.tsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Navbar/AuthorInfo.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/PersonalDropdown.jsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageCreateModal.jsx
  apps/app/src/components/PageRenameModal.tsx
  apps/app/src/components/PageSideContents.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/User/Username.tsx
  apps/app/src/components/UsersHomepageFooter.module.scss
  apps/app/src/components/UsersHomepageFooter.tsx
  apps/app/src/pages/admin/index.page.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/events/user.js
  apps/app/src/server/events/user.ts
  apps/app/src/server/models/config.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/page.ts
  packages/core/src/utils/page-path-utils/index.ts
  packages/ui/src/components/UserPicture.tsx
Labels: type/improvement

#7943 fix: Auto-scroll search result content 2
  apps/app/src/components/SearchPage/SearchResultContent.tsx
Labels: type/bug

#7944 support: Omit core-js v2
  apps/app/package.json
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkForm.tsx
  yarn.lock
Labels: type/support

#7949 imprv: Clean up old toastr
  apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/components/Admin/ExportArchiveDataPage.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
  apps/app/src/components/Admin/ImportData/GrowiArchiveSection.jsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/styles/molecules/toastr.scss
Labels: type/improvement

#7950 fix: Bootstrap 4 dependencies
  apps/app/package.json
  yarn.lock
Labels: flag/exclude-from-changelog

#7946 fix: Transitioning to a non-existent page under "/me" results in a 500 error
  apps/app/src/pages/me/[[...path]].page.tsx
Labels: type/bug

#7908 fix: Admin page permission when the user transit with next-routing
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/ForbiddenPage.tsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/pages/admin/[...path].page.tsx
  apps/app/src/pages/admin/app.page.tsx
  apps/app/src/pages/admin/audit-log.page.tsx
  apps/app/src/pages/admin/customize.page.tsx
  apps/app/src/pages/admin/data-transfer.page.tsx
  apps/app/src/pages/admin/export.page.tsx
  apps/app/src/pages/admin/global-notification/[globalNotificationId].page.tsx
  apps/app/src/pages/admin/global-notification/new.page.tsx
  apps/app/src/pages/admin/importer.page.tsx
  apps/app/src/pages/admin/index.page.tsx
  apps/app/src/pages/admin/markdown.page.tsx
  apps/app/src/pages/admin/notification.page.tsx
  apps/app/src/pages/admin/plugins.page.tsx
  apps/app/src/pages/admin/search.page.tsx
  apps/app/src/pages/admin/security.page.tsx
  apps/app/src/pages/admin/slack-integration-legacy.page.tsx
  apps/app/src/pages/admin/slack-integration.page.tsx
  apps/app/src/pages/admin/user-group-detail/[userGroupId].page.tsx
  apps/app/src/pages/admin/user-groups.page.tsx
  apps/app/src/pages/admin/users/external-accounts.page.tsx
  apps/app/src/pages/admin/users/index.page.tsx
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/middlewares/admin-required.js
  apps/app/src/utils/admin-page-util.ts
Labels: type/bug

#7951 feat: Create modal
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/ParentPageSelectModal.tsx
  apps/app/src/stores/modal.tsx
Labels: type/feature

#7962 support: Enable build preset-themes blackboard.scss
  packages/preset-themes/src/styles/blackboard.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#7965 support: Reorganize global navigation
  apps/app/src/components/Fab.module.scss
  apps/app/src/components/Fab.tsx
  apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/components/Layout/AdminLayout.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Layout/SearchResultLayout.module.scss
  apps/app/src/components/Layout/ShareLinkLayout.tsx
  apps/app/src/components/Navbar/DrawerToggler.tsx
  apps/app/src/components/Navbar/GrowiNavbar.module.scss
  apps/app/src/components/Navbar/GrowiNavbar.tsx
  apps/app/src/components/Navbar/PersonalDropdown.jsx
  apps/app/src/components/Sidebar/AppearanceModeDropdown.tsx
  apps/app/src/components/Sidebar/PageTree/ItemsTree.module.scss
  apps/app/src/components/Sidebar/PersonalDropdown.tsx
  apps/app/src/components/Sidebar/Sidebar.module.scss
  apps/app/src/components/Sidebar/Sidebar.tsx
  apps/app/src/components/Sidebar/SidebarBrandLogo.tsx
  apps/app/src/components/Sidebar/SidebarNav.module.scss
  apps/app/src/components/Sidebar/SidebarNav.tsx
  apps/app/src/components/Sidebar/index.ts
  apps/app/src/components/UsersHomepageFooter.module.scss
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/styles/_editor.scss
  apps/app/src/styles/_mixins.scss
  apps/app/src/styles/_variables.scss
  apps/app/src/styles/theme/apply-colors.scss
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest.cy.ts
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts
  apps/app/test/cypress/e2e/60-home/60-home--home.cy.ts
  apps/app/test/cypress/support/commands.ts
  packages/preset-themes/src/styles/_variables.scss
  packages/ui/src/utils/browser-utils.ts
Labels: type/support, flag/exclude-from-changelog

#7968 support: Update CodeMirror to v6
  .devcontainer/docker-compose.yml
  apps/app/package.json
  apps/app/src-obsoleted/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/src-obsoleted/components/PageEditor/CodeMirrorEditor.module.scss
  apps/app/src-obsoleted/components/PageEditor/CommentMentionHelper.ts
  apps/app/src-obsoleted/components/PageEditor/ConflictDiffModal.tsx
  apps/app/src-obsoleted/components/PageEditor/EmojiPicker.tsx
  apps/app/src-obsoleted/components/PageEditor/EmojiPickerHelper.ts
  apps/app/src-obsoleted/components/UncontrolledCodeMirror.tsx
  apps/app/src/components/Common/LazyRenderer.tsx
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/index.ts
  apps/app/src/styles/_editor.scss
  apps/app/src/styles/_mixins.scss
  package.json
  packages/editor/.eslintignore
  packages/editor/.eslintrc.cjs
  packages/editor/.gitignore
  packages/editor/index.html
  packages/editor/package.json
  packages/editor/src/@types/declaration.d.ts
  packages/editor/src/components/CodeMirrorEditorContainer.module.scss
  packages/editor/src/components/CodeMirrorEditorContainer.tsx
  packages/editor/src/components/index.ts
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/components/playground/PlaygroundController.tsx
  packages/editor/src/components/playground/index.ts
  packages/editor/src/index.ts
  packages/editor/src/main.scss
  packages/editor/src/main.tsx
  packages/editor/src/services/codemirror-editor.ts
  packages/editor/src/services/index.ts
  packages/editor/src/stores/codemirror-editor.ts
  packages/editor/src/stores/index.ts
  packages/editor/src/stores/use-static-swr.tsx
  packages/editor/src/vite-env.d.ts
  packages/editor/tsconfig.json
  packages/editor/tsconfig.node.json
  packages/editor/vite.config.ts
  packages/remark-growi-directive/package.json
  yarn.lock
Labels: type/support

#7966 support: Eble to build antarctic
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#7969 support: Able to build styles/*.scss
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/src/styles/fire-red.scss
  packages/preset-themes/src/styles/future.scss
  packages/preset-themes/src/styles/halloween.scss
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/src/styles/island.scss
  packages/preset-themes/src/styles/jade-green.scss
  packages/preset-themes/src/styles/kibela.scss
  packages/preset-themes/src/styles/mono-blue.scss
  packages/preset-themes/src/styles/nature.scss
  packages/preset-themes/src/styles/spring.scss
  packages/preset-themes/src/styles/wood.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#7977 fix: Do not work image tag properties
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug

#7979 fix: Consider an empty page when renaming and duplicating
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/service/page.ts
  apps/app/test/integration/service/v5.public-page.test.ts
Labels: type/bug

#7980 fix: Consider an empty page when renaming and duplicating (v6.1.x)
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/service/page.ts
  apps/app/test/integration/service/v5.public-page.test.ts
Labels: type/bug

#7989 fix: Cleanup customize logo setting code
  apps/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
Labels: flag/exclude-from-changelog

#7990 fix: "Searching..." label appearing unnecessarily
  apps/app/src/components/SearchTypeahead.tsx
  apps/app/src/stores/search.tsx
Labels: type/bug

#7988 fix: Do not work img tag if use style property
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug

#7974 fix: Pages can be created under a non-existent user page
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/test/integration/models/user.test.js
  packages/core/src/utils/page-path-utils/index.spec.ts
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#7984 support: Upgrade to reactstrap v9
  apps/app/_obsolete/src/components/PageEditor/ConflictDiffModal.tsx
  apps/app/package.json
  apps/app/src/components/Admin/Users/UserMenu.tsx
  apps/app/src/components/BookmarkButtons.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/DescendantsPageListModal.tsx
  apps/app/src/components/ExpandOrContractButton.tsx
  apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/Page/CopyDropdown.jsx
  apps/app/src/components/PageAccessoriesModal/PageAccessoriesModal.tsx
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/RevisionComparer/RevisionComparer.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SearchPage/OperateAllControl.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/components/Sidebar/SidebarBrandLogo.tsx
  packages/ui/package.json
  packages/ui/src/interfaces/popper-data.ts
  packages/ui/src/utils/index.ts
  packages/ui/src/utils/reactstrap-modifiers.ts
  tools/replacer/.eslintrc.cjs
  tools/replacer/.gitignore
  tools/replacer/index.html
  tools/replacer/package.json
  tools/replacer/src/App.css
  tools/replacer/src/App.tsx
  tools/replacer/src/index.css
  tools/replacer/src/main.tsx
  tools/replacer/src/vite-env.d.ts
  tools/replacer/tsconfig.json
  tools/replacer/tsconfig.node.json
  tools/replacer/vite.config.ts
  yarn.lock
Labels: type/support

#7996 imprv: Flex expansion
  apps/app/src/client/services/layout.ts
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Layout/SearchResultLayout.module.scss
  apps/app/src/components/Layout/SearchResultLayout.tsx
  apps/app/src/components/Layout/ShareLinkLayout.tsx
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SearchPage/SearchControl.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/styles/_layout.scss
  apps/app/src/styles/style-app.scss
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  packages/core/scss/_flex-expand.scss
  packages/core/scss/placeholders/_flex-expand.scss
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/main.scss
Labels: flag/exclude-from-changelog

#7948 fix: Add option to lightbox
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug

#7862 fix: Type safe implementation for objects imported from ElasticsearchClient
  apps/app/src/interfaces/search.ts
  apps/app/src/server/service/search-delegator/elasticsearch-client.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
Labels: type/bug

#7957 imprv: Create Japanese ejs files
  apps/app/resource/locales/ja_JP/admin/userInvitation.ejs
  apps/app/resource/locales/ja_JP/admin/userResetPassword.ejs
  apps/app/resource/locales/ja_JP/admin/userWaitingActivation.ejs
Labels: type/improvement

#8003 fix: Add option to lightbox (6.1.x)
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug

#7875 imprv: Show modal when you delete plugin
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
  apps/app/src/features/growi-plugin/client/stores/admin-plugins.tsx
Labels: type/improvement

#8004 fix: Modification of links in the docs
  README.md
  README_JP.md
  apps/app/resource/locales/en_US/welcome.md
  apps/app/resource/locales/ja_JP/welcome.md
  apps/app/resource/locales/zh_CN/welcome.md
Labels: type/bug

#8001 fix: Pages can be created under a non-existent user page (During attachment upload)
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/routes/attachment.js
Labels: type/bug

#8010 fix: Fixing swagger for tag update api
  apps/app/src/server/routes/tag.js
Labels: type/bug

#8011 feat: Editor initialization
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/stores/use-static-swr.ts
  apps/app/src/stores/use-static-swr.tsx
  packages/core/scss/placeholders/_flex-expand.scss
  packages/core/src/swr/index.ts
  packages/core/src/swr/use-swr-static.ts
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/components/playground/PlaygroundController.tsx
  packages/editor/src/index.ts
  packages/editor/src/services/codemirror-editor.ts
  packages/editor/src/services/codemirror-editor/index.ts
  packages/editor/src/services/codemirror-editor/interfaces/react-codemirror.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/stores/codemirror-editor.ts
  turbo.json
Labels: flag/exclude-from-changelog

#8012 support: Bootstrap v5 braking changes Badges
  apps/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
  apps/app/src/components/Admin/Customize/ThemeColorBox.tsx
  apps/app/src/components/Admin/ElasticsearchManagement/StatusTable.jsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionItem.jsx
  apps/app/src/components/Admin/Notification/GlobalNotificationList.jsx
  apps/app/src/components/Admin/Notification/ManageGlobalNotification.tsx
  apps/app/src/components/Admin/Notification/NotificationSetting.jsx
  apps/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LdapSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/ShareLinkSetting.tsx
  apps/app/src/components/Admin/SlackIntegration/BotTypeCard.jsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserManagement.tsx
  apps/app/src/components/Admin/Users/ExternalAccountTable.tsx
  apps/app/src/components/Admin/Users/UserTable.tsx
  apps/app/src/components/Common/CountBadge.tsx
  apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/components/Layout/Admin.module.scss
  apps/app/src/components/Page/RenderTagLabels.tsx
  apps/app/src/components/PageEditorByHackmd.tsx
  apps/app/src/components/PageHistory/Revision.tsx
  apps/app/src/components/PageStatusAlert.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/components/TagCloudBox.tsx
  apps/app/src/components/TagList.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
  apps/app/src/features/questionnaire/client/components/ProactiveQuestionnaireModal.tsx
  apps/app/src/features/questionnaire/client/components/QuestionnaireToast.tsx
  apps/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
  apps/app/src/styles/theme/_reboot-bootstrap-theme-colors.scss
  packages/editor/src/components/playground/Playground.tsx
  packages/ui/src/components/Attachment.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: flag/exclude-from-changelog

#8013 support: Bootstrap v5 braking changes Close button
  apps/app/src/components/DescendantsPageListModal.module.scss
  apps/app/src/components/PageAccessoriesModal/PageAccessoriesModal.module.scss
  apps/app/src/components/PagePresentationModal.module.scss
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/features/questionnaire/client/components/QuestionnaireToast.tsx
  apps/app/src/styles/_override-rbt.scss
  apps/app/src/styles/theme/apply-colors.scss
Labels: flag/exclude-from-changelog

#8015 feat(editor): setCursor method
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/package.json
  packages/editor/src/components/playground/PlaygroundController.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor.ts
  yarn.lock
Labels: flag/exclude-from-changelog

#8016 support: Bootstrap v5 braking changes Buttons
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/CustomNavigation/CustomNav.tsx
  apps/app/src/components/PageEditor/Cheatsheet.tsx
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/PageSideContents.tsx
  apps/app/src/components/PasswordResetExecutionForm.tsx
  apps/app/src/components/PasswordResetRequestForm.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/Sidebar/PersonalDropdown.tsx
  apps/app/src/features/questionnaire/client/components/Question.tsx
  packages/remark-lsx/src/client/components/Lsx.tsx
Labels: flag/exclude-from-changelog

#8017 support: Bootstrap v5 braking changes Card
  apps/app/src/components/Admin/Common/Accordion.jsx
  apps/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/CreateTemplateModal.jsx
Labels: flag/exclude-from-changelog

#8020 support: Bootstrap v5 braking changes JavaScript
  apps/app/src/components/Admin/App/AwsSetting.tsx
  apps/app/src/components/Admin/App/GcsSetting.tsx
  apps/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
  apps/app/src/components/Admin/Common/AdminNavigation.tsx
  apps/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  apps/app/src/components/Admin/ElasticsearchManagement/StatusTable.jsx
  apps/app/src/components/Admin/ExportArchiveData/ArchiveFilesTableMenu.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionItem.jsx
  apps/app/src/components/Admin/LegacySlackIntegration/SlackConfiguration.jsx
  apps/app/src/components/Admin/Notification/GlobalNotificationList.jsx
  apps/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LdapSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
  apps/app/src/components/Admin/SlackIntegration/ManageCommandsProcessWithoutProxy.jsx
  apps/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  apps/app/src/components/Admin/Users/ExternalAccountTable.tsx
  apps/app/src/components/CustomNavigation/CustomNav.tsx
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Navbar/GlobalSearch.tsx
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
  apps/app/src/components/PageEditor/GridEditModal.jsx
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/SearchPage/SortControl.tsx
Labels: flag/exclude-from-changelog

#8022 support: Bootstrap v5 breaking changes Popover
  apps/app/src/styles/theme/_apply-colors-dark.scss
Labels: flag/exclude-from-changelog

#8021 support: Bootstrap v5 breaking changes Helpers
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/PageEditor/Editor.tsx
Labels: flag/exclude-from-changelog

#8028 support: Bootstrap v5 breaking changes Sass
  apps/app/src/styles/atoms/mixins/_buttons.scss
  apps/app/src/styles/theme/_apply-colors-dark.scss
  apps/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
  apps/app/src/styles/theme/_reboot-bootstrap-dropdown.scss
  apps/app/src/styles/theme/_reboot-bootstrap-nav.scss
  apps/app/src/styles/theme/_reboot-bootstrap-theme-colors.scss
  apps/app/src/styles/theme/apply-colors.scss
  apps/app/src/styles/theme/mixins/_hsl-badge.scss
  apps/app/src/styles/theme/mixins/_hsl-button.scss
  packages/preset-themes/src/styles/atoms/mixins/_buttons.scss
  packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss
Labels: flag/exclude-from-changelog

#8005 imprv: Export md with page name
  apps/app/src/server/routes/apiv3/page.js
Labels: type/improvement

#8029 feat: Presentation preview and support Marp
  apps/app/next.config.js
  apps/app/package.json
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/services/AdminCustomizeContainer.js
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/client/services/renderer/slide-viewer-renderer.tsx
  apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
  apps/app/src/interfaces/services/renderer.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/models/config.ts
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/services/renderer/renderer.tsx
  apps/app/src/stores/context.tsx
  apps/app/src/stores/slide-viewer-renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/components/GrowiSlides.tsx
  packages/presentation/src/components/MarpSlides.tsx
  packages/presentation/src/components/Presentation.tsx
  packages/presentation/src/components/RichSlideSection.tsx
  packages/presentation/src/components/Slides.global.scss
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/index.ts
  packages/presentation/src/services/growi-marpit.ts
  packages/presentation/src/services/parse-slide-frontmatter.ts
  packages/presentation/src/services/renderer/extract-sections.ts
  packages/presentation/src/services/renderer/slides.ts
  packages/preset-templates/dist/marp-example/en_US/meta.json
  packages/preset-templates/dist/marp-example/en_US/template.md
  yarn.lock
Labels: type/improvement

#8030 fix: Do not work register button
  apps/app/src/components/LoginForm.tsx
Labels: flag/exclude-from-changelog

#8031 feat: Save with new editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor.ts
Labels: flag/exclude-from-changelog

#7971 imprv: Add installed date to questionnaire answer
  apps/app/config/logger/config.dev.js
  apps/app/src/features/questionnaire/interfaces/growi-info.ts
  apps/app/src/features/questionnaire/server/models/schema/growi-info.ts
  apps/app/src/features/questionnaire/server/service/questionnaire.ts
  apps/app/src/server/models/config.ts
  apps/app/test/integration/service/questionnaire-cron.test.ts
  apps/app/test/integration/service/questionnaire.test.ts
Labels: type/improvement

#8035 support: Update user homepage deletion description
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
Labels: flag/exclude-from-changelog

#8040 imprv: Correct update message
  apps/app/src/client/services/AdminCustomizeContainer.js
  packages/presentation/src/components/Presentation.tsx
  packages/presentation/src/services/growi-marpit.ts
Labels: type/improvement

#8042 imprv: Codemirror custom hooks initialization
  apps/app/package.json
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/stores/admin/customize.tsx
  apps/app/src/stores/ui.tsx
  packages/core/package.json
  packages/core/src/swr/use-swr-static.ts
  packages/editor/package.json
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/services/codemirror-editor/interfaces/react-codemirror.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/stores/codemirror-editor.ts
  packages/remark-attachment-refs/package.json
  packages/remark-lsx/package.json
  yarn.lock
Labels: flag/exclude-from-changelog

#8033 support: Add grid utilities
  apps/app/src/components/Admin/AuditLog/DateRangePicker.tsx
  apps/app/src/components/Admin/AuditLog/SearchUsernameTypeahead.tsx
  apps/app/src/components/Admin/AuditLogManagement.tsx
  apps/app/src/components/Admin/G2GDataTransferExportForm.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  apps/app/src/styles/_editor.scss
Labels: flag/exclude-from-changelog

#8044 fix: Remove redundant toastSuccess for pasted attachments
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageEditor/Editor.tsx
Labels: type/bug

#8026 Fix/128041 129379 large ldap group tree sync error
  apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
  apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
  apps/app/src/server/service/ldap.ts
  apps/app/test/integration/service/ldap-user-group-sync.test.ts
Labels: type/bug
