Repository growilabs/growi, pull requests merged in 2023-11, with the labels that each got.

#8125 feat: Implementation of picker for emoji input
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/package.json
  packages/editor/src/@types/emoji-mart.d.ts
  packages/editor/src/@types/scss.d.ts
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/stores/index.ts
  packages/editor/src/stores/use-resolved-theme.ts
  packages/editor/vite.config.ts
  yarn.lock
Labels: type/feature

#8137 feat: Implementation of autocompletion function for emoji input
  packages/editor/src/@types/scss.d.ts
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/extensions/emojiAutocompletionSettings.ts
Labels: type/feature

#8167 imprv: Able to edit tags in editor
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/PageTags/PageTags.tsx
  apps/app/src/components/PageTags/RenderTagLabels.tsx
  apps/app/src/components/PageTags/TagEditModal.tsx
  apps/app/src/components/PageTags/TagsInput.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/modal.tsx
Labels: type/improvement

#8211 imprv: Certify shared page attachment middleware
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/middlewares/certify-shared-file.js
  apps/app/src/server/middlewares/certify-shared-page-attachment/certify-shared-page-attachment.spec.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/certify-shared-page-attachment.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/index.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/interfaces.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/retrieve-valid-share-link.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-attachment.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-referer/index.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-referer/retrieve-site-url.spec.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-referer/retrieve-site-url.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-referer/validate-referer.spec.ts
  apps/app/src/server/middlewares/certify-shared-page-attachment/validate-referer/validate-referer.ts
  apps/app/src/server/middlewares/certify-shared-page.js
  apps/app/src/server/models/index.js
  apps/app/src/server/models/share-link.js
  apps/app/src/server/models/share-link.ts
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/apiv3/share-links.js
  apps/app/src/server/routes/index.js
  apps/app/src/server/service/page.ts
  apps/app/src/server/util/mongoose-utils.ts
Labels: type/improvement

#8202 feat: Create today's and template page
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/Sidebar/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButtonDropdownMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/index.ts
  apps/app/src/server/routes/apiv3/pages.js
Labels: type/feature

#8206 imprv: Update RichAttachments feat on shared pages
  apps/app/src/components/Layout/ShareLinkLayout.tsx
  apps/app/src/components/ReactMarkdownComponents/RichAttachment.tsx
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/index.js
  apps/app/src/services/renderer/remark-plugins/attachment.ts
  apps/app/src/stores/attachment.tsx
  apps/app/src/styles/_mixins.scss
  apps/app/src/styles/_share-link.scss
  apps/app/src/styles/_sharelink.scss
  apps/app/src/styles/mixins/_share-link.scss
  apps/app/src/styles/style-app.scss
Labels: type/improvement

#8221 imprv: Feature dir for comment
  apps/app/src/components/PageComment/Comment.tsx
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/features/comment/server/events/consts.ts
  apps/app/src/features/comment/server/events/event-emitter.ts
  apps/app/src/features/comment/server/events/index.ts
  apps/app/src/features/comment/server/index.ts
  apps/app/src/features/comment/server/models/comment.ts
  apps/app/src/features/comment/server/models/index.ts
  apps/app/src/interfaces/comment.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/events/comment.ts
  apps/app/src/server/models/comment.js
  apps/app/src/server/models/index.js
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/service/comment.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/page.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/server/service/search.ts
  apps/app/test/integration/service/v5.public-page.test.ts
Labels: flag/exclude-from-changelog

#8191 imprv: Enable file uploading overlay
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/Editor.module.scss
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/interfaces/editor-settings.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/context.tsx
  apps/app/src/styles/_mixins.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/file-dropzone/index.ts
  packages/editor/src/services/file-dropzone/use-file-dropzone.ts
  packages/editor/src/services/file-dropzone/use-file-dropzone/FileDropzoneOverlay.tsx
  packages/editor/src/services/file-dropzone/use-file-dropzone/use-file-dropzone.ts
Labels: type/improvement, flag/exclude-from-changelog

#8179 imprv: Add Marp preset template for ja_JP and zh_CN
  packages/preset-templates/dist/marp-example/ja_JP/meta.json
  packages/preset-templates/dist/marp-example/ja_JP/template.md
  packages/preset-templates/dist/marp-example/zh_CN/meta.json
  packages/preset-templates/dist/marp-example/zh_CN/template.md
Labels: type/improvement

#8227 support: 134087 refactor conditional branch about doc.parsed snapshot
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/InAppNotificationList.tsx
  apps/app/src/components/InAppNotification/PageNotification/ModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/UserModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/useActionAndMsg.ts
  apps/app/src/interfaces/in-app-notification.ts
  apps/app/src/server/routes/apiv3/in-app-notification.ts
  apps/app/src/stores/in-app-notification.ts
Labels: type/support

#8239 support: Remove obsolete route for attachment on MongoDB GridFS
  apps/app/src/server/routes/attachment.js
  apps/app/src/server/routes/index.js
Labels: type/support, type/breaking

#8243 support: TypeScriptize attachment codes
  apps/app/package.json
  apps/app/src/interfaces/crowi-request.ts
  apps/app/src/migrations/20220613064207-add-attachment-type-to-existing-attachments.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_document.page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/invited.page.tsx
  apps/app/src/pages/maintenance.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/interfaces/attachment.ts
  apps/app/src/server/models/attachment.js
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/models/index.js
  apps/app/src/server/models/serializers/bookmark-serializer.js
  apps/app/src/server/models/serializers/index.ts
  apps/app/src/server/models/serializers/page-serializer.js
  apps/app/src/server/models/serializers/revision-serializer.js
  apps/app/src/server/models/serializers/user-group-relation-serializer.js
  apps/app/src/server/models/serializers/user-serializer.js
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/attachment/download.ts
  apps/app/src/server/routes/attachment/get-brand-logo.ts
  apps/app/src/server/routes/attachment/get.ts
  apps/app/src/server/routes/attachment/index.ts
  apps/app/src/server/routes/index.js
  apps/app/src/server/routes/ogp.ts
  apps/app/src/server/service/attachment.js
  apps/app/src/server/service/file-uploader/aws.ts
  apps/app/src/server/service/file-uploader/azure.ts
  apps/app/src/server/service/file-uploader/file-uploader.ts
  apps/app/src/server/service/file-uploader/gcs.js
  apps/app/src/server/service/file-uploader/gcs.ts
  apps/app/src/server/service/file-uploader/gridfs.ts
  apps/app/src/server/service/file-uploader/index.js
  apps/app/src/server/service/file-uploader/index.ts
  apps/app/src/server/service/file-uploader/local.ts
  apps/app/src/server/service/file-uploader/none.js
  apps/app/src/server/service/file-uploader/utils/headers.ts
  apps/app/src/server/service/file-uploader/utils/index.ts
  apps/app/src/server/service/g2g-transfer.ts
  apps/app/src/server/service/page.ts
  apps/app/src/utils/admin-page-util.ts
  packages/core/src/interfaces/attachment.ts
  packages/remark-attachment-refs/package.json
  packages/remark-attachment-refs/src/server/routes/refs.ts
  yarn.lock
Labels: type/support

#8247 support: Normalize vitest
  apps/app/.env.test
  apps/app/package.json
  apps/app/test-with-vite/.eslintrc.cjs
  apps/app/test-with-vite/download-mongo-binary/index.spec.ts
  apps/app/test-with-vite/download-mongo-binary/vitest.config.ts
  apps/app/test-with-vite/package.json
  apps/app/test-with-vite/setup/mongoms.ts
  package.json
  yarn.lock
Labels: type/support

#8213 feat: Make button changes text format in editor
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-markdown-elements.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-prefix.ts
Labels: type/feature

#8255 fix: Certify shared page attachment middleware
  apps/app/src/server/middlewares/certify-shared-page-attachment/retrieve-valid-share-link.ts
Labels: type/bug

#8256 fix: Certify shared page attachment middleware (6.2.x)
  apps/app/src/server/middlewares/certify-shared-page-attachment/retrieve-valid-share-link.ts
Labels: type/bug

#8196 feat: 133821 create announcement model
  apps/app/src/features/announcement/index.ts
  apps/app/src/features/announcement/server/events/announcement-utils.ts
  apps/app/src/features/announcement/server/events/index.ts
  apps/app/src/features/announcement/server/models/announcement.ts
  apps/app/src/features/announcement/server/models/index.ts
  apps/app/src/interfaces/announcement.ts
Labels: type/feature

#8242 feat: Update CreateTemplateModal
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/CreateTemplateModal.jsx
  apps/app/src/components/CreateTemplateModal.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/hooks.tsx
  apps/app/src/components/PageCreateModal.jsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/interfaces/template.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
Labels: type/feature

#8264 imprv: Layout of comments
  apps/app/src/components/Comments.tsx
  apps/app/src/components/Common/PageViewLayout.module.scss
  apps/app/src/components/Common/PageViewLayout.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/Sidebar/Sidebar.tsx
  packages/core/scss/_flex-expand.scss
Labels: type/improvement

#8262 imprv: Refactor deleteCompletelyUserHomeBySystem
  apps/app/src/server/events/user.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/service/page.ts
Labels: type/improvement

#8266 fix: Remove groups not related to the user from the user groups that are specified automatically when creating child pages
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/interfaces/page-grant.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/page.ts
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page.ts
  apps/app/test/integration/service/page-grant.test.js
Labels: type/bug

#8268 feat: Display search modal
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/PageControls/SearchButton.module.scss
  apps/app/src/components/PageControls/SearchButton.tsx
  apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/stores/search.ts
Labels: type/feature

#8246 feat: Able to open edit table modal in editor
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/stores/modal.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/stores/use-handsontable.ts
Labels: type/feature

#8275 imprv: Fluid layout switching
  apps/app/src/client/services/layout.ts
  apps/app/src/components/Common/PageViewLayout.module.scss
  apps/app/src/components/Common/PageViewLayout.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/Preview.module.scss
  apps/app/src/components/PageEditor/Preview.tsx
  apps/app/src/components/SearchPage/SearchResultContent.module.scss
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/components/Sidebar/Tag.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/styles/_layout.scss
  apps/app/src/styles/_mixins.scss
  apps/app/src/styles/mixins/_fluid-layout.scss
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts
Labels: flag/exclude-from-changelog

#8283 fix: User homepage deletion server login error on search
  apps/app/src/server/service/page.ts
Labels: flag/exclude-from-changelog

#8289 fix: Update deleteCompletelyUserHomeBySystem for v4 process
  apps/app/src/server/events/user.ts
  apps/app/src/server/service/page.ts
Labels: type/bug

#8277 feat: 78027 135782 bulk export UI mock
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/features/page-bulk-export/client/components/PageBulkExportSelectModal.tsx
  apps/app/src/features/page-bulk-export/client/stores/modal.tsx
Labels: type/feature
