Repository growilabs/growi, pull requests merged in 2023-02, with the labels that each got.

#7332 fix: Can't controll slack notification switch in editor
  packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
Labels: bug

#7336 imprv: Data mutation
  packages/app/src/client/services/page-operation.ts
  packages/app/src/components/DescendantsPageList.tsx
  packages/app/src/components/DescendantsPageListModal.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/NotFoundPage.tsx
  packages/app/src/components/Page/PageContents.tsx
  packages/app/src/components/Page/PageView.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageStatusAlert.tsx
  packages/app/src/components/PrivateLegacyPages.tsx
  packages/app/src/components/PutbackPageModal.jsx
  packages/app/src/components/SearchPage/SearchPageBase.tsx
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/SearchPage/SearchResultList.tsx
  packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
  packages/app/src/components/TrashPageList.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/middlewares/user.ts
  packages/app/src/stores/page-listing.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/search.tsx
  packages/app/src/stores/use-static-swr.tsx
Labels: improvement

#7342 fix: Typo in G2G alert component
  packages/app/public/static/locales/ja_JP/commons.json
Labels: bug, exclude from changelog

#7333 imprv: Disable lsx in shared page
  packages/app/src/interfaces/services/renderer.ts
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/services/renderer/renderer.tsx
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: improvement

#7326 support: Migrate Notation for v5 to v6
  bin/data-migrations/v6/README.md
  bin/data-migrations/v6/src/migration.js
  bin/data-migrations/v6/src/processor.js
Labels: support

#7349 fix: Border-color in edit mode
  packages/app/src/styles/theme/_apply-colors.scss
Labels: bug

#7352 feat: Server Side Rendering
  packages/app/src/components/Page/PageContents.tsx
  packages/app/src/components/Page/PageContentsUtilities.tsx
  packages/app/src/components/Page/PageView.tsx
  packages/app/src/components/PageAlert/PageAlerts.tsx
  packages/app/src/components/PageSideContents.tsx
  packages/app/src/components/ShareLink/ShareLinkPageContents.tsx
  packages/app/src/components/ShareLink/ShareLinkPageView.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/services/renderer/rehype-plugins/relocate-toc.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/stores/ui.tsx
Labels: feature

#7353 imprv: classname for fluid layout
  packages/app/src/client/services/layout.ts
  packages/app/src/components/PageEditor/Preview.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/styles/_editor.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: improvement

#7354 imprv: Anchor link
  packages/app/src/client/util/smooth-scroll.ts
  packages/app/src/components/ContentLinkButtons.tsx
  packages/app/src/components/Fab.tsx
  packages/app/src/components/PageSideContents.tsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/services/renderer/rehype-plugins/relative-links.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/styles/organisms/_wiki.scss
  yarn.lock
Labels: improvement

#7355 imprv: User data serialization
  packages/app/src/server/routes/apiv3/users.js
Labels: improvement

#7359 fix: Routing after creating page with shortcut
  packages/app/src/components/PageEditor.tsx
Labels: bug

#7360 fix: Scroll into view by anchor
  packages/app/src/components/Comments.tsx
  packages/app/src/components/Page/PageView.tsx
  packages/app/src/components/PageComment/Comment.module.scss
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/styles/_variables.scss
  packages/app/src/styles/organisms/_wiki.scss
Labels: bug

#7357 feat: Refactor common processes in Next Page
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/pages/utils/commons.ts
Labels: support

#7362 support: Bump SWR to v2.0.3
  packages/app/package.json
  packages/remark-lsx/package.json
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/stores/lsx.tsx
  yarn.lock
Labels: support

#7365 fix: Comment form background
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
Labels: bug

#7350 fix: Login screen background
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/src/styles/spring.scss
  packages/preset-themes/src/styles/wood.scss
Labels: bug

#7366 fix: Recent changes and Timeline
  packages/app/package.json
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/components/Sidebar/InfiniteScroll.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/stores/page-listing.tsx
  yarn.lock
Labels: bug

#7368 imprv: Allow iframe tag
  packages/app/src/services/renderer/renderer.tsx
Labels: improvement

#7371 fix: Keep showing page restricted alert
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#7343 fix: Error when clicking on a page you are not authorized to view on the search results page
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/interfaces/revision.ts
  packages/app/src/stores/page.tsx
Labels: bug

#7373 fix: Revision short body is not displayed on search results page
  packages/app/src/server/crowi/express-init.js
Labels: bug

#7341 feat: Detect i18n locale from browser accept languages
  packages/app/config/next-i18next.config.ts
  packages/app/src/client/util/locale-utils.ts
  packages/app/src/pages/utils/commons.ts
Labels: feature

#7380 support: create README.md for v6 migration
  bin/data-migrations/v6/README.md
Labels: support

#7367 feat: Presentation
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  packages/app/docker/Dockerfile
  packages/app/package.json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/legacy/crowi-presentation.js
  packages/app/src/client/services/AdminMarkDownContainer.js
  packages/app/src/client/util/reveal/plugins/growi-renderer.js
  packages/app/src/client/util/reveal/plugins/markdown.js
  packages/app/src/components/Admin/MarkdownSetting/MarkDownSettingContents.tsx
  packages/app/src/components/Admin/MarkdownSetting/PresentationForm.jsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PagePresentationModal.jsx
  packages/app/src/components/PagePresentationModal.module.scss
  packages/app/src/components/PagePresentationModal.tsx
  packages/app/src/migrations/20230213090921-remove-presentation-configurations.js
  packages/app/src/server/models/config.ts
  packages/app/src/server/routes/apiv3/markdown-setting.js
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/modal.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/styles/_layout.scss
  packages/app/src/styles/_modal.scss
  packages/app/src/styles/_vendor-presentation.scss
  packages/app/src/styles/style-presentation.scss
  packages/presentation/.eslintignore
  packages/presentation/.eslintrc.js
  packages/presentation/.gitignore
  packages/presentation/README.md
  packages/presentation/package.json
  packages/presentation/src/components/Presentation.global.scss
  packages/presentation/src/components/Presentation.module.scss
  packages/presentation/src/components/Presentation.tsx
  packages/presentation/src/components/Slides.global.scss
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/consts/index.ts
  packages/presentation/src/index.ts
  packages/presentation/src/services/renderer/extract-sections.ts
  packages/presentation/tsconfig.base.json
  packages/presentation/tsconfig.build.json
  packages/presentation/tsconfig.json
  yarn.lock
Labels: feature

#7381 fix: Make collapse work for anchor tags
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/services/renderer/renderer.tsx
Labels: bug

#7389 fix: Can't controll slack notification button in comment editor
  packages/app/src/components/PageComment/CommentEditor.tsx
Labels: bug

#7393 feat: Manage guest sidebar mode with session
  packages/app/src/client/services/user-ui-settings.ts
  packages/app/src/interfaces/crowi-request.ts
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/server/routes/apiv3/user-ui-settings.ts
  packages/app/src/stores/ui.tsx
Labels: feature

#7396 fix: Sidebar mode on editor doesn't work in HackMD tab
  packages/app/src/stores/ui.tsx
Labels: bug

#7391 fix: Behavior when color schema is forced by GROWI themes
  packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
  packages/app/src/stores/use-next-themes.tsx
Labels: bug

#7399 imprv: Presentation behavior
  packages/app/src/components/PagePresentationModal.tsx
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/consts/index.ts
  packages/presentation/src/services/renderer/extract-sections.ts
  packages/ui/src/index.ts
  packages/ui/src/utils/use-fullscreen.ts
Labels: improvement

#7356 imprv: Add send email to user feat to `/reset-password` endpoint v6
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/resource/locales/en_US/admin/userResetPassword.txt
  packages/app/resource/locales/ja_JP/admin/userResetPassword.txt
  packages/app/resource/locales/zh_CN/admin/userResetPassword.txt
  packages/app/src/components/Admin/Users/PasswordResetModal.jsx
  packages/app/src/server/routes/apiv3/users.js
Labels: bug

#7398 fix: mono-blue subnavigation color
  packages/preset-themes/src/styles/mono-blue.scss
Labels: bug

#7401 feat: Manage guest ui setting with session
  packages/app/src/server/routes/apiv3/user-ui-settings.ts
Labels: feature

#7397 imprv: Initialize UserUISettings
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_app.page.tsx
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/server/middlewares/inject-user-ui-settings-to-localvars.ts
  packages/app/src/server/models/user-ui-settings.ts
  packages/app/src/server/util/mongoose-utils.ts
  packages/app/src/stores/use-context-swr.tsx
  packages/app/src/stores/use-static-swr.tsx
Labels: improvement

#7395 fix: Error when pressing the conflict resolution button on PageStatusAlert
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
Labels: bug

#7404 imprv: PasswordResetModal styles and ejs format
  packages/app/resource/locales/en_US/admin/userInvitation.txt
  packages/app/resource/locales/en_US/admin/userResetPassword.txt
  packages/app/resource/locales/en_US/admin/userWaitingActivation.txt
  packages/app/resource/locales/en_US/notifications/comment.txt
  packages/app/resource/locales/en_US/notifications/notActiveUser.txt
  packages/app/resource/locales/en_US/notifications/pageCreate.txt
  packages/app/resource/locales/en_US/notifications/pageDelete.txt
  packages/app/resource/locales/en_US/notifications/pageEdit.txt
  packages/app/resource/locales/en_US/notifications/pageLike.txt
  packages/app/resource/locales/en_US/notifications/pageMove.txt
  packages/app/resource/locales/en_US/notifications/passwordReset.txt
  packages/app/resource/locales/en_US/notifications/passwordResetSuccessful.txt
  packages/app/resource/locales/en_US/notifications/userActivation.txt
  packages/app/resource/locales/ja_JP/admin/userInvitation.txt
  packages/app/resource/locales/ja_JP/admin/userResetPassword.txt
  packages/app/resource/locales/ja_JP/admin/userWaitingActivation.txt
  packages/app/resource/locales/ja_JP/notifications/notActiveUser.txt
  packages/app/resource/locales/ja_JP/notifications/passwordReset.txt
  packages/app/resource/locales/ja_JP/notifications/passwordResetSuccessful.txt
  packages/app/resource/locales/ja_JP/notifications/userActivation.txt
  packages/app/resource/locales/zh_CN/admin/userInvitation.txt
  packages/app/resource/locales/zh_CN/admin/userResetPassword.txt
  packages/app/resource/locales/zh_CN/admin/userWaitingActivation.txt
  packages/app/resource/locales/zh_CN/notifications/comment.txt
  packages/app/resource/locales/zh_CN/notifications/notActiveUser.txt
  packages/app/resource/locales/zh_CN/notifications/pageCreate.txt
  packages/app/resource/locales/zh_CN/notifications/pageDelete.txt
  packages/app/resource/locales/zh_CN/notifications/pageEdit.txt
  packages/app/resource/locales/zh_CN/notifications/pageLike.txt
  packages/app/resource/locales/zh_CN/notifications/pageMove.txt
  packages/app/resource/locales/zh_CN/notifications/passwordReset.txt
  packages/app/resource/locales/zh_CN/notifications/passwordResetSuccessful.txt
  packages/app/resource/locales/zh_CN/notifications/userActivation.txt
  packages/app/src/components/Admin/Users/PasswordResetModal.jsx
  packages/app/src/server/routes/apiv3/users.js
Labels: improvement

#7400 imprv: UnsavedAlertDialog and page transition when next routing
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/UnsavedAlertDialog.tsx
Labels: improvement

#7394 fix: Page body is blank when opening editor after duplicating page
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/editor.tsx
Labels: bug

#7402 fix: Unable to transition requested page after login
  packages/app/src/components/LoginForm.tsx
  packages/app/src/interfaces/user.ts
  packages/app/src/server/middlewares/login-required.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/index.js
  packages/app/src/server/routes/login-passport.js
  packages/app/src/server/util/createRedirectToForUnauthenticated.ts
  packages/app/test/integration/middlewares/login-required.test.js
Labels: bug

#7412 fix: PageStatusAlert does not disappear after loading latest revision
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#7413 fix: PageStatusAlert is displayed on unnecessary pages
  packages/app/src/client/services/side-effects/page-updated.ts
Labels: bug

#7425 fix: Behavior when conflicts occur when saving pages
  packages/app/src/components/PageEditor.tsx
Labels: bug

#7419 fix: Color of the close icon in modal header
  packages/app/src/styles/theme/_apply-colors.scss
Labels: bug

#7423 feat: Refactor template modal with hooks
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/TemplateModal.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/modal.tsx
Labels: feature

#7428 imprv: Determine page grant considering wiki mode when creating a new page by uploading attachments
  packages/app/src/server/routes/attachment.js
Labels: improvement

#7414 feat: Compare all page revisions on PageAccessoriesModal History tab
  packages/app/src/components/InfiniteScroll.tsx
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/components/PageHistory.tsx
  packages/app/src/components/PageHistory/PageRevisionTable.tsx
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/RevisionComparer/RevisionComparer.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/server/routes/apiv3/revisions.js
  packages/app/src/stores/page.tsx
  packages/core/src/interfaces/revision.ts
Labels: feature
