Repository growilabs/growi, pull requests merged in 2023-01, with the labels that each got.

#7191 support: Remove flavor from Dockerfile
  .github/workflows/release.yml
  packages/app/docker/Dockerfile
Labels: exclude from changelog

#7202 ci(Mergify): configuration update
  .mergify.yml
Labels: support

#7203 support: Remove the "entities" package
  packages/app/package.json
  yarn.lock
Labels: exclude from changelog

#7206 imprv: Show tool tip for presentation feature
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/NotAvailable.tsx
  packages/app/src/components/NotAvailableForGuest.tsx
  packages/app/src/components/NotAvailableForNow.tsx
Labels: improvement

#7209 fix: Lsx behavior
  packages/app/src/server/models/page.ts
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/factory-attributes.js
  packages/remark-growi-directive/test/micromark-extension-growi-directive.test.js
  packages/remark-lsx/src/server/routes/lsx.js
  packages/remark-lsx/src/stores/lsx.tsx
Labels: bug

#7210 fix: Launch with PROMSTER_ENABLED=true failed
  packages/app/package.json
  packages/app/src/server/middlewares/promster.js
  packages/app/src/server/middlewares/promster.ts
  yarn.lock
Labels: bug

#7212 support: Arm architecture
  .github/workflows/release-rc.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  packages/app/docker/Dockerfile
Labels: support

#7215 fix: Make PLANTUML_URI v5.x compatible
  packages/app/src/services/renderer/remark-plugins/plantuml.ts
  packages/app/src/services/renderer/renderer.tsx
Labels: bug

#7216 fix: Attach i18n User Setting and TagEditModal
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Page/TagEditModal.jsx
  packages/app/src/components/Page/TagsInput.tsx
Labels: bug

#7213 imprv: Do not use api for fetching pages when using shared pages
  packages/app/src/client/services/layout.ts
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: improvement

#7219 support Refactor attribute for blackout in VRT
  packages/app/src/components/Admin/AdminHome/SystemInfomationTable.tsx
  packages/app/src/components/Layout/MainPane.tsx
  packages/app/src/components/Me/ApiSettings.tsx
  packages/app/src/components/Me/ProfileImageSettings.tsx
  packages/app/src/components/Navbar/AuthorInfo.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/User/UserDate.jsx
  packages/app/test/cypress/integration/10-install/10-install--install.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--access-to-side-bar.spec.ts
  packages/app/test/cypress/integration/50-sidebar/50-sidebar--switching-sidebar-mode.spec.ts
  packages/app/test/cypress/support/blackout.ts
  packages/app/test/cypress/support/screenshot.ts
Labels: exclude from changelog

#7218 imprv: Reduce frequent API calling by SWR
  packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  packages/app/src/components/PageEditor/DrawioModal.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/in-app-notification.ts
  packages/app/src/stores/personal-settings.tsx
  packages/app/src/stores/user.tsx
Labels: improvement

#7225 fix: Omit remark-growi-directive shortcuts
  packages/remark-growi-directive/src/mdast-util-growi-directive/index.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/directive-leaf.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/directive-text.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/factory-attributes.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/html.js
  packages/remark-growi-directive/test/fixtures/leaf/input.md
  packages/remark-growi-directive/test/fixtures/leaf/output.md
  packages/remark-growi-directive/test/fixtures/leaf/tree.json
  packages/remark-growi-directive/test/fixtures/text/input.md
  packages/remark-growi-directive/test/fixtures/text/output.md
  packages/remark-growi-directive/test/fixtures/text/tree.json
  packages/remark-growi-directive/test/mdast-util-growi-directive.test.js
  packages/remark-growi-directive/test/micromark-extension-growi-directive.test.js
Labels: bug

#7226 fix: Lsx "filter" and "except" options does not work
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/server/routes/lsx.js
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: bug

#7227 fix: delete page method from page tree
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
Labels: bug

#7228 fix: refactor pageEditor initValue
  packages/app/src/components/PageEditor.tsx
Labels: bug

#7229 imprv: Display the header title on each page
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/admin/[...path].page.tsx
  packages/app/src/pages/admin/index.page.tsx
  packages/app/src/pages/installer.page.tsx
  packages/app/src/pages/invited.page.tsx
  packages/app/src/pages/login/index.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/pages/user-activation.page.tsx
  packages/app/src/pages/utils/commons.ts
Labels: improvement

#7187 feat: Enable features used sticky-event
  packages/app/src/components/Fab.module.scss
  packages/app/src/components/Fab.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Layout/ShareLinkLayout.tsx
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigation.module.scss
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.module.scss
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.tsx
  packages/app/src/components/SearchPage/SearchResultContent.module.scss
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/components/StickyStretchableScroller.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/styles/_layout.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
  packages/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.spec.ts
  packages/app/test/cypress/integration/60-home/60-home--home.spec.ts
  packages/preset-themes/src/styles/theme/_apply-colors.scss
Labels: feature

#7214 imprv: Do not request /pages.getPageTag when on a shared page
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/stores/page.tsx
Labels: improvement

#7232 fix: Initial value of the page grant respects the parent page's one
  packages/app/src/pages/[[...path]].page.tsx
Labels: bug

#7239 fix: Lsx encode prefix twice
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: bug

#7240 imprv: Do not retrieve page data using API in shared page
  packages/app/src/stores/page.tsx
Labels: improvement

#7243 fix: Page path is not displayed in browser tab on shared page
  packages/app/src/pages/share/[[...path]].page.tsx
Labels: bug

#7224 fix: 112734 delete page modal label
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
Labels: bug

#7249 fix: Refactor axios date serializer config
  packages/app/package.json
  packages/app/src/utils/axios.ts
  yarn.lock
Labels: bug

#7261 imprv: UI admin g2g transfer advanced options
  packages/app/src/components/Admin/App/AwsSetting.tsx
  packages/app/src/components/Admin/App/FileUploadSetting.tsx
  packages/app/src/components/Admin/App/GcsSetting.tsx
  packages/app/src/components/Admin/G2GDataTransfer.tsx
  packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
  packages/app/src/pages/admin/data-transfer.page.tsx
Labels: feature

#7264 fix: grw-skeleton
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
Labels: bug

#7259 fix: Cannot login unless local strategy is enabled
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/login-passport.js
  packages/core/src/models/vo/error-apiv3.ts
Labels: bug

#7252 feat: Use configured xss custom whitelist
  packages/app/src/components/Admin/MarkdownSetting/WhiteListInput.jsx
  packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_private-legacy-pages.page.tsx
  packages/app/src/pages/_search.page.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/services/xss/xssOption.ts
Labels: feature

#7269 fix: apply-colors-dark
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/app/src/styles/theme/_apply-colors.scss
  packages/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
  packages/preset-themes/src/styles/future.scss
  packages/preset-themes/src/styles/halloween.scss
Labels: bug

#7268 fix: Refactor uri decoding in getServerSideProps
  packages/app/src/pages/utils/commons.ts
Labels: bug

#7270 fix: Body of shared page is not displayed
  packages/app/src/pages/share/[[...path]].page.tsx
Labels: bug

#6727 feat: GROWI to GROWI transfer
  packages/app/config/logger/config.dev.js
  packages/app/package.json
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/en_US/commons.json
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/ja_JP/commons.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/public/static/locales/zh_CN/commons.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/client/services/g2g-transfer.ts
  packages/app/src/components/Admin/App/AwsSetting.tsx
  packages/app/src/components/Admin/App/FileUploadSetting.tsx
  packages/app/src/components/Admin/App/GcsSetting.tsx
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.jsx
  packages/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  packages/app/src/components/Admin/ExportArchiveDataPage.jsx
  packages/app/src/components/Admin/ExportArchiveDataPage.tsx
  packages/app/src/components/Admin/G2GDataTransfer.tsx
  packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
  packages/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
  packages/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionItem.jsx
  packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  packages/app/src/components/Common/CustomCopyToClipBoard.tsx
  packages/app/src/components/DataTransferForm.tsx
  packages/app/src/interfaces/g2g-transfer.ts
  packages/app/src/interfaces/transfer-key.ts
  packages/app/src/pages/admin/data-transfer.page.tsx
  packages/app/src/pages/installer.page.tsx
  packages/app/src/server/crowi/index.js
  packages/app/src/server/models/transfer-key.ts
  packages/app/src/server/models/user.js
  packages/app/src/server/models/vo/g2g-transfer-error.ts
  packages/app/src/server/routes/apiv3/g2g-transfer.ts
  packages/app/src/server/routes/apiv3/import.js
  packages/app/src/server/routes/apiv3/index.js
  packages/app/src/server/routes/apiv3/overwrite-params/attachmentFiles.chunks.js
  packages/app/src/server/routes/apiv3/overwrite-params/pages.js
  packages/app/src/server/routes/apiv3/overwrite-params/revisions.js
  packages/app/src/server/service/attachment.js
  packages/app/src/server/service/config-manager.ts
  packages/app/src/server/service/export.js
  packages/app/src/server/service/file-uploader/aws.ts
  packages/app/src/server/service/file-uploader/gcs.js
  packages/app/src/server/service/file-uploader/gridfs.js
  packages/app/src/server/service/file-uploader/local.js
  packages/app/src/server/service/file-uploader/none.js
  packages/app/src/server/service/file-uploader/uploader.js
  packages/app/src/server/service/g2g-transfer.ts
  packages/app/src/server/service/growi-bridge.js
  packages/app/src/server/service/import.js
  packages/app/src/server/util/createGrowiPagesFromImports.js
  packages/app/src/styles/_installer.scss
  packages/app/src/styles/style-app.scss
  packages/app/src/utils/vo/transfer-key.ts
  yarn.lock
Labels: feature

#7275 fix: Color of login form
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/src/styles/spring.scss
  packages/preset-themes/src/styles/wood.scss
Labels: bug

#7281 fix: Type guard comment.createdAt
  packages/app/src/components/PageComment/Comment.tsx
Labels: bug

#7272 fix: Bug in Page Tree Selected Item Background Color
  packages/app/src/components/Sidebar/PageTree/Item.tsx
Labels: bug

#7284 fix: Ignore backslash in page path
  packages/core/src/test/util/page-path-utils.test.js
  packages/core/src/utils/page-path-utils.ts
Labels: bug

#7283 feat: UI file upload settings at src growi
  packages/app/src/components/Admin/App/FileUploadSetting.tsx
  packages/app/src/components/Admin/G2GDataTransfer.tsx
Labels: feature

#7276 fix: Error toaster appears after renaming
  packages/app/src/components/PageRenameModal.tsx
  packages/app/src/server/routes/apiv3/page.js
Labels: bug

#7287 fix: Color for blinked section
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/fire-red.scss
  packages/preset-themes/src/styles/future.scss
  packages/preset-themes/src/styles/halloween.scss
  packages/preset-themes/src/styles/island.scss
  packages/preset-themes/src/styles/jade-green.scss
  packages/preset-themes/src/styles/kibela.scss
  packages/preset-themes/src/styles/mono-blue.scss
  packages/preset-themes/src/styles/nature.scss
  packages/preset-themes/src/styles/wood.scss
Labels: bug

#7286 fix: Share link management button is not available
  .github/workflows/reusable-app-prod.yml
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.tsx
  packages/app/src/components/ShareLink/ShareLink.tsx
  packages/app/src/components/ShareLink/ShareLinkForm.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/test/cypress/integration/22-sharelink/22-sharelink--access-to-sharelink.spec.ts
Labels: bug

#7285 fix: Previous editing markdown remains after changing page
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/use-static-swr.tsx
Labels: bug

#7292 fix: Invalid URL in markdown breaks browser
  packages/app/src/components/PageEditor/DrawioModal.tsx
  packages/app/src/components/PageEditor/LinkEditModal.jsx
  packages/app/src/components/ReactMarkdownComponents/Header.tsx
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/server/middlewares/safe-redirect.ts
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: bug

#7299 feat: Proactive questionnaire
  packages/app/public/static/locales/en_US/translation.json
  packages/app/public/static/locales/ja_JP/translation.json
  packages/app/public/static/locales/zh_CN/translation.json
  packages/app/src/components/Navbar/PersonalDropdown.tsx
  packages/app/src/components/Questionnaire/ProactiveQuestionnaireModal.tsx
Labels: feature

#7301 fix: Delete updated contents when save with shortcut
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/editor.tsx
Labels: bug

#7278 imprv: SSR
  packages/app/package.json
  packages/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  packages/app/src/client/services/side-effects/hackmd-draft-updated.ts
  packages/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  packages/app/src/client/services/side-effects/hash-changed.ts
  packages/app/src/client/services/side-effects/page-updated.ts
  packages/app/src/components/Comments.tsx
  packages/app/src/components/Common/LazyRenderer.tsx
  packages/app/src/components/CustomNavigation/CustomTabContent.tsx
  packages/app/src/components/Layout/MainPane.tsx
  packages/app/src/components/Page.tsx
  packages/app/src/components/Page/DisplaySwitcher.tsx
  packages/app/src/components/Page/PageContents.tsx
  packages/app/src/components/Page/PageView.module.scss
  packages/app/src/components/Page/PageView.tsx
  packages/app/src/components/Page/RevisionRenderer.tsx
  packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
  packages/app/src/components/ShareLink/ShareLinkPageContents.tsx
  packages/app/src/components/TableOfContents.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_document.page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.ts
  packages/app/src/services/renderer/renderer.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/styles/_mixins.scss
Labels: improvement

#7304 fix: GrowiContextualSubNavigation style is broken
  packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.tsx
Labels: bug

#7305 imprv: Override process for CommonSanitizeOptions
  packages/app/src/services/renderer/renderer.tsx
Labels: improvement

#7291 fix: Modal does not close after clicking on path in DescendantsPageListModal
  packages/app/src/components/DescendantsPageListModal.tsx
Labels: bug

#7300 fix: Guest users are able to move to pages that require authentication
  packages/app/src/pages/utils/commons.ts
Labels: bug

#7250 fix: Undeleteable trash pages when clicked empty trash button bug
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
Labels: bug

#7310 imprv: SSR 2
  packages/app/src/components/Page/PageView.tsx
Labels: exclude from changelog

#7307 fix: Request to "/_api/v3/personal-settings" occurs when in guest mode
  packages/app/src/stores/personal-settings.tsx
Labels: bug

#7313 fix: Request to "/_api/v3/page/is-grant-normalized" occurs when in guest mode
  packages/app/src/stores/page.tsx
Labels: bug

#7321 fix: Can delete own user
  packages/app/src/server/routes/apiv3/users.js
Labels: bug

#7324 fix: Show load latest revision button when update drawio or table from view
  packages/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  packages/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  packages/app/src/components/Page/PageContents.tsx
Labels: bug

#7323 support: Add test for View and Edit contents when saving
  packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
Labels: support

#7318 support: Bump SWR to v2
  packages/app/package.json
  packages/app/src/client/util/toastr.ts
  packages/app/src/components/Admin/App/ConfirmModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
  packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  packages/app/src/components/Layout/BasicLayout.tsx
  packages/app/src/components/Me/BasicInfoSettings.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/NotAvailable.tsx
  packages/app/src/components/Page/PageContents.tsx
  packages/app/src/components/Page/RevisionLoader.tsx
  packages/app/src/components/PageAlert/TrashPageAlert.tsx
  packages/app/src/components/SearchPage.tsx
  packages/app/src/components/SearchPage/SearchControl.tsx
  packages/app/src/components/ShareLink/ShareLinkPageContents.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/StickyStretchableScroller.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/_app.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/pages/utils/commons.ts
  packages/app/src/stores/activity.ts
  packages/app/src/stores/attachment.tsx
  packages/app/src/stores/comment.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/editor.tsx
  packages/app/src/stores/in-app-notification.ts
  packages/app/src/stores/maintenanceMode.tsx
  packages/app/src/stores/page-listing.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/renderer.tsx
  packages/app/src/stores/search.tsx
  packages/app/src/stores/share-link.tsx
  packages/app/src/stores/tag.tsx
  packages/app/src/stores/template.tsx
  packages/app/src/stores/ui.tsx
  packages/app/src/stores/use-context-swr.tsx
  packages/app/src/stores/user-group.tsx
  packages/app/src/stores/user.tsx
  packages/app/src/stores/xss.ts
  yarn.lock
Labels: support
