Repository growilabs/growi, pull requests merged in 2023-12, with the labels that each got.

#8291 imprv: improve external user group sync service test
  apps/app/test/integration/service/external-user-group-sync.test.ts
Labels: type/improvement, flag/exclude-from-changelog

#8294 feat: Able to use handsontable modal in editor
  apps/app/_obsolete/src/components/PageEditor/MarkdownTableInterceptor.js
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/components/PageEditor/MarkdownTableDataImportForm.tsx
  apps/app/src/components/PageEditor/MarkdownTableUtil.js
  apps/app/src/components/PageEditor/markdown-table-util-for-editor.ts
  apps/app/src/components/PageEditor/markdown-table-util-for-view.ts
  apps/app/src/stores/modal.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/stores/use-handsontable.ts
Labels: type/feature

#8248 support: 133781 refactor where to get users to be notified
  apps/app/src/interfaces/in-app-notification.ts
  apps/app/src/server/models/activity.ts
  apps/app/src/server/routes/apiv3/bookmarks.js
  apps/app/src/server/routes/apiv3/page.js
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/routes/login.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/activity.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/in-app-notification/in-app-notification-utils.ts
  apps/app/src/server/service/page.ts
  apps/app/src/server/service/pre-notify.ts
Labels: type/support

#8299 feat: 132740 setting UI in me page
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/user-ui-settings.ts
  apps/app/src/components/Me/OtherSettings.tsx
  apps/app/src/components/Me/QuestionnaireSettings.tsx
  apps/app/src/components/Me/SidebarCollapsedIcon.jsx
  apps/app/src/components/Me/SidebarDockIcon.jsx
  apps/app/src/components/Me/UISettings.module.scss
  apps/app/src/components/Me/UISettings.tsx
Labels: type/feature, flag/exclude-from-changelog

#8280 fix: 135815 fix key prop warning
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
Labels: type/bug

#8279 imprv: Upload handler use apiv3 post
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/index.js
Labels: type/improvement

#8314 imprv: Refactor DrawioViewer re-rendering by the resizing trigger
  packages/remark-drawio/src/components/DrawioViewer.module.scss
  packages/remark-drawio/src/components/DrawioViewer.tsx
Labels: type/improvement

#8321 imprv: Remove skip to run cypress in 23-editor
  apps/app/test/cypress/e2e/23-editor/23-editor--with-navigation.cy.ts
Labels: type/improvement

#8322 fix: SAML callback action throws the field is undefined error when the ACL Rule string is only white space
  apps/app/src/server/service/passport.ts
  apps/app/test/integration/service/passport.test.js
Labels: type/bug

#8323 support: Add test for delete-completely-user-home-by-system.ts
  apps/app/src/server/events/user.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/service/page/consts.ts
  apps/app/src/server/service/page/delete-completely-user-home-by-system.integ.ts
  apps/app/src/server/service/page/delete-completely-user-home-by-system.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/page/should-use-v4-process.ts
Labels: type/support

#8334 feat: Apply i18n to `Create today's ...` page path
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
Labels: type/feature

#8332 feat: Change VSCode settings
  .vscode/settings.json
Labels: type/feature, flag/exclude-from-changelog

#8338 feat: Enable toggling between light and dark modes from user settings
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Me/ColorModeSettings.module.scss
  apps/app/src/components/Me/ColorModeSettings.tsx
  apps/app/src/components/Me/OtherSettings.tsx
Labels: type/feature

#8339 fix: Keycloak group sync config not loaded on sync execution
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
  apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.integ.ts
  apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
Labels: type/bug

#8324 feat: Able to use templete modal in editor
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/stores/modal.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TemplateButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/stores/use-template-modal.ts
Labels: type/feature

#8238 feat: New incremental search
  apps/app/package.json
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageControls/SearchButton.module.scss
  apps/app/src/components/PageControls/SearchButton.tsx
  apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
  apps/app/src/features/search/client/components/SearchForm.tsx
  apps/app/src/features/search/client/components/SearchHelp.tsx
  apps/app/src/features/search/client/components/SearchMenuItem.module.scss
  apps/app/src/features/search/client/components/SearchMenuItem.tsx
  apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/components/SearchResultMenuItem.tsx
  apps/app/src/features/search/client/interfaces/downshift.ts
  apps/app/src/features/search/client/stores/search.ts
  yarn.lock
Labels: type/feature

#8343 Feat/136137 137441 keep groups unrelated to user on group grant change
  apps/app/_obsolete/src/components/PageEditorByHackmd.tsx
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/interfaces/page-operation.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/migrations/20230723061824-granted-group-to-array-of-objects.js
  apps/app/src/migrations/20231223155127-non-null-granted-groups.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/interfaces/page-operation.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page.js
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page.ts
  apps/app/test/integration/models/v5.page.test.js
  apps/app/test/integration/service/page-grant.test.js
  apps/app/test/integration/service/v5.page.test.ts
  apps/app/test/integration/service/v5.public-page.test.ts
Labels: type/feature

#8353 support: Automated RC release workflow
  .github/workflows/release-rc-v7.yml
Labels: type/support

#8340 feat: Able to use drawio modal in editor
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/components/Page/markdown-drawio-util-for-view.ts
  apps/app/src/components/Page/markdown-table-util-for-view.ts
  apps/app/src/components/PageEditor/DrawioCommunicationHelper.ts
  apps/app/src/components/PageEditor/DrawioModal.tsx
  apps/app/src/components/PageEditor/MarkdownDrawioUtil.js
  apps/app/src/components/PageEditor/markdown-drawio-util-for-editor.ts
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/fold-drawio.ts
  packages/editor/src/stores/use-drawio.ts
Labels: type/feature

#8358 fix: plugin is broken after unzipping
  apps/app/package.json
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  yarn.lock
Labels: type/bug

#8359 imprv: Allow plugin that contain slashes in the branch name to be installed
  apps/app/src/features/growi-plugin/server/models/vo/github-url.spec.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
Labels: type/improvement

#8360 imprv: Add types for unzip-stream
  apps/app/package.json
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  yarn.lock
Labels: flag/exclude-from-changelog
