Repository growilabs/growi, pull requests merged in 2023-03, with the labels that each got.

#7432 imprv: Save the correct page body when uploading the attachment
  packages/app/src/components/PageEditor.tsx
  packages/app/src/server/routes/attachment.js
Labels: bug, improvement

#7436 fix: PageDeleteModal warns even if you have delete permission
  packages/app/src/components/PageDeleteModal.tsx
Labels: bug

#7435 fix: Unable to delete multiple pages
  packages/app/src/server/routes/apiv3/pages.js
  packages/app/src/server/service/page.ts
Labels: bug

#7424 fix: Error when trying to create a new page with attachments
  packages/app/src/client/services/page-operation.ts
  packages/app/src/client/services/side-effects/hackmd-draft-updated.ts
  packages/app/src/client/services/side-effects/page-updated.ts
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/Page/PageContentsUtilities.tsx
  packages/app/src/components/Page/PageView.tsx
  packages/app/src/components/PageAlert/OldRevisionAlert.tsx
  packages/app/src/components/PageAlert/PageAlerts.tsx
  packages/app/src/components/PageAttachment.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/components/PageEditor/ConflictDiffModal.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageHistory.tsx
  packages/app/src/components/PagePathNav.tsx
  packages/app/src/components/SavePageControls.tsx
  packages/app/src/components/ShareLink/ShareLink.tsx
  packages/app/src/components/ShareLink/ShareLinkForm.tsx
  packages/app/src/components/ShareLink/ShareLinkPageView.tsx
  packages/app/src/components/Sidebar/PageTree.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/pages/share/[[...path]].page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
  packages/app/src/stores/ui.tsx
Labels: bug

#7454 fix: Email is not sent to Admin user when the user is created at user registration restricted
  packages/app/src/server/routes/login.js
Labels: bug

#7461 imprv: Include anyone with the link page in the deletion target
  packages/app/src/server/models/page.ts
  packages/app/src/server/routes/apiv3/pages.js
Labels: improvement

#7465 imprv: Add markdown header link (h4, h5, h6)
  packages/app/src/services/renderer/renderer.tsx
Labels: improvement

#7443 fix: Search results are not highlighted when searching for quoteted words
  packages/app/src/components/SearchPage/SearchPageBase.tsx
Labels: bug

#7458 support: Bump Next.js to v13
  packages/app/next.config.js
  packages/app/package.json
  packages/app/src/@types/i18next.d.ts
  packages/app/src/components/Admin/Common/AdminNavigation.jsx
  packages/app/src/components/Admin/ManageExternalAccount.tsx
  packages/app/src/components/Admin/PluginsExtension/PluginCard.tsx
  packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
  packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  packages/app/src/components/Admin/UserManagement.tsx
  packages/app/src/components/CustomNavigation/CustomNav.jsx
  packages/app/src/components/CustomNavigation/CustomTabContent.tsx
  packages/app/src/components/LoginForm.tsx
  packages/app/src/components/Navbar/AuthorInfo.tsx
  packages/app/src/components/Navbar/GrowiNavbar.tsx
  packages/app/src/components/Navbar/PersonalDropdown.jsx
  packages/app/src/components/PageAccessoriesModal.tsx
  packages/app/src/components/PageAlert/OldRevisionAlert.tsx
  packages/app/src/components/PageComment/Comment.tsx
  packages/app/src/components/PageEditorByHackmd.tsx
  packages/app/src/components/PageHistory/Revision.tsx
  packages/app/src/components/PageHistory/RevisionDiff.tsx
  packages/app/src/components/PageList/PageListItemL.tsx
  packages/app/src/components/PagePathHierarchicalLink.tsx
  packages/app/src/components/PageTimeline.tsx
  packages/app/src/components/PasswordResetExecutionForm.tsx
  packages/app/src/components/PasswordResetRequestForm.tsx
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/app/src/components/Sidebar/CustomSidebar.tsx
  packages/app/src/components/Sidebar/PageTree/Item.tsx
  packages/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
  packages/app/src/components/Sidebar/RecentChanges.tsx
  packages/app/src/components/Sidebar/SidebarNav.tsx
  packages/app/src/components/TagCloudBox.tsx
  packages/app/src/components/TagList.tsx
  packages/app/src/components/User/Username.tsx
  packages/app/src/pages/forgot-password-errors.page.tsx
  packages/app/src/stores/modal.tsx
  packages/remark-lsx/src/components/LsxPageList/LsxPage.tsx
  yarn.lock
Labels: support

#7471 fix: Internal server error when input wrong tag to markdown
  packages/app/package.json
  packages/app/src/components/Page/RevisionRenderer.tsx
  yarn.lock
Labels: bug

#7474 imprv: Page path hierarchical link color
  packages/app/src/components/SearchPage/SearchResultContent.module.scss
  packages/app/src/components/SearchPage/SearchResultContent.tsx
  packages/app/src/styles/_page-path.scss
  packages/app/src/styles/theme/_apply-colors-dark.scss
  packages/app/src/styles/theme/_apply-colors-light.scss
Labels: improvement

#7473 fix: Scrolling table in preview causes editor to scroll to row 1 (workaround)
  packages/app/src/components/ReactMarkdownComponents/Table.tsx
  packages/app/src/services/renderer/renderer.tsx
Labels: bug

#7478 imprv: container styles
  packages/app/src/components/Layout/MainPane.tsx
  packages/app/src/components/PageContentFooter.tsx
  packages/app/src/components/SearchPage/SearchPageBase.tsx
  packages/app/src/components/Sidebar/Tag.tsx
  packages/app/src/pages/me/[[...path]].page.tsx
  packages/app/src/pages/tags.page.tsx
  packages/app/src/pages/trash.page.tsx
  packages/app/src/styles/_layout.scss
Labels: exclude from changelog

#7483 imprv: Reverse switch for display or hidden page settings
  packages/app/public/static/locales/en_US/admin.json
  packages/app/public/static/locales/ja_JP/admin.json
  packages/app/public/static/locales/zh_CN/admin.json
  packages/app/src/components/Admin/Security/SecuritySetting.jsx
Labels: improvement

#7463 fix: Page paths in search results are not displayed correctly
  packages/app/src/server/service/search-delegator/elasticsearch.ts
Labels: bug

#7488 fix: Responses 500 status code when invalid regular expressions are inputted to lsx's execpt option
  packages/remark-lsx/src/server/routes/lsx.js
Labels: bug

#7491 fix: Search results are not highlighted when searching for quoteted words (PageListItemL)
  packages/app/src/interfaces/search.ts
  packages/app/src/server/service/search.ts
Labels: bug

#7494 fix: Language selection dropdown in installer does not reflect browser language setting
  packages/app/src/components/InstallerForm.tsx
Labels: bug

#7498 fix: Attachment links do not work correctly
  packages/app/src/components/ReactMarkdownComponents/NextLink.tsx
Labels: bug

#7499 fix: Error when transitioning to a user home page where creator does not exist
  packages/app/src/components/Page/PageView.tsx
  packages/core/src/interfaces/page.ts
Labels: bug

#7497 fix: Show handsontable edit modal color in dark theme
  packages/app/src/styles/theme/_apply-colors-dark.scss
Labels: bug

#7484 fix: CodeBlock string is be `[object Object]` if searched
  packages/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
Labels: bug

#7504 fix: Supress `activeTab` prop type error
  packages/app/src/components/PageAccessoriesModal.tsx
Labels: bug

#7506 imprv: ToC placeholder
  packages/app/package.json
  packages/app/resource/locales/en_US/sandbox.md
  packages/app/resource/locales/ja_JP/sandbox.md
  packages/app/resource/locales/zh_CN/sandbox.md
  packages/app/src/services/renderer/renderer.tsx
  packages/remark-growi-directive/package.json
  yarn.lock
Labels: improvement

#7510 fix: The same level template page is being applied to lower level pages unintentionally
  packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  packages/app/src/components/PageEditor.tsx
  packages/app/src/pages/[[...path]].page.tsx
  packages/app/src/stores/context.tsx
  packages/app/src/stores/page.tsx
Labels: bug

#7523 fix: Lsx filter and except option do not work when the path includes special characters
  packages/remark-lsx/src/server/routes/lsx.js
Labels: bug
