Repository growilabs/growi, pull requests merged in 2023-06, with the labels that each got.

#7765 support: Refactor plugin related modules
  apps/app/src/features/activate-plugin/index.ts
  apps/app/src/features/activate-plugin/utils/index.ts
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/PluginCard.module.scss
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/PluginInstallerForm.tsx
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/index.ts
  apps/app/src/features/growi-plugin/components/GrowiPluginsActivator.client.tsx
  apps/app/src/features/growi-plugin/components/index.ts
  apps/app/src/features/growi-plugin/interfaces/growi-plugin.ts
  apps/app/src/features/growi-plugin/interfaces/index.ts
  apps/app/src/features/growi-plugin/models/growi-plugin.ts
  apps/app/src/features/growi-plugin/models/index.ts
  apps/app/src/features/growi-plugin/routes/growi-plugins.ts
  apps/app/src/features/growi-plugin/services/growi-plugin.ts
  apps/app/src/features/growi-plugin/services/index.ts
  apps/app/src/features/growi-plugin/stores/growi-plugin.tsx
  apps/app/src/features/growi-plugin/utils/growi-facade-utils.client.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_document.page.tsx
  apps/app/src/pages/admin/plugins.page.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/service/customize.ts
  apps/app/src/stores/renderer.tsx
  apps/app/src/stores/template.tsx
Labels: type/support

#7768 fix: When uploading an attachment and creating a new page, it does not inherit the grant of the parent page
  apps/app/src/components/PageEditor.tsx
Labels: type/bug

#7769 fix: Lsx options
  .devcontainer/devcontainer.json
  apps/app/package.json
  package.json
  packages/remark-lsx/package.json
  packages/remark-lsx/src/@types/declaration.d.ts
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/server/index.ts
  packages/remark-lsx/src/server/routes/list-pages/add-depth-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/add-sort-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/generate-base-query.ts
  packages/remark-lsx/src/server/routes/list-pages/get-toppage-viewers-count.ts
  packages/remark-lsx/src/server/routes/list-pages/index.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/index.ts
  packages/remark-lsx/src/server/routes/lsx.ts
  packages/remark-lsx/src/stores/lsx.tsx
  packages/remark-lsx/tsconfig.json
  packages/remark-lsx/vite.server.config.ts
  packages/remark-lsx/vitest.config.ts
  yarn.lock
Labels: type/bug

#7774 feat(lsx): Load more
  .vscode/launch.json
  apps/app/src/components/Sidebar/InfiniteScroll.tsx
  packages/remark-lsx/src/components/Lsx.module.scss
  packages/remark-lsx/src/components/Lsx.tsx
  packages/remark-lsx/src/interfaces/api.ts
  packages/remark-lsx/src/server/routes/list-pages/add-depth-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/generate-base-query.ts
  packages/remark-lsx/src/server/routes/list-pages/index.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/index.ts
  packages/remark-lsx/src/stores/lsx.tsx
  packages/remark-lsx/src/stores/lsx/index.ts
  packages/remark-lsx/src/stores/lsx/lsx.ts
  packages/remark-lsx/src/stores/lsx/parse-num-option.spec.ts
  packages/remark-lsx/src/stores/lsx/parse-num-option.ts
  packages/remark-lsx/src/utils/depth-utils.ts
  packages/remark-lsx/src/utils/page-node.spec.ts
  packages/remark-lsx/src/utils/page-node.ts
  packages/remark-lsx/vite.client.config.ts
Labels: type/feature

#7776 support: Add tests for remark-lsx
  packages/remark-lsx/src/server/routes/list-pages/add-depth-condition.spec.ts
  packages/remark-lsx/src/utils/depth-utils.spec.ts
Labels: flag/exclude-from-changelog

#7783 feat(plugin): Specify repository branch name
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/growi-plugin/components/Admin/PluginsExtensionPageContents/PluginInstallerForm.tsx
  apps/app/src/features/growi-plugin/models/vo/github-url.spec.ts
  apps/app/src/features/growi-plugin/models/vo/github-url.ts
  apps/app/src/features/growi-plugin/services/growi-plugin.ts
Labels: type/feature

#7786 support: Add e2e tests for editor
  .github/workflows/reusable-app-prod.yml
  apps/app/src/components/PageDuplicateModal.tsx
  apps/app/src/components/SavePageControls/GrantSelector.tsx
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--use-tools.spec.ts
  apps/app/test/cypress/integration/23-editor/23-editor--saving.spec.ts
  apps/app/test/cypress/integration/23-editor/23-editor--with-navigation.ts
  apps/app/test/cypress/integration/23-editor/assets/example.txt
Labels: type/support

#7794 fix: Slack channels data for User Triggered Notification is not loaded
  apps/app/src/stores/editor.tsx
Labels: type/bug

#7755 imprv: Can use normal browser transition in searching page
  apps/app/src/components/SearchPage.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
Labels: type/improvement

#7795 fix: Unable to execute the migration of draw.io
  bin/data-migrations/src/migrations/v60x/index.js
Labels: type/bug, flag/exclude-from-changelog

#7796 imprv: Supress unnecessary bookmark API requests when using for mutation purposes
  apps/app/src/stores/bookmark.ts
Labels: type/improvement

#7797 fix: Bookmarks mutation for the current user
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/Sidebar/PageTree/Item.tsx
  apps/app/src/stores/bookmark.ts
Labels: type/bug

#7798 imprv: Suppress unnecessary bookmark API requests
  apps/app/src/components/BookmarkButtons.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/Sidebar/PageTree/Item.tsx
  apps/app/src/stores/bookmark.ts
  apps/app/src/stores/page.tsx
Labels: type/improvement

#7772 feat: Deciding whether to use SSR based on the volume of latestRevisionBodyLength
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/stores/page.tsx
  packages/core/src/interfaces/page.ts
Labels: type/feature

#7800 imprv: Show tooltip when copying password
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
Labels: type/improvement

#7815 fix(lsx): Prefix is not uniquely determined by usage
  packages/remark-lsx/src/server/routes/list-pages/index.ts
  packages/remark-lsx/src/services/renderer/lsx.ts
Labels: type/bug

#7824 fix: Email body of global notification is not displayed
  apps/app/resource/locales/en_US/admin/userInvitation.ejs
  apps/app/resource/locales/en_US/admin/userResetPassword.ejs
  apps/app/resource/locales/en_US/admin/userWaitingActivation.ejs
  apps/app/resource/locales/en_US/notifications/comment.ejs
  apps/app/resource/locales/en_US/notifications/notActiveUser.ejs
  apps/app/resource/locales/en_US/notifications/pageCreate.ejs
  apps/app/resource/locales/en_US/notifications/pageDelete.ejs
  apps/app/resource/locales/en_US/notifications/pageEdit.ejs
  apps/app/resource/locales/en_US/notifications/pageLike.ejs
  apps/app/resource/locales/en_US/notifications/pageMove.ejs
  apps/app/resource/locales/en_US/notifications/passwordReset.ejs
  apps/app/resource/locales/en_US/notifications/passwordResetSuccessful.ejs
  apps/app/resource/locales/en_US/notifications/userActivation.ejs
  apps/app/resource/locales/en_US/welcome.md
  apps/app/resource/locales/ja_JP/admin/userInvitation.ejs
  apps/app/resource/locales/ja_JP/admin/userResetPassword.ejs
  apps/app/resource/locales/ja_JP/admin/userWaitingActivation.ejs
  apps/app/resource/locales/ja_JP/notifications/comment.ejs
  apps/app/resource/locales/ja_JP/notifications/comment.txt
  apps/app/resource/locales/ja_JP/notifications/notActiveUser.ejs
  apps/app/resource/locales/ja_JP/notifications/pageCreate.ejs
  apps/app/resource/locales/ja_JP/notifications/pageCreate.txt
  apps/app/resource/locales/ja_JP/notifications/pageDelete.ejs
  apps/app/resource/locales/ja_JP/notifications/pageDelete.txt
  apps/app/resource/locales/ja_JP/notifications/pageEdit.ejs
  apps/app/resource/locales/ja_JP/notifications/pageEdit.txt
  apps/app/resource/locales/ja_JP/notifications/pageLike.ejs
  apps/app/resource/locales/ja_JP/notifications/pageLike.txt
  apps/app/resource/locales/ja_JP/notifications/pageMove.ejs
  apps/app/resource/locales/ja_JP/notifications/pageMove.txt
  apps/app/resource/locales/ja_JP/notifications/passwordReset.ejs
  apps/app/resource/locales/ja_JP/notifications/passwordResetSuccessful.ejs
  apps/app/resource/locales/ja_JP/notifications/userActivation.ejs
  apps/app/resource/locales/zh_CN/admin/userInvitation.ejs
  apps/app/resource/locales/zh_CN/admin/userResetPassword.ejs
  apps/app/resource/locales/zh_CN/admin/userWaitingActivation.ejs
  apps/app/resource/locales/zh_CN/notifications/comment.ejs
  apps/app/resource/locales/zh_CN/notifications/notActiveUser.ejs
  apps/app/resource/locales/zh_CN/notifications/pageCreate.ejs
  apps/app/resource/locales/zh_CN/notifications/pageDelete.ejs
  apps/app/resource/locales/zh_CN/notifications/pageEdit.ejs
  apps/app/resource/locales/zh_CN/notifications/pageLike.ejs
  apps/app/resource/locales/zh_CN/notifications/pageMove.ejs
  apps/app/resource/locales/zh_CN/notifications/passwordReset.ejs
  apps/app/resource/locales/zh_CN/notifications/passwordResetSuccessful.ejs
  apps/app/resource/locales/zh_CN/notifications/userActivation.ejs
  apps/app/src/server/routes/apiv3/forgot-password.js
  apps/app/src/server/routes/apiv3/user-activation.ts
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/routes/login.js
  apps/app/src/server/service/global-notification/global-notification-mail.js
Labels: type/bug

#7826 imprv: Can use normal browser transition in searching page
  apps/app/src/components/SearchPage.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
Labels: type/improvement

#7771 imprv: Update email alert
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Me/BasicInfoSettings.tsx
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/personal-setting.js
  apps/app/src/stores/personal-settings.tsx
  apps/app/tsconfig.json
Labels: type/improvement

#7809 support: Dependencies specification for local packages
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  apps/app/package.json
  apps/slackbot-proxy/package.json
  bin/github-actions/bump-versions/README.md
  bin/github-actions/bump-versions/cli.js
  bin/github-actions/bump-versions/flow/bump-versions.js
  bin/github-actions/bump-versions/index.js
  bin/github-actions/bump-versions/step/printHelp.js
  package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/presentation/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  turbo.json
  yarn.lock
Labels: type/support

#7828 fix: Brand logo fill color transition
  apps/app/src/styles/theme/apply-colors.scss
Labels: type/bug

#7784 fix: Handsontable not display full screen
  apps/app/src/components/PageEditor/HandsontableModal.tsx
Labels: type/bug

#7830 feat: Plugin kit
  packages/pluginkit/.eslintignore
  packages/pluginkit/.eslintrc.js
  packages/pluginkit/.gitignore
  packages/pluginkit/package.json
  packages/pluginkit/src/consts/index.ts
  packages/pluginkit/src/consts/types.ts
  packages/pluginkit/src/index.ts
  packages/pluginkit/src/model/growi-plugin-validation-data.ts
  packages/pluginkit/src/model/growi-plugin-validation-error.ts
  packages/pluginkit/src/model/index.ts
  packages/pluginkit/src/server/utils/v4/index.ts
  packages/pluginkit/src/server/utils/v4/package-json/import.spec.ts
  packages/pluginkit/src/server/utils/v4/package-json/import.ts
  packages/pluginkit/src/server/utils/v4/package-json/index.ts
  packages/pluginkit/src/server/utils/v4/package-json/validate.spec.ts
  packages/pluginkit/src/server/utils/v4/package-json/validate.ts
  packages/pluginkit/src/server/utils/v4/template.ts
  packages/pluginkit/test/fixtures/example-package/template1/index.js
  packages/pluginkit/test/fixtures/example-package/template1/package.json
  packages/pluginkit/tsconfig.json
  packages/pluginkit/vite.config.ts
  packages/pluginkit/vitest.config.ts
  packages/preset-templates/dist/example/ja_JP/meta.json
  packages/preset-templates/dist/example/ja_JP/template.md
  packages/preset-templates/package.json
  packages/preset-templates/test/index.test.ts
  packages/preset-templates/tsconfig.json
  packages/preset-templates/vitest.config.ts
  turbo.json
  yarn.lock
Labels: type/feature

#7827 fix: Editing user group settings
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
Labels: type/bug

#7534 feat: Rich Attachment
  apps/app/public/images/icons/editor/attachment.svg
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/PageAttachment.tsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageAttachment/PageAttachmentList.tsx
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
  apps/app/src/components/ReactMarkdownComponents/RichAttachment.module.scss
  apps/app/src/components/ReactMarkdownComponents/RichAttachment.tsx
  apps/app/src/components/ReactMarkdownComponents/TableWithEditButton.tsx
  apps/app/src/components/User/Username.tsx
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/services/renderer/remark-plugins/attachment.ts
  apps/app/src/stores/attachment.tsx
  apps/app/src/stores/modal.tsx
  packages/core/src/interfaces/attachment.ts
  packages/ui/src/components/Attachment.tsx
Labels: type/feature

#7790 imprv: After reset password footer modal design
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/server/routes/apiv3/users.js
Labels: type/improvement

#7832 imprv: Convert jsx into tsx
  apps/app/src/components/Page/TagEditModal.tsx
Labels: type/improvement

#7758 imprv: Able to send new passsword by email
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/server/routes/apiv3/users.js
Labels: type/improvement

#7836 feat: Add a lead to https://growi.cloud/help/
  apps/app/src/components/Sidebar/SidebarNav.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/pages/utils/commons.ts
Labels: type/feature, flag/exclude-from-changelog
