Repository growilabs/growi, pull requests merged in 2023-09, with the labels that each got.

#8047 support: Remove questionnaire logger
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/questionnaire/server/service/questionnaire.ts
Labels: flag/exclude-from-changelog

#8050 feat: CodeMirror editor toolbar
  apps/app/package.json
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Layout/MainPane.tsx
  apps/app/src/components/Layout/PageViewLayout.module.scss
  apps/app/src/components/Layout/PageViewLayout.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/styles/font-icons.scss
  packages/core/scss/placeholders/_flex-expand.scss
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TemplateButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.module.scss
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/index.ts
  packages/editor/src/components/CodeMirrorEditor/Toolbar/scss/toolbar-button.scss
  packages/editor/src/components/CodeMirrorEditor/index.ts
  packages/editor/src/main.scss
  yarn.lock
Labels: flag/exclude-from-changelog

#8054 Feat/123278 129841 keycloak group sync config
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/KeycloakGroupManagement.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/KeycloakGroupSyncSettingsForm.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/LdapGroupSyncSettingsForm.tsx
  apps/app/src/features/external-user-group/client/stores/external-user-group.ts
  apps/app/src/features/external-user-group/interfaces/external-user-group.ts
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
Labels: type/feature

#8057 imprv: Add CSP style-src for Safari and Content-Disposition of attachment (for v6.1.x)
  apps/app/src/server/routes/attachment.js
Labels: type/improvement

#8058 imprv: i18n resetting password mail body
  apps/app/src/server/routes/apiv3/users.js
Labels: type/improvement

#8041 support: Revoke well classes
  apps/app/src/components/Admin/App/FileUploadSetting.tsx
  apps/app/src/components/Admin/App/MaintenanceMode.tsx
  apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
  apps/app/src/components/Admin/App/SiteUrlSetting.tsx
  apps/app/src/components/Admin/App/V5PageMigration.tsx
  apps/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeTitle.tsx
  apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/components/Admin/G2GDataTransferExportForm.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  apps/app/src/components/Admin/ImportData/GrowiArchiveSection.jsx
  apps/app/src/components/Admin/ImportData/ImportDataPageContents.jsx
  apps/app/src/components/Admin/LegacySlackIntegration/SlackConfiguration.jsx
  apps/app/src/components/Admin/MarkdownSetting/MarkDownSettingContents.tsx
  apps/app/src/components/Admin/Notification/GlobalNotification.jsx
  apps/app/src/components/Admin/Security/FacebookSecuritySetting.jsx
  apps/app/src/components/Admin/Security/LdapSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.tsx
  apps/app/src/components/ErrorBoudary.jsx
  apps/app/src/components/Page/CopyDropdown.jsx
  apps/app/src/components/Page/CopyDropdown.module.scss
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/components/PageEditorByHackmd.tsx
  apps/app/src/components/RevisionComparer/RevisionComparer.module.scss
  apps/app/src/components/RevisionComparer/RevisionComparer.tsx
  apps/app/src/styles/theme/_apply-colors-dark.scss
  apps/app/src/styles/theme/apply-colors.scss
  packages/core/scss/bootstrap/_override.scss
Labels: type/support, type/breaking

#8056 imprv: Ignore GROWI's CSS in Marp slides.
  apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/components/Presentation/Slides.tsx
  apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
  packages/presentation/src/components/GrowiSlides.tsx
  packages/presentation/src/components/MarpSlides.tsx
  packages/presentation/src/components/Slides.global.scss
  packages/presentation/src/components/Slides.module.scss
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/services/growi-marpit.ts
Labels: type/improvement

#8073 fix: Url to join to the slack team
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  README_JP.md
  SECURITY.md
  apps/app/resource/locales/en_US/welcome.md
  apps/app/resource/locales/ja_JP/welcome.md
  apps/app/resource/locales/zh_CN/welcome.md
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts
  apps/slackbot-proxy/src/views/top.ejs
Labels: type/bug

#8069 imprv: Search behavior
  CHANGELOG.md
  apps/app/src/client/services/search-operation.ts
  apps/app/src/components/Navbar/GlobalSearch.tsx
  apps/app/src/components/Page/RenderTagLabels.tsx
  apps/app/src/components/SearchPage.tsx
  apps/app/src/components/SearchPage/SearchControl.tsx
  apps/app/src/components/Sidebar/RecentChanges.tsx
  apps/app/src/components/TagCloudBox.tsx
  apps/app/src/components/TagList.tsx
  apps/app/src/stores/tag.tsx
Labels: type/improvement

#8039 imprv: Indent with tab
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/improvement, flag/exclude-from-changelog

#8055 imprv: Fix inner personal dropdown
  apps/app/src/components/Sidebar/PersonalDropdown.tsx
Labels: flag/exclude-from-changelog

#8081 imprv: Reconfigure sidbar
  apps/app/src/components/Sidebar/PersonalDropdown.tsx
  apps/app/src/components/Sidebar/SidebarNav.tsx
Labels: flag/exclude-from-changelog

#8075 feat: Workflow creation page
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/workflow.ts
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/SubNavButtons/CommunicationMenuItems.tsx
  apps/app/src/components/Workflow/CreateWorkflowPage.tsx
  apps/app/src/components/Workflow/WorkflowModal.tsx
  apps/app/src/stores/modal.tsx
Labels: flag/exclude-from-changelog

#8076 imprv: Move workflow related source code under the features directory
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/features/approval-workflow/client/components/CreateWorkflowPage.tsx
  apps/app/src/features/approval-workflow/client/components/WorkflowListPage.tsx
  apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx
  apps/app/src/features/approval-workflow/client/services/workflow.ts
  apps/app/src/features/approval-workflow/client/stores/workflow.ts
  apps/app/src/features/approval-workflow/interfaces/workflow.ts
  apps/app/src/features/approval-workflow/server/models/workflow.integ.ts
  apps/app/src/features/approval-workflow/server/models/workflow.ts
  apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts
  apps/app/src/features/approval-workflow/server/services/workflow.integ.ts
  apps/app/src/features/approval-workflow/server/services/workflow.spec.ts
  apps/app/src/features/approval-workflow/server/services/workflow.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/stores/modal.tsx
Labels: flag/exclude-from-changelog

#8083 imprv: Admin customize presentation form
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/services/AdminCustomizeContainer.js
  apps/app/src/components/Admin/Customize/Customize.jsx
  apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizePresentationSetting.tsx
  apps/app/src/server/routes/apiv3/customize-setting.js
Labels: type/improvement

#8082 support: Apply colors v7
  apps/app/_obsolete/src/styles/theme/_apply-colors-dark.scss
  apps/app/_obsolete/src/styles/theme/_apply-colors-light.scss
  apps/app/_obsolete/src/styles/theme/_hsl-functions.scss
  apps/app/_obsolete/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-border-colors.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-buttons.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-colors.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-dropdown.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-nav.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-tables.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-text.scss
  apps/app/_obsolete/src/styles/theme/_reboot-bootstrap-theme-colors.scss
  apps/app/_obsolete/src/styles/theme/_reboot-toastr-colors.scss
  apps/app/_obsolete/src/styles/theme/apply-colors.scss
  apps/app/_obsolete/src/styles/theme/mixins/_count-badge.scss
  apps/app/_obsolete/src/styles/theme/mixins/_hsl-badge.scss
  apps/app/_obsolete/src/styles/theme/mixins/_hsl-button.scss
  apps/app/_obsolete/src/styles/theme/mixins/_list-group.scss
  apps/app/_obsolete/src/styles/theme/mixins/_page-editor-mode-manager.scss
  apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/components/PagePresentationModal.module.scss
  apps/app/src/components/Sidebar/PageTree/Item.module.scss
  apps/app/src/components/Sidebar/PageTree/Item.tsx
  apps/app/src/components/Sidebar/Sidebar.module.scss
  apps/app/src/components/Sidebar/SidebarNav.module.scss
  apps/app/src/pages/_app.page.tsx
  apps/app/src/server/.node-dev.json
  apps/app/src/styles/_variables.scss
  apps/app/src/styles/organisms/_wiki.scss
  apps/app/vite.styles-prebuilt.config.ts
  packages/core/scss/_growi-official-colors.scss
  packages/core/scss/bootstrap/_init-stage-1.scss
  packages/core/scss/bootstrap/_init-stage-2.scss
  packages/core/scss/bootstrap/_init.scss
  packages/core/scss/bootstrap/_variables.scss
  packages/core/scss/bootstrap/apply.scss
  packages/core/scss/bootstrap/init.scss
  packages/core/scss/bootstrap/theming/_buttons.scss
  packages/core/scss/bootstrap/theming/_list-group.scss
  packages/core/scss/bootstrap/theming/_pagination.scss
  packages/core/scss/bootstrap/theming/_progress.scss
  packages/core/scss/bootstrap/theming/_root-dark.scss
  packages/core/scss/bootstrap/theming/_root-light.scss
  packages/core/scss/bootstrap/theming/_root.scss
  packages/core/scss/bootstrap/theming/_tables.scss
  packages/core/scss/bootstrap/theming/_variables.scss
  packages/core/scss/bootstrap/theming/apply.scss
  packages/core/scss/bootstrap/theming/utils/_color-palette.scss
  packages/core/scss/bootstrap/utilities.scss
  packages/presentation/src/components/Presentation.module.scss
  packages/preset-themes/package.json
  packages/preset-themes/src/styles/_variables.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/mono-blue.scss
  packages/preset-themes/vite.themes.config.ts
  turbo.json
Labels: flag/exclude-from-changelog

#8085 imprv: i18n "Create /Sidebar page" label
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Sidebar/CustomSidebar.tsx
Labels: type/improvement

#8092 fix: Do not work img tag if use style property 62x
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug

#8074 imprv: Save with Mod+Enter
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
  packages/editor/src/consts/global-code-mirror-editor-key.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/improvement, flag/exclude-from-changelog

#8093 fix: Do not work img tag if use style property 70x
  apps/app/src/components/ReactMarkdownComponents/LightBox.tsx
Labels: type/bug, flag/exclude-from-changelog

#8094 support: Omit HackMD (CodiMD)
  README.md
  README_JP.md
  _obsolete/packages/.eslintignore
  _obsolete/packages/hackmd/.eslintignore
  _obsolete/packages/hackmd/.gitignore
  _obsolete/packages/hackmd/package.json
  _obsolete/packages/hackmd/src/hackmd-agent.js
  _obsolete/packages/hackmd/src/hackmd-styles.ts
  _obsolete/packages/hackmd/src/index.ts
  _obsolete/packages/hackmd/src/style.scss
  _obsolete/packages/hackmd/tsconfig.json
  _obsolete/packages/hackmd/vite.config.js
  apps/app/.env.development
  apps/app/_obsolete/src/client/services/side-effects/hackmd-draft-updated.ts
  apps/app/_obsolete/src/components/PageEditorByHackmd.tsx
  apps/app/_obsolete/src/components/PageEditorByHackmd/HackmdEditor.jsx
  apps/app/_obsolete/src/interfaces/hackmd.ts
  apps/app/_obsolete/src/server/routes/hackmd.js
  apps/app/_obsolete/src/stores/hackmd.ts
  apps/app/package.json
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/page-operation.ts
  apps/app/src/client/services/side-effects/page-updated.ts
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionConfigurationModal.jsx
  apps/app/src/components/Navbar/PageEditorModeManager.jsx
  apps/app/src/components/Navbar/PageEditorModeManager.module.scss
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageStatusAlert.tsx
  apps/app/src/interfaces/page-operation.ts
  apps/app/src/interfaces/websocket.ts
  apps/app/src/models/admin/import-option-for-pages.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/interfaces/page-operation.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page-operation.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/serializers/page-serializer.js
  apps/app/src/server/models/vo/s2c-message.js
  apps/app/src/server/routes/apiv3/overwrite-params/pages.js
  apps/app/src/server/routes/index.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/page.ts
  apps/app/src/server/service/system-events/sync-page-status.ts
  apps/app/src/stores/context.tsx
  apps/app/src/stores/remote-latest-page.ts
  apps/app/src/stores/ui.tsx
  apps/app/src/styles/_editor.scss
  apps/app/tsconfig.build.server.json
  packages/core/src/interfaces/page.ts
  yarn.lock
Labels: type/support, type/breaking

#8100 fix: Marp is enabled incorrectly problem
  packages/presentation/src/services/renderer/slides.ts
Labels: type/bug

#8071 support: Use new accordion
  apps/app/src/components/Admin/Common/Accordion.jsx
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Labels: flag/exclude-from-changelog

#8105 support: Omit promster
  .github/release-drafter.yml
  apps/app/.env.development
  apps/app/package.json
  apps/app/src/server/crowi/express-init.js
  apps/app/src/server/crowi/index.js
  apps/app/src/server/middlewares/promster.ts
  apps/app/src/server/service/config-loader.ts
  yarn.lock
Labels: type/support, type/breaking

#8089 Imprv/129542 129840 show sync status on external group sync
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/ElasticsearchManagement/RebuildIndexControls.jsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/KeycloakGroupManagement.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/LdapGroupManagement.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
  apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
  apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts
  apps/app/src/features/external-user-group/server/service/ldap-user-group-sync.ts
  apps/app/src/interfaces/websocket.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/service/ldap.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/test/integration/service/external-user-group-sync.test.ts
  apps/app/test/integration/service/ldap-user-group-sync.test.ts
Labels: type/improvement

#8061 imprv: Download a markdown file using the page name as the file name
  apps/app/src/server/routes/apiv3/page.js
Labels: type/improvement

#8101 feat: Unit test implementation of serializeWorkflowSecurely
  apps/app/src/features/approval-workflow/server/models/serializers/workflow-serializer.spec.ts
  apps/app/src/features/approval-workflow/server/models/serializers/workflow-serializer.ts
  apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts
Labels: flag/exclude-from-changelog
