Repository growilabs/growi, pull requests merged in 2023-10, with the labels that each got.

#8129 support: Internationalization USER_REGISTRATION_APPROVAL_REQUEST label for v61x
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
Labels: type/support

#8130 support: Internationalization USER_REGISTRATION_APPROVAL_REQUEST label for v62x
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
Labels: type/support

#8131 support: Internationalization USER_REGISTRATION_APPROVAL_REQUEST label for v70x
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
Labels: type/support

#8138 Prepare v6.2.2
  CHANGELOG.md
  apps/app/package.json
  apps/slackbot-proxy/package.json
  package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/presentation/package.json
  packages/preset-templates/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  yarn.lock
Labels: flag/exclude-from-changelog, type/prepare-next-version

#8103 imprv: Support to attach some files in editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-text.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/replace-text.ts
  packages/editor/src/services/file-dropzone/index.ts
  packages/editor/src/services/file-dropzone/use-file-dropzone.ts
  packages/editor/src/services/index.ts
  yarn.lock
Labels: type/improvement

#8124 imprv: Support Ctrl+V file paste.
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/improvement

#8144 feat: 131878 refactoring of event handler
  apps/app/src/interfaces/ui.ts
  apps/app/src/stores/modal.tsx
Labels: type/feature

#8141 imprv: Fix heading style
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/improvement

#8143 imprv: Change font size in editor header level
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/improvement

#8145 support: Apply colors and fix layout in login page
  apps/app/src/components/CompleteUserRegistrationForm.tsx
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/InvitedForm.tsx
  apps/app/src/components/Layout/NoLoginLayout.module.scss
  apps/app/src/components/Layout/NoLoginLayout.tsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/components/PageEditor/HandsontableModal.tsx
Labels: type/support

#8157 feat: Create PageCreateButton component outline
  apps/app/src/components/Sidebar/PageCreateButton.tsx
  apps/app/src/components/Sidebar/SidebarNav.tsx
  apps/app/src/components/TreeItem/NewPageCreateButton.tsx
Labels: type/feature

#8146 imprv: Limit the file types in editor.
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/consts/accepted-upload-file-type.ts
  packages/editor/src/consts/index.ts
  packages/editor/src/services/file-dropzone/use-file-dropzone.ts
Labels: type/improvement

#8172 feat: Add Create New Page logic
  apps/app/src/server/service/page.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/stores/ui.tsx
Labels: type/feature

#8175 Imprv/133399 133400 provider dependent group sync
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/features/external-user-group/server/models/external-user-group.ts
  apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts
Labels: type/improvement

#8181 imprv: Sidebar on edit
  apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
  apps/app/src/components/Sidebar/Sidebar.module.scss
  apps/app/src/components/Sidebar/SidebarHead/ToggleCollapseButton.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.module.scss
  apps/app/src/components/Sidebar/SidebarNav/SidebarNav.module.scss
  apps/app/src/components/Sidebar/_button-styles.scss
  apps/app/src/components/Sidebar/_variables.scss
  apps/app/src/stores/ui.tsx
  apps/app/src/styles/_editor.scss
  apps/app/src/styles/_variables.scss
  packages/editor/index.html
  packages/editor/src/components/playground/Playground.tsx
Labels: type/improvement

#8182 support: Install material-symbols
  apps/app/_obsolete/src/components/Sidebar/AppearanceModeDropdown.tsx
  apps/app/package.json
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Sidebar/PageCreateButton.tsx
  apps/app/src/components/Sidebar/SidebarHead/ToggleCollapseButton.module.scss
  apps/app/src/components/Sidebar/SidebarHead/ToggleCollapseButton.tsx
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
  apps/app/src/components/Sidebar/SidebarNav/SecondaryItems.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/features/questionnaire/client/components/QuestionnaireModal.tsx
  apps/app/src/styles/font-icons.scss
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/EmojiButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TableButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TemplateButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/scss/toolbar-button.scss
  packages/editor/src/main.scss
  yarn.lock
Labels: type/support

#8173 feat: Create New Page button handler
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/Admin/Customize/CustomizePresentationSetting.tsx
  apps/app/src/components/Sidebar/PageCreateButton.tsx
  apps/app/src/interfaces/page-operation.ts
  apps/app/src/server/routes/apiv3/pages.js
Labels: type/feature

#8174 feat: Create page when click edit button if page is not found
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Navbar/hooks.tsx
Labels: type/feature

#8194 fix: Show liker counts in lsx
  packages/remark-lsx/src/client/components/LsxPageList/LsxPage.tsx
Labels: type/bug

#8188 feat: Omit `/attachemnts.add` endpoint page creating code
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/server/routes/attachment.js
Labels: type/feature

#8187 support: Refactor components under components/inappnotification
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/PageNotification/ModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/UserModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/useActionAndMsg.ts
Labels: type/support

#8195 imprv: Printing styles
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Page/CopyDropdown.jsx
  apps/app/src/components/Page/RenderTagLabels.tsx
  apps/app/src/components/Page/TagLabels.tsx
  apps/app/src/components/PageSideContents.tsx
Labels: type/improvement

#8203 imprv: Printing styles 2
  apps/app/src/components/Layout/MainPane.tsx
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/components/PageSideContents.tsx
Labels: type/improvement
