Repository growilabs/growi, pull requests merged in 2023-07, with the labels that each got.

#7843 imprv: Change from txt to ejs
  apps/app/src/server/routes/apiv3/users.js
Labels: type/improvement, flag/exclude-from-changelog

#7838 imprv: Improve release parent group button
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
Labels: type/improvement

#7849 fix: Page body is not displayed when skipSSR
  apps/app/src/pages/[[...path]].page.tsx
Labels: type/bug

#7850 imprv: Load templates from the server 2
  apps/app/package.json
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginInstallerForm.tsx
  apps/app/src/features/growi-plugin/interfaces/growi-plugin.ts
  apps/app/src/features/growi-plugin/server/consts/index.ts
  apps/app/src/features/growi-plugin/server/models/growi-plugin.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/generate-template-plugin-meta.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/generate-theme-plugin-meta.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/index.ts
  apps/app/src/features/templates/server/routes/apiv3/index.ts
  apps/app/src/features/templates/stores/template.tsx
  apps/app/src/server/crowi/express-init.js
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/stores/modal.tsx
  packages/core/src/interfaces/growi-facade.ts
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/template.ts
  packages/pluginkit/src/model/growi-plugin-package-data.ts
  packages/pluginkit/src/model/growi-plugin-validation-data.ts
  packages/pluginkit/src/model/growi-plugin-validation-error.ts
  packages/pluginkit/src/model/index.ts
  packages/pluginkit/src/v4/server/utils/common/import-package-json.spec.ts
  packages/pluginkit/src/v4/server/utils/common/import-package-json.ts
  packages/pluginkit/src/v4/server/utils/common/index.ts
  packages/pluginkit/src/v4/server/utils/common/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/src/v4/server/utils/common/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/server/utils/index.ts
  packages/pluginkit/src/v4/server/utils/package-json/import.spec.ts
  packages/pluginkit/src/v4/server/utils/package-json/import.ts
  packages/pluginkit/src/v4/server/utils/package-json/index.ts
  packages/pluginkit/src/v4/server/utils/package-json/validate.spec.ts
  packages/pluginkit/src/v4/server/utils/template.ts
  packages/pluginkit/src/v4/server/utils/template/get-markdown.ts
  packages/pluginkit/src/v4/server/utils/template/get-status.ts
  packages/pluginkit/src/v4/server/utils/template/index.ts
  packages/pluginkit/src/v4/server/utils/template/scan.ts
  packages/pluginkit/src/v4/server/utils/template/validate-all-locales.ts
  packages/pluginkit/src/v4/server/utils/template/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/utils/template.ts
  packages/pluginkit/tsconfig.json
  packages/pluginkit/vite.config.ts
  packages/preset-templates/test/index.test.ts
  yarn.lock
Labels: type/improvement

#7855 fix(lsx): Except option
  packages/remark-lsx/src/server/routes/list-pages/index.ts
Labels: type/bug

#7853 imprv: TemplateModal Dropdown closing when click and use RegExp test for isAttachmentLink
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/services/renderer/remark-plugins/attachment.ts
Labels: type/improvement, flag/exclude-from-changelog

#7859 imprv: Add type guard
  apps/app/src/services/renderer/remark-plugins/attachment.ts
Labels: flag/exclude-from-changelog

#7818 fix: SSL connection error to Elasticsearch8 using self certificate
  apps/app/src/server/service/search-delegator/elasticsearch-client.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
Labels: type/bug

#7865 fix: The official docker image missed preset-templates
  apps/app/docker/Dockerfile
  apps/app/docker/Dockerfile.dockerignore
  apps/app/package.json
  apps/app/src/components/TemplateModal/TemplateModal.module.scss
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/features/templates/server/routes/apiv3/index.ts
  apps/slackbot-proxy/package.json
  package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/pluginkit/package.json
  packages/presentation/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  yarn.lock
Labels: type/bug

#7864 support: Cypress test for TemplateModal
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
Labels: flag/exclude-from-changelog

#7868 imprv: VRT
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts
Labels: type/improvement, flag/exclude-from-changelog

#7877 fix: Revert current page mutation and add workaround for saving page
  apps/app/src/components/PageEditor.tsx
  apps/app/src/pages/[[...path]].page.tsx
Labels: type/bug

#7698 fix: Work put back page on bookmark sidebar
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/DescendantsPageList.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/SearchPage/SearchResultList.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/trash.page.tsx
Labels: type/bug

#7863 fix: Avoid unnecessary next routing
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#7880 imprv: Routing with next link
  apps/app/src/components/Admin/Common/AdminNavigation.jsx
  apps/app/src/components/Admin/Common/AdminNavigation.tsx
  apps/app/src/components/Admin/Notification/ManageGlobalNotification.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupPageList.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Layout/AdminLayout.tsx
  apps/app/src/components/PageList/PageListItemS.tsx
Labels: type/improvement

#7823 imprv: Show spinner while installing and logging-in
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/InvitedForm.tsx
  apps/app/src/components/LoginForm.tsx
Labels: type/improvement

#7761 feat: Authentication settings cannot be disabled if there will be no administrator user available to log in
  apps/app/src/components/Me/DisassociateModal.tsx
  apps/app/src/features/questionnaire/interfaces/growi-info.ts
  apps/app/src/interfaces/external-account.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/routes/apiv3/security-settings/checkSetupStrategiesHasAdmin.ts
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/stores/personal-settings.tsx
  packages/core/src/interfaces/external-account.ts
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/user.ts
Labels: type/feature

#7882 fix: Auto-scroll does not work when accessing the page when the header string is CJK
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/ReactMarkdownComponents/Header.tsx
  apps/app/src/components/Sidebar.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--use-tools.cy.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
  apps/app/test/cypress/e2e/22-sharelink/22-sharelink--access-to-sharelink.cy.ts
  apps/app/test/cypress/e2e/23-editor/23-editor--saving.cy.ts
  apps/app/test/cypress/support/assertions.ts
  apps/app/test/cypress/support/commands.ts
  apps/app/test/cypress/support/index.ts
Labels: type/bug

#7889 support: Render SearchPageBase in CSR
  apps/app/src/components/SearchPage/SearchPageBase.tsx
Labels: type/support

#7888 fix: Auto popup PageAccessoriesModal and show page history
  apps/app/src/client/services/ShowPageAccessoriesModal.tsx
  apps/app/src/components/Admin/Security/ShareLinkSetting.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/PageAccessoriesModal/PageAccessoriesModal.module.scss
  apps/app/src/components/PageAccessoriesModal/PageAccessoriesModal.tsx
  apps/app/src/components/PageAccessoriesModal/PageAttachment.tsx
  apps/app/src/components/PageAccessoriesModal/PageHistory.tsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLink.tsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkForm.tsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkList.tsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/index.ts
  apps/app/src/components/PageAccessoriesModal/hooks.tsx
  apps/app/src/components/PageAccessoriesModal/index.ts
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/stores/modal.tsx
Labels: type/bug

#7897 feat: 123475 126853 editor template plugin badge
  apps/app/src/components/TemplateModal/TemplateModal.tsx
Labels: type/feature

#7804 fix: Cancel a comment will cancel all comments
  apps/app/src/components/Comments.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageSideContents.tsx
  apps/app/src/server/service/page.ts
  packages/core/src/interfaces/page.ts
Labels: type/bug

#7898 imprv: Template name truncation
  apps/app/src/components/TemplateModal/TemplateModal.tsx
Labels: type/improvement

#7903 imprv: Show alert for trashed pages only when the page is not empty
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
Labels: type/improvement

#7845 imprv: Don't show icon and count in two steps
  apps/app/src/components/PageList/PageListItemS.module.scss
Labels: type/improvement

#7840 imprv: Replace isAdmin with usersAdminHooks
  apps/app/src/components/Navbar/PageEditorModeManager.jsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/Sidebar/SidebarNav.tsx
  apps/app/src/stores/context.tsx
Labels: type/improvement

#7907 fix: Questionnaire wikiType
  apps/app/src/features/questionnaire/server/service/questionnaire.ts
  apps/app/test/integration/service/questionnaire.test.ts
Labels: type/bug

#7900 support: Add 20-basic-features--comments.cy.ts
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/CommentControl.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--username-mention.cy.ts
Labels: flag/exclude-from-changelog

#7923 fix: Revert dynamic import.
  apps/app/src/components/SearchPage/SearchPageBase.tsx
Labels: type/bug

#7886 imprv: Improved Design for Bookmarks Sidebar
  apps/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/PageList/PageListItemS.module.scss
  apps/app/src/components/PageList/PageListItemS.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: type/improvement

#7926 fix: Improve page data mutation after renaming and deleting by GrowiContextualSubNavigation
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: type/bug

#7914 fix: Sidebar doesn't show the link to the administration panel when logged in as an Admin
  apps/app/src/stores/context.tsx
Labels: type/bug

#7925 fix: Page creation and update process
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
Labels: type/bug

#7927 imprv: Improve default behavior of skipSSR
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/models/page.ts
Labels: type/improvement

#7817 imprv: presentation style preview
  apps/app/next.config.js
  apps/app/package.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
  apps/app/src/stores/renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/components/Slides.tsx
  packages/presentation/src/index.ts
  packages/presentation/src/services/renderer/slides.ts
  yarn.lock
Labels: type/improvement

#7929 imprv: Do not use loadConfigs in skipSSR
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/utils/commons.ts
Labels: type/improvement

#7931 imprv: Import assert
  apps/app/src/server/models/page.ts
Labels: flag/exclude-from-changelog

#7932 imprv: Chage getConfig place
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
Labels: flag/exclude-from-changelog
