Repository growilabs/growi, pull requests merged in 2023-05, with the labels that each got.

#7613 feat: typescriptize and refactor to functional component LinkEditModal
  apps/app/src/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/src/components/PageEditor/LinkEditModal.jsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
Labels: feature

#7619 imprv: GFM table performance
  apps/app/package.json
  packages/micromark-extension-gfm-table/.eslintignore
  packages/micromark-extension-gfm-table/.eslintrc.cjs
  packages/micromark-extension-gfm-table/.gitignore
  packages/micromark-extension-gfm-table/.prettierignore
  packages/micromark-extension-gfm-table/.remarkignore
  packages/micromark-extension-gfm-table/dev/index.js
  packages/micromark-extension-gfm-table/dev/lib/html.js
  packages/micromark-extension-gfm-table/dev/lib/syntax.js
  packages/micromark-extension-gfm-table/package.json
  packages/micromark-extension-gfm-table/readme.md
  packages/micromark-extension-gfm-table/test/fixtures/align.html
  packages/micromark-extension-gfm-table/test/fixtures/align.md
  packages/micromark-extension-gfm-table/test/fixtures/basic.html
  packages/micromark-extension-gfm-table/test/fixtures/basic.md
  packages/micromark-extension-gfm-table/test/fixtures/containers.html
  packages/micromark-extension-gfm-table/test/fixtures/containers.md
  packages/micromark-extension-gfm-table/test/fixtures/gfm.html
  packages/micromark-extension-gfm-table/test/fixtures/gfm.md
  packages/micromark-extension-gfm-table/test/fixtures/grave.html
  packages/micromark-extension-gfm-table/test/fixtures/grave.md
  packages/micromark-extension-gfm-table/test/fixtures/indent.html
  packages/micromark-extension-gfm-table/test/fixtures/indent.md
  packages/micromark-extension-gfm-table/test/fixtures/loose.html
  packages/micromark-extension-gfm-table/test/fixtures/loose.md
  packages/micromark-extension-gfm-table/test/fixtures/some-escapes.html
  packages/micromark-extension-gfm-table/test/fixtures/some-escapes.md
  packages/micromark-extension-gfm-table/test/index.js
  packages/micromark-extension-gfm-table/tsconfig.json
  yarn.lock
Labels: improvement

#7627 imprv: Omit clobber prefix
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
  apps/app/src/services/renderer/renderer.tsx
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts
  apps/app/test/cypress/integration/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.spec.ts
Labels: improvement

#7628 imprv: GFM footnote styles
  apps/app/resource/locales/en_US/sandbox.md
  apps/app/resource/locales/ja_JP/sandbox.md
  apps/app/resource/locales/zh_CN/sandbox.md
  apps/app/src/styles/organisms/_wiki.scss
Labels: improvement

#7629 imprv: Replaced by IAttachmentHasId
  apps/app/src/components/PageAttachment.tsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageAttachment/PageAttachmentList.tsx
  apps/app/src/interfaces/attachment.ts
  apps/app/src/stores/attachment.tsx
  packages/ui/src/components/Attachment.tsx
Labels: bug, improvement

#7450 feat: Bookmarks folder
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/util/bookmark-utils.ts
  apps/app/src/client/util/input-validator.ts
  apps/app/src/components/BookmarkButtons.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderNameInput.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Bookmarks/BookmarkMoveToRootBtn.tsx
  apps/app/src/components/Bookmarks/DragAndDropWrapper.tsx
  apps/app/src/components/Common/ClosableTextInput.tsx
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/DeleteBookmarkFolderModal.tsx
  apps/app/src/components/Icons/CompressIcon.tsx
  apps/app/src/components/Icons/ExpandIcon.tsx
  apps/app/src/components/Icons/FolderIcon.tsx
  apps/app/src/components/Icons/FolderPlusIcon.tsx
  apps/app/src/components/Icons/TriangleIcon.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/SubNavButtons.tsx
  apps/app/src/components/NotFoundPage.tsx
  apps/app/src/components/PageList/BookmarkList.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/PageList/PageListItemS.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/Sidebar/Bookmarks.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/Sidebar/PageTree/Item.tsx
  apps/app/src/components/Sidebar/SidebarContents.tsx
  apps/app/src/components/Sidebar/SidebarNav.tsx
  apps/app/src/components/UsersHomePageFooter.module.scss
  apps/app/src/components/UsersHomePageFooter.tsx
  apps/app/src/interfaces/bookmark-info.ts
  apps/app/src/interfaces/ui.ts
  apps/app/src/server/models/bookmark-folder.ts
  apps/app/src/server/models/errors.ts
  apps/app/src/server/routes/apiv3/bookmark-folder.ts
  apps/app/src/server/routes/apiv3/bookmarks.js
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/stores/bookmark-folder.ts
  apps/app/src/stores/bookmark.ts
  apps/app/src/stores/modal.tsx
  apps/app/src/styles/theme/_apply-colors-dark.scss
  apps/app/src/styles/theme/_apply-colors-light.scss
  apps/app/src/styles/theme/apply-colors.scss
  apps/app/src/styles/theme/mixins/_list-group.scss
  apps/app/test/cypress/integration/20-basic-features/20-basic-features--click-page-icons.spec.ts
  packages/preset-themes/src/styles/island.scss
Labels: feature

#7623 feat: Elasticsearchv8 module
  apps/app/resource/search/mappings-es8-for-ci.json
  apps/app/resource/search/mappings-es8.json
  apps/app/src/server/service/search-delegator/elasticsearch-client.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
Labels: feature

#7637 fix: Revision schema migration for v5 to v6
  apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
  turbo.json
Labels: bug

#7640 imprv: GFM table performance 2
  apps/app/package.json
  packages/micromark-extension-gfm-table/.eslintignore
  packages/micromark-extension-gfm-table/.eslintrc.cjs
  packages/micromark-extension-gfm-table/.gitignore
  packages/micromark-extension-gfm-table/.prettierignore
  packages/micromark-extension-gfm-table/.remarkignore
  packages/micromark-extension-gfm-table/dev/index.js
  packages/micromark-extension-gfm-table/dev/lib/html.js
  packages/micromark-extension-gfm-table/dev/lib/syntax.js
  packages/micromark-extension-gfm-table/package.json
  packages/micromark-extension-gfm-table/readme.md
  packages/micromark-extension-gfm-table/test/fixtures/align.html
  packages/micromark-extension-gfm-table/test/fixtures/align.md
  packages/micromark-extension-gfm-table/test/fixtures/basic.html
  packages/micromark-extension-gfm-table/test/fixtures/basic.md
  packages/micromark-extension-gfm-table/test/fixtures/containers.html
  packages/micromark-extension-gfm-table/test/fixtures/containers.md
  packages/micromark-extension-gfm-table/test/fixtures/gfm.html
  packages/micromark-extension-gfm-table/test/fixtures/gfm.md
  packages/micromark-extension-gfm-table/test/fixtures/grave.html
  packages/micromark-extension-gfm-table/test/fixtures/grave.md
  packages/micromark-extension-gfm-table/test/fixtures/indent.html
  packages/micromark-extension-gfm-table/test/fixtures/indent.md
  packages/micromark-extension-gfm-table/test/fixtures/loose.html
  packages/micromark-extension-gfm-table/test/fixtures/loose.md
  packages/micromark-extension-gfm-table/test/fixtures/some-escapes.html
  packages/micromark-extension-gfm-table/test/fixtures/some-escapes.md
  packages/micromark-extension-gfm-table/test/index.js
  packages/micromark-extension-gfm-table/tsconfig.json
  turbo.json
  yarn.lock
Labels: improvement

#7633 imprv: Optimize fonts with next/font
  .gitattributes
  apps/app/public/static/fonts/Lato-Bold-latin-ext.woff2
  apps/app/public/static/fonts/Lato-Bold-latin.woff2
  apps/app/public/static/fonts/Lato-Regular-latin-ext.woff2
  apps/app/public/static/fonts/Lato-Regular-latin.woff2
  apps/app/public/static/fonts/PressStart2P-latin-ext.woff2
  apps/app/public/static/fonts/PressStart2P-latin.woff2
  apps/app/resource/fonts/PressStart2P-latin.woff2
  apps/app/resource/fonts/SourceHanCodeJP-Regular.woff2
  apps/app/src/components/PageEditor/CodeMirrorEditor.module.scss
  apps/app/src/components/PageEditor/DrawioModal.tsx
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
  apps/app/src/components/StaffCredit/StaffCredit.module.scss
  apps/app/src/components/StaffCredit/StaffCredit.tsx
  apps/app/src/pages/_app.page.tsx
  apps/app/src/styles/_editor.scss
  apps/app/src/styles/_fonts.scss
  apps/app/src/styles/_variables.scss
  apps/app/src/styles/atoms/_code.scss
  apps/app/src/styles/bootstrap/_variables.scss
  apps/app/src/styles/style-app.scss
  packages/preset-themes/src/styles/_variables.scss
  packages/preset-themes/src/styles/bootstrap/_variables.scss
Labels: improvement

#7643 feat: Set questionnaire server origin
  apps/app/src/server/service/config-loader.ts
Labels: feature, exclude from changelog

#7592 support: Elasticsearch8
  .devcontainer/docker-compose.yml
  apps/app/package.json
  apps/app/resource/search/mappings-es6.json
  apps/app/resource/search/mappings-es8-for-ci.json
  apps/app/resource/search/mappings-es8.json
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/search-delegator/elasticsearch-client.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  yarn.lock
Labels: support

#7645 feat: Mermaid
  apps/app/package.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/components/ReactMarkdownComponents/MermaidViewer.tsx
  apps/app/src/services/renderer/remark-plugins/mermaid.ts
  yarn.lock
Labels: feature

#7647 feat: Support Mermaid (move into the feature dierctory)
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/features/mermaid-plugin/components/MermaidViewer.tsx
  apps/app/src/features/mermaid-plugin/components/index.ts
  apps/app/src/features/mermaid-plugin/index.ts
  apps/app/src/features/mermaid-plugin/services/index.ts
  apps/app/src/features/mermaid-plugin/services/mermaid.ts
Labels: feature

#7651 feat: Create mdcont prefix processor (data-migration script)
  bin/data-migrations/v6/src/processor.js
Labels: feature, exclude from changelog

#7650 imprv: Admin user can use `reset-password` without email settings
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/resource/locales/ja_JP/admin/userResetPassword.txt
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/server/routes/apiv3/users.js
Labels: improvement

#7656 feat: Add Mermaid diagrams (/Sandbox/Diagrams)
  apps/app/resource/locales/en_US/sandbox-diagrams.md
  apps/app/resource/locales/ja_JP/sandbox-diagrams.md
  apps/app/resource/locales/zh_CN/sandbox-diagrams.md
Labels: feature, exclude from changelog

#7652 fix: The environment variable for disabling link sharing
  apps/app/src/server/service/config-loader.ts
Labels: bug

#7658 fix: Other people's bookmarks are displayed in your bookmark tree
  apps/app/src/server/models/bookmark-folder.ts
Labels: exclude from changelog

#7659 support: mongoose update
  .devcontainer/docker-compose.yml
  apps/app/package.json
  apps/app/src/server/models/activity.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/page.ts
  apps/app/src/server/util/mongoose-utils.ts
  apps/app/test/integration/service/questionnaire-cron.test.ts
  yarn.lock
Labels: support

#7663 imprv: Font size
  apps/app/src/components/Layout/SearchResultLayout.module.scss
  apps/app/src/components/PageEditor/CodeMirrorEditor.module.scss
  apps/app/src/styles/_search.scss
  apps/app/src/styles/organisms/_wiki.scss
  apps/app/src/styles/style-app.scss
Labels: improvement

#7654 feat: 116481 refactor link edit modal
  apps/app/src/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/src/components/PageEditor/LinkEditModal.jsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/modal.tsx
Labels: feature

#7638 imprv: Unify whitelist description
  apps/app/src/client/services/AdminLocalSecurityContainer.js
  apps/app/src/client/services/AdminMarkDownContainer.js
  apps/app/src/components/Admin/MarkdownSetting/WhitelistInput.jsx
  apps/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Me/BasicInfoSettings.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/login/index.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/models/config.ts
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/markdown-setting.js
  apps/app/src/server/routes/apiv3/security-setting.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/search.ts
  apps/app/src/server/service/xss.js
  apps/app/src/services/renderer/renderer.tsx
  apps/app/src/services/xss/index.js
  apps/app/src/services/xss/xssOption.ts
  apps/app/src/stores/context.tsx
Labels: improvement

#7653 imprv: Update docker-compse
  .devcontainer/docker-compose.yml
Labels: improvement, exclude from changelog

#7634 imprv: Change from EnvVarsTable.jsx to EnvVarsTable.tsx
  apps/app/src/components/Admin/AdminHome/AdminHome.jsx
  apps/app/src/components/Admin/AdminHome/EnvVarsTable.tsx
Labels: improvement, exclude from changelog

#7660 imprv: Change from DuplicatedPathsTable.jsx to DuplicatedPathsTable.tsx
  apps/app/src/components/DuplicatedPathsTable.tsx
Labels: improvement

#7670 fix: Check userId when updateBookmark
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/server/models/bookmark-folder.ts
Labels: bug

#7668 fix: Your bookmarks are displayed on other users home pages
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/Sidebar/PageTree/Item.tsx
  apps/app/src/components/UsersHomePageFooter.tsx
  apps/app/src/server/routes/apiv3/bookmark-folder.ts
  apps/app/src/stores/bookmark-folder.ts
  apps/app/src/stores/bookmark.ts
Labels: bug

#7676 fix: Remove console.log
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
Labels: bug, exclude from changelog

#7675 fix: Remove console.log
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
Labels: exclude from changelog

#7680 fix: remark-attachment-refs does not work in production
  packages/remark-attachment-refs/vite.client.config.ts
Labels: bug

#7677 imprv: Update name attribute of PageRenameModal.tsx (v6.1.x)
  apps/app/src/components/PageRenameModal.tsx
Labels: improvement

#7684 fix: Bookmark folders owned by others are accessible for manipulation
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/UsersHomePageFooter.tsx
  apps/app/src/server/models/bookmark-folder.ts
Labels: bug

#7689 support: Restrict the 'populate' method in model modules
  apps/app/package.json
  apps/app/src/server/models/.eslintrc.js
  apps/app/src/server/models/eslint-rules-dir/no-populate.js
  apps/app/src/server/models/eslint-rules-dir/test/no-populate.spec.ts
  apps/app/vitest.config.unit.ts
  package.json
  vitest.workspace.ts
  yarn.lock
Labels: support

#7686 fix: Update name attribute of PageRenameModal.tsx
  apps/app/src/components/PageRenameModal.tsx
Labels: bug

#7673 fix: User picture of bookmark not showing inside bookmark folder
  apps/app/src/client/util/bookmark-utils.ts
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/interfaces/bookmark-info.ts
  apps/app/src/server/models/bookmark-folder.ts
  apps/app/src/server/models/serializers/bookmark-serializer.js
  apps/app/src/server/routes/apiv3/bookmark-folder.ts
  apps/app/src/server/routes/apiv3/bookmarks.js
Labels: bug

#7679 imprv: Implement infinite scroll into PageTimeline
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageList/PageList.tsx
  apps/app/src/components/PageTimeline.tsx
  apps/app/src/stores/page-timeline.tsx
Labels: type/improvement

#7697 fix: Hash and search query in the relative link are omitted wrongly
  .eslintrc.js
  apps/app/src/server/models/eslint-rules-dir/test/no-populate.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.ts
  apps/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.spec.ts
  apps/app/test/unit/services/renderer/pukiwiki-like-linker.test.ts
Labels: type/bug

#7694 imprv: Refactoring migration script
  bin/data-migrations/README.md
  bin/data-migrations/src/index.js
  bin/data-migrations/src/migrations/custom.js
  bin/data-migrations/src/migrations/v60x/bracketlink.js
  bin/data-migrations/src/migrations/v60x/csv.js
  bin/data-migrations/src/migrations/v60x/drawio.js
  bin/data-migrations/src/migrations/v60x/index.js
  bin/data-migrations/src/migrations/v60x/plantuml.js
  bin/data-migrations/src/migrations/v60x/tsv.js
  bin/data-migrations/src/migrations/v61x/index.js
  bin/data-migrations/src/migrations/v61x/mdcont.js
  bin/data-migrations/v6/src/processor.js
Labels: type/improvement

#7699 imprv: Update migration script docs
  bin/data-migrations/README.md
Labels: type/improvement

#7749 support: Convert unit tests by Jest to Vitest
  .eslintrc.js
  apps/app/.eslintrc.js
  apps/app/config/migrate-mongo-config.js
  apps/app/config/migrate-mongo-config.spec.ts
  apps/app/jest.config.js
  apps/app/package.json
  apps/app/src/server/console.js
  apps/app/src/server/crowi/express-init.js
  apps/app/src/server/crowi/index.js
  apps/app/src/server/middlewares/exclude-read-only-user.spec.ts
  apps/app/src/server/middlewares/safe-redirect.spec.ts
  apps/app/src/server/middlewares/safe-redirect.ts
  apps/app/src/server/util/mongoose-utils.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.ts
  apps/app/src/utils/page-delete-config.test.ts
  apps/app/src/utils/to-array-from-csv.spec.ts
  apps/app/test/integration/.eslintrc.js
  apps/app/test/integration/global-setup.js
  apps/app/test/integration/migrations/20210913153942-migrate-slack-app-integration-schema.test.ts
  apps/app/test/integration/service/questionnaire-cron.test.ts
  apps/app/test/integration/setup.js
  apps/app/test/unit/migrate-mongo-config.test.js
  apps/app/vitest.config.ts
  package.json
  packages/core/.eslintrc.js
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/plugin/util/option-parser.spec.ts
  packages/core/src/service/localstorage-manager.js
  packages/core/src/utils/env-utils.spec.ts
  packages/core/src/utils/objectid-utils.spec.ts
  packages/core/src/utils/page-path-utils/index.spec.ts
  packages/core/src/utils/page-path-utils/is-top-page.spec.ts
  packages/core/src/utils/path-utils.spec.ts
  packages/core/test/service/localstorage-manager.test.js
  packages/core/test/util/env-utils.test.js
  packages/core/vitest.config.ts
  vitest.workspace.ts
  yarn.lock
Labels: type/support

#7752 support: Refactor ConfigManager
  .eslintrc.js
  apps/app/src/server/crowi/index.js
  apps/app/src/server/service/config-manager.spec.ts
  apps/app/src/server/service/config-manager.ts
  apps/app/src/server/service/customize.ts
  apps/app/src/server/service/file-uploader-switch.ts
  apps/app/src/server/service/file-uploader/aws.ts
  apps/app/src/server/service/file-uploader/file-uploader.ts
  apps/app/src/server/service/file-uploader/gcs.js
  apps/app/src/server/service/file-uploader/gridfs.ts
  apps/app/src/server/service/file-uploader/local.js
  apps/app/src/server/service/file-uploader/none.js
  apps/app/src/server/service/file-uploader/uploader.js
  apps/app/src/server/service/g2g-transfer.ts
  apps/app/src/server/service/installer.ts
  apps/app/src/server/service/slack-integration.ts
  apps/app/test/integration/service/config-manager.test.js
  package.json
  yarn.lock
Labels: type/support

#7751 support: typescriptize SlackLegacyUtil
  apps/app/src/server/service/slack-integration.ts
  apps/app/src/server/util/slack-legacy.js
  apps/app/src/server/util/slack-legacy.ts
  apps/app/test/integration/utils/slack-legacy.test.js
Labels: type/support

#7702 imprv: Make migration script type safe
  bin/data-migrations/src/index.js
  bin/data-migrations/src/migrations/custom.js
  bin/data-migrations/src/migrations/v60x/bracketlink.js
  bin/data-migrations/src/migrations/v60x/csv.js
  bin/data-migrations/src/migrations/v60x/drawio.js
  bin/data-migrations/src/migrations/v60x/plantuml.js
  bin/data-migrations/src/migrations/v60x/tsv.js
  bin/data-migrations/src/migrations/v61x/mdcont.js
  bin/data-migrations/src/types.d.ts
Labels: type/improvement

#7753 feat: 123275 123281 ldap group sync config
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/Security/LdapSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  apps/app/src/components/Admin/UserGroup/ExternalGroup/ExternalGroupManagement.tsx
  apps/app/src/components/Admin/UserGroup/ExternalGroup/LDAPGroupSyncSettingsForm.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/interfaces/external-user-group.ts
  apps/app/src/server/routes/apiv3/external-user-group.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/stores/external-user-group.ts
Labels: feature

#7754 support: Refactor AclService
  apps/app/.env.test
  apps/app/package.json
  apps/app/src/server/crowi/index.js
  apps/app/src/server/service/acl.integ.test.ts
  apps/app/src/server/service/acl.integ.ts
  apps/app/src/server/service/acl.ts
  apps/app/test-with-vite/.eslintrc.js
  apps/app/test-with-vite/setup/mongoms.ts
  apps/app/test-with-vite/tsconfig.json
  apps/app/test/integration/models/config.test.js
  apps/app/tsconfig.json
  apps/app/vitest.config.integ.ts
  apps/app/vitest.config.ts
  packages/core/vitest.config.ts
  packages/slack/vitest.config.ts
  yarn.lock
Labels: type/support

#7762 imprv: Update preset templates
  apps/app/package.json
  apps/app/src/components/TemplateModal/index.tsx
  apps/app/src/components/TemplateModal/use-formatter.spec.tsx
  apps/app/src/components/TemplateModal/use-formatter.tsx
  apps/app/src/stores/modal.tsx
  apps/app/src/stores/template.tsx
  yarn.lock
Labels: type/improvement

#7667 fix: Bookmarks status not updated on search result
  apps/app/src/components/BookmarkButtons.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/interfaces/bookmark-info.ts
  apps/app/src/server/routes/apiv3/bookmarks.js
  apps/app/src/stores/bookmark.ts
Labels: type/bug

#7764 imprv: Insert template
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/components/TemplateModal/index.tsx
Labels: type/improvement

#7750 fix: Unable to perform bookmark operations from bookmark item control
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
Labels: type/bug
