Repository growilabs/growi, pull requests merged in 2024-05, with the labels that each got.

#8780 support: Make AwsFileUploader type safe
  apps/app/src/server/service/file-uploader/aws.ts
Labels: type/support

#8767 fix: An error occurred during user activation via email
  apps/app/src/components/CompleteUserRegistrationForm.tsx
  apps/app/src/pages/user-activation.page.tsx
  apps/app/src/server/routes/user-activation.ts
Labels: type/bug

#8777 imprv: Rename on blur
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderNameInput.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Common/ClosableTextInput.tsx
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/Sidebar/PageTreeItem/Ellipsis.tsx
  apps/app/src/components/TreeItem/NewPageInput/NewPageInput.tsx
Labels: type/improvement

#8600 feat: Apply locale to defualt page title
  apps/app/config/i18next.config.js
  apps/app/config/next-i18next.config.js
  apps/app/package.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/util/locale-utils.ts
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/service/i18next.ts
  yarn.lock
Labels: type/feature

#8770 Feat/78037 144924 download bulk export from in app notification be
  apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
  apps/app/src/features/page-bulk-export/server/models/page-bulk-export-job.ts
  apps/app/src/features/page-bulk-export/server/models/page-bulk-export-result.ts
  apps/app/src/features/page-bulk-export/server/routes/apiv3/page-bulk-export.ts
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
  apps/app/src/interfaces/activity.ts
  apps/app/src/server/interfaces/attachment.ts
  apps/app/src/server/models/activity.ts
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/models/subscription.ts
  apps/app/src/server/service/attachment.js
  apps/app/src/server/service/file-uploader/aws/index.ts
  apps/app/src/server/service/file-uploader/aws/multipart-upload.ts
  apps/app/src/server/service/file-uploader/azure.ts
  apps/app/src/server/service/file-uploader/gcs.ts
  apps/app/src/server/service/file-uploader/local.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/in-app-notification/in-app-notification-utils.ts
  apps/app/src/server/service/pre-notify.ts
  packages/core/src/interfaces/attachment.ts
Labels: type/feature

#8787 fix: Dynamic import the locale file
  apps/app/src/server/service/i18next.ts
Labels: type/bug, flag/exclude-from-changelog

#8772 fix: Auto-scroll to the active page in the page tree
  apps/app/src/components/ItemsTree/ItemsTree.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/components/Sidebar/Sidebar.tsx
  apps/app/src/components/TreeItem/ItemNode.ts
  apps/app/src/stores/ui.tsx
Labels: type/bug

#8782 imprv: behavior of dropdown toggle in 'Recent Changes' sidebar
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
Labels: type/improvement

#8709 feat: Show Yjs status indicator in SubNavigation
  apps/app/src/client/services/side-effects/yjs.ts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/interfaces/websocket.ts
  apps/app/src/interfaces/yjs.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/socket-io.js
  apps/app/src/server/service/yjs-connection-manager.ts
  apps/app/src/stores/page.tsx
  apps/app/src/stores/websocket.tsx
  apps/app/src/stores/yjs.ts
Labels: type/feature

#8774 feat: Add a button to open PageCreateModal in the new page creation lead
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
Labels: type/feature

#8800 imprv: Add indexes for performance
  apps/app/src/server/models/activity.ts
  apps/app/src/server/models/in-app-notification.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/user.js
Labels: type/improvement

#8725 fix: Drawio not available with GROWI slides
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/client/services/renderer/slide-viewer-renderer.tsx
  apps/app/src/components/Admin/Customize/CustomizePresentationSetting.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/Page/RevisionRenderer.tsx
  apps/app/src/components/Page/SlideRenderer.tsx
  apps/app/src/components/PageEditor/Preview.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/Presentation/Presentation.tsx
  apps/app/src/components/Presentation/Slides.tsx
  apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/stores/slide-viewer-renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/client/components/GrowiSlides.tsx
  packages/presentation/src/client/components/MarpSlides.tsx
  packages/presentation/src/client/components/Presentation.global.scss
  packages/presentation/src/client/components/Presentation.module.scss
  packages/presentation/src/client/components/Presentation.tsx
  packages/presentation/src/client/components/RichSlideSection.tsx
  packages/presentation/src/client/components/Slides.module.scss
  packages/presentation/src/client/components/Slides.tsx
  packages/presentation/src/client/consts/index.ts
  packages/presentation/src/client/index.ts
  packages/presentation/src/client/services/growi-marpit.ts
  packages/presentation/src/client/services/renderer/extract-sections.ts
  packages/presentation/src/services/index.ts
  packages/presentation/src/services/parse-slide-frontmatter.ts
  packages/presentation/src/services/renderer/slides.ts
  packages/presentation/src/services/use-slides-by-frontmatter.ts
  packages/presentation/vite.config.ts
  yarn.lock
Labels: type/bug

#8801 imprv: Behavior when creating first user fails
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/server/routes/apiv3/installer.ts
Labels: type/improvement

#8805 support: Modify env var for S3 Object-ACL
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/file-uploader/aws.ts
Labels: type/support

#8806 fix: Admin layout
  apps/app/src/components/Admin/App/AppSetting.jsx
  apps/app/src/components/Admin/App/FileUploadSetting.tsx
  apps/app/src/components/Admin/App/MailSetting.tsx
  apps/app/src/components/Admin/App/MaintenanceMode.tsx
  apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
  apps/app/src/components/Admin/App/SiteUrlSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeThemeOptions.tsx
  apps/app/src/components/Admin/Customize/CustomizeTitle.tsx
  apps/app/src/components/Admin/Customize/PagingSizeUncontrolledDropdown.jsx
  apps/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.tsx
  apps/app/src/components/Admin/ElasticsearchManagement/RebuildIndexControls.jsx
  apps/app/src/components/Admin/ElasticsearchManagement/StatusTable.jsx
  apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/components/Admin/ExportArchiveDataPage.tsx
  apps/app/src/components/Admin/FullTextSearchManagement.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
  apps/app/src/components/Admin/ImportData/GrowiArchiveSection.jsx
  apps/app/src/components/Admin/ImportData/ImportDataPageContents.jsx
  apps/app/src/components/Admin/LegacySlackIntegration/SlackConfiguration.jsx
  apps/app/src/components/Admin/MarkdownSetting/MarkDownSettingContents.tsx
  apps/app/src/components/Admin/MarkdownSetting/WhitelistInput.jsx
  apps/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  apps/app/src/components/Admin/Notification/GlobalNotification.jsx
  apps/app/src/components/Admin/Notification/NotificationSetting.jsx
  apps/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LdapSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SecurityManagementContents.jsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Admin/Security/ShareLinkSetting.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/Layout/Admin.module.scss
  apps/app/src/components/Layout/AdminLayout.tsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkList.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/KeycloakGroupSyncSettingsForm.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/LdapGroupSyncSettingsForm.tsx
  apps/app/src/features/questionnaire/client/stores/questionnaire.tsx
Labels: type/bug

#8809 fix: Display share page date
  apps/app/src/components/ShareLinkPageView.tsx
Labels: type/bug

#8792 Feat/78037 135787 download bulk export from in app notification fe
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/ModelNotification/ModelNotification.tsx
  apps/app/src/components/InAppNotification/ModelNotification/PageBulkExportJobModelNotification.tsx
  apps/app/src/components/InAppNotification/ModelNotification/PageModelNotification.tsx
  apps/app/src/components/InAppNotification/ModelNotification/UserModelNotification.tsx
  apps/app/src/components/InAppNotification/ModelNotification/index.tsx
  apps/app/src/components/InAppNotification/ModelNotification/useActionAndMsg.ts
  apps/app/src/components/InAppNotification/PageNotification/index.tsx
  apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
  apps/app/src/interfaces/in-app-notification.ts
  apps/app/src/models/serializers/in-app-notification-snapshot/page-bulk-export-job.ts
  apps/app/src/server/models/in-app-notification.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/in-app-notification/in-app-notification-utils.ts
Labels: type/feature

#8808 imprv: Hide the page creation button for users without editing permissions
  apps/app/src/components/Sidebar/SidebarNav/SidebarNav.tsx
Labels: type/improvement

#8817 fix: BookmarkItem occures an error when the related page has been deleted
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/server/service/page/index.ts
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/v5.public-page.test.ts
Labels: type/bug

#8796 imprv: Behavior of dropdown toggle for WIP in 'Page Tree' sidebar
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
Labels: type/improvement

#8818 fix: BookmarkItem occures an error when the related page has been deleted 2
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
  apps/app/src/interfaces/bookmark-info.ts
  apps/app/src/stores/bookmark.ts
Labels: type/bug

#8823 fix: S3 configurations are considered invalid wrongly
  apps/app/src/server/service/file-uploader/aws.ts
Labels: type/bug

#8773 fix: Do not insert initial value when input is empty in editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/server/service/yjs-connection-manager.ts
Labels: type/bug, type/feature

#8831 imprv: toastr location
  apps/app/src/components/Layout/BasicLayout.module.scss
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.module.scss
  apps/app/src/components/PageEditor/EditorNavbarBottom.module.scss
  apps/app/src/components/Sidebar/SidebarHead/ToggleCollapseButton.module.scss
  apps/app/src/styles/_editor.scss
  apps/app/src/styles/mixins/_editing.scss
Labels: type/improvement

#8839 support: Upgrade yjs packages
  apps/app/package.json
  packages/editor/package.json
  yarn.lock
Labels: type/support

#8840 support: Apply changesets
  .changeset/config.json
  package.json
  packages/pluginkit/package.json
  yarn.lock
Labels: type/support

#8832 imprv: Behavior of dropdown toggle in groundglassbar
  apps/app/src/components/PageControls/PageControls.tsx
Labels: type/improvement

#8830 fix: Table icon is not displayed when hovering over the table
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.module.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/table-util/use-show-table-icon.ts
  packages/editor/svg/table.svg
Labels: type/bug

#8850 fix: [v6] An error occurred during user activation via email
  apps/app/src/components/CompleteUserRegistrationForm.tsx
  apps/app/src/pages/user-activation.page.tsx
  apps/app/src/server/routes/user-activation.ts
Labels: type/bug

#8827 fix: Drawio not available with GROWI slides in v6
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/client/services/renderer/slide-viewer-renderer.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/Page/RevisionRenderer.tsx
  apps/app/src/components/Page/SlideRenderer.tsx
  apps/app/src/components/PageEditor/Preview.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/Presentation/Presentation.tsx
  apps/app/src/components/Presentation/Slides.tsx
  apps/app/src/components/ReactMarkdownComponents/SlideViewer.tsx
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.integ.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/stores/slide-viewer-renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/client/components/GrowiSlides.tsx
  packages/presentation/src/client/components/MarpSlides.tsx
  packages/presentation/src/client/components/Presentation.global.scss
  packages/presentation/src/client/components/Presentation.module.scss
  packages/presentation/src/client/components/Presentation.tsx
  packages/presentation/src/client/components/RichSlideSection.tsx
  packages/presentation/src/client/components/Slides.module.scss
  packages/presentation/src/client/components/Slides.tsx
  packages/presentation/src/client/consts/index.ts
  packages/presentation/src/client/index.ts
  packages/presentation/src/client/services/growi-marpit.ts
  packages/presentation/src/client/services/renderer/extract-sections.ts
  packages/presentation/src/services/index.ts
  packages/presentation/src/services/parse-slide-frontmatter.ts
  packages/presentation/src/services/renderer/slides.ts
  packages/presentation/src/services/use-slide-by-frontmatter.ts
  packages/presentation/vite.config.ts
  yarn.lock
Labels: type/bug

#8851 imprv: Support tag in github-url.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
Labels: type/improvement

#8841 fix: Slack notification not sent on page update
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/user-notification/index.ts
  apps/app/src/server/util/slack.js
Labels: type/bug

#8828 feat: Design coding of search result page
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/SearchPage.module.scss
  apps/app/src/components/SearchPage.tsx
  apps/app/src/components/SearchPage/OperateAllControl.tsx
  apps/app/src/components/SearchPage/SearchControl.tsx
  apps/app/src/components/SearchPage/SearchModalTriggerinput.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
Labels: type/feature

#8812 feat: Select unrelated group inheritance on child page create
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/create-page/index.ts
  apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
  apps/app/src/client/services/create-page/use-create-page.tsx
  apps/app/src/client/services/create-page/use-create-template-page.ts
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/GrantedGroupsInheritanceSelectModal.tsx
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageCreateModal.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebarNotFound.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-new-page.ts
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/interfaces/page-grant.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/stores/modal.tsx
  apps/app/src/stores/page.tsx
  apps/app/test/integration/service/v5.non-public-page.test.ts
Labels: type/feature

#8852 fix: Brackets appearance when Nord editor theme
  packages/editor/src/services-internal/editor-theme/nord.ts
Labels: type/bug

#8854 support: Add test for pluginkit
  .changeset/blue-tips-joke.md
  packages/pluginkit/src/v4/server/utils/common/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/server/utils/template/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/test/fixtures/example-package/invalid-template1/index.js
  packages/pluginkit/test/fixtures/example-package/invalid-template1/package.json
  packages/pluginkit/test/fixtures/example-package/theme1/index.js
  packages/pluginkit/test/fixtures/example-package/theme1/package.json
  packages/preset-themes/package.json
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/interfaces/growi-theme-metadata.ts
Labels: flag/exclude-from-changelog

#8856 support: Add theme plugin validator
  .changeset/nine-keys-hide.md
  packages/core/src/interfaces/growi-theme-metadata.ts
  packages/pluginkit/src/model/growi-plugin-validation-data.ts
  packages/pluginkit/src/v4/server/utils/theme/index.ts
  packages/pluginkit/src/v4/server/utils/theme/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/src/v4/server/utils/theme/validate-growi-plugin-directive.ts
  packages/pluginkit/test/fixtures/example-package/invalid-theme1/index.js
  packages/pluginkit/test/fixtures/example-package/invalid-theme1/package.json
  packages/pluginkit/test/fixtures/example-package/invalid-theme2/index.js
  packages/pluginkit/test/fixtures/example-package/invalid-theme2/package.json
Labels: flag/exclude-from-changelog

#8865 fix: Supress warning of checkbox
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
Labels: type/bug

#8802 imprv: Display selected tree item in page select modal as active
  apps/app/src/components/PageSelectModal/PageSelectModal.tsx
  apps/app/src/components/PageSelectModal/TreeItemForModal.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/TreeItemLayout.tsx
  apps/app/src/interfaces/page.ts
  apps/app/src/server/service/page/index.ts
Labels: type/improvement
