Repository growilabs/growi, pull requests merged in 2024-10, with the labels that each got.

#9183 imprv: Documentation URL for g2gtransfer
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
Labels: type/improvement

#9127 imprv: Add GitHub Markdown alerts
  apps/app/package.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/features/callout/components/CalloutViewer.module.scss
  apps/app/src/features/callout/components/CalloutViewer.tsx
  apps/app/src/features/callout/components/index.ts
  apps/app/src/features/callout/index.ts
  apps/app/src/features/callout/services/callout.ts
  apps/app/src/features/callout/services/consts.ts
  apps/app/src/features/callout/services/index.ts
  apps/app/src/features/mermaid/components/MermaidViewer.tsx
  yarn.lock
Labels: type/improvement

#9096 fix: Ensure text-only paste for mixed content from various sources
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/PageEditor/OptionsSelector.tsx
  packages/editor/src/client/components-internal/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/client/components-internal/playground/Playground.tsx
  packages/editor/src/client/components-internal/playground/PlaygroundController.tsx
  packages/editor/src/client/services-internal/file-dropzone/use-file-dropzone/use-file-dropzone.ts
  packages/editor/src/client/stores/use-editor-settings.ts
  packages/editor/src/consts/editor-settings.ts
  packages/editor/src/consts/index.ts
  packages/editor/src/consts/paste-mode.ts
  yarn.lock
Labels: type/bug

#9179 fix: Forgot password API - reject requests with invalid email format
  apps/app/src/server/middlewares/apiv3-form-validator.ts
  apps/app/src/server/routes/apiv3/forgot-password.js
  apps/app/src/server/routes/forgot-password.ts
Labels: type/bug

#9092 imprv: Update Recent Changes when a page is created, updated, or deleted
  apps/app/src/client/components/DescendantsPageList.tsx
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/client/components/PageEditor/PageEditor.tsx
  apps/app/src/client/components/PageEditor/page-path-rename-utils.ts
  apps/app/src/client/components/SearchPage/SearchPageBase.tsx
  apps/app/src/client/components/SearchPage/SearchResultContent.tsx
  apps/app/src/client/components/SearchPage/SearchResultList.tsx
  apps/app/src/client/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/client/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/components/PageView/PageAlerts/TrashPageAlert.tsx
  apps/app/src/components/PageView/PageAlerts/WipPageAlert.tsx
  apps/app/src/stores/page-listing.tsx
Labels: type/improvement

#9173 feat: Separate markdown into headings and paragraphs
  .changeset/config.json
  apps/app/next.config.js
  apps/app/package.json
  packages/markdown-splitter/.eslintignore
  packages/markdown-splitter/.eslintrc.cjs
  packages/markdown-splitter/.gitignore
  packages/markdown-splitter/package.json
  packages/markdown-splitter/src/index.ts
  packages/markdown-splitter/src/services/markdown-splitter.ts
  packages/markdown-splitter/test/index.spec.ts
  packages/markdown-splitter/tsconfig.json
  packages/markdown-splitter/vite.config.ts
  packages/markdown-splitter/vitest.config.ts
  yarn.lock
Labels: type/feature

#9125 fix: Make it impossible to overwrite grants on descendant pages when 'anyone with the link' is selected.
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/NotAvailable.tsx
  apps/app/src/client/components/SavePageControls.tsx
  apps/app/src/server/service/page/index.ts
Labels: type/bug

#9099 fix: Display revisions only if they are not corrupted
  apps/app/src/server/routes/apiv3/revisions.js
Labels: type/bug

#9218 support: Upgrade codemirror and yjs packages
  packages/editor/package.json
  yarn.lock
Labels: type/support

#9220 support: Improve typings for PageService
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
Labels: type/support

#9226 support: Evaluate whether env vars are secret or not by the `isSecret` property
  apps/app/src/server/service/config-loader.ts
Labels: type/support, type/improvement

#9228 support: Hide env vars for OpenAI
  apps/app/src/server/middlewares/certify-ai-service.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/openai/assistant/assistant.ts
  apps/app/src/server/service/openai/client-delegator/openai-client-delegator.ts
  apps/app/src/server/service/openai/client.ts
  apps/app/src/server/service/openai/embeddings.ts
  apps/app/src/server/service/openai/openai.ts
Labels: type/support

#9232 fix: Set an unknown label when the user is not found
  apps/app/src/server/routes/ogp.ts
Labels: type/bug

#9217 feat: Generate vector store inside GROWI
  apps/app/src/features/openai/server/models/vector-store.ts
  apps/app/src/server/routes/apiv3/openai/thread.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/openai/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/server/service/openai/client-delegator/interfaces.ts
  apps/app/src/server/service/openai/client-delegator/openai-client-delegator.ts
  apps/app/src/server/service/openai/openai.ts
Labels: type/feature

#9184 imprv: 122312 154280 write the component test
  apps/app/src/client/components/NotAvailableForReadOnlyUser.spec.tsx
Labels: type/improvement, flag/exclude-from-changelog

#9145 fix: Mermaid diagrams fail to render in search results with 'syntax error in text'"
  apps/app/package.json
  apps/app/src/features/mermaid/components/MermaidViewer.tsx
  apps/app/src/features/mermaid/services/mermaid.ts
  yarn.lock
Labels: type/bug, flag/exclude-from-changelog

#9255 fix: Cannot use lsx and some GitHub Alerts
  apps/app/package.json
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/features/callout/components/CalloutViewer.tsx
  apps/app/src/features/callout/services/callout.ts
  apps/app/src/features/callout/services/consts.ts
  yarn.lock
Labels: type/bug, flag/exclude-from-changelog

#9252 imprv: Error handling for when a thread cannot be created
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
  apps/app/src/features/openai/interfaces/message-error.ts
  apps/app/src/features/openai/server/routes/message.ts
Labels: type/improvement, flag/exclude-from-changelog

#9258 fix: Global search button is not clickable
  apps/app/src/client/components/Sidebar/AppTitle/AppTitle.module.scss
Labels: type/bug, flag/exclude-from-changelog

#9239 feat: brush up assistant instruction
  apps/app/src/server/service/config-loader.ts
Labels: type/feature, flag/exclude-from-changelog

#9267 fix: Collaborative editing occurs unstable behavior
  packages/editor/package.json
  yarn.lock
Labels: type/bug

#9270 fix: Edit button appear for the side of header
  apps/app/src/client/components/ReactMarkdownComponents/Header.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/yjs.ts
Labels: type/bug

#9251 feat: Split markdown into specified tokens
  packages/markdown-splitter/package.json
  packages/markdown-splitter/src/index.ts
  packages/markdown-splitter/src/services/markdown-splitter.ts
  packages/markdown-splitter/src/services/markdown-token-splitter.ts
  packages/markdown-splitter/test/index.spec.ts
  yarn.lock
Labels: type/feature, flag/exclude-from-changelog

#9256 feat: Automatic thread deletion using node-cron
  apps/app/package.json
  apps/app/src/features/openai/server/models/thread-relation.ts
  apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
  apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/services/thread-deletion-cron.ts
  apps/app/src/server/crowi/index.js
  yarn.lock
Labels: type/feature

#9254 feat: Implement OpenAI thread-relation model
  apps/app/package.json
  apps/app/src/features/openai/server/models/thread-relation.ts
  apps/app/src/features/openai/server/routes/thread.ts
  apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
  apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
  apps/app/src/features/openai/server/services/openai-api-error-handler.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/services/thread-deletion-cron.ts
  apps/app/src/server/crowi/index.js
  yarn.lock
Labels: type/feature, flag/exclude-from-changelog

#9288 fix: Evaluating inline porps
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
  apps/app/src/services/renderer/remark-plugins/codeblock.ts
Labels: type/bug, flag/exclude-from-changelog

#9295 fix: Replace the word ROM
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/components/Admin/Security/SecuritySetting.jsx
Labels: type/bug

#9299 support: Omit docs route
  apps/app/src/server/routes/apiv3/docs.js
  apps/app/src/server/routes/index.js
Labels: type/support

#9296 fix: Couln't show old revision
  apps/app/src/stores/page.tsx
Labels: type/bug

#9302 support: Maintenance API docs generation
  apps/app/bin/swagger-jsdoc/definition-apiv1.js
  apps/app/bin/swagger-jsdoc/definition-apiv3.js
  apps/app/bin/swagger-jsdoc/generate-spec-apiv1.sh
  apps/app/bin/swagger-jsdoc/generate-spec-apiv3.sh
  apps/app/config/swagger-definition.js
  apps/app/package.json
  apps/app/src/server/models/openapi/error-v3.ts
  apps/app/src/server/models/openapi/page.ts
  apps/app/src/server/models/openapi/revision.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/routes/apiv3/revisions.js
  apps/app/src/server/routes/page.js
  yarn.lock
Labels: type/support

#9294 imprv: Error handling for when monthly usage limit is exceeded (2)
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
  apps/app/src/features/openai/interfaces/message-error.ts
  apps/app/src/features/openai/server/routes/message.ts
  apps/app/src/features/openai/server/services/getStreamErrorCode.ts
Labels: type/improvement

#9284 imprv: Add remark-directive
  apps/app/package.json
  apps/app/src/features/callout/services/callout.ts
  apps/app/src/services/renderer/renderer.tsx
  packages/remark-growi-directive/src/mdast-util-growi-directive/lib/index.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/directive-leaf.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/directive-text.js
  packages/remark-growi-directive/src/micromark-extension-growi-directive/lib/html.js
  yarn.lock
Labels: type/bug

#9311 support: JSDoc for OpenAPI document
  apps/app/bin/swagger-jsdoc/definition-apiv3.js
  apps/app/src/server/routes/apiv3/admin-home.js
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/bookmarks.js
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/routes/apiv3/export.js
  apps/app/src/server/routes/apiv3/healthcheck.ts
  apps/app/src/server/routes/apiv3/import.js
  apps/app/src/server/routes/apiv3/markdown-setting.js
  apps/app/src/server/routes/apiv3/mongo.js
  apps/app/src/server/routes/apiv3/notification-setting.js
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/routes/apiv3/personal-setting.js
  apps/app/src/server/routes/apiv3/revisions.js
  apps/app/src/server/routes/apiv3/search.js
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/apiv3/share-links.js
  apps/app/src/server/routes/apiv3/slack-integration-legacy-settings.js
  apps/app/src/server/routes/apiv3/slack-integration-settings.js
  apps/app/src/server/routes/apiv3/statistics.js
  apps/app/src/server/routes/apiv3/user-group-relation.js
  apps/app/src/server/routes/apiv3/user-group.js
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/routes/search.ts
Labels: type/support, type/improvement

#9297 feat: Create vector store file for each divided chunk
  .changeset/config.json
  apps/app/next.config.js
  apps/app/package.json
  apps/app/src/features/openai/server/services/markdown-splitter/markdown-splitter.spec.ts
  apps/app/src/features/openai/server/services/markdown-splitter/markdown-splitter.ts
  apps/app/src/features/openai/server/services/markdown-splitter/markdown-token-splitter.spec.ts
  apps/app/src/features/openai/server/services/markdown-splitter/markdown-token-splitter.ts
  apps/app/src/features/openai/server/services/openai.ts
  packages/markdown-splitter/.eslintignore
  packages/markdown-splitter/.eslintrc.cjs
  packages/markdown-splitter/.gitignore
  packages/markdown-splitter/package.json
  packages/markdown-splitter/src/index.ts
  packages/markdown-splitter/tsconfig.json
  packages/markdown-splitter/vite.config.ts
  packages/markdown-splitter/vitest.config.ts
  pnpm-lock.yaml
Labels: type/feature

#9318 feat: Make it clear whether the uploaded file is saved in the vector store
  apps/app/src/features/openai/server/models/vector-store-file-relation.ts
  apps/app/src/features/openai/server/services/openai.ts
Labels: type/feature, flag/exclude-from-changelog

#9317 fix: Unsupported emoji in Editor
  apps/app/package.json
  apps/app/resource/locales/en_US/sandbox-diagrams.md
  apps/app/resource/locales/en_US/sandbox-math.md
  apps/app/resource/locales/fr_FR/sandbox-diagrams.md
  apps/app/resource/locales/fr_FR/sandbox-math.md
  apps/app/resource/locales/ja_JP/sandbox-diagrams.md
  apps/app/resource/locales/zh_CN/sandbox-diagrams.md
  apps/app/resource/locales/zh_CN/sandbox-math.md
  apps/app/src/services/renderer/remark-plugins/emoji.ts
  apps/app/src/services/renderer/renderer.tsx
  pnpm-lock.yaml
Labels: type/bug, flag/exclude-from-changelog

#9323 support: Use `pnpm deploy` instead of `turbo prune`
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release-subpackages.yml
  .github/workflows/release.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
  .gitignore
  apps/app/docker/Dockerfile
  apps/app/package.json
  apps/slackbot-proxy/docker/Dockerfile
  apps/slackbot-proxy/package.json
  package.json
  pnpm-lock.yaml
Labels: type/support

#9325 support: Pull LFS files with turbo
  .devcontainer/postCreateCommand.sh
  .github/workflows/reusable-app-prod.yml
  apps/app/package.json
  apps/app/turbo.json
Labels: type/support

#9329 support: Fix to run playwright job
  .github/workflows/reusable-app-prod.yml
Labels: flag/exclude-from-changelog

#9330 imprv: Sandbox
  apps/app/resource/locales/en_US/sandbox.md
  apps/app/resource/locales/fr_FR/sandbox.md
  apps/app/resource/locales/ja_JP/sandbox.md
  apps/app/resource/locales/zh_CN/sandbox.md
Labels: type/improvement

#9332 imprv: Update default value for S3_OBJECT_ACL
  apps/app/src/server/service/config-loader.ts
Labels: type/improvement, type/breaking

#9334 support: Omit MongoDB 4.x compatible code
  apps/app/docker/README.md
  apps/app/src/server/service/search-delegator/aggregate-to-index.ts
Labels: type/support

#9326 feat: Delete obsolete VectorStoreFile when rebuilding VectorStore
  apps/app/src/features/openai/server/models/vector-store-file-relation.ts
  apps/app/src/features/openai/server/models/vector-store.ts
  apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
  apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/page/index.ts
Labels: type/feature, flag/exclude-from-changelog

#9336 feat: Create one VectorStoreFile per page
  apps/app/src/features/openai/server/services/openai.ts
Labels: flag/exclude-from-changelog

#9341 feat: Execute cron jobs at random times for each app
  apps/app/src/features/openai/server/services/thread-deletion-cron.ts
  apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts
Labels: type/feature, flag/exclude-from-changelog
