Repository growilabs/growi, pull requests merged in 2024-01, with the labels that each got.

#8362 support: New FireRed
  packages/preset-themes/src/styles/fire-red.scss
  packages/preset-themes/vite.themes.config.ts
Labels: type/support, flag/exclude-from-changelog

#8297 feat: Uniform behavior when creating pages from create new page button
  apps/app/src/client/services/use-on-template-button-clicked.ts
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
Labels: type/feature

#8364 support: New JadeGreen
  packages/preset-themes/src/styles/jade-green.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8365 feat: refactor PageSideContents tag design
  apps/app/src/components/PageTags/PageTags.tsx
  apps/app/src/components/PageTags/TagLabels.module.scss
Labels: type/feature

#8366 fix: Move react-stickynode to dependencies
  apps/app/package.json
Labels: flag/exclude-from-changelog

#8356 feat: Build GROWI custom icons
  apps/app/package.json
  apps/app/src/components/FontFamily/GlobalFonts.tsx
  apps/app/src/components/FontFamily/use-growi-custom-icons.tsx
  apps/app/src/components/Me/SidebarCollapsedIcon.jsx
  apps/app/src/components/Me/SidebarDockIcon.jsx
  apps/app/src/components/Me/UISettings.module.scss
  apps/app/src/components/Me/UISettings.tsx
  apps/app/src/server/service/mail.ts
  apps/app/src/styles/_fonts.scss
  packages/custom-icons/.gitignore
  packages/custom-icons/.svgtofontrc
  packages/custom-icons/package.json
  packages/custom-icons/svg/sidebar-collapsed.svg
  packages/custom-icons/svg/sidebar-dock.svg
  packages/custom-icons/turbo.json
  yarn.lock
Labels: type/feature

#8370 feat: 137722 refactor side contents design
  apps/app/src/components/PageTags/PageTags.tsx
  apps/app/src/components/PageTags/TagLabels.module.scss
Labels: type/feature, flag/exclude-from-changelog

#8367 support: New Future
  packages/preset-themes/src/styles/future.scss
  packages/preset-themes/vite.themes.config.ts
Labels: type/support, flag/exclude-from-changelog

#8369 feat: Show In-App Notification content in sidebar
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/components/Sidebar/InAppNotification/index.ts
  apps/app/src/components/Sidebar/SidebarContents.tsx
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
  apps/app/src/interfaces/ui.ts
Labels: type/feature, flag/exclude-from-changelog

#8371 feat: Show notifications in sidebar
  apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/InAppNotificationList.tsx
  apps/app/src/components/InAppNotification/InAppNotificationPage.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
Labels: type/feature

#8375 feat: 137726 page side contents layout
  apps/app/src/components/Common/PageViewLayout.module.scss
  apps/app/src/components/PageSideContents/PageAccessoriesControl.module.scss
  apps/app/src/components/PageTags/TagLabels.module.scss
Labels: type/feature, flag/exclude-from-changelog

#8335 feat: Do not displayed `Create Today's ...` for guest users
  apps/app/src/components/PageHistory/PageRevisionTable.tsx
  apps/app/src/components/PageSelectModal/TreeItemForModal.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/NewPageCreateButton.tsx
  apps/app/src/components/TreeItem/NewPageInput.tsx
  apps/app/src/components/TreeItem/NewPageInput/NewPageCreateButton.tsx
  apps/app/src/components/TreeItem/NewPageInput/NewPageInput.tsx
  apps/app/src/components/TreeItem/NewPageInput/index.ts
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/components/TreeItem/NotDraggableForClosableTextInput.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/components/TreeItem/UseNewPageInput.tsx
  apps/app/src/components/TreeItem/index.ts
  apps/app/src/components/TreeItem/interfaces/index.ts
Labels: type/feature, flag/exclude-from-changelog

#8382 support: New kibela
  packages/preset-themes/src/styles/kibela.scss
  packages/preset-themes/vite.themes.config.ts
Labels: type/support, flag/exclude-from-changelog

#8383 fix: Configured auditlog environment variables are not reflected in the administration screen
  apps/app/src/pages/admin/audit-log.page.tsx
  apps/app/src/stores/context.tsx
Labels: type/bug

#8373 feat: Unread filtering for In-app notification
  apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
Labels: type/feature

#8384 support: New Nature
  packages/preset-themes/src/styles/nature.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8361 feat: Scroll sync in editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/Preview.tsx
  apps/app/src/components/PageEditor/ScrollSyncHelper.js
  apps/app/src/components/PageEditor/ScrollSyncHelper.ts
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/extensions/setDataLine.ts
Labels: type/feature

#8389 feat: Apply grant data when new button clicked
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
  apps/app/src/server/routes/apiv3/pages.js
Labels: type/feature

#8378 imprv: Use unzip stream instead of unzipper
  apps/app/package.json
  apps/app/src/server/service/growi-bridge/index.ts
  apps/app/src/server/service/growi-bridge/unzip-stream-utils.ts
  apps/app/src/server/service/import.js
  yarn.lock
Labels: type/improvement

#8395 support: New Wood
  packages/preset-themes/public/images/wood/wood-navbar.jpg
  packages/preset-themes/public/images/wood/wood.jpg
  packages/preset-themes/public/images/wood/wood.svg
  packages/preset-themes/src/styles/wood.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8391 fix: Non-admin user cannot rename pages
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/server/service/page.ts
  packages/core/src/interfaces/page.ts
Labels: type/bug

#8399 fix: Normalization of 20-basic-features--access-to-pagelist.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-pagelist.cy.ts
Labels: type/bug

#8398 support: New Spring
  packages/preset-themes/public/images/spring/spring02.jpg
  packages/preset-themes/public/images/spring/spring02.svg
  packages/preset-themes/src/styles/spring.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8396 imprv: 137433 improve paste operations in markdown
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/list-util/markdown-list-util.ts
Labels: type/improvement, flag/exclude-from-changelog

#8403 fix: Normalization of 30-search--search.cy.ts
  apps/app/src/components/PageControls/SearchButton.tsx
  apps/app/src/features/search/client/components/SearchForm.tsx
  apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/test/cypress/e2e/30-search/30-search--search.cy.ts
Labels: type/bug

#8372 feat: Notification count badge
  apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/components/InAppNotification/InAppNotificationList.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
  apps/app/src/components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItem.tsx
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
Labels: type/feature

#8400 fix: Normalization of 20-basic-features--use-tools.cy.ts
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--use-tools.cy.ts
Labels: type/bug, flag/exclude-from-changelog

#8404 fix: Duplicate root pages are created unintentionally
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#8405 support: New Blackboard
  packages/preset-themes/public/images/blackboard/blackboard.png
  packages/preset-themes/src/styles/blackboard.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8407 fix: Normalization of 21-basic-features-for-guest--access-to-page.cy.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest.cy.ts
Labels: type/bug, flag/exclude-from-changelog

#8408 fix: Normalization of 20-basic-features--sticky-features.cy.ts
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts
Labels: type/bug, flag/exclude-from-changelog

#8409 support: New Halloween
  packages/preset-themes/public/images/halloween/halloween-navbar.jpg
  packages/preset-themes/public/images/halloween/halloween.jpg
  packages/preset-themes/src/styles/halloween.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8387 feat: Support editor theme
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/components/playground/PlaygroundController.tsx
  packages/editor/src/services/editor-theme/ayu.ts
  packages/editor/src/services/editor-theme/cobalt.ts
  packages/editor/src/services/editor-theme/index.ts
  packages/editor/src/services/editor-theme/original-dark.ts
  packages/editor/src/services/editor-theme/original-light.ts
  packages/editor/src/services/editor-theme/rose-pine.ts
  packages/editor/src/services/index.ts
  yarn.lock
Labels: type/feature

#8410 fix: Non-admin user cannot rename pages v63x
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/server/service/page/index.ts
  packages/core/src/interfaces/page.ts
Labels: type/bug

#8411 feat: Commentable using CodeMirrorEditor
  apps/app/src/components/PageComment/CommentEditor.tsx
  packages/editor/src/components/index.ts
Labels: type/feature, flag/exclude-from-changelog

#8415 support: Create Classic theme
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/styles/classic.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8416 feat: color bg
  apps/app/src/components/PageTags/RenderTagLabels.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/components/Sidebar/Tag.tsx
  apps/app/src/components/TagCloudBox.tsx
  apps/app/src/components/TagList.module.scss
  apps/app/src/components/TagList.tsx
  apps/app/src/styles/_tag.scss
  apps/app/src/styles/atoms/_tag.scss
  apps/app/src/styles/style-app.scss
  packages/core/scss/bootstrap/apply.scss
  packages/core/scss/bootstrap/override/_helpers.scss
  packages/core/scss/bootstrap/override/helpers/_color-bg.scss
  packages/core/scss/bootstrap/theming/_variables.scss
  packages/core/scss/bootstrap/utilities.scss
Labels: flag/exclude-from-changelog

#8414 feat: Normalize duplicated root pages to valid paths when server startup
  apps/app/src/server/crowi/index.js
  apps/app/src/server/service/normalize-data/index.ts
  apps/app/src/server/service/normalize-data/rename-duplicate-root-pages.ts
Labels: type/feature

#8418 fix: Tree item click handler
  apps/app/src/components/PageSelectModal/TreeItemForModal.tsx
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/components/TreeItem/interfaces/index.ts
Labels: type/bug

#8413 fix: Preventing duplication of `/user/username` pages
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#8406 fix: Logs are not saved when viewing the page
  .vscode/settings.json
  apps/app/.eslintrc.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/utils/commons.ts
Labels: type/bug

#8420 fix: Normalization of 20-basic-features--comments.cy.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts
Labels: type/bug, flag/exclude-from-changelog

#8424 feat: Implement .btn-outline-neutral
  apps/app/src/components/Me/ColorModeSettings.module.scss
  apps/app/src/components/Me/ColorModeSettings.tsx
  apps/app/src/components/PageSideContents/PageAccessoriesControl.tsx
  packages/core/scss/bootstrap/mixins/_button-outline-neutral-variant.scss
  packages/core/scss/bootstrap/override/_buttons.scss
Labels: flag/exclude-from-changelog

#8417 fix: implement dropdown using reactstrap
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendToggle.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
Labels: type/bug

#8421 fix: Error when deleting comments
  apps/app/src/components/PageSideContents/PageAccessoriesControl.tsx
  apps/app/src/server/models/obsolete-page.js
Labels: flag/exclude-from-changelog

#8427 fix: Page tree indentation of the bottom page
  apps/app/src/components/ItemsTree/ItemsTree.module.scss
Labels: type/bug, flag/exclude-from-changelog

#8374 fix: Page being able to delete completely when not allowed
  apps/app/src/components/PageDeleteModal.tsx
Labels: type/bug
