Repository growilabs/growi, pull requests merged in 2024-02, with the labels that each got.

#8422 fix: Renaming result is not reflected in PagePathNav
  apps/app/src/pages/[[...path]].page.tsx
Labels: type/bug, flag/exclude-from-changelog

#8176 feat: Built-in Collaborative Editor
  apps/app/package.json
  apps/app/src/client/services/side-effects/page-updated.ts
  apps/app/src/components/ItemsTree/ItemsTree.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Navbar/hooks.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
  apps/app/src/interfaces/websocket.ts
  apps/app/src/server/service/socket-io.js
  apps/app/src/server/service/yjs-connection-manager.ts
  apps/app/src/stores/ui.tsx
  apps/app/src/stores/use-static-swr.ts
  apps/app/src/stores/websocket.tsx
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/websocket.ts
  packages/core/src/swr/index.ts
  packages/core/src/swr/use-global-socket.ts
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/consts/index.ts
  packages/editor/src/consts/ydoc-awareness-user-color.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/stores/index.ts
  packages/editor/src/stores/use-collaborative-editor-mode.ts
  yarn.lock
Labels: type/feature

#8436 fix: Dropdown container
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
Labels: flag/exclude-from-changelog

#8412 fix: 139350 fix paste operation in editor
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/list-util/markdown-list-util.ts
Labels: type/bug

#8438 fix: Global search shortcut key do not work
  apps/app/_obsolete/src/components/Navbar/GlobalSearch.module.scss
  apps/app/_obsolete/src/components/Navbar/GlobalSearch.tsx
  apps/app/src/components/Hotkeys/Subscribers/FocusToGlobalSearch.jsx
  apps/app/src/stores/ui.tsx
Labels: type/bug, flag/exclude-from-changelog

#8437 imprv: Wiki header border style
  apps/app/src/styles/organisms/_wiki.scss
Labels: type/improvement

#8423 fix: fix style of dropend toggle of page create button
  apps/app/src/components/Sidebar/SidebarNav/SidebarNav.module.scss
Labels: type/bug, flag/exclude-from-changelog

#8355 imprv: Insert number list only 1 in editor when enter line
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/utils/insert-newline-continue-markup.ts
  packages/editor/src/services/list-util/markdown-list-util.ts
Labels: type/improvement

#8331 feat: Multiple group grant for page
  apps/app/_obsolete/src/components/PageEditorByHackmd.tsx
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/AdminGeneralSecurityContainer.js
  apps/app/src/components/Admin/AuditLog/AuditLogDisableMode.tsx
  apps/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageAlert/PageGrantAlert.tsx
  apps/app/src/components/PageDuplicateModal.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageManagement/ApiErrorMessage.jsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
  apps/app/src/interfaces/page-operation.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/migrations/20230723061824-granted-group-to-array-of-objects.js
  apps/app/src/migrations/20231223155127-non-null-granted-groups.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/models/config.ts
  apps/app/src/server/models/interfaces/page-operation.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/apiv3/page.js
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/test/integration/models/v5.page.test.js
  apps/app/test/integration/service/page-grant.test.js
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/v5.non-public-page.test.ts
  apps/app/test/integration/service/v5.page.test.ts
  apps/app/test/integration/service/v5.public-page.test.ts
  packages/core/src/interfaces/page.ts
Labels: type/feature

#8442 feat: Enable and fix page duplication of user unrelated pages
  apps/app/src/server/routes/apiv3/pages.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/page/index.ts
Labels: type/feature

#8440 imprv: Typescriptize PageTagRelation model and some routing actions
  apps/app/src/client/services/use-create-page-and-transit.tsx
  apps/app/src/client/services/use-on-template-button-clicked.ts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/PageTags/PageTags.tsx
  apps/app/src/components/Skeleton.tsx
  apps/app/src/interfaces/page-tag-relation.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/events/activity.ts
  apps/app/src/server/models/GlobalNotificationSetting.ts
  apps/app/src/server/models/GlobalNotificationSetting/GlobalNotificationMailSetting.js
  apps/app/src/server/models/GlobalNotificationSetting/GlobalNotificationSlackSetting.js
  apps/app/src/server/models/GlobalNotificationSetting/consts.ts
  apps/app/src/server/models/index.ts
  apps/app/src/server/models/page-tag-relation.js
  apps/app/src/server/models/page-tag-relation.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/tag.ts
  apps/app/src/server/routes/apiv3/interfaces/apiv3-response.ts
  apps/app/src/server/routes/apiv3/notification-setting.js
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/apiv3/page/cteate-page.ts
  apps/app/src/server/routes/apiv3/page/index.js
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/routes/index.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/routes/tag.js
  apps/app/src/server/service/global-notification/global-notification-mail.js
  apps/app/src/server/service/global-notification/global-notification-slack.js
  apps/app/src/server/service/page/delete-completely-user-home-by-system.integ.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/server/service/user-notification/index.ts
  apps/app/src/stores/page.tsx
  apps/app/test/integration/models/v5.page.test.js
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/v5.non-public-page.test.ts
  apps/app/test/integration/service/v5.page.test.ts
  apps/app/test/integration/service/v5.public-page.test.ts
  apps/app/test/integration/setup-crowi.ts
Labels: flag/exclude-from-changelog

#8441 fix: LinkEditModal
  apps/app/_obsolete/src/components/PageEditor/MarkdownLinkUtil.js
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/stores/modal.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/LinkEditButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/services/link-util/Linker.ts
  packages/editor/src/services/link-util/markdown-link-util.ts
  packages/editor/src/stores/use-link-edit-modal.ts
Labels: type/bug, flag/exclude-from-changelog

#8444 feat: CollapsedParentsDropdown to display ancestor pathname
  apps/app/src/components/Common/PagePathHierarchicalLink/CollapsedParentsDropdown.tsx
Labels: type/feature

#8449 fix: Fix Dropup menu style
  packages/core/scss/bootstrap/_variables.scss
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/override/_dropdown.scss
Labels: type/bug, flag/exclude-from-changelog

#8450 fix: Tuncate former link in small mode
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
Labels: type/bug, flag/exclude-from-changelog

#8448 fix: Comment Editor Height
  apps/app/src/components/PageComment/CommentEditor.module.scss
Labels: type/bug, flag/exclude-from-changelog

#8453 feat: Multi group grant duplication (add test for when onlyDuplicateUserRelatedResources is false)
  apps/app/test/integration/service/v5.non-public-page.test.ts
Labels: type/feature

#8455 fix: When the revision body is empty no differences are detected
  apps/app/src/components/PageHistory/RevisionDiff.tsx
Labels: type/bug, flag/exclude-from-changelog

#8439 imprv: improve PageHeader component
  apps/app/src/components/Common/ClosableTextInput.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/components/PageHeader/TextInputForPageTitleAndPath.tsx
  apps/app/src/components/PageHeader/page-header-utils.ts
Labels: type/improvement

#8460 fix: Use default backward keymap
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
Labels: type/bug

#8459 imprv: Creating/updating page APIs
  apps/app/src/client/services/create-page/index.ts
  apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
  apps/app/src/client/services/create-page/use-create-template-page.ts
  apps/app/src/client/services/page-operation.ts
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/client/services/use-create-page-and-transit.tsx
  apps/app/src/client/services/use-on-template-button-clicked.ts
  apps/app/src/components/CreateTemplateModal.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks/index.ts
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-new-page.ts
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/interfaces/apiv3/index.ts
  apps/app/src/interfaces/apiv3/page.ts
  apps/app/src/interfaces/page-operation.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/server/models/interfaces/page-operation.ts
  apps/app/src/server/models/page-operation.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/cteate-page.ts
  apps/app/src/server/routes/apiv3/page/index.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/routes/index.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/installer.ts
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  packages/core/src/utils/page-path-utils/index.spec.ts
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/improvement

#8467 fix: Check page existence
  apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/CreateTemplateModal.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/server/routes/apiv3/page/check-page-existence.ts
  apps/app/src/server/routes/apiv3/page/index.js
  apps/app/src/server/routes/index.js
  apps/app/src/server/routes/page.js
Labels: flag/exclude-from-changelog

#8466 imprv: Update page accessories modal design
  packages/ui/src/components/Attachment.tsx
Labels: type/improvement

#8452 fix: PersonalDropdownMenu position
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.tsx
  apps/app/src/components/Sidebar/SidebarNav/SecondaryItems.tsx
  apps/app/src/components/Sidebar/SidebarNav/SidebarNav.tsx
Labels: type/bug

#8457 fix: Page list count is wrong
  apps/app/src/components/Common/CountBadge.tsx
  apps/app/src/components/PageSideContents/PageAccessoriesControl.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
Labels: type/bug, flag/exclude-from-changelog

#8463 feat: Adapting styles to PageHeader
  apps/app/package.json
  apps/app/src/components/Common/ClosableTextInput.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageHeader/PageHeader.module.scss
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  yarn.lock
Labels: type/feature

#8456 fix: CreateTemplateModal does not close
  apps/app/src/components/CreateTemplateModal.tsx
Labels: type/bug, flag/exclude-from-changelog

#8470 fix: PageHeader behavior and position
  apps/app/src/components/Common/ClosableTextInput.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageHeader/PageHeader.module.scss
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.module.scss
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.module.scss
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/models/linked-page-path.js
Labels: flag/exclude-from-changelog

#8464 feat: Normal page delete fix after multi group grant page delete impl
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/test/integration/service/page.test.js
Labels: type/bug, type/feature

#8475 fix: Default theme color
  packages/preset-themes/src/styles/default.scss
Labels: flag/exclude-from-changelog

#8471 imprv: Dynamic import for keymap
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/keymaps/index.ts
Labels: type/improvement

#8458 fix: User settings rayout (User information)
  apps/app/src/components/CustomNavigation/CustomNav.module.scss
  apps/app/src/components/Me/BasicInfoSettings.tsx
  apps/app/src/components/Me/PersonalSettings.jsx
  apps/app/src/components/Me/ProfileImageSettings.tsx
  apps/app/src/components/Me/UserSettings.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
Labels: flag/exclude-from-changelog

#8468 imprv: 139427 140551 adjustment modal space
  apps/app/src/components/PageDuplicateModal.tsx
Labels: type/improvement

#8446 feat: implement function to select parent page from PageSelectModal
  apps/app/src/components/ItemsTree/ItemsTree.tsx
  apps/app/src/components/PageEditor/page-path-rename-utils.ts
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/components/PageSelectModal/PageSelectModal.tsx
  apps/app/src/components/PageSelectModal/TreeItemForModal.tsx
Labels: type/feature

#8485 fix: Search results are not highlighted
  apps/app/src/components/SearchPage/SearchPageBase.module.scss
  apps/app/src/components/SearchPage/SearchPageBase.tsx
Labels: type/bug

#8476 imprv: Attachment
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/interfaces/editor-settings.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/context.tsx
  apps/app/src/stores/editor.tsx
  packages/core/src/consts/accepted-upload-file-type.ts
  packages/core/src/consts/index.ts
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropdownItem.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/consts/index.ts
  packages/editor/src/services/file-dropzone/use-file-dropzone/use-file-dropzone.ts
Labels: flag/exclude-from-changelog

#8489 imprv: Use createPage in useNewPageInput
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
Labels: type/improvement

#8492 fix: Navtab icon
  apps/app/src/components/DescendantsPageListModal.tsx
  apps/app/src/components/Icons/PageListIcon.jsx
  apps/app/src/components/Icons/TimeLineIcon.jsx
  apps/app/src/components/NotFoundPage.tsx
  apps/app/src/components/TrashPageList.tsx
Labels: flag/exclude-from-changelog

#8454 imprv: Update design outline for side contents tag
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/PageTags/PageTags.tsx
  apps/app/src/components/PageTags/RenderTagLabels.tsx
  apps/app/src/components/PageTags/TagLabels.module.scss
Labels: type/improvement

#8495 imprv: Update user homepage side contents design
  apps/app/src/components/TableOfContents.tsx
Labels: flag/exclude-from-changelog

#8494 feat: Enable multi group grant in grant fix
  apps/app/src/server/routes/apiv3/page/index.js
Labels: type/feature, flag/exclude-from-changelog

#8497 feat: 140020 140992 sidebar style
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/Sidebar.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx
Labels: type/feature

#8482 imprv: change sidebar input positions
  apps/app/src/components/Sidebar/PageTreeItem/Ellipsis.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8498 fix: list markdown not pasting properly
  packages/editor/src/services/list-util/markdown-list-util.ts
Labels: type/bug, type/improvement, flag/exclude-from-changelog

#8507 imprv: Multi group grant page duplicate explanation
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageDuplicateModal.tsx
Labels: type/improvement

#8473 imprv: Fix broken layout of search result page
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/SearchPage.tsx
  apps/app/src/components/SearchPage/OperateAllControl.tsx
  apps/app/src/components/SearchPage/SearchControl.module.scss
  apps/app/src/components/SearchPage/SearchControl.tsx
  apps/app/src/components/SearchPage/SearchOptionModal.tsx
  apps/app/src/components/SearchPage/SortControl.module.scss
  apps/app/src/components/SearchPage/SortControl.tsx
Labels: type/improvement

#8517 fix: Mutation for current page
  apps/app/src/client/services/page-operation.ts
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/client/util/bookmark-utils.ts
  apps/app/src/components/ContentLinkButtons.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageAccessoriesModal/PageAttachment.tsx
  apps/app/src/components/PageContentFooter.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/page-path-rename-utils.ts
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/PageStatusAlert.tsx
  apps/app/src/components/PageTimeline.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/components/ShareLinkPageView.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebarSubstance.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/page.ts
  apps/app/src/stores/page.tsx
  packages/core/src/interfaces/page.ts
Labels: flag/exclude-from-changelog

#8511 imprv: 139425-140982 & fix-sidbar-fontsize&margin
  apps/app/src/components/ItemsTree/ItemsTree.tsx
  apps/app/src/components/Sidebar/Bookmarks.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebar.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebarSubstance.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/components/Sidebar/PageTree/PageTree.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChanges.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/components/Sidebar/Tag.tsx
  apps/app/src/components/TagList.tsx
Labels: type/improvement

#8428 fix: Current page item in page tree is not active
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.module.scss
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/styles/molecules/_list-group-item.scss
Labels: type/bug, flag/exclude-from-changelog

#8524 feat: Replace simple line icon with Material Symbols Outlined
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SecurityManagementContents.jsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Admin/SlackIntegration/Bridge.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  apps/app/src/components/Admin/UserManagement.module.scss
  apps/app/src/components/Admin/UserManagement.tsx
  apps/app/src/components/Admin/Users/ExternalAccountTable.tsx
  apps/app/src/components/Admin/Users/UserMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.tsx
  apps/app/src/components/ExpandOrContractButton.tsx
  apps/app/src/components/ItemsTree/ItemsTree.module.scss
  apps/app/src/components/Me/ExternalAccountLinkedMe.jsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageComment/ReplyComments.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageEditor/Editor.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
  apps/app/src/components/Sidebar/PageTreeItem/Ellipsis.tsx
  apps/app/src/components/Sidebar/SidebarHeaderReloadButton.tsx
  apps/app/src/components/TreeItem/NewPageInput/NewPageCreateButton.tsx
  apps/app/src/components/User/UserInfo.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
  apps/app/src/pages/installer.page.tsx
  packages/ui/src/components/Attachment.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: flag/exclude-from-changelog

#8526 fix: Mutation for current page 2
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/stores/page.tsx
Labels: type/bug

#8484 feat: WIP Page
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/services/create-page/use-create-template-page.ts
  apps/app/src/client/services/page-operation.ts
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/ItemsTree/ItemsTree.tsx
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Page/PageView.tsx
  apps/app/src/components/PageAlert/PageAlerts.tsx
  apps/app/src/components/PageAlert/WipPageAlert.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebarNotFound.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-new-page.ts
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
  apps/app/src/components/Sidebar/PageTree/PageTree.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChanges.tsx
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.module.scss
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/components/Sidebar/SidebarContents.module.scss
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/components/TreeItem/interfaces/index.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/index.js
  apps/app/src/server/routes/apiv3/page/publish-page.ts
  apps/app/src/server/routes/apiv3/page/unpublish-page.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/stores/page-listing.tsx
  apps/app/src/utils/should-create-wip-page.ts
  packages/core/src/interfaces/page.ts
Labels: type/feature

#8525 feat: Login lead in guest mode
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/stores/page.tsx
Labels: type/feature

#8461 feat: implement to add table when doing a line break in table markdown
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/list-util/insert-newline-continue-markup.ts
  packages/editor/src/services/paste-util/paste-markdown-util.ts
  packages/editor/src/services/table-util/index.ts
  packages/editor/src/services/table-util/insert-new-row-to-table-markdown.ts
  packages/editor/src/services/table-util/markdown-table.d.ts
  packages/editor/src/services/table-util/markdown-table.js
  yarn.lock
Labels: type/feature

#8521 fix: Two dropzone file dialog opening.
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropdownItem.tsx
  packages/editor/src/services/file-dropzone/use-file-dropzone/use-file-dropzone.ts
Labels: type/bug, type/improvement, flag/exclude-from-changelog

#8513 imprv: Fix search modal broken design by pagepath
  apps/app/src/features/search/client/components/SearchForm.tsx
  apps/app/src/features/search/client/components/SearchHelp.tsx
  apps/app/src/features/search/client/components/SearchMenuItem.tsx
  apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/components/SearchResultMenuItem.tsx
Labels: type/improvement

#8531 imprv: Add left margin in edit mode preview
  apps/app/src/components/PageEditor/Preview.module.scss
Labels: type/improvement

#8527 fix: Unable to create new pages under user's home page
  apps/app/src/server/routes/apiv3/page/create-page.ts
Labels: type/bug

#8515 fix: pages are not displayed in page tree
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
Labels: type/bug

#8528 support: Node.js v20
  .devcontainer/Dockerfile
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/list-unhealthy-branches.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  .mergify.yml
  README.md
  README_JP.md
  apps/app/docker/Dockerfile
  apps/app/package.json
  apps/slackbot-proxy/docker/Dockerfile
  package.json
  yarn.lock
Labels: type/support

#8533 support: Downgrade string-width
  apps/app/package.json
  apps/app/src/services/renderer/remark-plugins/xsv-to-table.ts
  packages/editor/package.json
  yarn.lock
Labels: flag/exclude-from-changelog

#8518 fix: Multi group grant page becomes public when one of groups deleted
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
  apps/app/src/features/external-user-group/server/models/external-user-group.ts
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
  apps/app/src/interfaces/user-group.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/user-group.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/user-group.ts
  apps/app/test/integration/models/v5.page.test.js
  apps/app/test/integration/service/user-groups.test.ts
Labels: type/bug

#8532 imprv: Update SearchTypeahead.tsx
  apps/app/src/components/SearchTypeahead.tsx
  apps/app/test/cypress/e2e/30-search/30-search--search.cy.ts
Labels: type/improvement

#8535 imprv: pastEnd for Preview
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/Preview.tsx
  packages/ui/src/utils/index.ts
  packages/ui/src/utils/use-rect.ts
Labels: flag/exclude-from-changelog

#8505 fix: display of page title in page tree
  apps/app/src/components/Sidebar/Sidebar.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
Labels: type/bug

#8539 imprv: Styling adjustments for the login lead
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: type/improvement
