Repository growilabs/growi, pull requests merged in 2024-03, with the labels that each got.

#8537 Feat: Replace Fontawesome icons with Material Symbols
  apps/app/src/components/Admin/AdminHome/AdminHome.jsx
  apps/app/src/components/Admin/App/AppSettingsPageContents.tsx
  apps/app/src/components/Admin/App/MaskedInput.tsx
  apps/app/src/components/Admin/AuditLog/ActivityTable.tsx
  apps/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
  apps/app/src/components/Admin/AuditLog/DateRangePicker.tsx
  apps/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
  apps/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/components/Admin/G2GDataTransferExportForm.tsx
  apps/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  apps/app/src/components/Admin/Notification/NotificationTypeIcon.tsx
  apps/app/src/components/Admin/Notification/UserTriggerNotification.jsx
  apps/app/src/components/Admin/Security/LocalSecuritySettingContents.jsx
  apps/app/src/components/Admin/Security/SecurityManagementContents.jsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/Admin/SlackIntegration/Bridge.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/Users/SortIcons.tsx
  apps/app/src/components/Admin/Users/UserMenu.module.scss
  apps/app/src/components/Admin/Users/UserMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkMoveToRootBtn.tsx
  apps/app/src/components/Common/CustomCopyToClipBoard.tsx
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/Me/AssociateModal.tsx
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/components/PageManagement/ApiErrorMessage.jsx
  apps/app/src/components/PageRenameModal.tsx
  apps/app/src/components/SystemVersion.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/components/UsersHomepageFooter.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
  packages/remark-attachment-refs/src/client/components/AttachmentList.tsx
  packages/remark-lsx/src/client/components/Lsx.tsx
  packages/remark-lsx/src/client/components/LsxPageList/LsxListView.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
Labels: flag/exclude-from-changelog

#8541 fix: Unable to create pages from PageCreateModal
  apps/app/src/client/services/use-toastr-on-error.tsx
  apps/app/src/components/PageCreateModal.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
Labels: type/bug

#8545 fix: Unable to displaying content on the editor when opened on the same page, browser, and user,
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/stores/use-collaborative-editor-mode.ts
Labels: type/bug, flag/exclude-from-changelog

#8547 feat: Migration script for Bootstrap5
  bin/data-migrations/README.md
  bin/data-migrations/src/migrations/v70x/bootstrap5.js
  bin/data-migrations/src/migrations/v70x/index.js
Labels: type/feature

#8550 imprv: WIP Page wording
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
Labels: type/improvement, flag/exclude-from-changelog

#8549 imprv: Change home material icon size in path
  apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.module.scss
  apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.tsx
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
Labels: type/improvement

#8552 imprv: Re-calculate TOC height when Tags Element height updated
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/TableOfContents.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8522 feat: Not required latest revision when updating from Editor
  .github/workflows/ci-app-prod.yml
  .mergify.yml
  apps/app/src/client/services/create-page/use-create-template-page.ts
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/PageCreateModal.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/Sidebar/Custom/CustomSidebarNotFound.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-new-page.ts
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
  apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx
  apps/app/src/interfaces/apiv3/page.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/revision.js
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
  packages/core/src/interfaces/revision.ts
Labels: type/feature

#8544 imprv: Refactor editor navbar
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.module.scss
  apps/app/src/components/PageControls/_button-styles.scss
  apps/app/src/components/PageEditor/EditorNavbar/EditingUserList.module.scss
  apps/app/src/components/PageEditor/EditorNavbar/EditingUserList.tsx
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.module.scss
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.tsx
  apps/app/src/components/PageEditor/EditorNavbar/index.ts
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageHeader/EditingUserList.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.module.scss
  apps/app/src/components/PageHeader/index.ts
Labels: type/improvement, flag/exclude-from-changelog

#8548 fix: Theme select style
  apps/app/src/components/Admin/Customize/ThemeColorBox.tsx
  packages/core/src/interfaces/growi-theme-metadata.ts
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/interfaces/growi-theme-metadata.ts
Labels: flag/exclude-from-changelog

#8529 imprv: All editor config option is available
  apps/app/_obsolete/src/components/PageEditor/Editor.tsx
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SlackNotification.tsx
  apps/app/src/interfaces/editor-settings.ts
  apps/app/src/server/models/editor-settings.ts
  apps/app/src/stores/editor.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/consts/editor-settings.ts
  packages/editor/src/consts/index.ts
  packages/editor/src/services/codemirror-editor/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/services/editor-theme/index.ts
  packages/editor/src/services/keymaps/index.ts
  packages/editor/src/stores/index.ts
  packages/editor/src/stores/use-default-extensions.ts
  packages/editor/src/stores/use-editor-settings.ts
Labels: type/improvement, flag/exclude-from-changelog

#8501 feat: 139718 141055 sidebar account modal design
  apps/app/_obsolete/src/components/Navbar/GrowiNavbar.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.tsx
Labels: type/feature

#8530 imprv: Replace original icon
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/components/PageEditor/Cheatsheet.tsx
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
  apps/app/src/components/UsersHomepageFooter.module.scss
  apps/app/src/components/UsersHomepageFooter.tsx
  apps/app/src/pages/installer.page.tsx
  packages/custom-icons/svg/drawer_io.svg
  packages/custom-icons/svg/external_link.svg
  packages/custom-icons/svg/format_quote.svg
  packages/custom-icons/svg/header.svg
  packages/custom-icons/svg/recently_created.svg
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8519 fix: Show both UserGroups and ExternalUserGroups for group delete modal transfer select
  apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupPage.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
  apps/app/src/server/routes/apiv3/user-group.js
Labels: type/bug

#8554 fix: Text color for .list-group-item.active
  apps/app/src/styles/molecules/_list-group-item.scss
Labels: flag/exclude-from-changelog

#8556 fix: Me pages layout
  apps/app/src/components/Admin/Security/LdapAuthTest.tsx
  apps/app/src/components/Me/ApiSettings.tsx
  apps/app/src/components/Me/AssociateModal.tsx
  apps/app/src/components/Me/ColorModeSettings.tsx
  apps/app/src/components/Me/ExternalAccountLinkedMe.jsx
  apps/app/src/components/Me/InAppNotificationSettings.tsx
  apps/app/src/components/Me/PasswordSettings.jsx
  apps/app/src/components/Me/ProfileImageSettings.tsx
  apps/app/src/components/Me/QuestionnaireSettings.tsx
  apps/app/src/components/Me/UISettings.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
Labels: flag/exclude-from-changelog

#8546 imprv: Update tag edit modal design
  apps/app/src/components/PageTags/RenderTagLabels.tsx
  apps/app/src/components/PageTags/TagEditModal.tsx
  apps/app/src/components/PageTags/TagLabels.module.scss
  apps/app/src/components/PageTags/TagsInput.module.scss
  apps/app/src/components/PageTags/TagsInput.tsx
  apps/app/src/styles/_override-rbt.scss
Labels: type/improvement, flag/exclude-from-changelog

#8553 feat: Replace original icons with Material Symbols
  apps/app/_obsolete/src/components/Sidebar/AppearanceModeDropdown.tsx
  apps/app/src/components/Icons/CompressIcon.tsx
  apps/app/src/components/Icons/CreatePageIcon.tsx
  apps/app/src/components/Icons/ExpandIcon.tsx
  apps/app/src/components/Icons/FolderIcon.tsx
  apps/app/src/components/Icons/FolderPlusIcon.tsx
  apps/app/src/components/Icons/KeyboardReturnEnterIcon.tsx
  apps/app/src/components/Icons/MoonIcon.jsx
  apps/app/src/components/Icons/PagePreviewIcon.jsx
  apps/app/src/components/Icons/ReturnTopIcon.tsx
  apps/app/src/components/Icons/SunIcon.jsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/components/ShortcutsModal.tsx
  apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
  apps/app/src/components/UsersHomepageFooter.tsx
Labels: flag/exclude-from-changelog

#8540 imprv: 139425 141028 fix switch
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.module.scss
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
Labels: type/improvement

#8558 fix: 137284 142153 fix icon build
  packages/custom-icons/svg/drawer_io.svg
  packages/custom-icons/svg/header.svg
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
Labels: type/bug

#8516 imprv: 133910 140441 replace spinner
  apps/app/src/components/LoadingSpinner.jsx
  apps/app/src/components/LoadingSpinner.module.scss
  apps/app/src/components/LoginForm.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8557 imprv: Re-implement ConflictDiffModal with @codemirror/merge
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageEditor/ConflictDiffModal.module.scss
  apps/app/src/components/PageEditor/ConflictDiffModal.tsx
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  packages/editor/package.json
  packages/editor/src/components/CodeMirrorEditorDiff.tsx
  packages/editor/src/components/MergeViewer.tsx
  packages/editor/src/components/index.ts
  packages/editor/src/consts/global-code-mirror-editor-key.ts
  yarn.lock
Labels: type/improvement

#8555 fix: Editor layout and styles
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/styles/_editor.scss
  packages/core/scss/_flex-expand.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.module.scss
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
Labels: flag/exclude-from-changelog

#8564 fix: File dialog works correctly
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropdownItem.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/AttachmentsDropup.tsx
Labels: type/bug

#8568 fix: Page cannot be updated
  apps/app/src/components/PageEditor/PageEditor.tsx
Labels: type/bug, flag/exclude-from-changelog

#8562 Fix: Add Admin header return button
  apps/app/src/components/Icons/GrowiLogo.jsx
  apps/app/src/components/Icons/GrowiLogo.module.scss
  apps/app/src/components/Layout/AdminLayout.tsx
  apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
Labels: flag/exclude-from-changelog

#8523 imprv: design of input field for slack channel
  apps/app/public/images/icons/slack/slack-logo-background.svg
  apps/app/public/images/icons/slack/slack-logo-dark-background.svg
  apps/app/public/static/locales/en_US/translation.json
  apps/app/src/components/PageEditor/EditorNavbarBottom.module.scss
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageEditor/OptionsSelector.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/SlackLogo.jsx
  apps/app/src/components/SlackNotification.module.scss
  apps/app/src/components/SlackNotification.tsx
  apps/app/src/styles/atoms/_custom_control.scss
  packages/core/scss/bootstrap/_variables.scss
Labels: type/improvement, flag/exclude-from-changelog

#8565 imprv: 133910 141620 replace fa rotate
  apps/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
  apps/app/src/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/components/PageRenameModal.tsx
  apps/app/src/styles/style-app.scss
  packages/core/scss/_rotate.scss
Labels: type/improvement

#8543 imprv: replace spinner pulse
  apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
  apps/app/src/components/Admin/AuditLogManagement.tsx
  apps/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  apps/app/src/components/Admin/ElasticsearchManagement/ReconnectControls.tsx
  apps/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/DescendantsPageList.tsx
  apps/app/src/components/InAppNotification/InAppNotificationList.tsx
  apps/app/src/components/InAppNotification/InAppNotificationPage.tsx
  apps/app/src/components/InfiniteScroll.tsx
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/InvitedForm.tsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Me/QuestionnaireSettings.tsx
  apps/app/src/components/Page/RevisionLoader.tsx
  apps/app/src/components/PageAccessoriesModal/PageAttachment.tsx
  apps/app/src/components/PageControls/BookmarkButtons.tsx
  apps/app/src/components/PageEditor/DrawioModal.tsx
  apps/app/src/components/PageList/PageList.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/pages/tags.page.tsx
Labels: type/improvement

#8569 support: Refactor ycollab
  apps/app/package.json
  packages/editor/src/@types/y-codemirror.next.d.ts
  packages/editor/src/stores/use-collaborative-editor-mode.ts
  packages/editor/src/stores/use-default-extensions.ts
Labels: type/support

#8572 support: New Antarctic theme
  packages/preset-themes/public/images/antarctic/antarctic.svg
  packages/preset-themes/public/images/antarctic/bg.svg
  packages/preset-themes/public/images/antarctic/topimage.svg
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8573 imprv: replace icon external link
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Labels: type/improvement

#8574 support: New Hufflepuff theme
  packages/preset-themes/public/images/hufflepuff/badger-dark.jpg
  packages/preset-themes/public/images/hufflepuff/badger-light.png
  packages/preset-themes/public/images/hufflepuff/badger-light3.png
  packages/preset-themes/public/images/hufflepuff/hufflepuff-dark-bg.svg
  packages/preset-themes/public/images/hufflepuff/hufflepuff-light-bg.svg
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/vite.themes.config.ts
Labels: flag/exclude-from-changelog

#8575 feat: Replace icon font with Material Symbols Outlined
  apps/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeNoscriptSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionItem.jsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/InAppNotification/PageNotification/ModelNotification.tsx
  apps/app/src/components/InAppNotification/PageNotification/useActionAndMsg.ts
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/InvitedForm.tsx
  apps/app/src/components/Me/DisassociateModal.tsx
  apps/app/src/components/Me/ExternalAccountRow.jsx
  apps/app/src/components/PageAlert/PageRedirectedAlert.tsx
  apps/app/src/components/PageComment/CommentControl.tsx
  apps/app/src/components/PageDeleteModal.tsx
  apps/app/src/components/PageEditor/HandsontableModal.tsx
  apps/app/src/components/RevisionComparer/RevisionComparer.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-pagelist.cy.ts
  packages/remark-lsx/src/client/components/LsxPageList/LsxPage.tsx
Labels: flag/exclude-from-changelog

#8578 imprv: remove user group modal select icon option
  apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
Labels: type/improvement

#8566 imprv: Fix page titles not breaking lines in page view
  apps/app/src/components/Common/PagePathNav/PagePathNav.module.scss
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8576 feat: 137284 141666 refactor icon
  apps/app/src/components/UsersHomepageFooter.tsx
  packages/custom-icons/svg/drawer_io.svg
  packages/custom-icons/svg/format_quote.svg
  packages/custom-icons/svg/header.svg
  packages/custom-icons/svg/recently_created.svg
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
Labels: type/feature

#8581 support: Remove unnecessary tools
  apps/app/bin/cdn/cdn-resources-downloader.ts
  apps/app/bin/download-cdn-resources.ts
  apps/app/config/logger/config.dev.js
  apps/app/resource/cdn-manifests.js
  apps/app/src/interfaces/interceptor-manager.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/services/cdn-resources-service.js
  apps/app/src/services/interceptor-manager.js
  apps/app/src/stores/context.tsx
  apps/app/src/utils/download.ts
  packages/core/src/utils/basic-interceptor.js
  packages/core/src/utils/index.ts
Labels: flag/exclude-from-changelog

#8579 feat: Prevent opening edit modal if revision is outdated
  apps/app/src/components/ReactMarkdownComponents/DrawioViewerWithEditButton.tsx
  apps/app/src/components/ReactMarkdownComponents/TableWithEditButton.tsx
  apps/app/src/stores/page.tsx
Labels: type/feature, flag/exclude-from-changelog

#8571 feat: Resolve conflict from editor
  apps/app/src/client/services/side-effects/page-updated.ts
  apps/app/src/client/services/update-page/conflict.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/conflict.tsx
  apps/app/src/components/PageStatusAlert.tsx
  apps/app/src/server/models/vo/s2c-message.js
  apps/app/src/stores/alert.tsx
  apps/app/src/stores/editor.tsx
Labels: type/feature

#8586 support: Upgrade Next.js v14
  apps/app/config/next-i18next.config.js
  apps/app/next-env.d.ts
  apps/app/next.config.js
  apps/app/package.json
  apps/app/src/components/LoginForm.tsx
  apps/app/src/pages/_app.page.tsx
  apps/app/src/server/crowi/dev.js
  apps/app/src/services/i18next-hmr.ts
  apps/app/tsconfig.build.client.json
  packages/presentation/package.json
  packages/remark-lsx/package.json
  packages/ui/package.json
  yarn.lock
Labels: type/support

#8585 fix: Trash header layout
  apps/app/src/pages/trash.page.tsx
Labels: flag/exclude-from-changelog

#8582 fix: Cannot view past revisionBody in editor
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/components/PageAlert/OldRevisionAlert.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/PageEditorReadOnly.tsx
  apps/app/src/components/PageEditor/ScrollSyncHelper.tsx
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditorReadOnly.tsx
  packages/editor/src/components/index.ts
  packages/editor/src/consts/global-code-mirror-editor-key.ts
Labels: type/bug

#8587 imprv: Supress re-rendering
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
Labels: flag/exclude-from-changelog

#8584 fix: Styling error in the Slack Integration
  apps/app/_obsolete/src/styles/theme/apply-colors.scss
  apps/app/next-env.d.ts
  apps/app/src/components/Admin/SlackIntegration/BotTypeCard.tsx
  apps/app/src/components/Admin/SlackIntegration/Bridge.tsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxyConnectionStatus.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxyConnectionStatus.tsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxyConnectionStatus.tsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/DeleteSlackBotSettingsModal.tsx
  apps/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
  apps/app/src/components/Admin/SlackIntegration/SlackAppIntegrationControl.tsx
  apps/app/src/components/Admin/SlackIntegration/SlackIntegration.tsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  apps/app/src/components/Admin/SlackIntegration/slack-integration-util.ts
  apps/app/src/components/Admin/SlackIntegration/slak-integration-util.js
  apps/app/src/components/Layout/Admin.module.scss
  apps/app/src/pages/admin/slack-integration.page.tsx
  packages/slack/src/interfaces/index.ts
Labels: type/bug

#8598 imprv: Special page layout
  apps/app/src/components/Admin/AuditLog/AuditLogDisableMode.tsx
  apps/app/src/components/Common/PageViewLayout.module.scss
  apps/app/src/components/Common/PageViewLayout.tsx
  apps/app/src/components/Layout/AdminLayout.tsx
  apps/app/src/components/Navbar/GroundGlassBar.module.scss
  apps/app/src/components/Navbar/GroundGlassBar.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.module.scss
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/Navbar/GrowiNavbarBottom.module.scss
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/pages/forgot-password-errors.page.tsx
  apps/app/src/pages/forgot-password.page.tsx
  apps/app/src/pages/maintenance.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/reset-password.page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/styles/_layout.scss
Labels: type/improvement

#8593 imprv: 133920 142527 replace spinner pulse of outside app
  apps/app/src/components/Admin/App/QuestionnaireSettings.tsx
  apps/app/src/components/Admin/AuditLogManagement.tsx
  apps/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  apps/app/src/components/Admin/ElasticsearchManagement/ReconnectControls.tsx
  apps/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
  apps/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/components/DescendantsPageList.tsx
  apps/app/src/components/InAppNotification/InAppNotificationList.tsx
  apps/app/src/components/InAppNotification/InAppNotificationPage.tsx
  apps/app/src/components/InfiniteScroll.tsx
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/InvitedForm.tsx
  apps/app/src/components/LoadingSpinner.tsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Me/QuestionnaireSettings.tsx
  apps/app/src/components/Page/RevisionLoader.tsx
  apps/app/src/components/PageAccessoriesModal/PageAttachment.tsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageControls/BookmarkButtons.tsx
  apps/app/src/components/PageEditor/DrawioModal.tsx
  apps/app/src/components/PageList/PageList.tsx
  apps/app/src/components/PagePresentationModal.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/SearchPage/SearchPageBase.tsx
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/styles/vendor.scss
  apps/app/turbo.json
  packages/remark-attachment-refs/package.json
  packages/remark-attachment-refs/src/client/components/AttachmentList.tsx
  packages/remark-lsx/src/client/components/Lsx.tsx
  packages/ui/package.json
  packages/ui/src/components/LoadingSpinner.module.scss
  packages/ui/src/components/LoadingSpinner.tsx
  packages/ui/src/components/index.ts
Labels: type/improvement

#8589 feat: 37284 141692 replace fa to custom icon
  apps/app/src/components/Admin/Security/SecurityManagementContents.jsx
  apps/app/src/components/LoginForm.tsx
  apps/app/src/components/Me/AssociateModal.tsx
  packages/custom-icons/svg/facebook.svg
  packages/custom-icons/svg/github.svg
  packages/custom-icons/svg/google.svg
  packages/custom-icons/svg/slack.svg
Labels: type/feature, flag/exclude-from-changelog

#8604 fix: Visibility of PageViewReadOnly
  apps/app/src/components/PageEditor/PageEditorReadOnly.tsx
Labels: type/bug

#8605 imprv: Styling publish specific group modal
  apps/app/next-env.d.ts
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/PageEditor/EditorNavbarBottom.module.scss
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8599 feat: Show search icon and footprints on page control when guest user seeing pages
  apps/app/src/components/PageControls/PageControls.tsx
Labels: type/feature

#8609 fix: New welcome markdown
  apps/app/resource/locales/en_US/welcome.md
  apps/app/resource/locales/ja_JP/welcome.md
Labels: flag/exclude-from-changelog

#8594 feat: Reflect update results from view in ydoc
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/socket-io.js
  apps/app/src/server/service/yjs-connection-manager.ts
Labels: type/feature

#8538 imprv: truncate page path when editing
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.tsx
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.module.scss
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.module.scss
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8596 imprv: 137284 142875 original icon font size frexible
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
  apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
  apps/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
  apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
  apps/app/src/components/Me/UISettings.tsx
  apps/app/src/pages/installer.page.tsx
  apps/app/src/styles/_fonts.scss
  packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
Labels: type/improvement

#8601 feat: Update App Title presentation to show confidential
  apps/app/src/components/Admin/App/AppSetting.jsx
  apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
  apps/app/src/components/Sidebar/AppTitle/AppTitle.tsx
Labels: type/feature

#8619 Prepare v7.0.1-RC.0
  CHANGELOG.md
  apps/app/package.json
  apps/slackbot-proxy/package.json
  package.json
  packages/core/package.json
  packages/editor/package.json
  packages/presentation/package.json
  packages/preset-templates/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  yarn.lock
Labels: flag/exclude-from-changelog, type/prepare-next-version

#8628 support: Omit configurations for publishing to GitHub Container Registry(ghcr.io)
  .github/workflows/release-rc.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  .github/workflows/reusable-app-build-image.yml
  apps/app/docker/codebuild/buildspec.yml
Labels: type/support

#8624 fix: Counting comments when removing the thread
  apps/app/src/features/comment/server/models/comment.ts
  apps/app/src/server/routes/comment.js
Labels: type/bug

#8608 fix: Uncorrect update bookmark button clicked on page control
  apps/app/_obsolete/src/styles/theme/_apply-colors-light.scss
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.module.scss
  apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
  apps/app/src/components/DeleteBookmarkFolderModal.tsx
  apps/app/src/stores/page.tsx
Labels: type/bug

#8632 support(ci): bump @azure/identity
  apps/app/package.json
  yarn.lock
Labels: type/support

#8622 support: Automated rc release workflow for master
  .github/workflows/release-rc-scheduled.yml
Labels: type/support, flag/exclude-from-changelog

#8634 imprv: Disable RequestedAuthnContext in SAML authentication
  apps/app/src/server/service/passport.ts
Labels: type/improvement

#8635 imprv: Disable RequestedAuthnContext in SAML authentication (v7.0.x)
  apps/app/src/server/service/passport.ts
Labels: type/improvement

#8636 support: Remove obsolete code
  apps/app/.eslintignore
  apps/app/_obsolete/src/components/PageEditor/CodeMirrorEditor.jsx
  apps/app/_obsolete/src/components/PageEditor/CodeMirrorEditor.module.scss
  apps/app/_obsolete/src/components/PageEditor/CommentMentionHelper.ts
  apps/app/_obsolete/src/components/PageEditor/ConflictDiffModal.tsx
  apps/app/_obsolete/src/components/Sidebar/AppearanceModeDropdown.tsx
  apps/app/_obsolete/src/styles/theme/_apply-colors-dark.scss
  apps/app/_obsolete/src/styles/theme/_apply-colors-light.scss
  apps/app/_obsolete/src/styles/theme/_reboot-toastr-colors.scss
  apps/app/_obsolete/src/styles/theme/apply-colors.scss
  apps/app/src/styles/_mixins.scss
  apps/app/src/styles/atoms/mixins/_buttons.scss
  packages/preset-themes/src/styles/atoms/mixins/_buttons.scss
  packages/preset-themes/src/styles/atoms/mixins/_code.scss
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/src/styles/theme/_hsl-functions.scss
  packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss
Labels: flag/exclude-from-changelog

#8637 imprv: Support color scheme in Page History (diff2html)
  apps/app/package.json
  apps/app/src/components/PageHistory/RevisionDiff.module.scss
  apps/app/src/components/PageHistory/RevisionDiff.tsx
  apps/app/src/components/RevisionComparer/RevisionComparer.module.scss
  apps/app/src/components/RevisionComparer/RevisionComparer.tsx
  yarn.lock
Labels: type/improvement

#8638 fix: Supress PageAccessoriesModal rerendering for keeping radio button selections of PageHistory
  apps/app/src/components/PageHistory/PageRevisionTable.tsx
  apps/app/src/stores/modal.tsx
Labels: type/bug

#8640 fix: Set `d-none` when the sidebar is closed in order to prevent scrollbars from appearing
  apps/app/src/components/Sidebar/Sidebar.tsx
Labels: type/bug

#8641 imprv: PersonalDropdown style
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.module.scss
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.tsx
  apps/app/src/components/Sidebar/SidebarNav/SecondaryItems.module.scss
Labels: type/improvement

#8642 imprv: Prevent tooltip flickering
  apps/app/src/components/PageControls/BookmarkButtons.tsx
  apps/app/src/components/PageControls/LikeButtons.tsx
  apps/app/src/components/PageControls/SeenUserInfo.tsx
  apps/app/src/components/PageControls/SubscribeButton.tsx
  apps/app/src/styles/atoms/_tooltip.scss
  apps/app/src/styles/style-app.scss
Labels: type/improvement

#8643 imprv: PagePathNav and PagePathHeader styles
  apps/app/src/components/Common/PagePathNav/PagePathNav.module.scss
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/PageHeader/PagePathHeader.module.scss
  apps/app/src/components/PageHeader/PagePathHeader.tsx
Labels: type/improvement
