Repository growilabs/growi, pull requests merged in 2024-09, with the labels that each got.

#9059 fix: Input text becomes empty when opening the ReadOnlyEditor
  packages/editor/src/client/components/CodeMirrorEditorReadOnly.tsx
  packages/editor/src/client/stores/codemirror-editor.ts
Labels: type/bug

#9023 imprv: Display page tree in page select modal with scrollbar
  apps/app/src/client/components/PageSelectModal/PageSelectModal.tsx
Labels: type/improvement

#9053 fix: API v3 Page update
  apps/app/src/server/models/user-group-relation.ts
  apps/app/src/server/util/compare-objectId.ts
Labels: type/bug

#9061 imprv: CollapseSidebar (Playwright util)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/21-basic-features-for-guest/access-to-page.spec.ts
  apps/app/playwright/utils/CollapseSidebar.ts
  apps/app/src/client/components/Sidebar/Tag.tsx
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
Labels: type/improvement, flag/exclude-from-changelog

#9063 support: Replace tests with Playwright (50-sidebar/50-sidebar--switching-sidebar-mode.cy.ts)
  apps/app/playwright/50-sidebar/switching-sidebar-mode.spec.ts
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--switching-sidebar-mode.cy.ts
Labels: type/support, flag/exclude-from-changelog

#9064 support: Replace tests with Playwright (50-sidebar/50-sidebar--access-to-side-bar.cy.ts)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/50-sidebar/access-to-sidebar.spec.ts
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts
Labels: flag/exclude-from-changelog

#9043 fix: Scrolling may not occurs when clicking on the edit button next to the header
  yarn.lock
Labels: type/bug, type/improvement

#9066 imprv: Prevent looping to update a hook for TrashPageAlert
  apps/app/src/stores/ui.tsx
Labels: type/improvement

#9065 support: Omit Cypress
  .github/workflows/ci-app-prod.yml
  .github/workflows/reusable-app-prod.yml
  apps/app/.gitignore
  apps/app/cypress.config.ts
  apps/app/package.json
  apps/app/regconfig.json
  apps/app/test/cypress/.eslintrc.js
  apps/app/test/cypress/e2e/0-advanced-examples/misc.cy.ts
  apps/app/test/cypress/e2e/0-advanced-examples/viewport.cy.ts
  apps/app/test/cypress/fixtures/user-admin.json
  apps/app/test/cypress/support/assertions.ts
  apps/app/test/cypress/support/blackout.ts
  apps/app/test/cypress/support/commands.ts
  apps/app/test/cypress/support/index.ts
  apps/app/test/cypress/support/screenshot.ts
  apps/app/test/cypress/tsconfig.json
  bin/github-actions/generate-cypress-spec-arg.mjs
  package.json
  yarn.lock
Labels: type/support

#9069 fix: Return error when grant is string for PUT /_api/v3/page
  apps/app/src/server/routes/apiv3/page/update-page.ts
Labels: type/bug

#9073 fix: Supress rendering too many invisible DropdownMenu components
  apps/app/src/client/components/Bookmarks/BookmarkFolderItemControl.tsx
  apps/app/src/client/components/Bookmarks/BookmarkFolderMenu.tsx
  apps/app/src/client/components/Common/Dropdown/PageItemControl.spec.tsx
  apps/app/src/client/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/client/components/InAppNotification/InAppNotificationDropdown.tsx
Labels: type/bug

#9072 fix: Page content does not update when switching revisions
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/stores/page.tsx
Labels: type/bug

#9071 fix: Unable to navigate to the data transfer page
  apps/app/src/client/components/Admin/G2GDataTransferExportForm.tsx
  apps/app/src/client/components/Admin/ImportData/GrowiArchive/ImportCollectionConfigurationModal.jsx
  apps/app/src/client/components/Admin/ImportData/GrowiArchive/ImportCollectionItem.jsx
  apps/app/src/client/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  apps/app/src/models/admin/growi-archive-import-option.js
  apps/app/src/models/admin/growi-archive-import-option.ts
  apps/app/src/models/admin/import-mode.ts
  apps/app/src/models/admin/import-option-for-pages.ts
  apps/app/src/models/admin/import-option-for-revisions.js
  apps/app/src/models/admin/import-option-for-revisions.ts
  apps/app/src/server/routes/apiv3/import.js
  apps/app/src/server/service/g2g-transfer.ts
  apps/app/src/server/service/import/import-settings.ts
  apps/app/src/server/service/import/import.ts
  apps/app/src/server/service/import/index.ts
  apps/app/src/server/service/import/overwrite-params/index.ts
Labels: type/bug

#9076 fix: issue that material symbols icons are not displayed in ReplyComments component
  apps/app/src/client/components/PageComment/ReplyComments.tsx
Labels: type/bug

#9083 fix: Removing comment doesn't work
  .github/workflows/ci-app.yml
  apps/app/package.json
  apps/app/src/client/components/PageComment.tsx
  apps/app/src/server/routes/comment.js
  apps/app/turbo.json
Labels: type/bug

#9086 fix: Updated content is not reflected on the View screen even after refreshing the page
  apps/app/src/stores/page.tsx
Labels: type/bug

#9100 supoort: Add Playwright test for data transfer
  apps/app/playwright/40-admin/access-to-admin-page.spec.ts
Labels: flag/exclude-from-changelog

#9087 fix: The grant of pages can be changed via api even if restricted
  apps/app/src/interfaces/apiv3/page.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
Labels: type/bug

#9098 imprv: Corrected wording on admin page (/admin/data-transfer)
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/client/components/Admin/G2GDataTransfer.tsx
  apps/app/src/client/components/DataTransferForm.tsx
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#9089 fix: Shared page is not displayed when skipping SSR
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/stores/page.tsx
Labels: type/bug

#9095 imprv: Add hover-activated clipboard copy button with icon
  apps/app/src/components/Common/PagePathNav/PagePathNav.module.scss
  apps/app/src/components/Common/PagePathNav/PagePathNavLayout.tsx
Labels: type/improvement

#9139 support: Update logo image in README.md for the official docker image
  apps/app/docker/README.md
Labels: type/support

#9140 fix: add descendants page list modal spec
  apps/app/src/client/components/CustomNavigation/CustomNav.tsx
  apps/app/src/client/components/DescendantsPageListModal.spec.tsx
Labels: type/bug, flag/exclude-from-changelog

#9141 support: Upgrade @testing-library/react
  apps/app/package.json
  apps/app/src/client/components/Common/Dropdown/PageItemControl.spec.tsx
  yarn.lock
Labels: type/support

#9101 imprv: ROM users can manage comments
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/client/components/NotAvailableForReadOnlyUser.tsx
  apps/app/src/client/components/PageComment.tsx
  apps/app/src/client/components/PageComment/CommentControl.tsx
  apps/app/src/client/components/PageComment/CommentEditor.tsx
  apps/app/src/client/services/AdminGeneralSecurityContainer.js
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/middlewares/exclude-read-only-user.ts
  apps/app/src/server/models/config.ts
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/index.js
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#9144 support: Improve vitest environment
  apps/app/package.json
  apps/app/test-with-vite/download-mongo-binary/vitest.config.ts
  apps/app/vitest.config.components.ts
  apps/app/vitest.config.integ.ts
  apps/app/vitest.config.ts
  apps/app/vitest.workspace.mts
  package.json
  packages/pluginkit/src/v4/utils/template.spec.ts
  packages/pluginkit/vitest.config.ts
  vitest.workspace.mts
  yarn.lock
Labels: type/support

#9106 imprv: Corrected wording on admin page (/admin/data-transfer)
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/client/components/Admin/G2GDataTransfer.tsx
  apps/app/src/client/components/DataTransferForm.tsx
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#9123 fix: Make CustomNavTab responsive
  apps/app/src/client/components/Admin/Notification/NotificationSetting.jsx
  apps/app/src/client/components/CustomNavigation/CustomNav.module.scss
  apps/app/src/client/components/CustomNavigation/CustomNav.tsx
  apps/app/src/client/components/DescendantsPageListModal.module.scss
  apps/app/src/client/components/DescendantsPageListModal.spec.tsx
  apps/app/src/client/components/DescendantsPageListModal.tsx
Labels: type/bug

#9157 imprv: Documentation URL for g2gtransfer
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/src/client/components/Admin/G2GDataTransfer.tsx
  apps/app/src/client/components/DataTransferForm.tsx
  apps/app/src/pages/admin/data-transfer.page.tsx
  apps/app/src/pages/installer.page.tsx
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#9094 fix: PageControls unexpectedly move in response to opening and closing the sidebar
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: type/bug

#9166 imprv: PageTitleHeader max-width
  apps/app/src/client/components/PageHeader/PageTitleHeader.spec.tsx
  apps/app/src/client/components/PageHeader/PageTitleHeader.tsx
  package.json
  yarn.lock
Labels: type/improvement

#9171 fix: Make PageAccessoriesModal responsive
  apps/app/src/client/components/PageAccessoriesModal/PageAccessoriesModal.module.scss
  apps/app/src/client/components/PageAccessoriesModal/PageAccessoriesModal.tsx
Labels: type/bug

#9124 fix: Notification count badge
  apps/app/src/client/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/client/components/InAppNotification/InAppNotificationElm.tsx
  apps/app/src/client/components/InAppNotification/InAppNotificationPage.tsx
  apps/app/src/client/components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx
  apps/app/src/interfaces/in-app-notification.ts
  apps/app/src/migrations/20240924181317-changed-status-in-inappnotifications-from-unread-to-unopened.js
  apps/app/src/server/models/in-app-notification.ts
  apps/app/src/server/routes/apiv3/in-app-notification.ts
  apps/app/src/server/service/in-app-notification.ts
Labels: type/bug
