Repository growilabs/growi, pull requests merged in 2024-11, with the labels that each got.

#9351 support: Stop managing font files with Git LFS
  .devcontainer/postCreateCommand.sh
  .gitattributes
  .github/workflows/reusable-app-prod.yml
  apps/app/docker/Dockerfile
  apps/app/docker/codebuild/buildspec.yml
  apps/app/package.json
  apps/app/resource/fonts/MaterialSymbolsOutlined-opsz,wght,FILL@20..48,300,0..1.woff2
  apps/app/resource/fonts/PressStart2P-latin.woff2
  apps/app/resource/fonts/SourceHanCodeJP-Regular-subset-jis2.woff2
  apps/app/resource/fonts/SourceHanCodeJP-Regular-subset-main.woff2
  apps/app/turbo.json
Labels: type/support

#9350 imprv: Reduce sanitizing
  apps/app/src/services/renderer/recommended-whitelist.spec.ts
  apps/app/src/services/renderer/recommended-whitelist.ts
  apps/app/src/styles/organisms/_wiki.scss
Labels: type/improvement

#9347 feat: Set the maximum number of minutes until the request in an environment variable
  apps/app/src/features/openai/server/services/thread-deletion-cron.ts
  apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts
  apps/app/src/server/service/config-loader.ts
Labels: type/feature

#9355 imprv: Tidy up /Sandbox
  apps/app/resource/locales/en_US/sandbox-markdown.md
  apps/app/resource/locales/en_US/sandbox.md
  apps/app/resource/locales/fr_FR/sandbox-markdown.md
  apps/app/resource/locales/fr_FR/sandbox.md
  apps/app/resource/locales/ja_JP/sandbox-markdown.md
  apps/app/resource/locales/ja_JP/sandbox.md
  apps/app/resource/locales/zh_CN/sandbox-markdown.md
  apps/app/resource/locales/zh_CN/sandbox.md
  apps/app/src/server/service/installer.ts
Labels: type/improvement

#9356 fix: NextLink isCreatablePage always returns false
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
Labels: type/bug

#9149 imprv: Avoid using req.t()
  apps/app/src/server/crowi/express-init.js
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/apiv3/user-activation.ts
  apps/app/src/server/routes/login-passport.js
Labels: type/improvement

#9363 support: Improve playwright report
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright.config.ts
Labels: type/support

#9365 imprv: Open the link of PageTreeItem in a new tab when the user middle click
  apps/app/src/client/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
  apps/app/src/client/components/TreeItem/interfaces/index.ts
Labels: type/improvement

#9348 fix: Duplicate page names alert should not occur on a single page
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/stores/page-listing.tsx
Labels: type/bug

#9372 fix(i18n): i18n for server side
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/login-passport.js
  apps/app/src/server/service/i18next.ts
Labels: type/bug

#9362 feat: Return sources when generating responses (Knowledge assistant)
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
  apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
  apps/app/src/features/openai/server/models/vector-store-file-relation.ts
  apps/app/src/features/openai/server/routes/message.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/services/replace-annotation-with-page-link.ts
  apps/app/src/migrations/20241107172359-rename-pageId-to-page.js
Labels: type/feature

#9376 fix: Add await
  apps/app/src/features/openai/server/services/thread-deletion-cron.ts
  apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts
Labels: flag/exclude-from-changelog

#9377 feat(ai): Swtch summary mode
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
  apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
  apps/app/src/features/openai/server/routes/message.ts
  apps/app/src/features/openai/server/services/assistant/assistant.ts
  apps/app/src/server/service/config-loader.ts
Labels: type/feature

#9383 support: Omit remark-toc
  apps/app/package.json
  apps/app/src/services/renderer/renderer.tsx
  pnpm-lock.yaml
Labels: type/support

#9374 support: Welcome back new Christmas theme
  packages/preset-themes/public/images/christmas/christmas-dark-bg.svg
  packages/preset-themes/public/images/christmas/christmas-light-bg.svg
  packages/preset-themes/public/images/christmas/christmas-navbar.jpg
  packages/preset-themes/public/images/christmas/christmas.jpg
  packages/preset-themes/src/consts/preset-themes.ts
  packages/preset-themes/src/styles/christmas.scss
  packages/preset-themes/vite.themes.config.ts
Labels: type/support

#9371 imprv: Sidebar button displays tooltip
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Sidebar/Custom/CustomSidebar.tsx
  apps/app/src/client/components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx
  apps/app/src/client/components/Sidebar/SidebarNav/PrimaryItem.tsx
  apps/app/src/stores/ui.tsx
Labels: type/improvement

#9388 fix: Output TextDirective and LeafDirective HTML
  apps/app/package.json
  apps/app/src/services/renderer/remark-plugins/echo-directive.ts
  apps/app/src/services/renderer/renderer.tsx
  pnpm-lock.yaml
Labels: type/bug

#9379 fix: i18n for security settings
  apps/app/config/i18next.config.js
  apps/app/package.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Admin/Security/SamlSecuritySettingContents.jsx
  apps/app/src/client/components/InstallerForm.tsx
  apps/app/src/client/util/apiv3-client.ts
  apps/app/src/features/openai/server/services/replace-annotation-with-page-link.ts
  apps/app/src/pages/_app.page.tsx
  apps/app/src/pages/_document.page.tsx
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/routes/apiv3/security-settings/index.js
  apps/app/src/server/routes/login-passport.js
  apps/app/src/server/service/i18next.ts
  apps/app/src/server/util/locale-utils.ts
  packages/editor/package.json
  pnpm-lock.yaml
Labels: type/bug

#9393 support: Type checking
  .vscode/settings.json
  apps/app/package.json
  apps/app/src/server/service/file-uploader/file-uploader.ts
  apps/app/src/services/renderer/recommended-whitelist.ts
  apps/slackbot-proxy/package.json
  package.json
  packages/core/package.json
  packages/editor/package.json
  packages/pluginkit/package.json
  packages/presentation/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  pnpm-lock.yaml
Labels: type/support

#9392 imprv: GitHub Alert with directive syntax
  apps/app/resource/locales/en_US/sandbox-markdown.md
  apps/app/resource/locales/fr_FR/sandbox-markdown.md
  apps/app/resource/locales/ja_JP/sandbox-markdown.md
  apps/app/resource/locales/zh_CN/sandbox-markdown.md
  apps/app/src/features/callout/components/CalloutViewer.tsx
  apps/app/src/features/callout/services/callout.spec.ts
  apps/app/src/features/callout/services/callout.ts
Labels: type/improvement

#9405 fix: Fixed the message when all read
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/fr_FR/commons.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/src/client/components/InAppNotification/InAppNotificationDropdown.tsx
  apps/app/src/client/components/InAppNotification/InAppNotificationPage.tsx
Labels: type/bug

#9407 imprv(ai): GROWI AI Knowledge Assistant instructions
  apps/app/src/server/service/config-loader.ts
Labels: type/improvement

#9410 imprv(ai): Knowedge Assistant model configuration by env var
  apps/app/src/features/openai/server/services/assistant/assistant.ts
  apps/app/src/server/service/config-loader.ts
Labels: type/improvement

#9413 support: Import OpenAI features dynamically
  apps/app/src/features/openai/server/routes/index.ts
  apps/app/src/features/openai/server/routes/message.ts
  apps/app/src/features/openai/server/services/cron/index.ts
  apps/app/src/features/openai/server/services/cron/thread-deletion-cron.ts
  apps/app/src/features/openai/server/services/cron/vector-store-file-deletion-cron.ts
  apps/app/src/features/openai/server/services/index.ts
  apps/app/src/features/openai/server/services/is-ai-enabled.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
Labels: type/support

#9419 imprv(ai): Shorten thread deletion expiredAt
  apps/app/src/features/openai/server/models/thread-relation.ts
  apps/app/src/features/openai/server/services/normalize-data/index.ts
  apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/index.ts
  apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/normalize-thread-relation-expired-at.integ.ts
  apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/normalize-thread-relation-expired-at.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/normalize-data/index.ts
Labels: type/improvement

#9361 imprv: Use stream.pipeline
  apps/app/package.json
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.integ.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/service/export.js
  apps/app/src/server/service/file-uploader/local.ts
  apps/app/src/server/service/growi-bridge/index.ts
  apps/app/src/server/service/import/import.ts
  apps/app/src/server/service/page/delete-completely-user-home-by-system.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  pnpm-lock.yaml
Labels: type/improvement

#9418 imprv: AI Integration page wording
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/features/openai/client/components/AiIntegration/AiIntegrationDisableMode.tsx
Labels: type/improvement, flag/exclude-from-changelog

#9432 imprv: Fonts preload settings
  apps/app/src/client/components/StaffCredit/StaffCredit.tsx
  apps/app/src/components/FontFamily/use-material-symbols-outlined.tsx
  apps/app/src/components/FontFamily/use-source-han-code-jp.tsx
Labels: type/improvement

#9431 support: `@uiw/react-codemirror` in apps/app
  apps/app/package.json
  pnpm-lock.yaml
Labels: type/support, flag/exclude-from-changelog

#9337 fix: Deleted pages appear in the page tree
  apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
Labels: type/bug

#9434 fix: Notification for new user creation
  apps/app/src/server/routes/login.js
Labels: type/bug

#9404 feat(ai): Set a rate limit for vector store rebuild
  apps/app/src/features/rate-limiter/config/index.ts
  apps/app/src/features/rate-limiter/middleware/consume-points.integ.ts
  apps/app/src/features/rate-limiter/middleware/consume-points.ts
  apps/app/src/features/rate-limiter/middleware/factory.ts
  apps/app/src/features/rate-limiter/middleware/rate-limiter-factory.ts
Labels: type/feature

#8715 feat: implementions of announcement creation function
  apps/app/src/features/announcement/client/utils/announcement-utils.ts
  apps/app/src/features/announcement/interfaces/announcement.ts
  apps/app/src/features/announcement/routes/apiv3/announcement.ts
  apps/app/src/features/announcement/server/events/announcement-utils.ts
  apps/app/src/features/announcement/server/models/announcement.ts
  apps/app/src/features/announcement/server/service/announcement.ts
  apps/app/src/interfaces/activity.ts
  apps/app/src/interfaces/announcement.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/index.js
Labels: type/feature

#9444 fix: Failed to export the page markdown
  apps/app/src/server/routes/apiv3/page/index.ts
Labels: type/bug

#9430 imprv: Slim down the sidebar scrollbar
  apps/app/src/client/components/Sidebar/Sidebar.module.scss
  apps/app/src/client/components/Sidebar/Sidebar.tsx
Labels: type/improvement
