Repository growilabs/growi, pull requests merged in 2024-07, with the labels that each got.

#8933 imprv: Add env var for set Elasticsearch reindex bulk size
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/server/service/search.ts
Labels: type/improvement

#8936 imprv: Dark theme support for emoji mart
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  packages/editor/package.json
  packages/editor/src/@types/emoji-mart.d.ts
  packages/editor/src/client/components-internal/CodeMirrorEditor/Toolbar/EmojiButton.tsx
  packages/editor/src/client/services-internal/extensions/emojiAutocompletionSettings.ts
  packages/editor/vite.config.ts
  yarn.lock
Labels: type/improvement

#8938 fix: Page history colorscheme is broken
  apps/app/src/client/components/PageHistory/RevisionDiff.tsx
  apps/app/src/stores/admin/customize.tsx
Labels: type/bug

#8937 imprv: Restrict indexing for full text search when the body length exceeds the threshold
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageView/PageAlerts/FullTextSearchNotCoverAlert.tsx
  apps/app/src/components/PageView/PageAlerts/PageAlerts.tsx
  apps/app/src/features/comment/server/models/comment.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/page-tag-relation.ts
  apps/app/src/server/models/tag.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/search-delegator/aggregate-to-index.ts
  apps/app/src/server/service/search-delegator/bulk-write.d.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#8932 feat: Implement an api client to request sync latest revision body to yjs draft
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/client/services/page-operation.ts
Labels: 4️⃣ phase/WIP

#8941 fix: Presentation section tag
  apps/app/src/client/components/PagePresentationModal.tsx
  apps/app/src/client/services/renderer/renderer.tsx
  packages/presentation/package.json
  packages/presentation/src/client/components/Presentation.global.scss
  packages/presentation/src/client/components/Presentation.module.scss
  packages/presentation/src/client/components/Presentation.tsx
  packages/presentation/src/client/services/growi-marpit.ts
  packages/presentation/src/client/services/renderer/extract-sections.ts
  packages/presentation/src/client/services/sanitize-option.ts
Labels: type/bug

#8935 support: Replace tests with Playwright (20-basic-features/20-basic-features--use-tools)
  apps/app/playwright/20-basic-features/use-tools.spec.ts
  apps/app/src/client/components/PageTags/TagEditModal.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--use-tools.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8942 support: Update GROWI logo type in NoLogin
  apps/app/public/images/growi-brand-logo-login.svg
  apps/app/src/components/Layout/NoLoginLayout.module.scss
  apps/app/src/components/Layout/NoLoginLayout.tsx
Labels: type/support

#8943 imprv: Archive importing and exporting
  apps/app/src/client/components/Admin/ExportArchiveData/ArchiveFilesTable.tsx
  apps/app/src/client/components/Admin/ExportArchiveData/ArchiveFilesTableMenu.tsx
  apps/app/src/client/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/client/components/Admin/ExportArchiveDataPage.tsx
  apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.jsx
  apps/app/src/client/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/client/components/RevisionComparer/RevisionComparer.tsx
Labels: type/improvement

#8944 fix: PageTitleHeader rename input status
  apps/app/src/client/components/PageCreateModal.tsx
  apps/app/src/client/components/PageHeader/PageTitleHeader.tsx
Labels: type/bug

#8946 fix: Initialize sanitize option
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/services/renderer/renderer.tsx
Labels: type/bug

#8940 imprv: lang attribute in Html element to correctly reflect locale
  apps/app/src/pages/_document.page.tsx
  apps/app/src/pages/utils/commons.ts
Labels: type/improvement

#8945 support: Replace tests with Playwright (20-basic-features/20-basic-features--access-to-page.cy.ts)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/20-basic-features/access-to-page.spec.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8948 support: Typescriptize SocketIoService
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/socket-io.ts
Labels: type/support

#8950 support: Rreplace tests with Playwright (23-editor/23-editor--template-modal.cy.ts)
  apps/app/playwright/23-editor/template-modal.spec.ts
  apps/app/src/client/components/TemplateModal/TemplateModal.tsx
  apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8954 support: Typescriptize Revision model
  apps/app/src/client/components/PageHistory/PageRevisionTable.tsx
  apps/app/src/client/components/PageHistory/RevisionDiff.tsx
  apps/app/src/client/components/RevisionComparer/RevisionComparer.tsx
  apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
  apps/app/src/server/models/index.ts
  apps/app/src/server/models/revision.js
  apps/app/src/server/models/revision.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/revisions.js
  apps/app/src/server/routes/tag.js
  apps/app/src/server/service/page/index.ts
  packages/core/src/interfaces/revision.ts
Labels: type/support

#8953 support: Upgrade y-mongodb-provider
  .eslintrc.js
  apps/app/package.json
  apps/app/src/server/service/yjs-connection-manager.ts
  packages/editor/package.json
  yarn.lock
Labels: type/support

#8949 support: Refactor Yjs service
  apps/app/nodemon.json
  apps/app/src/client/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/client/services/side-effects/yjs.ts
  apps/app/src/interfaces/websocket.ts
  apps/app/src/interfaces/yjs.ts
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/socket-io.ts
  apps/app/src/server/service/yjs-connection-manager.ts
  apps/app/src/server/service/yjs.integ.ts
  apps/app/src/server/service/yjs.ts
  apps/app/src/stores/yjs.ts
  packages/pluginkit/src/model/growi-plugin-package-data.ts
Labels: type/support

#8957 support: Update favicon
  apps/app/public/favicon.ico
  apps/app/public/favicon.svg
  apps/app/public/images/icons/favicon/android-icon-144x144.png
  apps/app/public/images/icons/favicon/android-icon-192x192.png
  apps/app/public/images/icons/favicon/android-icon-36x36.png
  apps/app/public/images/icons/favicon/android-icon-48x48.png
  apps/app/public/images/icons/favicon/android-icon-72x72.png
  apps/app/public/images/icons/favicon/android-icon-96x96.png
  apps/app/public/images/icons/favicon/apple-icon-114x114.png
  apps/app/public/images/icons/favicon/apple-icon-120x120.png
  apps/app/public/images/icons/favicon/apple-icon-144x144.png
  apps/app/public/images/icons/favicon/apple-icon-152x152.png
  apps/app/public/images/icons/favicon/apple-icon-180x180.png
  apps/app/public/images/icons/favicon/apple-icon-57x57.png
  apps/app/public/images/icons/favicon/apple-icon-60x60.png
  apps/app/public/images/icons/favicon/apple-icon-72x72.png
  apps/app/public/images/icons/favicon/apple-icon-76x76.png
  apps/app/public/images/icons/favicon/apple-icon-precomposed.png
  apps/app/public/images/icons/favicon/apple-icon.png
  apps/app/public/images/icons/favicon/browserconfig.xml
  apps/app/public/images/icons/favicon/favicon-16x16.png
  apps/app/public/images/icons/favicon/favicon-32x32.png
  apps/app/public/images/icons/favicon/favicon-96x96.png
  apps/app/public/images/icons/favicon/ms-icon-144x144.png
  apps/app/public/images/icons/favicon/ms-icon-150x150.png
  apps/app/public/images/icons/favicon/ms-icon-310x310.png
  apps/app/public/images/icons/favicon/ms-icon-70x70.png
  apps/app/src/pages/_document.page.tsx
Labels: type/support

#8826 fix: Enable # next to headline in view
  apps/app/src/client/components/Page/DisplaySwitcher.tsx
  apps/app/src/client/components/PageEditor/PageEditor.tsx
  apps/app/src/client/components/PageEditor/ScrollSyncHelper.tsx
  apps/app/src/client/components/ReactMarkdownComponents/Header.tsx
  apps/app/src/stores-universal/context.tsx
  apps/app/src/stores/editor.tsx
  packages/editor/src/client/services/use-codemirror-editor/utils/set-caret-line.ts
Labels: type/bug

#8961 fix: Healthcheck with checkServices=mongo
  apps/app/package.json
  apps/app/src/features/questionnaire/server/service/questionnaire.ts
  apps/app/src/migrations/20180927102719-init-serverurl.js
  apps/app/src/migrations/20190618055300-abolish-crowi-classic-auth.js
  apps/app/src/migrations/20190618104011-add-config-app-installed.js
  apps/app/src/migrations/20200420160390-remove-crowi-layout.js
  apps/app/src/migrations/20200512005851-remove-behavior-type.js
  apps/app/src/migrations/20200514001356-update-theme-color-for-dark.js
  apps/app/src/migrations/20200620203632-normalize-locale-id.js
  apps/app/src/migrations/20200827045151-remove-layout-setting.js
  apps/app/src/migrations/20200828024025-copy-aws-setting.js
  apps/app/src/migrations/20200901034313-update-mail-transmission.js
  apps/app/src/migrations/20200903080025-remove-timeline-type.js.js
  apps/app/src/migrations/20200915035234-rename-s3-config.js
  apps/app/src/migrations/20210830074539-update-configs-for-slackbot.js
  apps/app/src/migrations/20211005131430-config-without-proxy-command-permission-for-renaming.js
  apps/app/src/migrations/20220311011114-convert-page-delete-config.js
  apps/app/src/migrations/20221014130200-remove-customize-is-saved-states-of-tab-changes.js
  apps/app/src/migrations/20221219011829-remove-basic-auth-related-config.js
  apps/app/src/migrations/20230213090921-remove-presentation-configurations.js
  apps/app/src/migrations/20230731075753-add_installed_date_to_config.js
  apps/app/src/server/models/config.ts
  apps/app/src/server/routes/apiv3/healthcheck.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/config-manager.spec.ts
  apps/app/src/server/service/config-manager.ts
  yarn.lock
Labels: type/bug

#8939 feat: Sync latest revision body to Yjs draft
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Common/Dropdown/PageItemControl.tsx
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/client/services/page-operation.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/page/sync-latest-revision-body-to-yjs-draft.ts
Labels: type/feature

#8952 support: Rreplace tests with Playwright (23-editor/23-editor--saving.cy.ts)
  apps/app/playwright/23-editor/saving.spec.ts
  apps/app/test/cypress/e2e/23-editor/23-editor--saving.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8970 fix: Disable registerAccessiblePageChecker
  apps/app/src/server/service/yjs/yjs.ts
Labels: type/bug

#8966 imprv: Editing from view
  apps/app/src/client/components/ReactMarkdownComponents/DrawioViewerWithEditButton.tsx
  apps/app/src/client/components/ReactMarkdownComponents/TableWithEditButton.tsx
Labels: type/improvement

#8971 feat: Alerts when trying to sync with latest revision when yjs data is corrupt
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/client/services/page-operation.ts
  apps/app/src/server/routes/apiv3/page/sync-latest-revision-body-to-yjs-draft.ts
  apps/app/src/server/service/yjs/yjs.ts
Labels: type/feature

#8973 support: Normalize Revision.pageId (for #8954)
  apps/app/src/server/models/revision.ts
  apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
  apps/app/src/server/service/normalize-data/index.ts
Labels: type/support

#8975 fix: Hide the sync to the latest revision menu item when not editing
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/client/services/page-operation.ts
  apps/app/src/interfaces/yjs.ts
  apps/app/src/server/service/yjs/yjs.ts
Labels: type/bug

#8977 fix: Handle error when folding drawio blocks
  packages/editor/src/client/services/use-codemirror-editor/utils/fold-drawio.ts
Labels: type/bug

#8978 fix: Sync the editor text with the latest revision menu (2)
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: type/bug

#8965 support: Chage text size in sidebar
  apps/app/src/client/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/client/components/Bookmarks/BookmarkFolderTree.module.scss
  apps/app/src/client/components/InAppNotification/PageNotification/ModelNotification.module.scss
  apps/app/src/client/components/InAppNotification/PageNotification/ModelNotification.tsx
  apps/app/src/client/components/PageList/PageListItemS.module.scss
  apps/app/src/client/components/Sidebar/PageTreeItem/PageTreeItem.module.scss
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.module.scss
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
Labels: type/support

#8987 fix: The $size query when aggregation to rebuild the index
  apps/app/src/server/service/search-delegator/aggregate-to-index.ts
Labels: type/bug

#8855 imprv: User group link in admin page
  apps/app/src/client/components/Admin/UserGroup/UserGroupTable.module.scss
  apps/app/src/client/components/Admin/UserGroup/UserGroupTable.tsx
Labels: type/improvement

#8991 support: Replace possition usericon
  apps/app/src/client/components/Sidebar/SidebarNav/SecondaryItems.tsx
Labels: type/support

#8986 support: Sidebar header text size
  apps/app/src/client/components/Sidebar/Bookmarks.tsx
  apps/app/src/client/components/Sidebar/Custom/CustomSidebar.tsx
  apps/app/src/client/components/Sidebar/InAppNotification/InAppNotification.tsx
  apps/app/src/client/components/Sidebar/PageTree/PageTree.tsx
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChanges.tsx
  apps/app/src/client/components/Sidebar/Sidebar.module.scss
  apps/app/src/client/components/Sidebar/Tag.tsx
Labels: type/support

#8983 support: Replace tests with playwright (23-editor/23-editor--with-navigation.cy.ts)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/23-editor/assets/example.txt
  apps/app/playwright/23-editor/with-navigation.spec.ts
  apps/app/src/client/components/ReactMarkdownComponents/RichAttachment.tsx
  apps/app/src/components/PageView/PageAlerts/PageGrantAlert.tsx
  apps/app/test/cypress/e2e/23-editor/23-editor--with-navigation.cy.ts
Labels: flag/exclude-from-changelog

#8996 fix: Enable page creation under GRANT_RESTRICTED pages
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/service/page-grant.ts
Labels: type/bug

#9001 fix: Non-admin user gets 500 error when opening history modal
  apps/app/src/server/routes/apiv3/customize-setting.js
Labels: type/bug

#8998 fix: Migration script (20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js)
  apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
Labels: type/bug

#9003 fix: Pointer cursor for the create button in the installer
  apps/app/src/client/components/InstallerForm.tsx
Labels: type/bug

#9004 fix: font-family for monospace
  apps/app/src/styles/_fonts.scss
Labels: type/bug

#9000 fix: Some OIDC authentication settings not being applied
  apps/app/src/server/service/passport.ts
Labels: type/bug

#9005 fix: Undo in the comment editor
  apps/app/src/client/components/PageComment/CommentEditor.tsx
  apps/app/src/client/components/PageEditor/PageEditor.tsx
  packages/editor/src/client/components-internal/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/client/components-internal/playground/Playground.tsx
  packages/editor/src/client/components/CodeMirrorEditorMain.tsx
  packages/editor/src/client/services/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/client/stores/codemirror-editor.ts
Labels: type/bug

#9002 feat: Automatically repair corrupted data, at least for the latest revision
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/routes/apiv3/revisions.js
  apps/app/src/server/service/revision/normalize-latest-revision-if-broken.integ.ts
  apps/app/src/server/service/revision/normalize-latest-revision-if-broken.ts
  apps/app/src/server/service/yjs/sync-ydoc.ts
  apps/app/src/server/service/yjs/yjs.integ.ts
  apps/app/src/server/service/yjs/yjs.ts
Labels: type/bug

#9008 fix: Revision pageId schema type
  apps/app/src/client/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  apps/app/src/client/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  apps/app/src/client/components/Me/ProfileImageSettings.tsx
  apps/app/src/client/components/PageComment.tsx
  apps/app/src/client/components/SearchPage/SearchResultContent.tsx
  apps/app/src/features/external-user-group/server/models/external-user-group-relation.ts
  apps/app/src/server/events/user.ts
  apps/app/src/server/interfaces/mongoose-utils.ts
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/models/external-account.ts
  apps/app/src/server/models/named-query.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/password-reset-order.ts
  apps/app/src/server/models/revision.ts
  apps/app/src/server/models/share-link.ts
  apps/app/src/server/models/update-post.ts
  apps/app/src/server/models/user-group-relation.ts
  apps/app/src/server/models/user-group.ts
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/routes/attachment/get.ts
  apps/app/src/server/service/normalize-data/convert-revision-page-id-to-objectid.ts
  apps/app/src/server/service/normalize-data/index.ts
  apps/app/src/server/service/page/delete-completely-user-home-by-system.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/revision/normalize-latest-revision-if-broken.integ.ts
  apps/app/src/server/service/search-delegator/elasticsearch.ts
  apps/app/src/server/util/granted-group.ts
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/v5.non-public-page.test.ts
  packages/core/package.json
  packages/core/src/interfaces/common.spec.ts
  packages/core/src/interfaces/common.ts
  packages/core/src/interfaces/user.ts
Labels: type/bug
