Repository growilabs/growi, pull requests merged in 2024-06, with the labels that each got.

#8871 fix: Supress warning of checkbox 2
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
Labels: type/bug

#8813 imprv: Autofocus on PageTitleHeader when edigin untitled page
  .devcontainer/devcontainer.json
  .github/workflows/ci-app-prod.yml
  .github/workflows/reusable-app-prod.yml
  apps/app/package.json
  apps/app/playwright.config.ts
  apps/app/playwright/.auth/.gitkeep
  apps/app/playwright/.eslintrc.mjs
  apps/app/playwright/.gitignore
  apps/app/playwright/20-basic-features/access-to-page.spec.ts
  apps/app/playwright/20-basic-features/create-page-button.spec.ts
  apps/app/playwright/auth.setup.ts
  apps/app/src/client/services/create-page/use-create-page.tsx
  apps/app/src/components/Common/SubmittableInput/AutosizeSubmittableInput.tsx
  apps/app/src/components/LoginForm/LoginForm.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageEditor/page-path-rename-utils.ts
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/components/Sidebar/PageCreateButton/CreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendToggle.tsx
  apps/app/src/server/service/file-uploader/aws.ts
  apps/app/src/stores/ui.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
  apps/app/test/cypress/e2e/23-editor/23-editor--saving.cy.ts
  package.json
  packages/pluginkit/vitest.config.ts
  yarn.lock
Labels: type/feature

#8869 imprv(plugin): Support github tag in githuburl.ts v6
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
Labels: type/improvement

#8868 imprv(plugin): Support github tag in githuburl.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
Labels: type/improvement

#8875 support: Upgrade turbo to v2
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
  apps/app/docker/Dockerfile
  apps/app/turbo.json
  apps/slackbot-proxy/docker/Dockerfile
  package.json
  packages/custom-icons/turbo.json
  packages/editor/turbo.json
  packages/pluginkit/turbo.json
  packages/preset-themes/turbo.json
  turbo.json
Labels: type/support

#8857 imprv: Behavior when clicking on a label in the dropdown
  apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
Labels: type/improvement

#8874 support: Add playwright test for installer
  .github/workflows/ci-app-prod.yml
  .github/workflows/ci-app.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
  apps/app/playwright.config.ts
  apps/app/playwright/10-installer/install.spec.ts
  apps/app/src/components/InstallerForm.tsx
  apps/app/test/cypress/e2e/10-install/10-install--install.cy.ts
Labels: type/support

#8877 support: Watch with nodemon
  apps/app/nodemon.json
  apps/app/package.json
  apps/app/src/server/.node-dev.json
  apps/slackbot-proxy/package.json
  package.json
  yarn.lock
Labels: type/support

#8878 imprv: DrawioViewerScript should respect the base path in DRAWIO_URI
  apps/app/src/components/Script/DrawioViewerScript/DrawioViewerScript.tsx
  apps/app/src/components/Script/DrawioViewerScript/index.ts
  apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.spec.ts
  apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.ts
Labels: type/improvement

#8880 fix: Behaviour of input during Japanese input
  apps/app/src/components/Admin/App/AppSetting.jsx
Labels: type/bug

#8833 imprv: Styling icon on the side of header
  apps/app/src/components/ReactMarkdownComponents/Header.module.scss
  apps/app/src/components/ReactMarkdownComponents/Header.tsx
  apps/app/src/styles/_layout.scss
  apps/app/src/styles/organisms/_wiki.scss
  packages/ui/src/utils/browser-utils.ts
  packages/ui/src/utils/use-rect.ts
Labels: type/improvement

#8882 support: Replace tests with Playwright (Access to /me page)
  apps/app/nodemon.json
  apps/app/playwright/20-basic-features/access-to-page.spec.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8883 support: Replace tests with Playwright (40-admin/access-to-admin-page)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/40-admin/access-to-admin-page.spec.ts
  apps/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.tsx
  apps/app/test/cypress/e2e/40-admin/40-admin--access-to-admin-page.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8836 fix: Match width of video tag to img tag
  apps/app/src/client/services/renderer/renderer.tsx
  apps/app/src/components/Admin/MarkdownSetting/WhitelistInput.jsx
  apps/app/src/components/Admin/MarkdownSetting/WhitelistInput.tsx
  apps/app/src/components/Admin/MarkdownSetting/XssForm.jsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserFormByInput.tsx
  apps/app/src/interfaces/rehype.ts
  apps/app/src/interfaces/services/rehype-sanitize.ts
  apps/app/src/interfaces/services/renderer.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/crowi/index.js
  apps/app/src/server/models/config.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/routes/apiv3/user-group.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/customize.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/slack-command-handler/create-page-service.js
  apps/app/src/server/service/xss.js
  apps/app/src/services/general-xss-filter/general-xss-filter.spec.ts
  apps/app/src/services/general-xss-filter/general-xss-filter.ts
  apps/app/src/services/general-xss-filter/index.ts
  apps/app/src/services/renderer/recommended-whitelist.spec.ts
  apps/app/src/services/renderer/recommended-whitelist.ts
  apps/app/src/services/renderer/renderer.tsx
  apps/app/src/services/xss/commonmark-spec.js
  apps/app/src/services/xss/index.js
  apps/app/src/services/xss/recommended-whitelist.js
  apps/app/src/services/xss/xssOption.ts
  apps/app/src/stores/xss.ts
  apps/app/src/styles/organisms/_wiki.scss
  apps/app/test/integration/service/page-grant.test.ts
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/v5.non-public-page.test.ts
  apps/app/test/integration/service/v5.page.test.ts
  apps/app/test/integration/service/v5.public-page.test.ts
  apps/app/test/integration/setup-crowi.ts
Labels: type/bug

#8889 imprv: DrawioViewerScript should respect the base path in DRAWIO_URI 2
  apps/app/src/components/Script/DrawioViewerScript/DrawioViewerScript.tsx
  apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.spec.ts
  apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
Labels: type/improvement

#8892 support: Use typescript-transform-paths instead of tsconfig-paths
  apps/app/package.json
  apps/app/tsconfig.build.server-tsc-alias.json
  apps/app/tsconfig.json
  apps/slackbot-proxy/package.json
  apps/slackbot-proxy/tsconfig.json
  package.json
  packages/remark-growi-directive/package.json
  packages/remark-growi-directive/tsconfig.base.json
  packages/remark-growi-directive/tsconfig.build.json
  packages/remark-growi-directive/tsconfig.json
  packages/slack/package.json
  yarn.lock
Labels: type/support

#8895 support: Decrease max SSR body length
  apps/app/src/server/service/config-loader.ts
Labels: type/support

#8898 support: Update module resolution settings
  .changeset/tasty-baboons-burn.md
  apps/app/next-env.d.ts
  apps/app/next.config.js
  apps/app/package.json
  apps/app/test/cypress/tsconfig.json
  apps/app/test/integration/tsconfig.json
  apps/app/test/tsconfig.json
  apps/app/tsconfig.build.client.json
  apps/app/tsconfig.build.server.json
  apps/app/tsconfig.json
  apps/app/turbo.json
  packages/editor/package.json
  packages/editor/tsconfig.json
  packages/editor/tsconfig.node.json
  packages/editor/vite.config.ts
  packages/pluginkit/tsconfig.json
  tsconfig.base.json
  yarn.lock
Labels: type/support

#8900 fix: Set `z-0` to correct navbar and header overlap when the anchor is specified
  apps/app/src/components/Common/PageViewLayout.tsx
Labels: type/bug

#8890 support: Replace tests with playwright (60-home/60-home--home)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright.config.ts
  apps/app/playwright/60-home/home.spec.ts
  apps/app/src/components/Me/AssociateModal.tsx
  apps/app/src/components/Me/PersonalSettings.jsx
  apps/app/test/cypress/e2e/60-home/60-home--home.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8896 fix: Minimum number of characters in password cannot be changed
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/util/t-with-opt.ts
  apps/app/src/components/InstallerForm.tsx
  apps/app/src/components/LoginForm/LoginForm.tsx
  apps/app/src/pages/installer.page.tsx
  apps/app/src/pages/login/index.page.tsx
  apps/app/src/server/middlewares/login-form-validator.ts
  apps/app/src/server/middlewares/register-form-validator.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/routes/apiv3/installer.ts
Labels: type/bug

#8891 feat: New marker color
  apps/app/src/components/SearchPage/SearchPageBase.module.scss
  apps/app/src/styles/_marker.scss
  apps/app/src/styles/_variables.scss
  apps/app/src/styles/style-app.scss
  packages/preset-themes/src/styles/antarctic.scss
  packages/preset-themes/src/styles/blackboard.scss
  packages/preset-themes/src/styles/classic.scss
  packages/preset-themes/src/styles/default.scss
  packages/preset-themes/src/styles/fire-red.scss
  packages/preset-themes/src/styles/future.scss
  packages/preset-themes/src/styles/halloween.scss
  packages/preset-themes/src/styles/hufflepuff.scss
  packages/preset-themes/src/styles/jade-green.scss
  packages/preset-themes/src/styles/nature.scss
  packages/preset-themes/src/styles/wood.scss
Labels: type/feature

#8903 support: Replace tests with playwright (20-basic-features/20-basic-features--click-page-icons)
  apps/app/playwright/20-basic-features/click-page-icons.spec.ts
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--click-page-icons.cy.ts
Labels: type/support

#8905 fix: Set `z-0` to correct navbar and header overlap when the anchor is specified
  apps/app/src/components/Common/PageViewLayout.tsx
Labels: type/bug

#8879 fix: Missing HTTP Response in SAML Login With ABLC Callback
  apps/app/src/components/LoginForm/LoginForm.tsx
  apps/app/src/interfaces/errors/external-account-login-error.ts
  apps/app/src/pages/login/index.page.tsx
  apps/app/src/server/routes/login-passport.js
Labels: type/bug

#8885 support: Replace tests with playwright (21-basic-features-for-guest/21-basic-features-for-guest--access-to-page)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright.config.ts
  apps/app/playwright/21-basic-features-for-guest/access-to-page.spec.ts
  apps/app/playwright/utils/CollapseSidebar.ts
  apps/app/playwright/utils/index.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8907 support: Replace tests with playwright (20-basic-features/20-basic-features--access-to-pagelist)
  apps/app/playwright/20-basic-features/access-to-pagelist.spec.ts
  apps/app/src/components/DescendantsPageListModal.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-pagelist.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8908 support: Replace tests with Playwright (20-basic-features/20-basic-features--comments)
  apps/app/playwright/20-basic-features/comments.spec.ts
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8901 fix: Vim keymap works correctly
  apps/app/src/stores/alert.tsx
  apps/app/src/stores/modal.tsx
Labels: type/bug

#8909 support: Replace tests with Playwright (21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest)
  apps/app/playwright/21-basic-features-for-guest/sticky-for-guest.spec.ts
  apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest.cy.ts
Labels: flag/exclude-from-changelog

#8911 support: Replace tests with Playwright (22-sharelink/22-sharelink--access-to-sharelink)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/22-sharelink/access-to-sharelink.spec.ts
  apps/app/playwright/auth.setup.ts
  apps/app/playwright/utils/Login.ts
  apps/app/playwright/utils/index.ts
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkList.tsx
  apps/app/src/components/Sidebar/SidebarNav/PersonalDropdown.tsx
  apps/app/test/cypress/e2e/22-sharelink/22-sharelink--access-to-sharelink.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8913 support: Replace tests with Playwright (20-basic-features/20-basic-features--sticky-features.cy.ts)
  apps/app/playwright/20-basic-features/click-page-icons.spec.ts
  apps/app/playwright/20-basic-features/sticky-features.spec.ts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts
Labels: type/support, flag/exclude-from-changelog

#8921 support: Upgrade playwright
  package.json
  yarn.lock
Labels: type/support

#8920 support: Upgrade vitest
  apps/app/package.json
  apps/app/vitest.config.components.ts
  apps/app/vitest.config.integ.ts
  apps/app/vitest.config.ts
  package.json
  yarn.lock
Labels: type/support

#8924 imprv: Button opacity of TableWithEditButton and DrawioViewerWithEditButton
  apps/app/src/client/components/ReactMarkdownComponents/DrawioViewerWithEditButton.module.scss
  apps/app/src/client/components/ReactMarkdownComponents/DrawioViewerWithEditButton.tsx
  apps/app/src/client/components/ReactMarkdownComponents/TableWithEditButton.module.scss
  apps/app/src/components/PageView/PageView.module.scss
  apps/app/src/components/PageView/PageView.tsx
Labels: type/improvement

#8923 imprv: Size for skeleton for tags
  apps/app/src/client/components/PageTags/PageTags.tsx
  apps/app/src/client/components/PageTags/TagLabels.module.scss
Labels: type/improvement

#8925 imprv: Rename label for bookmark item
  apps/app/src/client/components/Bookmarks/BookmarkItem.tsx
Labels: type/bug
