Repository growilabs/growi, pull requests merged in 2024-04, with the labels that each got.

#8615 imprv: wip Improved white space
  apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx
Labels: type/improvement, flag/exclude-from-changelog

#8648 fix: Login buttons for external auth provider does not work
  apps/app/src/components/CompleteUserRegistration.tsx
  apps/app/src/components/LoginForm/ExternalAuthButton.tsx
  apps/app/src/components/LoginForm/LoginForm.module.scss
  apps/app/src/components/LoginForm/LoginForm.tsx
  apps/app/src/components/LoginForm/index.ts
  apps/app/src/pages/login/index.page.tsx
  packages/core/src/interfaces/external-account.ts
Labels: type/bug

#8651 fix: Login form style is broken
  apps/app/src/components/LoginForm/LoginForm.module.scss
Labels: type/bug

#8652 support: Add light and dark badge color
  packages/core/scss/bootstrap/override/helpers/_color-bg.scss
Labels: type/support

#8656 fix: Custom logo style
  apps/app/src/components/Sidebar/SidebarBrandLogo.tsx
Labels: type/bug

#8655 fix: Admin users badge color in /admin/users
  apps/app/src/components/Admin/UserManagement.tsx
  apps/app/src/components/Admin/Users/UserTable.tsx
Labels: type/bug

#8658 Prepare v6.3.4
  CHANGELOG.md
  apps/app/package.json
  package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/presentation/package.json
  packages/preset-templates/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  yarn.lock
Labels: flag/exclude-from-changelog, type/prepare-next-version

#8659 Prepare v6.3.4
  apps/app/package.json
  apps/slackbot-proxy/package.json
  package.json
  packages/core/package.json
  packages/hackmd/package.json
  packages/presentation/package.json
  packages/preset-templates/package.json
  packages/preset-themes/package.json
  packages/remark-attachment-refs/package.json
  packages/remark-drawio/package.json
  packages/remark-growi-directive/package.json
  packages/remark-lsx/package.json
  packages/slack/package.json
  packages/ui/package.json
  yarn.lock
Labels: flag/exclude-from-changelog, type/prepare-next-version

#8664 fix: Cannot display error when page path is duplicated
  apps/app/src/components/TreeItem/NewPageInput/NewPageInput.tsx
Labels: type/bug

#8668 imprv: Enable box-shadow
  packages/core/scss/bootstrap/_variables.scss
Labels: type/improvement

#8670 imprv: Set font-display to icon fonts
  apps/app/src/components/FontFamily/use-growi-custom-icons.tsx
  apps/app/src/components/FontFamily/use-lato.tsx
  apps/app/src/components/FontFamily/use-material-symbols-outlined.tsx
  apps/app/src/components/FontFamily/use-source-han-code-jp.tsx
Labels: type/improvement

#8671 imprv: Add border to the page title header when editing
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.module.scss
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
Labels: type/improvement

#8536 imprv: 136128 hide title of untitled page
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/server/routes/apiv3/page/create-page.ts
Labels: type/improvement

#8680 fix: Add filePath to the schema of attachement for backward compatibility for v3.3 or earlier (v6.3.x)
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/service/file-uploader/aws.ts
Labels: type/bug

#8631 imprv: New Comment style
  apps/app/_obsolete/src/styles/theme/apply-colors.scss
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/Comments.tsx
  apps/app/src/components/PageComment.module.scss
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/Comment.module.scss
  apps/app/src/components/PageComment/Comment.tsx
  apps/app/src/components/PageComment/CommentControl.tsx
  apps/app/src/components/PageComment/CommentEditor.module.scss
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageComment/CommentPreview.module.scss
  apps/app/src/components/PageComment/CommentPreview.tsx
  apps/app/src/components/PageComment/ReplyComments.module.scss
  apps/app/src/components/PageComment/ReplyComments.tsx
  apps/app/src/components/PageComment/SwitchingButtonGroup.module.scss
  apps/app/src/components/PageComment/SwitchingButtonGroup.tsx
  apps/app/src/components/PageComment/_comment-inheritance.scss
  apps/app/src/components/PageEditor/_page-editor-inheritance.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/stores/codemirror-editor.ts
Labels: type/improvement

#8684 support: Upgrade actions from v3 to v4
  .github/workflows/ci-app.yml
  .github/workflows/ci-slackbot-proxy.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/list-unhealthy-branches.yml
  .github/workflows/release-rc-scheduled.yml
  .github/workflows/release-rc.yml
  .github/workflows/release-slackbot-proxy.yml
  .github/workflows/release.yml
  .github/workflows/reusable-app-build-image.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
Labels: type/support

#8672 fix: react-toastify colors
  apps/app/src/client/util/toastr.ts
  apps/app/src/components/Layout/RawLayout.module.scss
  apps/app/src/components/Layout/RawLayout.tsx
Labels: type/bug

#8629 imprv: Border in search modal
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/components/SearchResultMenuItem.tsx
Labels: type/improvement

#8645 fix: Page content preview not shown in duplicate alert page
  apps/app/src/client/util/apiv3-client.ts
  apps/app/src/features/external-user-group/server/models/external-user-group-relation.ts
  apps/app/src/server/models/page.ts
  apps/app/src/server/models/user-group-relation.ts
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/stores/page-listing.tsx
Labels: type/bug

#8688 support: Upgrade actions from v3 to v4 (2)
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
Labels: type/support

#8689 support: Commonize upload-attachments operation
  apps/app/src/client/services/upload-attachments/index.ts
  apps/app/src/client/services/upload-attachments/upload-attachments.ts
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/interfaces/apiv3/attachment.ts
  apps/app/src/interfaces/attachment.ts
  apps/app/src/server/service/file-uploader/file-uploader.ts
Labels: flag/exclude-from-changelog

#8678 fix: Footnotes making page scrollable.
  apps/app/src/components/PageEditor/ScrollSyncHelper.tsx
  apps/app/src/services/renderer/rehype-plugins/add-line-number-attribute.ts
  apps/app/src/styles/organisms/_wiki.scss
Labels: type/bug

#8425 fix: Cypress test
  .github/workflows/ci-app-prod.yml
  .github/workflows/reusable-app-prod.yml
  apps/app/src/components/Sidebar/PageCreateButton/CreateButton.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendMenu.tsx
  apps/app/src/components/Sidebar/PageCreateButton/DropendToggle.tsx
  apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
  apps/app/src/components/Sidebar/Tag.tsx
  apps/app/test/cypress/e2e/23-editor/23-editor--saving.cy.ts
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts
Labels: flag/exclude-from-changelog

#8682 fix: Tags are unintentionally created when a conversion is finalized
  apps/app/src/components/PageTags/TagsInput.tsx
Labels: type/bug

#8570 imprv: Disable groups not assignable to page due to parent grant
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/server/models/user-group-relation.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/service/page-grant.ts
  apps/app/src/stores/page.tsx
Labels: type/improvement

#8701 fix: Failed upload cypress test result screenshots
  .github/workflows/ci-app-prod.yml
  .github/workflows/reusable-app-prod.yml
  .github/workflows/reusable-app-reg-suit.yml
Labels: type/bug, flag/exclude-from-changelog

#8702 fix: Cypress test (22-sharelink)
  apps/app/test/cypress/e2e/20-basic-features/20-basic-features--use-tools.cy.ts
  apps/app/test/cypress/e2e/22-sharelink/22-sharelink--access-to-sharelink.cy.ts
Labels: type/bug, flag/exclude-from-changelog

#8700 imprv: WIP Page behavior
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/interfaces/apiv3/page.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
Labels: type/improvement

#8520 feat: Multipart upload page export
  apps/app/package.json
  apps/app/src/features/page-bulk-export/server/routes/apiv3/page-bulk-export.ts
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export.ts
  apps/app/src/server/service/file-uploader/aws/index.ts
  apps/app/src/server/service/file-uploader/aws/multipart-upload.ts
  apps/app/src/server/util/stream.ts
  yarn.lock
Labels: type/feature

#8694 support: Localize comment components
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/components/PageComment/SwitchingButtonGroup.module.scss
  apps/app/src/components/PageComment/SwitchingButtonGroup.tsx
  apps/app/src/components/SlackNotification.tsx
Labels: type/support

#8681 feat: Mark to check for the presence of drafts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
Labels: type/feature

#8667 feat: refs #143808/134809: OpenTelemetry で GROWI から Trace/Metrics を吐き出せる
  .devcontainer/docker-compose.yml
  apps/app/package.json
  apps/app/src/server/crowi/index.js
  apps/app/src/server/crowi/opentelemetry.ts
  yarn.lock
Labels: type/feature

#8691 fix: lsx icon layout and color
  packages/remark-lsx/src/client/components/Lsx.tsx
  packages/remark-lsx/src/client/components/LsxPageList/LsxListView.module.scss
  packages/remark-lsx/src/client/components/LsxPageList/LsxPage.tsx
Labels: type/bug

#8704 fix: Cypress test (23-editor)
  apps/app/src/components/PageEditor/Preview.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts
  apps/app/test/cypress/e2e/23-editor/23-editor--with-navigation.cy.ts
  packages/editor/src/components/CodeMirrorEditor/Toolbar/TemplateButton.tsx
Labels: type/bug, flag/exclude-from-changelog

#8705 imprv: search results form improvements
  apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
  apps/app/src/components/SearchPage/SearchControl.tsx
  apps/app/src/components/SearchPage/SearchModalTriggerinput.tsx
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/stores/search.ts
Labels: type/improvement

#8711 imprv: Sm size dropdown menu
  apps/app/src/components/PageControls/PageControls.tsx
Labels: type/improvement

#8695 imprv: Show unrelated groups and disable ungrantable groups in grant select
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/SavePageControls.tsx
  apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx
  apps/app/src/components/SavePageControls/GrantSelector/use-my-user-groups.ts
  apps/app/src/features/external-user-group/client/stores/external-user-group.ts
  apps/app/src/interfaces/page.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/models/user-group-relation.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/routes/apiv3/me.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/service/page-grant.ts
  apps/app/src/stores/page.tsx
  apps/app/src/stores/ui.tsx
  apps/app/src/stores/user-group.tsx
  apps/app/test/integration/service/page-grant.test.ts
Labels: type/improvement

#8707 imprv: Truncate page path title in view
  apps/app/src/components/Common/CopyDropdown/CopyDropdown.jsx
  apps/app/src/components/Common/PagePathNav/PagePathNav.module.scss
  apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/interfaces/user-ui-settings.ts
  apps/app/src/server/models/user-ui-settings.ts
  apps/app/src/stores/ui.tsx
Labels: type/improvement

#8716 support: Localize in app
  apps/app/public/static/locales/en_US/commons.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/ja_JP/commons.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/commons.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/AuthorInfo/AuthorInfo.tsx
  apps/app/src/components/Common/CopyDropdown/CopyDropdown.jsx
  apps/app/src/components/ContentLinkButtons.tsx
  apps/app/src/components/PageHistory/Revision.tsx
  apps/app/src/components/PageSideContents/PageSideContents.tsx
  apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
  apps/app/src/components/UsersHomepageFooter.tsx
Labels: type/support

#8633 fix: Initialize grant correctly after when page transition
  apps/app/src/client/services/page-operation.ts
Labels: type/bug

#8717 fix: Login layout when external auth only
  apps/app/src/components/LoginForm/LoginForm.tsx
Labels: type/bug

#8714 feat: can specify otel config from config manager
  apps/app/src/server/crowi/index.js
  apps/app/src/server/crowi/opentelemetry.ts
  apps/app/src/server/service/config-loader.ts
Labels: type/feature

#8731 imprv: Comment editor performance
  apps/app/src/components/Comments.tsx
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
  apps/app/src/components/SearchPage/SearchResultContent.tsx
  apps/app/src/server/routes/comment.js
  apps/app/src/stores/comment.tsx
  apps/app/src/stores/ui.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/consts/global-code-mirror-editor-key.ts
Labels: type/improvement

#8720 fix: 139426 page rename modal content margin
  apps/app/src/components/PageRenameModal.tsx
Labels: type/bug, flag/exclude-from-changelog

#8723 fix: CopyDropdown hidden behind modal issue
  apps/app/src/components/Common/CopyDropdown/CopyDropdown.jsx
Labels: type/bug, flag/exclude-from-changelog

#8741 fix: Close the comment editor after the post
  apps/app/src/components/Comments.tsx
  apps/app/src/components/PageComment.tsx
  apps/app/src/components/PageComment/Comment.tsx
  apps/app/src/components/PageComment/CommentEditor.tsx
Labels: type/bug

#8742 fix: Editor styles
  apps/app/src/components/PageComment/CommentEditor.module.scss
  packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
  packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
  packages/editor/src/components/CodeMirrorEditorComment.tsx
Labels: type/bug

#8744 support: Upgrade date-fns
  apps/app/package.json
  apps/app/src/components/Admin/AuditLog/ActivityTable.tsx
  apps/app/src/components/Admin/AuditLogManagement.tsx
  apps/app/src/components/Admin/ExportArchiveData/ArchiveFilesTable.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx
  apps/app/src/components/Admin/Users/ExternalAccountTable.tsx
  apps/app/src/components/Admin/Users/UserTable.tsx
  apps/app/src/components/AuthorInfo/AuthorInfo.tsx
  apps/app/src/components/Me/ExternalAccountRow.jsx
  apps/app/src/components/PageAccessoriesModal/ShareLink/ShareLinkList.tsx
  apps/app/src/components/PageAlert/TrashPageAlert.tsx
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/components/PageCreateModal.tsx
  apps/app/src/components/PageEditor/ConflictDiffModal.tsx
  apps/app/src/components/PageList/PageListItemL.tsx
  apps/app/src/components/Sidebar/PageCreateButton/hooks/use-create-todays-memo.tsx
  apps/app/src/components/TemplateModal/use-formatter.tsx
  apps/app/src/components/User/UserDate.jsx
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/models/obsolete-page.js
  apps/app/src/server/models/page-operation.ts
  apps/app/src/server/models/password-reset-order.ts
  apps/app/src/server/models/user-registration-order.ts
  apps/app/src/server/service/config-loader.ts
  apps/app/src/server/service/config-manager.ts
  apps/app/src/server/service/in-app-notification.ts
  apps/app/src/server/service/installer.ts
  apps/app/test/integration/service/v5.page.test.ts
  apps/slackbot-proxy/package.json
  apps/slackbot-proxy/src/controllers/growi-to-slack.ts
  apps/slackbot-proxy/src/entities/relation.ts
  apps/slackbot-proxy/src/services/RelationsService.ts
  packages/slack/package.json
  packages/slack/src/utils/generate-last-update-markdown.ts
  packages/ui/package.json
  packages/ui/src/components/Attachment.tsx
  yarn.lock
Labels: type/support

#8738 support: Adjust design details
  apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
  apps/app/src/components/Bookmarks/BookmarkItem.tsx
  apps/app/src/components/ContentLinkButtons.tsx
  apps/app/src/components/PageSideContents/PageAccessoriesControl.module.scss
  apps/app/src/components/PageSideContents/PageAccessoriesControl.tsx
  apps/app/src/components/Sidebar/Sidebar.module.scss
  apps/app/src/components/TagList.tsx
  apps/app/src/components/TreeItem/SimpleItem.tsx
Labels: type/support

#8746 fix: Error on today's memo create from hotkey when memo exists
  apps/app/src/server/routes/apiv3/page/check-page-existence.ts
Labels: type/bug

#8743 support: Upgrade vite and vitest
  .devcontainer/devcontainer.json
  .vscode/launch.json
  apps/app/src/components/Admin/AuditLog/ActivityTable.tsx
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/server/.node-dev.json
  apps/app/src/server/crowi/express-init.js
  apps/app/src/server/service/config-manager.spec.ts
  apps/app/src/server/service/customize.ts
  package.json
  packages/pluginkit/vitest.config.ts
  packages/preset-themes/src/index.ts
  packages/ui/src/components/UserPicture.tsx
  vitest.workspace.ts
  yarn.lock
Labels: type/support

#8734 fix: CopyDropdown protrudes from the screen issue
  apps/app/src/components/Common/CopyDropdown/CopyDropdown.jsx
  apps/app/src/components/Common/CopyDropdown/CopyDropdown.module.scss
Labels: type/bug

#8750 fix: Word break does not work with long code block
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
Labels: type/bug

#8730 fix: Always autofocus when moving to the Editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
Labels: type/bug

#8708 feat: Implementation to retrieve the existence of drafts in Yjs
  apps/app/src/client/services/side-effects/yjs-draft.ts
  apps/app/src/components/Navbar/PageEditorModeManager.tsx
  apps/app/src/components/Page/DisplaySwitcher.tsx
  apps/app/src/interfaces/page.ts
  apps/app/src/interfaces/websocket.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/socket-io.js
  apps/app/src/server/service/yjs-connection-manager.ts
  apps/app/src/stores/page.tsx
  apps/app/src/stores/websocket.tsx
Labels: type/feature

#8749 fix: Material and Eclipse colors
  packages/editor/src/services/editor-theme/.eslintrc.cjs
  packages/editor/src/services/editor-theme/eclipse.ts
  packages/editor/src/services/editor-theme/index.ts
  packages/editor/src/services/editor-theme/material.ts
Labels: type/bug

#8748 fix: Nord and Original-dark theme in editor
  packages/editor/src/services/editor-theme/index.ts
  packages/editor/src/services/editor-theme/nord.ts
  packages/editor/src/services/editor-theme/original-dark.ts
Labels: type/bug

#8753 fix: Codeblock overflow
  apps/app/src/components/Layout/BasicLayout.tsx
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
  apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx
Labels: type/bug

#8755 fix: Cypress test (50-sidebar--access-to-side-bar.cy.ts)
  apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts
Labels: type/bug

#8727 fix: ts error about type of ejs
  apps/app/src/server/service/mail.ts
Labels: type/bug, flag/exclude-from-changelog

#8754 imprv: behaviour when pressing enter after numerical input (ex: 2.3.4.)
  packages/editor/src/services/list-util/insert-newline-continue-markup.ts
Labels: type/improvement

#8699 imprv: FootstrampIcon uses material symbols
  packages/ui/scss/molecules/_page_list.scss
  packages/ui/src/components/FootstampIcon.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
  packages/ui/src/components/index.ts
Labels: type/improvement

#8757 support: Localize in app tags language en change ja ch revision
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/components/PageControls/PageControls.tsx
Labels: type/support

#8759 fix: Parent group selection dropdown does not work
  apps/app/src/components/Admin/UserGroup/UserGroupForm.tsx
Labels: type/bug

#8758 fix: Tags are not created when space key is entered (Firefox)
  apps/app/src/components/PageTags/TagsInput.tsx
Labels: type/bug

#8752 fix: EditingUserList shows user icons even when the user is not opening the editor
  apps/app/src/components/PageEditor/PageEditor.tsx
  packages/editor/src/components/CodeMirrorEditorMain.tsx
  packages/editor/src/components/playground/Playground.tsx
  packages/editor/src/stores/use-collaborative-editor-mode.ts
Labels: type/bug

#8756 fix: Behaviour of table operation by enter key in editor
  packages/editor/src/services/table-util/insert-new-row-to-table-markdown.ts
Labels: type/bug

#8760 support: Editor mobile appearance
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageEditor/EditorNavbar/EditingUserList.tsx
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.module.scss
  apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.tsx
  apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
Labels: type/support

#8763 support: Improve types in IPage and IRevision
  apps/app/src/client/services/layout.ts
  apps/app/src/components/AuthorInfo/AuthorInfo.tsx
  apps/app/src/components/ContentLinkButtons.tsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageAuthorInfo/PageAuthorInfo.tsx
  apps/app/src/components/PageContentFooter.tsx
  apps/app/src/components/User/Username.tsx
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/stores/remote-latest-page.ts
  packages/core/src/interfaces/common.ts
  packages/core/src/interfaces/page.ts
  packages/core/src/interfaces/revision.ts
Labels: type/support

#8726 imprv: Truncate page path title in editor
  apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.module.scss
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.module.scss
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
Labels: type/improvement

#8762 fix: Editor theme active line (material, nord)
  packages/editor/src/services/editor-theme/material.ts
  packages/editor/src/services/editor-theme/nord.ts
Labels: type/bug

#8766 support: Update modal header design
  apps/app/src/components/Admin/App/ConfirmModal.tsx
  apps/app/src/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ErrorViewer.tsx
  apps/app/src/components/Admin/ImportData/GrowiArchive/ImportCollectionConfigurationModal.jsx
  apps/app/src/components/Admin/Notification/NotificationDeleteModal.jsx
  apps/app/src/components/Admin/Security/DeleteAllShareLinksModal.jsx
  apps/app/src/components/Admin/Security/LdapAuthTestModal.jsx
  apps/app/src/components/Admin/SlackIntegration/ConfirmBotChangeModal.jsx
  apps/app/src/components/Admin/SlackIntegration/DeleteSlackBotSettingsModal.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
  apps/app/src/components/Admin/UserGroup/UserGroupModal.tsx
  apps/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
  apps/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.tsx
  apps/app/src/components/Admin/Users/PasswordResetModal.jsx
  apps/app/src/components/Admin/Users/UserInviteModal.jsx
  apps/app/src/components/Common/ImageCropModal.tsx
  apps/app/src/components/CreateTemplateModal.tsx
  apps/app/src/components/DeleteBookmarkFolderModal.tsx
  apps/app/src/components/EmptyTrashModal.tsx
  apps/app/src/components/Me/AssociateModal.tsx
  apps/app/src/components/Me/DisassociateModal.tsx
  apps/app/src/components/PageAlert/FixPageGrantAlert.tsx
  apps/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
  apps/app/src/components/PageComment/DeleteCommentModal.tsx
  apps/app/src/components/PageCreateModal.tsx
  apps/app/src/components/PageDuplicateModal.tsx
  apps/app/src/components/PageEditor/GridEditModal.jsx
  apps/app/src/components/PageEditor/LinkEditModal.tsx
  apps/app/src/components/PageRenameModal.tsx
  apps/app/src/components/PrivateLegacyPages.tsx
  apps/app/src/components/PrivateLegacyPagesMigrationModal.tsx
  apps/app/src/components/PutbackPageModal.jsx
  apps/app/src/components/SearchPage/SearchOptionModal.tsx
  apps/app/src/components/ShortcutsModal.tsx
  apps/app/src/components/TemplateModal/TemplateModal.tsx
  apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
Labels: type/support

#8765 fix: Admin customize screen
  apps/app/src/components/Admin/Common/AdminNavigation.module.scss
  apps/app/src/components/Admin/Common/AdminNavigation.tsx
  apps/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
  apps/app/src/components/Admin/Customize/CustomizeThemeOptions.tsx
  apps/app/src/components/Admin/Customize/ThemeColorBox.module.scss
  apps/app/src/components/Admin/Customize/ThemeColorBox.tsx
  apps/app/src/components/Layout/Admin.module.scss
  apps/app/src/interfaces/sidebar-config.ts
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/_private-legacy-pages.page.tsx
  apps/app/src/pages/_search.page.tsx
  apps/app/src/pages/me/[[...path]].page.tsx
  apps/app/src/pages/tags.page.tsx
  apps/app/src/pages/trash.page.tsx
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/models/config.ts
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/stores/admin/sidebar-config.tsx
Labels: type/bug

#8775 imprv: Re-calculate max-width for page tile on editor
  apps/app/src/components/PageControls/PageControls.tsx
  apps/app/src/components/PageHeader/PageHeader.tsx
  apps/app/src/components/PageHeader/PagePathHeader.tsx
  apps/app/src/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/interfaces/user-ui-settings.ts
  apps/app/src/server/models/user-ui-settings.ts
  apps/app/src/stores/ui.tsx
Labels: type/improvement
