Repository growilabs/growi, pull requests merged in 2024-08, with the labels that each got.

#9009 fix: Hide WideViewMenuItem in search result
  apps/app/src/client/components/PageControls/PageControls.tsx
  apps/app/src/client/components/SearchPage/SearchResultContent.tsx
Labels: type/bug

#9011 fix: Wrongly autofocus to PageHeader even after updating
  apps/app/src/client/components/PageEditor/PageEditor.tsx
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/client/services/update-page/index.ts
  apps/app/src/client/services/update-page/update-page.ts
  apps/app/src/client/services/update-page/use-update-page.tsx
Labels: type/bug

#9013 support: Typescriptize REPL launcher
  apps/app/package.json
  apps/app/src/server/console.js
  apps/app/src/server/repl.ts
Labels: type/support

#8960 imprv: lang attribute in Html element
  apps/app/src/pages/_app.page.tsx
  apps/app/src/pages/_document.page.tsx
  apps/app/src/pages/utils/commons.ts
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/locale.ts
Labels: type/improvement

#8976 fix: Use the scrollbar to prevent the toolbar from being hidden
  packages/editor/src/client/components-internal/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
  packages/editor/src/client/components-internal/CodeMirrorEditor/Toolbar/Toolbar.tsx
Labels: type/bug

#9018 support: Update import lines
  apps/app/src/interfaces/crowi-request.ts
  apps/app/src/server/models/attachment.ts
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/routes/apiv3/g2g-transfer.ts
  apps/app/src/server/routes/apiv3/invited.ts
  apps/app/src/server/routes/apiv3/notification-setting.js
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/attachment/get-brand-logo.ts
  apps/app/src/server/routes/attachment/get.ts
  apps/app/src/server/routes/ogp.ts
  apps/app/src/server/routes/page.js
  apps/app/src/server/service/attachment.js
  apps/app/src/server/service/file-uploader/aws.ts
  apps/app/src/server/service/file-uploader/azure.ts
  apps/app/src/server/service/file-uploader/file-uploader.ts
  apps/app/src/server/service/file-uploader/gcs.ts
  apps/app/src/server/service/file-uploader/gridfs.ts
  apps/app/src/server/service/file-uploader/local.ts
  apps/app/src/server/service/file-uploader/utils/headers.ts
  apps/app/src/server/service/g2g-transfer.ts
  apps/app/src/server/service/global-notification/global-notification-mail.js
  apps/app/src/server/service/global-notification/global-notification-slack.js
  apps/app/src/server/service/pre-notify.ts
  apps/app/src/server/service/slack-command-handler/keep.js
  apps/app/src/server/service/slack-command-handler/note.js
  apps/app/src/server/service/slack-command-handler/togetter.js
Labels: type/support

#9022 fix: Tests fail due to docker image and playwright version mismatch on CI
  .github/workflows/reusable-app-prod.yml
  package.json
  yarn.lock
Labels: type/bug

#9019 imprv: Serializers for User model and Attachment model
  .changeset/metal-donkeys-collect.md
  apps/app/package.json
  apps/app/src/client/components/Admin/AuditLog/ActivityTable.tsx
  apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group-relation.ts
  apps/app/src/server/middlewares/access-token-parser.js
  apps/app/src/server/models/serializers/bookmark-serializer.js
  apps/app/src/server/models/serializers/index.ts
  apps/app/src/server/models/serializers/page-serializer.js
  apps/app/src/server/models/serializers/revision-serializer.js
  apps/app/src/server/models/serializers/user-group-relation-serializer.js
  apps/app/src/server/models/serializers/user-serializer.js
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/activity.ts
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/bookmarks.js
  apps/app/src/server/routes/apiv3/forgot-password.js
  apps/app/src/server/routes/apiv3/in-app-notification.ts
  apps/app/src/server/routes/apiv3/page/create-page.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/routes/apiv3/revisions.js
  apps/app/src/server/routes/apiv3/user-group-relation.js
  apps/app/src/server/routes/apiv3/user-group.js
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/service/search-delegator/private-legacy-pages.ts
  apps/app/src/server/service/search.ts
  packages/core/package.json
  packages/core/src/interfaces/common.ts
  packages/core/src/models/serializers/attachment-serializer.ts
  packages/core/src/models/serializers/index.ts
  packages/core/src/models/serializers/user-serializer.ts
  packages/remark-attachment-refs/package.json
  packages/remark-attachment-refs/src/client/components/RefsImg.tsx
  packages/remark-attachment-refs/src/client/stores/refs.tsx
  packages/remark-attachment-refs/src/server/routes/refs.ts
  yarn.lock
Labels: type/improvement

#9026 fix: Comment operation by API
  apps/app/src/server/routes/comment.js
  apps/app/src/server/service/activity.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/pre-notify.ts
Labels: type/bug

#9036 support: Dark mode support for CountBadge
  apps/app/src/client/components/Common/CountBadge.tsx
Labels: type/support

#9034 imprv: Add UI and logic for disabled user registration
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/stores-universal/context.tsx
Labels: type/improvement

#9035 imprv: translation modification
  apps/app/src/pages/_app.page.tsx
  apps/app/src/pages/_document.page.tsx
  apps/app/src/pages/utils/commons.ts
  packages/core/src/interfaces/locale.ts
Labels: type/improvement

#8994 fix: Import data
  apps/app/package.json
  apps/app/src/client/components/Admin/ExportArchiveDataPage.tsx
  apps/app/src/client/components/Admin/G2GDataTransferExportForm.tsx
  apps/app/src/client/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
  apps/app/src/migrations/20180926134048-make-email-unique.js
  apps/app/src/migrations/20181019114028-abolish-page-group-relation.js
  apps/app/src/migrations/20190618104011-add-config-app-installed.js
  apps/app/src/migrations/20200402160380-remove-deleteduser-from-relationgroup.js
  apps/app/src/migrations/20200620203632-normalize-locale-id.js
  apps/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
  apps/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  apps/app/src/migrations/20211005120030-slack-app-integration-rename-keys.js
  apps/app/src/migrations/20220411114257-set-sparse-option-to-slack-member-id.js
  apps/app/src/migrations/20220613064207-add-attachment-type-to-existing-attachments.js
  apps/app/src/migrations/20230731075753-add_installed_date_to_config.js
  apps/app/src/models/admin/growi-archive-import-option.js
  apps/app/src/models/admin/import-option-for-pages.js
  apps/app/src/models/admin/import-option-for-pages.ts
  apps/app/src/models/admin/import-option-for-revisions.js
  apps/app/src/server/crowi/index.js
  apps/app/src/server/crowi/setup-models.ts
  apps/app/src/server/models/GlobalNotificationSetting/GlobalNotificationMailSetting.js
  apps/app/src/server/models/GlobalNotificationSetting/GlobalNotificationSlackSetting.js
  apps/app/src/server/models/bookmark.js
  apps/app/src/server/models/index.ts
  apps/app/src/server/models/slack-app-integration.js
  apps/app/src/server/models/user.js
  apps/app/src/server/routes/apiv3/g2g-transfer.ts
  apps/app/src/server/routes/apiv3/import.js
  apps/app/src/server/routes/apiv3/overwrite-params/attachmentFiles.chunks.js
  apps/app/src/server/routes/apiv3/overwrite-params/pages.js
  apps/app/src/server/routes/apiv3/overwrite-params/revisions.js
  apps/app/src/server/service/activity.ts
  apps/app/src/server/service/comment.ts
  apps/app/src/server/service/export.js
  apps/app/src/server/service/g2g-transfer.ts
  apps/app/src/server/service/growi-bridge/index.ts
  apps/app/src/server/service/import/construct-convert-map.integ.ts
  apps/app/src/server/service/import/construct-convert-map.ts
  apps/app/src/server/service/import/get-model-from-collection-name.ts
  apps/app/src/server/service/import/import-mode.ts
  apps/app/src/server/service/import/import-settings.ts
  apps/app/src/server/service/import/import.spec.ts
  apps/app/src/server/service/import/import.ts
  apps/app/src/server/service/import/index.ts
  apps/app/src/server/service/import/overwrite-function.ts
  apps/app/src/server/service/import/overwrite-params/attachmentFiles.chunks.ts
  apps/app/src/server/service/import/overwrite-params/index.ts
  apps/app/src/server/service/import/overwrite-params/pages.ts
  apps/app/src/server/service/import/overwrite-params/revisions.ts
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/src/server/service/pre-notify.ts
  apps/app/src/server/service/search-delegator/private-legacy-pages.ts
  apps/app/src/server/util/mongoose-utils.ts
  apps/app/test/integration/crowi/crowi.test.js
  apps/app/test/integration/setup-crowi.ts
Labels: type/bug

#9039 support: Replace tests with playwright (30-search/30-search--search.cy.ts)
  .github/workflows/reusable-app-prod.yml
  apps/app/playwright/30-search/search.spect.ts
  apps/app/test/cypress/e2e/30-search/30-search--search.cy.ts
Labels: type/support, flag/exclude-from-changelog

#9042 fix: Serializer for accessing to an empty page
  .changeset/warm-hounds-relate.md
  apps/app/src/pages/[[...path]].page.tsx
  packages/core/src/interfaces/page.ts
Labels: type/bug

#9044 imprv: Show pages with grants that are set to be visible in security settings on RecentChanges and PageTree as well
  apps/app/src/server/models/page.ts
  apps/app/src/server/routes/apiv3/page-listing.ts
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/service/page/index.ts
  apps/app/src/server/service/page/page-service.ts
Labels: type/improvement
