Repository growilabs/growi, pull requests merged in 2024-12, with the labels that each got.

#9455 imprv: fix pipeline of callback version
  apps/app/src/server/service/export.js
  apps/app/src/server/service/growi-bridge/index.ts
  apps/app/src/server/service/import/import.ts
Labels: type/improvement

#9472 fix: Cannot comment when comments from rom user are allowed
  apps/app/src/pages/[[...path]].page.tsx
Labels: type/bug

#9471 fix: put / before the page name
  apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.jsx
Labels: type/bug

#9481 fix: TypeError occurs during export
  apps/app/src/server/service/export.js
Labels: type/bug

#9487 fix: Error when creating pages with deep hierarchy
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/TreeItem/NewPageInput/use-new-page-input.tsx
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#9450 fix: Wider copy to clipboard area
  apps/app/src/components/Common/PagePathNav/PagePathNav.module.scss
Labels: type/bug

#9456 fix: Spelling miss of external_link in i18n
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
Labels: type/bug

#9513 fix: remark-lsx pagination
  packages/remark-lsx/src/server/index.ts
Labels: type/bug

#9462 feat(ai): Save file to VectorStore in HTML format
  apps/app/package.json
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/utils/convert-markdown-to-html.ts
  apps/app/src/features/openai/server/utils/sanitize-markdown.ts
  pnpm-lock.yaml
Labels: type/feature

#9536 fix: Fix i18n of oidc settings
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/components/Admin/Security/OidcSecuritySettingContents.jsx
Labels: type/bug
