Repository growilabs/growi, pull requests merged in 2025-03, with the labels that each got.

#9695 imprv: Border color for dark mode
  packages/preset-themes/src/styles/classic.scss
  packages/preset-themes/src/styles/default.scss
Labels: type/improvement

#9699 fix: CodeQL error
  apps/app/src/features/openai/server/routes/middlewares/upsert-ai-assistant-validator.ts
Labels: type/bug

#9689 feat: Add AuthorInfo display setting to PageSideContents
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Admin/Customize/CustomizeFunctionSetting.tsx
  apps/app/src/client/components/AuthorInfo/AuthorInfo.module.scss
  apps/app/src/client/components/AuthorInfo/AuthorInfo.tsx
  apps/app/src/client/components/PageAuthorInfo/PageAuthorInfo.module.scss
  apps/app/src/client/components/PageAuthorInfo/PageAuthorInfo.tsx
  apps/app/src/client/components/PageSideContents/PageSideContents.tsx
  apps/app/src/client/services/AdminCustomizeContainer.js
  apps/app/src/components/PageView/PageViewLayout.module.scss
  apps/app/src/pages/[[...path]].page.tsx
  apps/app/src/pages/share/[[...path]].page.tsx
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/service/config-manager/config-definition.ts
  apps/app/src/stores-universal/context.tsx
Labels: type/feature, type/improvement

#9711 imprv: Fix RecentChanges dropdown label
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
Labels: type/improvement

#9717 fix: Special strings displayed as sanitized
  apps/app/src/features/openai/server/routes/middlewares/upsert-ai-assistant-validator.ts
Labels: type/bug

#9723 fix: Revert environment variable name
  apps/app/src/server/service/config-manager/config-definition.ts
Labels: type/bug

#9729 feat: Expose React Insance to window via GrowiFacade
  .changeset/fair-worms-wait.md
  apps/app/src/features/growi-plugin/client/components/GrowiPluginsActivator.tsx
  packages/core/src/interfaces/growi-facade.ts
Labels: type/feature

#9732 fix: SAML authentication error
  apps/app/src/server/service/config-manager/config-definition.ts
  apps/app/src/server/service/config-manager/config-loader.ts
  apps/app/src/server/service/config-manager/config-manager.ts
Labels: type/bug

#9737 fix: The link for Telemetry of GROWI Docs
  apps/app/src/features/opentelemetry/server/node-sdk.ts
Labels: type/bug

#9712 fix: Prevent GrowiPlugin from being downloaded outside the plugin directory
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/server/service/import/overwrite-function.ts
Labels: type/bug

#9738 imprv: Do not render html attachments
  apps/app/src/server/routes/attachment/get.ts
Labels: type/improvement

#9750 feat: Implement preset prompt view
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/QuickMenuList.tsx
Labels: type/feature

#9763 fix: Assistant remains default when made unpublished
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementModal.tsx
  apps/app/src/features/openai/interfaces/ai-assistant.ts
  apps/app/src/features/openai/server/models/ai-assistant.ts
  apps/app/src/features/openai/server/routes/ai-assistant.ts
  apps/app/src/features/openai/server/routes/update-ai-assistant.ts
  apps/app/src/features/openai/server/services/openai.ts
Labels: type/bug

#9770 fix: Migration script to remove index for 'ns' from config collection
  apps/app/src/migrations/19700101000000-foremost-1000-20241123211930-remove-index-for-ns-from-configs.js
Labels: type/bug

#9773 fix: Prevent empty compose.extend.yml
  .devcontainer/app/initializeCommand.sh
  .devcontainer/pdf-converter/initializeCommand.sh
Labels: type/bug, flag/exclude-from-changelog

#9775 feat: Add util method to get react instance of growi via growifacade
  .changeset/eighty-pots-approve.md
  packages/pluginkit/package.json
  packages/pluginkit/src/index.ts
  packages/pluginkit/src/v4/client/index.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.spec.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/index.ts
  packages/pluginkit/src/v4/client/utils/index.ts
  pnpm-lock.yaml
Labels: type/feature

#9772 fix: The order of multer middleware
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/customize-setting.js
  apps/app/src/server/routes/apiv3/g2g-transfer.ts
  apps/app/src/server/routes/index.js
Labels: type/bug

#9812 fix: growi pluginkit growifacade typo
  .changeset/violet-ties-draw.md
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.spec.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.ts
Labels: type/bug
