Repository growilabs/growi, pull requests merged in 2025-08, with the labels that each got.

#10126 support: Configure biome for slackbot-proxy (excluding services)
  apps/slackbot-proxy/.eslintignore
  apps/slackbot-proxy/.eslintrc.js
  apps/slackbot-proxy/package.json
  apps/slackbot-proxy/src/Server.ts
  apps/slackbot-proxy/src/config/logger/config.dev.ts
  apps/slackbot-proxy/src/config/logger/config.prod.ts
  apps/slackbot-proxy/src/controllers/growi-to-slack.ts
  apps/slackbot-proxy/src/controllers/privacy.ts
  apps/slackbot-proxy/src/controllers/slack.ts
  apps/slackbot-proxy/src/controllers/term.ts
  apps/slackbot-proxy/src/controllers/top.ts
  apps/slackbot-proxy/src/entities/installation.ts
  apps/slackbot-proxy/src/entities/order.ts
  apps/slackbot-proxy/src/entities/relation.ts
  apps/slackbot-proxy/src/entities/system-information.ts
  apps/slackbot-proxy/src/filters/CustomHttpErrorFilter.ts
  apps/slackbot-proxy/src/filters/ResourceNotFoundFilter.ts
  apps/slackbot-proxy/src/index.ts
  apps/slackbot-proxy/src/interfaces/growi-uri-injector.ts
  apps/slackbot-proxy/src/interfaces/slack-to-growi/slack-oauth-req.ts
  apps/slackbot-proxy/src/middlewares/GlobalHttpErrorHandlingMiddleware.ts
  apps/slackbot-proxy/src/middlewares/growi-to-slack/add-webclient-response-to-res.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/add-signing-secret-to-req.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/authorizer.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/extract-growi-uri-from-req.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/join-to-conversation.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/parse-interaction-req.ts
  apps/slackbot-proxy/src/middlewares/slack-to-growi/url-verification.ts
  apps/slackbot-proxy/src/models/errors.ts
  apps/slackbot-proxy/src/repositories/installation.ts
  apps/slackbot-proxy/src/repositories/order.ts
  apps/slackbot-proxy/src/repositories/relation.ts
  apps/slackbot-proxy/src/repositories/system-information.ts
  apps/slackbot-proxy/src/utils/logger/index.ts
  apps/slackbot-proxy/src/utils/welcome-message.ts
  apps/slackbot-proxy/tsconfig.json
  biome.json
Labels: type/support

#10206 support: Configure biome for slackbot-proxy services
  apps/slackbot-proxy/src/services/InstallerService.ts
  apps/slackbot-proxy/src/services/LinkSharedService.ts
  apps/slackbot-proxy/src/services/RegisterService.ts
  apps/slackbot-proxy/src/services/RelationsService.ts
  apps/slackbot-proxy/src/services/SelectGrowiService.ts
  apps/slackbot-proxy/src/services/SystemInformationService.ts
  apps/slackbot-proxy/src/services/UnregisterService.ts
  apps/slackbot-proxy/src/services/growi-uri-injector/ActionsBlockPayloadDelegator.ts
  apps/slackbot-proxy/src/services/growi-uri-injector/SectionBlockPayloadDelegator.ts
  apps/slackbot-proxy/src/services/growi-uri-injector/ViewInteractionPayloadDelegator.ts
  apps/slackbot-proxy/src/services/growi-uri-injector/block-elements/ButtonActionPayloadDelegator.ts
  apps/slackbot-proxy/src/services/growi-uri-injector/block-elements/CheckboxesActionPayloadDelegator.ts
  biome.json
Labels: type/support

#10208 support: Update axios for slackbot-proxy and slack package
  apps/slackbot-proxy/package.json
  packages/slack/package.json
  pnpm-lock.yaml
Labels: type/support

#10200 fix: remove srcdoc from whitelist
  apps/app/src/services/renderer/recommended-whitelist.ts
Labels: type/bug

#10181 fix: Auto-scroll to anchor for page view
  apps/app/src/components/PageView/PageView.tsx
Labels: type/bug

#10240 fix: Swagger for createPage
  apps/app/src/server/routes/apiv3/page/index.ts
Labels: type/bug, flag/exclude-from-changelog

#10241 fix: Auto-scroll to anchor for page view (for dev7.2.x)
  apps/app/src/components/PageView/PageView.tsx
Labels: type/bug

#10243 fix: Swagger for growi-sdk-typescript
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/share-links.js
  apps/app/src/server/routes/apiv3/users.js
Labels: type/bug, flag/exclude-from-changelog

#10256 support: Configure biome for app migrations files
  apps/app/.eslintrc.js
  apps/app/src/linter-checker/test.js
  apps/app/src/migrations/19700101000000-foremost-1000-20241123211930-remove-index-for-ns-from-configs.js
  apps/app/src/migrations/19700101000000-foremost-1010-20250109000000-generate-service-instance-id.js
  apps/app/src/migrations/20180926134048-make-email-unique.js
  apps/app/src/migrations/20180927102719-init-serverurl.js
  apps/app/src/migrations/20181019114028-abolish-page-group-relation.js
  apps/app/src/migrations/20190618104011-add-config-app-installed.js
  apps/app/src/migrations/20190619055421-adjust-page-grant.js
  apps/app/src/migrations/20190624110950-fill-last-update-user.js
  apps/app/src/migrations/20191102223901-drop-pages-indices.js
  apps/app/src/migrations/20191126173016-adjust-pages-path.js
  apps/app/src/migrations/20191127023815-drop-wrong-index-of-page-tag-relation.js
  apps/app/src/migrations/20200402160380-remove-deleteduser-from-relationgroup.js
  apps/app/src/migrations/20200514001356-update-theme-color-for-dark.js
  apps/app/src/migrations/20200620203632-normalize-locale-id.js
  apps/app/src/migrations/20200827045151-remove-layout-setting.js
  apps/app/src/migrations/20200828024025-copy-aws-setting.js
  apps/app/src/migrations/20200901034313-update-mail-transmission.js
  apps/app/src/migrations/20200903080025-remove-timeline-type.js.js
  apps/app/src/migrations/20200915035234-rename-s3-config.js
  apps/app/src/migrations/20210420160380-convert-double-to-date.js
  apps/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
  apps/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
  apps/app/src/migrations/20210921173042-add-is-trashed-field.js
  apps/app/src/migrations/20211005120030-slack-app-integration-rename-keys.js
  apps/app/src/migrations/20211005131430-config-without-proxy-command-permission-for-renaming.js
  apps/app/src/migrations/20211129125654-initialize-private-legacy-pages-named-query.js
  apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
  apps/app/src/migrations/20220131001218-convert-redirect-to-pages-to-page-redirect-documents.js
  apps/app/src/migrations/20220311011114-convert-page-delete-config.js
  apps/app/src/migrations/20220411114257-set-sparse-option-to-slack-member-id.js
  apps/app/src/migrations/20220613064207-add-attachment-type-to-existing-attachments.js
  apps/app/src/migrations/20221014130200-remove-customize-is-saved-states-of-tab-changes.js
  apps/app/src/migrations/20221219011829-remove-basic-auth-related-config.js
  apps/app/src/migrations/20230213090921-remove-presentation-configurations.js
  apps/app/src/migrations/20230723061824-granted-group-to-array-of-objects.js
  apps/app/src/migrations/20230731075753-add_installed_date_to_config.js
  apps/app/src/migrations/20231102012742-clean-user-ui-settings-collection.js
  apps/app/src/migrations/20231223155127-non-null-granted-groups.js
  apps/app/src/migrations/20240924181317-changed-status-in-inappnotifications-from-unread-to-unopened.js
  apps/app/src/migrations/20241107172359-rename-pageId-to-page.js
  apps/app/src/migrations/20250522105040-delete-old-index-for-vector-store-file-relation.js
  biome.json
Labels: type/support, flag/exclude-from-changelog

#10262 support: Configure biome for app callout/comment/templates features
  apps/app/.eslintrc.js
  apps/app/src/features/callout/components/CalloutViewer.tsx
  apps/app/src/features/callout/services/callout.spec.ts
  apps/app/src/features/callout/services/callout.ts
  apps/app/src/features/callout/services/consts.ts
  apps/app/src/features/callout/services/index.ts
  apps/app/src/features/comment/server/events/consts.ts
  apps/app/src/features/comment/server/models/comment.ts
  apps/app/src/features/templates/server/routes/apiv3/index.ts
  apps/app/src/features/templates/stores/template.tsx
  biome.json
Labels: type/support

#10259 fix: CodeQL problems
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  packages/remark-lsx/src/server/routes/list-pages/index.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/index.ts
Labels: type/bug

#10264 fix: CodeQL problems
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/export.js
  apps/app/src/server/routes/apiv3/page/update-page.ts
  packages/remark-lsx/src/client/components/Lsx.tsx
  packages/remark-lsx/src/client/stores/lsx/lsx.ts
Labels: type/bug, flag/exclude-from-changelog
