Repository growilabs/growi, pull requests merged in 2025-10, with the labels that each got.

#10351 feat: add page counts metrics
  apps/app/src/features/opentelemetry/server/custom-metrics/index.ts
  apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.spec.ts
  apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.ts
  apps/app/src/server/service/growi-info/growi-info.integ.ts
  apps/app/src/server/service/growi-info/growi-info.ts
  packages/core/src/interfaces/growi-app-info.ts
Labels: queued

#10234 support: Service integration test biome migration
  apps/app/.eslintrc.js
  apps/app/src/server/service/page-grant.ts
  apps/app/src/server/service/page/page-service.ts
  apps/app/test/integration/service/external-user-group-sync.test.ts
  apps/app/test/integration/service/ldap-user-group-sync.test.ts
  apps/app/test/integration/service/page-grant.test.ts
  apps/app/test/integration/service/page.test.js
  apps/app/test/integration/service/search/search-service.test.js
  apps/app/test/integration/service/user-groups.test.ts
  apps/app/test/integration/service/v5.migration.test.js
  apps/app/test/integration/service/v5.non-public-page.test.ts
  apps/app/test/integration/service/v5.page.test.ts
  apps/app/test/integration/service/v5.public-page.test.ts
  apps/app/test/integration/tsconfig.json
  biome.json
Labels: type/support, queued

#10309 support: Configure biome for growi-plugin feature
  apps/app/.eslintrc.js
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginCard.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginDeleteModal.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginInstallerForm.tsx
  apps/app/src/features/growi-plugin/client/components/Admin/PluginsExtensionPageContents/PluginsExtensionPageContents.tsx
  apps/app/src/features/growi-plugin/client/components/GrowiPluginsActivator.tsx
  apps/app/src/features/growi-plugin/client/stores/admin-plugins.tsx
  apps/app/src/features/growi-plugin/client/utils/growi-facade-utils.ts
  apps/app/src/features/growi-plugin/interfaces/growi-plugin.ts
  apps/app/src/features/growi-plugin/server/models/growi-plugin.integ.ts
  apps/app/src/features/growi-plugin/server/models/growi-plugin.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.spec.ts
  apps/app/src/features/growi-plugin/server/models/vo/github-url.ts
  apps/app/src/features/growi-plugin/server/routes/apiv3/admin/index.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/generate-template-plugin-meta.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/generate-theme-plugin-meta.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.integ.ts
  apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
  apps/app/src/server/service/customize.ts
  biome.json
Labels: type/support

#10376 support: Configure biome for rate-limiter feature
  apps/app/.eslintrc.js
  apps/app/src/features/rate-limiter/config/index.ts
  apps/app/src/features/rate-limiter/middleware/consume-points.integ.ts
  apps/app/src/features/rate-limiter/middleware/consume-points.ts
  apps/app/src/features/rate-limiter/middleware/factory.ts
  apps/app/src/features/rate-limiter/middleware/rate-limiter-factory.ts
  apps/app/src/features/rate-limiter/utils/config-generator.ts
  biome.json
Labels: type/support

#10378 fix: Cannot update v4 format pages
  apps/app/src/client/components/PageEditor/PageEditor.tsx
  apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
  apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
  apps/app/src/server/routes/apiv3/page/update-page.ts
  apps/app/src/server/service/page/index.ts
Labels: type/bug

#10380 support: Configure biome for app etc. dirs
  apps/app/.eslintrc.js
  apps/app/public/images/icons/favicon/manifest.json
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/ko_KR/admin.json
  apps/app/public/static/locales/ko_KR/translation.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/models/admin/growi-archive-import-option.ts
  apps/app/src/models/admin/import-mode.ts
  apps/app/src/models/admin/import-option-for-pages.ts
  apps/app/src/models/admin/import-option-for-revisions.ts
  apps/app/src/models/cdn-resource.js
  apps/app/src/models/linked-page-path.js
  apps/app/src/models/serializers/in-app-notification-snapshot/page-bulk-export-job.ts
  apps/app/src/models/serializers/in-app-notification-snapshot/page.ts
  apps/app/src/models/serializers/in-app-notification-snapshot/user.ts
  apps/app/src/models/vo/external-account-login-error.ts
  apps/app/test-with-vite/.eslintrc.cjs
  apps/app/test-with-vite/setup/mongoms.ts
  apps/app/test-with-vite/tsconfig.json
  biome.json
Labels: type/support

#10381 support: Configure biome for app services dir
  apps/app/.eslintrc.js
  apps/app/src/services/general-xss-filter/general-xss-filter.spec.ts
  apps/app/src/services/general-xss-filter/general-xss-filter.ts
  apps/app/src/services/layout/use-should-expand-content.ts
  apps/app/src/services/renderer/markdown-it/PreProcessor/EasyGrid.js
  apps/app/src/services/renderer/recommended-whitelist.spec.ts
  apps/app/src/services/renderer/recommended-whitelist.ts
  apps/app/src/services/renderer/rehype-plugins/add-class.ts
  apps/app/src/services/renderer/rehype-plugins/add-inline-code-property.ts
  apps/app/src/services/renderer/rehype-plugins/add-line-number-attribute.ts
  apps/app/src/services/renderer/rehype-plugins/keyword-highlighter.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.spec.ts
  apps/app/src/services/renderer/rehype-plugins/relative-links.ts
  apps/app/src/services/renderer/rehype-plugins/relocate-toc.ts
  apps/app/src/services/renderer/remark-plugins/attachment.ts
  apps/app/src/services/renderer/remark-plugins/codeblock.ts
  apps/app/src/services/renderer/remark-plugins/echo-directive.ts
  apps/app/src/services/renderer/remark-plugins/emoji.ts
  apps/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.spec.ts
  apps/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.ts
  apps/app/src/services/renderer/remark-plugins/xsv-to-table.ts
  apps/app/src/services/renderer/renderer.tsx
  biome.json
Labels: type/support, queued
