Repository growilabs/growi, pull requests merged in 2025-04, with the labels that each got.

#9825 support: Upgrade Next.js
  apps/app/package.json
  pnpm-lock.yaml
Labels: type/support

#9840 imprv: Adjust comment editor clickable area
  apps/app/src/client/components/PageComment/CommentEditor.module.scss
  apps/app/src/client/components/PageComment/CommentEditor.tsx
  apps/app/src/client/components/PageEditor/_page-editor-inheritance.scss
Labels: type/improvement

#9844 fix: CodeQL problems for Users API
  apps/app/src/server/routes/apiv3/users.js
Labels: type/bug, flag/exclude-from-changelog

#9847 fix: CodeQL problem "Database query built from user-controlled sources"
  apps/app/src/features/openai/server/routes/thread.ts
Labels: type/bug, flag/exclude-from-changelog

#9848 fix: CodeQL problems
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/server/routes/apiv3/users.js
Labels: type/bug, flag/exclude-from-changelog

#9850 fix: CodeQL problems
  apps/app/src/server/middlewares/inject-reset-order-by-token-middleware.ts
  apps/app/src/server/models/password-reset-order.ts
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/personal-setting.js
Labels: type/bug

#9852 fix: CodeQL problems
  apps/app/src/features/openai/server/routes/edit/index.ts
Labels: type/bug

#9870 fix: Export page API is broken
  apps/app/src/server/routes/apiv3/page/index.ts
Labels: type/bug

#9874 support: Improve the official docker image size
  apps/app/docker/Dockerfile
Labels: type/support, type/improvement

#9880 support(pdf-converter): Improve the official docker image size for pdf-converter
  apps/pdf-converter/docker/Dockerfile
Labels: type/support

#9884 fix: Tooltip for UserPicture doesn't work
  packages/ui/src/components/UserPicture.tsx
Labels: type/bug

#9886 fix: Profile image upload functionality and accepted file types
  apps/app/src/client/components/Me/ProfileImageSettings.tsx
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/attachment/image-content-type-validator.spec.ts
  apps/app/src/server/routes/attachment/image-content-type-validator.ts
Labels: type/bug

#9890 fix: ConfigLoader.loadFromDB for JSON parsing error handling
  apps/app/src/server/service/config-manager/config-loader.spec.ts
  apps/app/src/server/service/config-manager/config-loader.ts
  apps/app/src/server/service/config-manager/config-manager.spec.ts
Labels: type/bug

#9892 imprv: User picture tooltip
  apps/app/src/client/components/AuthorInfo/AuthorInfo.module.scss
  apps/app/src/client/components/Bookmarks/BookmarkFolderTree.module.scss
  apps/app/src/client/components/PageComment.tsx
  apps/app/src/client/components/PageComment/Comment.module.scss
  apps/app/src/client/components/PageComment/Comment.tsx
  apps/app/src/client/components/PageComment/CommentEditor.module.scss
  apps/app/src/client/components/PageComment/CommentEditor.tsx
  apps/app/src/client/components/PageComment/_comment-inheritance.scss
  apps/app/src/client/components/PageEditor/EditorNavbar/EditingUserList.tsx
  apps/app/src/client/components/PageHistory/Revision.module.scss
  apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
  apps/app/src/client/components/UsersHomepageFooter.module.scss
  apps/app/src/components/User/UserInfo.module.scss
  apps/app/src/components/User/UserInfo.tsx
  apps/app/src/styles/style-app.scss
  packages/ui/scss/molecules/_page_list.scss
  packages/ui/src/components/UserPicture.module.scss
  packages/ui/src/components/UserPicture.tsx
Labels: type/improvement

#9898 imprv: User picture tooltip (2)
  apps/app/src/client/components/PageEditor/EditorNavbar/EditingUserList.tsx
  packages/core/src/utils/page-path-utils/index.ts
  packages/editor/src/client/stores/use-collaborative-editor-mode.ts
  packages/editor/src/interfaces/editing-client.ts
  packages/ui/src/components/UserPicture.tsx
Labels: type/bug

#9904 feat: Implement predicate to check if file is supported by VectorStore
  apps/app/package.json
  apps/app/src/features/openai/server/utils/is-vector-store-compatible.ts
  apps/app/src/server/routes/apiv3/attachment.js
  pnpm-lock.yaml
Labels: type/feature
