Repository growilabs/growi, pull requests merged in 2025-07, with the labels that each got.

#10131 imprv: Adjust margin-top for .main at md and lg breakpoints
  apps/app/src/styles/_layout.scss
Labels: type/improvement

#10105 imprv: Circular reference prevention in axios date conversion
  apps/app/src/utils/axios-date-conversion.spec.ts
  apps/app/src/utils/axios.ts
Labels: type/improvement

#10128 fix: Bug causing export zip file to display twice
  apps/app/src/client/components/Admin/ExportArchiveDataPage.tsx
Labels: type/bug

#10149 support: Node.JS 22 (2)
  apps/app/docker/Dockerfile
  apps/pdf-converter/docker/Dockerfile
  apps/slackbot-proxy/docker/Dockerfile
Labels: type/support

#10166 fix: Add checking attachment file name and file size for g2g transformation
  apps/app/src/server/routes/apiv3/g2g-transfer.ts
Labels: type/bug

#10167 fix: Mermaid diagrams are not displayed when svg ids are duplicated
  apps/app/src/features/mermaid/components/MermaidViewer.tsx
Labels: type/bug

#10170 fix: validate invalid key in qiita importer
  apps/app/src/server/routes/admin.js
Labels: type/bug

#10189 imprv: Set a longer value for the export interval of OpenTelemetry metrics
  .changeset/fluffy-insects-laugh.md
  apps/app/src/features/opentelemetry/server/custom-metrics/application-metrics.ts
  apps/app/src/features/opentelemetry/server/custom-metrics/user-counts-metrics.spec.ts
  apps/app/src/features/opentelemetry/server/custom-metrics/user-counts-metrics.ts
  apps/app/src/features/opentelemetry/server/custom-resource-attributes/application-resource-attributes.spec.ts
  apps/app/src/features/opentelemetry/server/custom-resource-attributes/application-resource-attributes.ts
  apps/app/src/features/opentelemetry/server/node-sdk-configuration.ts
  apps/app/src/features/questionnaire/interfaces/growi-app-info.ts
  apps/app/src/server/service/growi-info/growi-info.integ.ts
  apps/app/src/server/service/growi-info/growi-info.ts
  packages/core/src/interfaces/growi-app-info.ts
Labels: type/improvement

#10184 fix: Mermaid diagrams are not displayed when svg ids are duplicated (for dev7.2.x)
  apps/app/src/features/mermaid/components/MermaidViewer.tsx
Labels: type/bug

#10192 fix: Puppeteer not launching in pdf-converter
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/steps/export-pages-to-fs-async.ts
  apps/pdf-converter/src/service/pdf-convert.ts
Labels: type/bug
