Repository growilabs/growi, pull requests merged in 2025-05, with the labels that each got.

#9897 imprv: Hide summary mode switch in editor assistant mode
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
  apps/app/src/features/openai/client/services/editor-assistant.tsx
  apps/app/src/features/openai/client/services/knowledge-assistant.tsx
Labels: type/improvement

#9913 imprv: AI models and instructions
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantChatInitialView.tsx
  apps/app/src/features/openai/client/services/knowledge-assistant.tsx
  apps/app/src/features/openai/server/routes/message.ts
  apps/app/src/features/openai/server/services/assistant/assistant.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/server/service/config-manager/config-definition.ts
Labels: type/improvement

#9901 imprv: add contributors that has not been added to konami command
  apps/app/resource/Contributor.js
Labels: type/improvement

#9916 imprv: Keep right sidebar open when citation link is clicked
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard.tsx
Labels: type/improvement

#9900 imprv: Disable page bulk export when file upload settings are not configured
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
Labels: type/improvement

#9918 imprv: Tidy up instructions
  apps/app/src/features/openai/server/routes/edit/index.ts
  apps/app/src/features/openai/server/services/assistant/assistant-types.ts
  apps/app/src/features/openai/server/services/assistant/assistant.ts
  apps/app/src/features/openai/server/services/assistant/chat-assistant.ts
  apps/app/src/features/openai/server/services/assistant/create-assistant.ts
  apps/app/src/features/openai/server/services/assistant/editor-assistant.ts
  apps/app/src/features/openai/server/services/assistant/index.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/server/service/config-manager/config-definition.ts
Labels: type/improvement

#9928 fix: Pages list API
  apps/app/src/server/routes/apiv3/pages/index.js
Labels: type/bug

#9930 fix: PagePathHeader maxWidth for editor
  apps/app/src/client/components/PageHeader/PagePathHeader.tsx
Labels: type/bug

#9938 fix: Picture size
  apps/app/src/client/components/Admin/Customize/CustomizeLogoSetting.tsx
  apps/app/src/client/components/Me/ProfileImageSettings.tsx
  apps/app/src/client/components/Sidebar/SidebarBrandLogo.tsx
Labels: type/bug

#9917 support: Migrate linter/formatter to biome for @growi/slack package
  .devcontainer/app/devcontainer.json
  .devcontainer/pdf-converter/devcontainer.json
  .vscode/settings.json
  biome.json
  package.json
  packages/slack/.eslintignore
  packages/slack/.eslintrc.cjs
  packages/slack/package.json
  packages/slack/src/consts/index.ts
  packages/slack/src/interfaces/channel.ts
  packages/slack/src/interfaces/connection-status.ts
  packages/slack/src/interfaces/growi-bot-event.ts
  packages/slack/src/interfaces/growi-command-processor.ts
  packages/slack/src/interfaces/growi-command.ts
  packages/slack/src/interfaces/growi-interaction-processor.ts
  packages/slack/src/interfaces/request-between-growi-and-proxy.ts
  packages/slack/src/interfaces/request-from-slack.ts
  packages/slack/src/interfaces/respond-util.ts
  packages/slack/src/interfaces/response-url.ts
  packages/slack/src/interfaces/slackbot-types.ts
  packages/slack/src/middlewares/parse-slack-interaction-request.ts
  packages/slack/src/middlewares/verify-growi-to-slack-request.ts
  packages/slack/src/middlewares/verify-slack-request.ts
  packages/slack/src/utils/block-kit-builder.ts
  packages/slack/src/utils/check-communicable.ts
  packages/slack/src/utils/generate-last-update-markdown.ts
  packages/slack/src/utils/get-supported-growi-actions-regexps.ts
  packages/slack/src/utils/interaction-payload-accessor.ts
  packages/slack/src/utils/logger/index.ts
  packages/slack/src/utils/payload-interaction-id-helpers.ts
  packages/slack/src/utils/permission-parser.ts
  packages/slack/src/utils/post-ephemeral-errors.ts
  packages/slack/src/utils/publish-initial-home-view.ts
  packages/slack/src/utils/reshape-contents-body.test.ts
  packages/slack/src/utils/reshape-contents-body.ts
  packages/slack/src/utils/respond-util-factory.ts
  packages/slack/src/utils/response-url.ts
  packages/slack/src/utils/slash-command-parser.test.ts
  packages/slack/src/utils/slash-command-parser.ts
  packages/slack/src/utils/webclient-factory.ts
  packages/slack/tsconfig.json
  packages/slack/vite.config.ts
  packages/slack/vitest.config.ts
  pnpm-lock.yaml
Labels: type/support

#9945 support: UI package biome migration
  biome.json
  packages/ui/.eslintignore
  packages/ui/.eslintrc.cjs
  packages/ui/package.json
  packages/ui/src/components/Attachment.tsx
  packages/ui/src/components/LoadingSpinner.tsx
  packages/ui/src/components/PagePath/PageListMeta.tsx
  packages/ui/src/components/PagePath/PagePathLabel.tsx
  packages/ui/src/components/UserPicture.tsx
  packages/ui/src/interfaces/breakpoints.ts
  packages/ui/src/interfaces/popper-data.ts
  packages/ui/src/utils/browser-utils.ts
  packages/ui/src/utils/use-fullscreen.ts
  packages/ui/src/utils/use-rect.ts
  packages/ui/tsconfig.json
  packages/ui/vite.config.ts
Labels: type/support

#9948 support: Remark lsx package biome migration
  .vscode/settings.json
  biome.json
  packages/remark-lsx/.eslintignore
  packages/remark-lsx/.eslintrc.cjs
  packages/remark-lsx/package.json
  packages/remark-lsx/src/client/components/Lsx.tsx
  packages/remark-lsx/src/client/components/LsxPageList/LsxListView.tsx
  packages/remark-lsx/src/client/components/LsxPageList/LsxPage.tsx
  packages/remark-lsx/src/client/components/lsx-context.ts
  packages/remark-lsx/src/client/services/renderer/lsx.ts
  packages/remark-lsx/src/client/stores/lsx/lsx.ts
  packages/remark-lsx/src/client/stores/lsx/parse-num-option.spec.ts
  packages/remark-lsx/src/client/stores/lsx/parse-num-option.ts
  packages/remark-lsx/src/client/utils/page-node.spec.ts
  packages/remark-lsx/src/client/utils/page-node.ts
  packages/remark-lsx/src/interfaces/api.ts
  packages/remark-lsx/src/interfaces/page-node.ts
  packages/remark-lsx/src/server/index.ts
  packages/remark-lsx/src/server/routes/list-pages/add-depth-condition.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/add-depth-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/add-num-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/add-sort-condition.ts
  packages/remark-lsx/src/server/routes/list-pages/generate-base-query.ts
  packages/remark-lsx/src/server/routes/list-pages/get-toppage-viewers-count.ts
  packages/remark-lsx/src/server/routes/list-pages/index.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/index.ts
  packages/remark-lsx/src/utils/depth-utils.spec.ts
  packages/remark-lsx/tsconfig.json
  packages/remark-lsx/vite.server.config.ts
  packages/remark-lsx/vitest.config.ts
Labels: type/support

#9951 fix: Vectorstore file not rebuilt after page update
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/server/service/attachment.js
Labels: type/bug

#9956 support: Update GitHub readme logo
  README.md
  README_JP.md
Labels: type/support, flag/exclude-from-changelog

#9952 support: Prevent SSRF for slack integration
  apps/app/src/server/routes/apiv3/slack-integration.js
  apps/slackbot-proxy/package.json
  apps/slackbot-proxy/src/services/InstallerService.ts
  biome.json
  packages/slack/package.json
  packages/slack/src/utils/respond-util-factory.ts
  packages/slack/src/utils/response-url-validator.ts
  pnpm-lock.yaml
Labels: type/support

#9946 imprv: Add orgId and appId to bulk export path
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/index.ts
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/request-pdf-converter.ts
  apps/pdf-converter/src/controllers/pdf.ts
  apps/pdf-converter/src/server.ts
  apps/pdf-converter/src/service/pdf-convert.ts
  apps/pdf-converter/tsconfig.json
  packages/pdf-converter-client/src/index.ts
Labels: type/improvement

#9971 imprv(api): Support Bearer token
  apps/app/bin/swagger-jsdoc/definition-apiv1.js
  apps/app/bin/swagger-jsdoc/definition-apiv3.js
  apps/app/src/features/questionnaire/server/routes/apiv3/questionnaire.ts
  apps/app/src/server/middlewares/access-token-parser/access-token-parser.integ.ts
  apps/app/src/server/middlewares/access-token-parser/access-token-parser.ts
  apps/app/src/server/routes/apiv3/activity.ts
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/routes/apiv3/bookmark-folder.ts
  apps/app/src/server/routes/apiv3/g2g-transfer.ts
  apps/app/src/server/routes/apiv3/import.js
  apps/app/src/server/routes/apiv3/in-app-notification.ts
  apps/app/src/server/routes/apiv3/page-listing.ts
Labels: type/improvement

#8837 feat: Update new sample video
  README.md
  README_JP.md
Labels: type/feature

#9906 feat: Save attachment to VectorStore
  apps/app/package.json
  apps/app/src/features/openai/server/models/vector-store-file-relation.ts
  apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
  apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
  apps/app/src/features/openai/server/services/openai.ts
  apps/app/src/features/openai/server/utils/is-vector-store-compatible.ts
  apps/app/src/migrations/20250522105040-delete-old-index-for-vector-store-file-relation.js
  apps/app/src/server/crowi/index.js
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/service/attachment.js
  pnpm-lock.yaml
Labels: type/feature

#9977 fix: Prevent submission during text composition in SearchTypeahead
  apps/app/src/client/components/PageTags/TagsInput.tsx
  apps/app/src/client/components/SearchTypeahead.tsx
Labels: type/bug

#9973 imprv: Headers and CopyDropdown UX
  apps/app/src/client/components/PageAccessoriesModal/ShareLink/ShareLinkList.tsx
  apps/app/src/client/components/PageHeader/PageHeader.tsx
  apps/app/src/client/components/PageHeader/PageTitleHeader.tsx
  apps/app/src/client/components/PagePathNavSticky/PagePathNavSticky.tsx
  apps/app/src/client/components/SearchPage/SearchResultContent.tsx
  apps/app/src/components/Common/PagePathNav/PagePathNavLayout.tsx
  apps/app/src/components/PageView/PageView.tsx
  apps/app/src/components/ShareLinkPageView/ShareLinkPageView.tsx
Labels: type/improvement

#9982 fix: Potential fix for code scanning alert no. 569: Information exposure through a stack trace
  packages/remark-lsx/src/server/routes/list-pages/index.spec.ts
  packages/remark-lsx/src/server/routes/list-pages/index.ts
Labels: type/bug, flag/exclude-from-changelog

#9981 imprv: Regex for path-utils
  packages/core/src/utils/path-utils.js
  packages/core/src/utils/path-utils.spec.ts
  packages/core/src/utils/path-utils.ts
Labels: type/improvement

#9985 fix: Editor assistant button is being displayed when ai functionality is not enabled
  apps/app/src/client/components/PageEditor/EditorNavbarBottom/EditorNavbarBottom.tsx
Labels: type/bug

#9980 imprv: Discard when form is submitted without Accept/Discard after showing diff
  apps/app/src/features/openai/client/services/editor-assistant.tsx
Labels: type/improvement

#9994 fix: OpenAI threads can be retrieved regardless of assistant's public permissions
  apps/app/src/features/openai/server/routes/delete-thread.ts
  apps/app/src/features/openai/server/routes/get-threads.ts
Labels: type/bug

#9996 support: Remove unnecessary option for rename API
  apps/app/src/server/routes/apiv3/pages/index.js
  apps/app/src/server/service/page/index.ts
Labels: type/support, flag/exclude-from-changelog

#9993 imprv: Prevent path traversal attack in pdf converter
  apps/app/src/features/page-bulk-export/server/service/page-bulk-export-job-cron/request-pdf-converter.ts
  apps/pdf-converter/package.json
  apps/pdf-converter/src/controllers/pdf.spec.ts
  apps/pdf-converter/src/controllers/pdf.ts
  apps/pdf-converter/src/service/pdf-convert.ts
  apps/pdf-converter/tsconfig.json
  apps/pdf-converter/vitest.config.ts
  packages/pdf-converter-client/src/index.ts
  pnpm-lock.yaml
Labels: type/improvement
