Repository growilabs/growi, pull requests merged in 2025-02, with the labels that each got.

#9602 fix: Serializing page data for share link
  apps/app/src/pages/share/[[...path]].page.tsx
Labels: type/bug

#9616 fix: Middlewares about installation
  apps/app/src/features/questionnaire/server/util/convert-to-legacy-format.spec.ts
  apps/app/src/server/middlewares/application-installed.ts
  apps/app/src/server/middlewares/application-not-installed.js
  apps/app/src/server/middlewares/application-not-installed.ts
  apps/app/src/server/routes/apiv3/index.js
  apps/app/src/server/routes/apiv3/installer.ts
  apps/app/src/server/routes/index.js
Labels: type/bug

#9620 imprv: Make loading restQiitaAPIService type-safe
  apps/app/src/server/crowi/index.js
  apps/app/src/server/util/importer.js
Labels: flag/exclude-from-changelog

#9624 support: Remove legacy ConfigManager
  apps/app/src/server/models/config.ts
  apps/app/src/server/service/config-manager/config-manager.ts
  apps/app/src/server/service/config-manager/legacy/config-loader.ts
  apps/app/src/server/service/config-manager/legacy/config-manager.ts
Labels: type/support

#9544 fix: PageTree auto-scrolling sometimges not woking
  apps/app/public/static/locales/en_US/translation.json
  apps/app/public/static/locales/fr_FR/translation.json
  apps/app/public/static/locales/ja_JP/translation.json
  apps/app/public/static/locales/zh_CN/translation.json
  apps/app/src/client/components/ItemsTree/ItemsTree.tsx
  apps/app/src/client/components/PageSelectModal/PageSelectModal.tsx
  apps/app/src/client/components/Sidebar/PageTree/PageTreeSubstance.tsx
  apps/app/src/client/components/Sidebar/PageTreeItem/PageTreeItem.tsx
  apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
  apps/app/src/client/components/TreeItem/interfaces/index.ts
  apps/app/src/interfaces/page-listing-results.ts
  apps/app/src/stores-universal/context.tsx
  apps/app/src/stores/page-listing.tsx
Labels: type/bug

#9633 support: Upgrade CodeMirror
  packages/editor/package.json
  packages/editor/src/client/components-internal/CodeMirrorEditor/CodeMirrorEditor.tsx
  pnpm-lock.yaml
Labels: type/support

#9629 imprv: Suppresses unnecessary re-rendering within PageEditor
  apps/app/src/client/components/PageEditor/EditorNavbar/EditorNavbar.tsx
  apps/app/src/client/components/PageEditor/PageEditor.tsx
Labels: type/improvement

#9647 fix: Authenticate before uploading at /_api/v3/import/upload endpoint
  apps/app/src/server/routes/apiv3/import.js
Labels: type/bug

#9641 fix: Data migration script for CSV and TSV
  bin/data-migrations/src/migrations/v60x/csv.js
  bin/data-migrations/src/migrations/v60x/tsv.js
Labels: type/bug

#9632 support: Display brand logo when editor mode
  apps/app/src/client/components/Sidebar/AppTitle/AppTitle.module.scss
  apps/app/src/client/components/Sidebar/AppTitle/AppTitle.tsx
  apps/app/src/client/components/Sidebar/Sidebar.tsx
Labels: type/support

#9655 support: Upgrade runtime versions
  .devcontainer/devcontainer.json
  .npmrc
  apps/app/docker/Dockerfile
  apps/slackbot-proxy/docker/Dockerfile
  package.json
Labels: type/support

#9653 fix: Redirection after login does not work on systems with guest mode enabled
  apps/app/src/pages/login/index.page.tsx
Labels: type/bug

#9690 feat: Normalize remark growi directives for v6.0.x or above
  bin/data-migrations/README.md
  bin/data-migrations/src/migrations/v60x/index.js
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/README.ja.md
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/example-expected.md
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/example.md
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/index.js
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/remark-growi-directive.js
  bin/data-migrations/src/migrations/v60x/remark-growi-directive/remark-growi-directive.spec.js
  bin/vitest.config.ts
  vitest.workspace.mts
Labels: type/feature
