Repository growilabs/growi, pull requests merged in 2025-06, with the labels that each got.

#10002 imprv(ai): Make input form position sticky
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
Labels: type/improvement

#9992 imprv: Security settings search results redesign
  apps/app/playwright/40-admin/access-to-admin-page.spec.ts
  apps/app/public/static/locales/en_US/admin.json
  apps/app/public/static/locales/fr_FR/admin.json
  apps/app/public/static/locales/ja_JP/admin.json
  apps/app/public/static/locales/zh_CN/admin.json
  apps/app/src/client/components/Admin/Security/SecuritySetting.jsx
  apps/app/src/client/services/AdminGeneralSecurityContainer.js
Labels: type/improvement

#10032 imprv: Type safe configuration for file uploading
  apps/app/src/server/routes/apiv3/app-settings.js
  apps/app/src/server/service/config-manager/config-definition.ts
  apps/app/src/server/service/file-uploader/aws/index.ts
  apps/app/src/server/service/file-uploader/azure.ts
  apps/app/src/server/service/file-uploader/gcs/index.ts
Labels: type/improvement

#10038 imprv: Message card markdown header size
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard/MessageCard.module.scss
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard/MessageCard.tsx
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard/ReactMarkdownComponents/Header.tsx
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard/ReactMarkdownComponents/NextLinkWrapper.tsx
Labels: type/improvement

#10044 fix(ai): Prevent unnecessary API request when GROWI AI is disabled
  apps/app/src/features/openai/client/components/AiAssistant/OpenDefaultAiAssistantButton.tsx
Labels: type/bug

#10046 fix: Prevent unnecessary API request when the user is guest
  apps/app/src/client/components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx
  apps/app/src/client/components/Sidebar/SidebarContents.tsx
  apps/app/src/client/components/Sidebar/SidebarNav/PrimaryItems.tsx
  apps/app/src/client/services/page-operation.ts
Labels: type/bug

#10049 fix: Hide Google OAuth client secret field
  apps/app/src/client/components/Admin/Security/GoogleSecuritySettingContents.jsx
Labels: type/bug

#10033 support: Configure biome for remark-drawio package
  biome.json
  packages/remark-drawio/.eslintignore
  packages/remark-drawio/.eslintrc.cjs
  packages/remark-drawio/package.json
  packages/remark-drawio/src/components/DrawioViewer.tsx
  packages/remark-drawio/src/interfaces/graph-viewer.ts
  packages/remark-drawio/src/services/renderer/remark-drawio.ts
  packages/remark-drawio/src/utils/embed.ts
  packages/remark-drawio/src/utils/global.ts
  packages/remark-drawio/tsconfig.json
Labels: type/support

#10058 support: Configure biome for preset-templates package
  biome.json
  packages/preset-templates/.eslintignore
  packages/preset-templates/.eslintrc.js
  packages/preset-templates/package.json
  packages/preset-templates/test/index.test.ts
  packages/preset-templates/tsconfig.json
Labels: type/support

#10063 imprv: OpenAPI Spec for GROWI API v1
  apps/app/src/server/models/openapi/v1-response.js
  apps/app/src/server/models/openapi/v1-response.ts
  apps/app/src/server/routes/apiv3/attachment.js
  apps/app/src/server/routes/apiv3/page/index.ts
  apps/app/src/server/routes/apiv3/users.js
  apps/app/src/server/routes/attachment/api.js
  apps/app/src/server/routes/comment.js
  apps/app/src/server/routes/page.js
  apps/app/src/server/routes/search.ts
  apps/app/src/server/routes/tag.js
Labels: type/improvement

#10054 support: Configure biome for remark-attachment-refs package
  biome.json
  packages/remark-attachment-refs/.eslintignore
  packages/remark-attachment-refs/.eslintrc.cjs
  packages/remark-attachment-refs/package.json
  packages/remark-attachment-refs/src/client/components/AttachmentList.tsx
  packages/remark-attachment-refs/src/client/components/ExtractedAttachments.tsx
  packages/remark-attachment-refs/src/client/components/Gallery.tsx
  packages/remark-attachment-refs/src/client/components/Ref.tsx
  packages/remark-attachment-refs/src/client/components/RefImg.tsx
  packages/remark-attachment-refs/src/client/components/Refs.tsx
  packages/remark-attachment-refs/src/client/components/RefsImg.tsx
  packages/remark-attachment-refs/src/client/components/util/refs-context.ts
  packages/remark-attachment-refs/src/client/services/renderer/refs.ts
  packages/remark-attachment-refs/src/client/stores/refs.tsx
  packages/remark-attachment-refs/src/server/index.ts
  packages/remark-attachment-refs/src/server/routes/refs.ts
  packages/remark-attachment-refs/src/utils/logger/index.ts
  packages/remark-attachment-refs/tsconfig.json
  packages/remark-attachment-refs/vite.server.config.ts
Labels: type/support

#10071 support: Configure biome for pluginkit package
  biome.json
  packages/pluginkit/.eslintignore
  packages/pluginkit/.eslintrc.cjs
  packages/pluginkit/package.json
  packages/pluginkit/src/model/growi-plugin-package-data.ts
  packages/pluginkit/src/model/growi-plugin-validation-data.ts
  packages/pluginkit/src/model/growi-plugin-validation-error.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.spec.ts
  packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.ts
  packages/pluginkit/src/v4/interfaces/template.ts
  packages/pluginkit/src/v4/server/utils/common/import-package-json.spec.ts
  packages/pluginkit/src/v4/server/utils/common/import-package-json.ts
  packages/pluginkit/src/v4/server/utils/common/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/src/v4/server/utils/common/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/server/utils/template/get-markdown.ts
  packages/pluginkit/src/v4/server/utils/template/get-status.ts
  packages/pluginkit/src/v4/server/utils/template/scan.ts
  packages/pluginkit/src/v4/server/utils/template/validate-all-locales.ts
  packages/pluginkit/src/v4/server/utils/template/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/src/v4/server/utils/template/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/server/utils/theme/validate-growi-plugin-directive.spec.ts
  packages/pluginkit/src/v4/server/utils/theme/validate-growi-plugin-directive.ts
  packages/pluginkit/src/v4/utils/template.spec.ts
  packages/pluginkit/src/v4/utils/template.ts
  packages/pluginkit/tsconfig.json
  packages/pluginkit/vite.config.ts
  packages/pluginkit/vitest.config.ts
Labels: type/support

#10076 fix: Unhandled exception in GlobalNotificationMailService
  apps/app/src/pages/utils/commons.ts
  apps/app/src/server/service/global-notification/global-notification-mail.js
Labels: type/bug

#10078 support: Configure biome for core package biome (excluding utils and models)
  biome.json
  packages/core/.eslintignore
  packages/core/.eslintrc.cjs
  packages/core/package.json
  packages/core/src/consts/accepted-upload-file-type.ts
  packages/core/src/consts/growi-plugin.ts
  packages/core/src/consts/system.ts
  packages/core/src/consts/ydoc-status.ts
  packages/core/src/interfaces/attachment.ts
  packages/core/src/interfaces/color-scheme.ts
  packages/core/src/interfaces/common.spec.ts
  packages/core/src/interfaces/common.ts
  packages/core/src/interfaces/config-manager.ts
  packages/core/src/interfaces/external-account.ts
  packages/core/src/interfaces/growi-app-info.ts
  packages/core/src/interfaces/growi-facade.ts
  packages/core/src/interfaces/growi-theme-metadata.ts
  packages/core/src/interfaces/has-object-id.ts
  packages/core/src/interfaces/lang.ts
  packages/core/src/interfaces/page.ts
  packages/core/src/interfaces/primitive/string.spec.ts
  packages/core/src/interfaces/primitive/string.ts
  packages/core/src/interfaces/revision.ts
  packages/core/src/interfaces/subscription.ts
  packages/core/src/interfaces/tag.ts
  packages/core/src/interfaces/user.ts
  packages/core/src/interfaces/vite.ts
  packages/core/src/remark-plugins/interfaces/option-parser.ts
  packages/core/src/remark-plugins/util/option-parser.spec.ts
  packages/core/src/remark-plugins/util/option-parser.ts
  packages/core/src/swr/use-swr-static.ts
  packages/core/src/swr/with-utils.ts
  packages/core/tsconfig.json
  packages/core/vite.config.ts
  packages/core/vitest.config.ts
Labels: type/support

#10077 support: Configure biome for pdf-converter-client package
  biome.json
  packages/pdf-converter-client/.eslintignore
  packages/pdf-converter-client/.eslintrc.cjs
  packages/pdf-converter-client/package.json
Labels: type/support

#10094 fix(ai): Message gets sent when pressing Enter to confirm text conversion
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
Labels: type/bug

#10089 feat(ai): Send pre-message before main chat stream
  apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx
  apps/app/src/features/openai/client/services/knowledge-assistant.tsx
  apps/app/src/features/openai/interfaces/knowledge-assistant/sse-schemas.ts
  apps/app/src/features/openai/server/routes/message/post-message.ts
  apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
  apps/app/src/features/openai/server/services/client-delegator/index.ts
  apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
  apps/app/src/features/openai/server/services/client-delegator/is-stream-response.ts
  apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
  apps/app/src/features/openai/server/services/openai.ts
Labels: type/feature

#10082 support: Configure biome for core package utils and models
  biome.json
  packages/core/.eslintignore
  packages/core/.eslintrc.cjs
  packages/core/src/models/devided-page-path.ts
  packages/core/src/models/serializers/attachment-serializer.ts
  packages/core/src/models/serializers/user-serializer.ts
  packages/core/src/models/vo/error-apiv3.ts
  packages/core/src/utils/browser-utils.ts
  packages/core/src/utils/env-utils.spec.ts
  packages/core/src/utils/growi-theme-metadata.ts
  packages/core/src/utils/is-deep-equals.ts
  packages/core/src/utils/objectid-utils.spec.ts
  packages/core/src/utils/objectid-utils.ts
  packages/core/src/utils/page-path-utils/generate-children-regexp.spec.ts
  packages/core/src/utils/page-path-utils/index.spec.ts
  packages/core/src/utils/page-path-utils/index.ts
  packages/core/src/utils/page-utils.ts
  packages/core/src/utils/path-utils.spec.ts
  packages/core/src/utils/path-utils.ts
Labels: type/support

#10093 imprv(ai): Search and Replace strategy for Editor Assistant
  apps/app/package.json
  apps/app/src/features/openai/client/services/client-engine-integration.tsx
  apps/app/src/features/openai/client/services/editor-assistant/diff-application.ts
  apps/app/src/features/openai/client/services/editor-assistant/error-handling.ts
  apps/app/src/features/openai/client/services/editor-assistant/fuzzy-matching.spec.ts
  apps/app/src/features/openai/client/services/editor-assistant/fuzzy-matching.ts
  apps/app/src/features/openai/client/services/editor-assistant/index.ts
  apps/app/src/features/openai/client/services/editor-assistant/processor.ts
  apps/app/src/features/openai/client/services/editor-assistant/search-replace-engine.spec.ts
  apps/app/src/features/openai/client/services/editor-assistant/search-replace-engine.ts
  apps/app/src/features/openai/client/services/editor-assistant/text-normalization.ts
  apps/app/src/features/openai/client/services/editor-assistant/use-editor-assistant.tsx
  apps/app/src/features/openai/docs/plan2/README.md
  apps/app/src/features/openai/docs/plan2/implementation-status.md
  apps/app/src/features/openai/docs/plan2/technical-specifications.md
  apps/app/src/features/openai/docs/plan2/test-implementation-plan.md
  apps/app/src/features/openai/docs/plan2/testing-framework.md
  apps/app/src/features/openai/interfaces/editor-assistant/llm-response-schemas.spec.ts
  apps/app/src/features/openai/interfaces/editor-assistant/llm-response-schemas.ts
  apps/app/src/features/openai/interfaces/editor-assistant/sse-schemas.spec.ts
  apps/app/src/features/openai/interfaces/editor-assistant/sse-schemas.ts
  apps/app/src/features/openai/interfaces/editor-assistant/types.ts
  apps/app/src/features/openai/server/routes/edit/index.ts
  apps/app/src/features/openai/server/services/editor-assistant/llm-response-stream-processor.spec.ts
  apps/app/src/features/openai/server/services/editor-assistant/llm-response-stream-processor.ts
  pnpm-lock.yaml
Labels: type/improvement

#10103 fix: Prevent dropdown menu from hiding behind sidebar
  apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.jsx
  apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.module.scss
Labels: type/bug

#10108 fix: GROWI AI finalize processing
  apps/app/src/features/openai/client/services/client-engine-integration.tsx
  apps/app/src/features/openai/client/services/editor-assistant/diff-application.ts
  apps/app/src/features/openai/client/services/editor-assistant/error-handling.ts
  apps/app/src/features/openai/interfaces/editor-assistant/sse-schemas.spec.ts
  apps/app/src/features/openai/interfaces/editor-assistant/sse-schemas.ts
  apps/app/src/features/openai/server/routes/edit/index.ts
Labels: type/bug

#9512 feat: Add shortcuts when editing
  packages/editor/src/client/services/use-codemirror-editor/use-codemirror-editor.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/add-multi-cursor.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/generate-add-markdown-symbol-command.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/insert-blockquote.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/insert-bullet-list.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/insert-link.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/insert-numbered-list.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/make-text-bold.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/make-text-code-block.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/make-text-code.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/make-text-italic.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/editor-shortcuts/make-text-strikethrough.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/insert-markdown-elements.ts
  packages/editor/src/client/services/use-codemirror-editor/utils/insert-prefix.ts
  packages/editor/src/client/stores/use-editor-settings.ts
  packages/editor/src/client/stores/use-editor-shortcuts.ts
Labels: type/feature

#10119 fix: Cannot change file upload destination to "MongoDB (GridFS)" or "local" for dev/7.2.x
  apps/app/src/server/routes/apiv3/app-settings.js
Labels: type/bug
