Repository growilabs/growi, pull requests merged in 2025-01, with the labels that each got.

#9541 fix: Unable to select group viewing permissions
  apps/app/src/server/service/normalize-data/convert-null-to-empty-granted-arrays.ts
  apps/app/src/server/service/normalize-data/index.ts
Labels: type/bug

#9550 fix: Escape page path when generating RegExp to find ancestors children
  .changeset/little-toys-reflect.md
  apps/app/src/server/service/page/index.ts
  packages/core/src/utils/page-path-utils/generate-children-regexp.spec.ts
  packages/core/src/utils/page-path-utils/generate-children-regexp.ts
  packages/core/src/utils/page-path-utils/index.ts
Labels: type/bug

#9582 feat: Add error handling for data migration
  bin/data-migrations/src/index.js
Labels: type/feature

#9590 imprv: Make data migration type safe
  bin/data-migrations/src/index.js
  bin/data-migrations/src/migrations/custom.js
  bin/data-migrations/src/types.d.ts
  bin/data-migrations/tsconfig.json
Labels: type/improvement

#9599 imprv: Data migration script performance
  bin/data-migrations/src/index.js
Labels: type/improvement
