Repository growilabs/growi, pull requests merged in 2025-09, with the labels that each got.

#10270 support: Configure biome for mermaid search plantuml features
  apps/app/.eslintrc.js
  apps/app/src/features/mermaid/components/MermaidViewer.tsx
  apps/app/src/features/mermaid/services/mermaid.ts
  apps/app/src/features/plantuml/services/plantuml.ts
  apps/app/src/features/search/client/components/SearchForm.tsx
  apps/app/src/features/search/client/components/SearchHelp.tsx
  apps/app/src/features/search/client/components/SearchMenuItem.tsx
  apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
  apps/app/src/features/search/client/components/SearchModal.tsx
  apps/app/src/features/search/client/components/SearchResultMenuItem.tsx
  apps/app/src/features/search/client/interfaces/downshift.ts
  apps/app/src/features/search/client/stores/search.ts
  biome.json
Labels: type/support

#10268 fix: Delete button is displayed on RichAttachment in guest mode
  apps/app/src/client/components/ReactMarkdownComponents/RichAttachment.tsx
Labels: type/bug

#10293 fix: Docker image build fails
  apps/app/docker/codebuild/.terraform.lock.hcl
  apps/app/docker/codebuild/codebuild.tf
  apps/app/docker/codebuild/main.tf
  apps/app/docker/codebuild/oidc.tf
Labels: type/bug, flag/exclude-from-changelog

#10322 fix: GithubActionsWorkflow (5)
  .github/workflows/release-rc.yml
Labels: flag/exclude-from-changelog

#10325 chore: Update Docker Hub links to growilabs
  README.md
  README_JP.md
  apps/app/docker/README.md
Labels: flag/exclude-from-changelog

#10331 fix: TreeItem opening logic
  apps/app/src/client/components/TreeItem/TreeItemLayout.tsx
Labels: type/bug
